// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

//go:build ignore_internal_tests
// +build ignore_internal_tests

package test

import "testing"

func TestRuntimeFilterGenerator(t *testing.T) {
	RunRuntimeFilterGenerator(t)
}
