// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package ddl_test

import "testing"

func TestShowCreateTable(t *testing.T) {
	RunShowCreateTable(t)
}

func TestDropNotNullColumn(t *testing.T) {
	RunDropNotNullColumn(t)
}

func TestTwoStates(t *testing.T) {
	RunTwoStates(t)
}

func TestWriteOnlyWriteNULL(t *testing.T) {
	RunWriteOnlyWriteNULL(t)
}

func TestWriteOnlyOnDupUpdate(t *testing.T) {
	RunWriteOnlyOnDupUpdate(t)
}

func TestWriteOnlyOnDupUpdateForAddColumns(t *testing.T) {
	RunWriteOnlyOnDupUpdateForAddColumns(t)
}

func TestWriteReorgForModifyColumnTimestampToInt(t *testing.T) {
	RunWriteReorgForModifyColumnTimestampToInt(t)
}

func TestWriteReorgForModifyColumn(t *testing.T) {
	RunWriteReorgForModifyColumn(t)
}

func TestWriteReorgForModifyColumnWithUniqIdx(t *testing.T) {
	RunWriteReorgForModifyColumnWithUniqIdx(t)
}

func TestWriteReorgForModifyColumnWithPKIsHandle(t *testing.T) {
	RunWriteReorgForModifyColumnWithPKIsHandle(t)
}

func TestWriteReorgForModifyColumnWithPrimaryIdx(t *testing.T) {
	RunWriteReorgForModifyColumnWithPrimaryIdx(t)
}

func TestWriteReorgForModifyColumnWithoutFirst(t *testing.T) {
	RunWriteReorgForModifyColumnWithoutFirst(t)
}

func TestWriteReorgForModifyColumnWithoutDefaultVal(t *testing.T) {
	RunWriteReorgForModifyColumnWithoutDefaultVal(t)
}

func TestDeleteOnlyForModifyColumnWithoutDefaultVal(t *testing.T) {
	RunDeleteOnlyForModifyColumnWithoutDefaultVal(t)
}

func TestWriteOnly(t *testing.T) {
	RunWriteOnly(t)
}

func TestWriteOnlyForAddColumns(t *testing.T) {
	RunWriteOnlyForAddColumns(t)
}

func TestDeleteOnly(t *testing.T) {
	RunDeleteOnly(t)
}

func TestSchemaChangeForDropColumnWithIndexes(t *testing.T) {
	RunSchemaChangeForDropColumnWithIndexes(t)
}

func TestSchemaChangeForDropColumnsWithIndexes(t *testing.T) {
	RunSchemaChangeForDropColumnsWithIndexes(t)
}

func TestDeleteOnlyForDropExpressionIndex(t *testing.T) {
	RunDeleteOnlyForDropExpressionIndex(t)
}

func TestDeleteOnlyForDropColumns(t *testing.T) {
	RunDeleteOnlyForDropColumns(t)
}

func TestWriteOnlyForDropColumn(t *testing.T) {
	RunWriteOnlyForDropColumn(t)
}

func TestWriteOnlyForDropColumns(t *testing.T) {
	RunWriteOnlyForDropColumns(t)
}

func TestShowIndex(t *testing.T) {
	RunShowIndex(t)
}

func TestParallelAlterIndex(t *testing.T) {
	RunParallelAlterIndex(t)
}

func TestParallelAlterModifyColumn(t *testing.T) {
	RunParallelAlterModifyColumn(t)
}

func TestParallelAlterModifyColumnWithData(t *testing.T) {
	RunParallelAlterModifyColumnWithData(t)
}

func TestParallelAlterModifyColumnToNotNullWithData(t *testing.T) {
	RunParallelAlterModifyColumnToNotNullWithData(t)
}

func TestParallelAddGeneratedColumnAndAlterModifyColumn(t *testing.T) {
	RunParallelAddGeneratedColumnAndAlterModifyColumn(t)
}

func TestParallelAlterModifyColumnAndAddPK(t *testing.T) {
	RunParallelAlterModifyColumnAndAddPK(t)
}

func TestParallelAddColumAndSetDefaultValue(t *testing.T) {
	RunParallelAddColumAndSetDefaultValue(t)
}

func TestParallelChangeColumnName(t *testing.T) {
	RunParallelChangeColumnName(t)
}

func TestParallelAlterAddIndex(t *testing.T) {
	RunParallelAlterAddIndex(t)
}

func TestParallelAlterAddVectorIndex(t *testing.T) {
	RunParallelAlterAddVectorIndex(t)
}

func TestParallelAlterAddColumnarIndex(t *testing.T) {
	RunParallelAlterAddColumnarIndex(t)
}

func TestParallelAlterAddExpressionIndex(t *testing.T) {
	RunParallelAlterAddExpressionIndex(t)
}

func TestParallelAddPrimaryKey(t *testing.T) {
	RunParallelAddPrimaryKey(t)
}

func TestParallelAlterAddPartition(t *testing.T) {
	RunParallelAlterAddPartition(t)
}

func TestParallelDropColumn(t *testing.T) {
	RunParallelDropColumn(t)
}

func TestParallelDropColumns(t *testing.T) {
	RunParallelDropColumns(t)
}

func TestParallelDropIfExistsColumns(t *testing.T) {
	RunParallelDropIfExistsColumns(t)
}

func TestParallelDropIndex(t *testing.T) {
	RunParallelDropIndex(t)
}

func TestParallelDropPrimaryKey(t *testing.T) {
	RunParallelDropPrimaryKey(t)
}

func TestParallelCreateAndRename(t *testing.T) {
	RunParallelCreateAndRename(t)
}

func TestParallelAlterAndDropSchema(t *testing.T) {
	RunParallelAlterAndDropSchema(t)
}

func TestCreateTableIfNotExists(t *testing.T) {
	RunCreateTableIfNotExists(t)
}

func TestCreateDBIfNotExists(t *testing.T) {
	RunCreateDBIfNotExists(t)
}

func TestDDLIfNotExists(t *testing.T) {
	RunDDLIfNotExists(t)
}

func TestDDLIfExists(t *testing.T) {
	RunDDLIfExists(t)
}

func TestParallelDDLBeforeRunDDLJob(t *testing.T) {
	RunParallelDDLBeforeRunDDLJob(t)
}

func TestParallelAlterSchemaCharsetAndCollate(t *testing.T) {
	RunParallelAlterSchemaCharsetAndCollate(t)
}

func TestParallelTruncateTableAndAddColumn(t *testing.T) {
	RunParallelTruncateTableAndAddColumn(t)
}

func TestParallelTruncateTableAndAddColumns(t *testing.T) {
	RunParallelTruncateTableAndAddColumns(t)
}

func TestWriteReorgForColumnTypeChange(t *testing.T) {
	RunWriteReorgForColumnTypeChange(t)
}

func TestCreateExpressionIndex(t *testing.T) {
	RunCreateExpressionIndex(t)
}

func TestCreateUniqueExpressionIndex(t *testing.T) {
	RunCreateUniqueExpressionIndex(t)
}

func TestDropExpressionIndex(t *testing.T) {
	RunDropExpressionIndex(t)
}

func TestParallelRenameTable(t *testing.T) {
	RunParallelRenameTable(t)
}

func TestConcurrentSetDefaultValue(t *testing.T) {
	RunConcurrentSetDefaultValue(t)
}
