// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package ddl_test

import "testing"

func TestCreateTableIfNotExistsLike(t *testing.T) {
	RunCreateTableIfNotExistsLike(t)
}

func TestCreateTableWithKeyWord(t *testing.T) {
	RunCreateTableWithKeyWord(t)
}

func TestUniqueKeyNullValue(t *testing.T) {
	RunUniqueKeyNullValue(t)
}

func TestUniqueKeyNullValueClusterIndex(t *testing.T) {
	RunUniqueKeyNullValueClusterIndex(t)
}

func TestModifyColumnAfterAddIndex(t *testing.T) {
	RunModifyColumnAfterAddIndex(t)
}

func TestModifyColumnOldColumnIDNotFound(t *testing.T) {
	RunModifyColumnOldColumnIDNotFound(t)
}

func TestIssue2293(t *testing.T) {
	RunIssue2293(t)
}

func TestIssue19229(t *testing.T) {
	RunIssue19229(t)
}

func TestIndexLength(t *testing.T) {
	RunIndexLength(t)
}

func TestIssue2858And2717(t *testing.T) {
	RunIssue2858And2717(t)
}

func TestIssue4432(t *testing.T) {
	RunIssue4432(t)
}

func TestIssue5092(t *testing.T) {
	RunIssue5092(t)
}

func TestTableDDLWithTimeType(t *testing.T) {
	RunTableDDLWithTimeType(t)
}

func TestUpdateMultipleTable(t *testing.T) {
	RunUpdateMultipleTable(t)
}

func TestNullGeneratedColumn(t *testing.T) {
	RunNullGeneratedColumn(t)
}

func TestDependedGeneratedColumnPrior2GeneratedColumn(t *testing.T) {
	RunDependedGeneratedColumnPrior2GeneratedColumn(t)
}

func TestChangingTableCharset(t *testing.T) {
	RunChangingTableCharset(t)
}

func TestModifyColumnOption(t *testing.T) {
	RunModifyColumnOption(t)
}

func TestIndexOnMultipleGeneratedColumn(t *testing.T) {
	RunIndexOnMultipleGeneratedColumn(t)
}

func TestIndexOnMultipleGeneratedColumn1(t *testing.T) {
	RunIndexOnMultipleGeneratedColumn1(t)
}

func TestIndexOnMultipleGeneratedColumn2(t *testing.T) {
	RunIndexOnMultipleGeneratedColumn2(t)
}

func TestIndexOnMultipleGeneratedColumn3(t *testing.T) {
	RunIndexOnMultipleGeneratedColumn3(t)
}

func TestIndexOnMultipleGeneratedColumn4(t *testing.T) {
	RunIndexOnMultipleGeneratedColumn4(t)
}

func TestIndexOnMultipleGeneratedColumn5(t *testing.T) {
	RunIndexOnMultipleGeneratedColumn5(t)
}

func TestCaseInsensitiveCharsetAndCollate(t *testing.T) {
	RunCaseInsensitiveCharsetAndCollate(t)
}

func TestZeroFillCreateTable(t *testing.T) {
	RunZeroFillCreateTable(t)
}

func TestBitDefaultValue(t *testing.T) {
	RunBitDefaultValue(t)
}

func TestCreateTableTooLarge(t *testing.T) {
	RunCreateTableTooLarge(t)
}

func TestChangeColumnPosition(t *testing.T) {
	RunChangeColumnPosition(t)
}

func TestAddIndexAfterAddColumn(t *testing.T) {
	RunAddIndexAfterAddColumn(t)
}

func TestResolveCharset(t *testing.T) {
	RunResolveCharset(t)
}

func TestAddColumnDefaultNow(t *testing.T) {
	RunAddColumnDefaultNow(t)
}

func TestAlterColumn(t *testing.T) {
	RunAlterColumn(t)
}

func TestAlterAlgorithm(t *testing.T) {
	RunAlterAlgorithm(t)
}

func TestTreatOldVersionUTF8AsUTF8MB4(t *testing.T) {
	RunTreatOldVersionUTF8AsUTF8MB4(t)
}

func TestDefaultColumnWithRand(t *testing.T) {
	RunDefaultColumnWithRand(t)
}

func TestDefaultValueAsExpressions(t *testing.T) {
	RunDefaultValueAsExpressions(t)
}

func TestChangingDBCharset(t *testing.T) {
	RunChangingDBCharset(t)
}

func TestSqlFunctionsInGeneratedColumns(t *testing.T) {
	RunSqlFunctionsInGeneratedColumns(t)
}

func TestSchemaNameAndTableNameInGeneratedExpr(t *testing.T) {
	RunSchemaNameAndTableNameInGeneratedExpr(t)
}

func TestParserIssue284(t *testing.T) {
	RunParserIssue284(t)
}

func TestAddExpressionIndex(t *testing.T) {
	RunAddExpressionIndex(t)
}

func TestDropColumnWithCompositeIndex(t *testing.T) {
	RunDropColumnWithCompositeIndex(t)
}

func TestDropColumnWithIndex(t *testing.T) {
	RunDropColumnWithIndex(t)
}

func TestDropColumnWithAutoInc(t *testing.T) {
	RunDropColumnWithAutoInc(t)
}

func TestDropColumnWithMultiIndex(t *testing.T) {
	RunDropColumnWithMultiIndex(t)
}

func TestDropColumnsWithMultiIndex(t *testing.T) {
	RunDropColumnsWithMultiIndex(t)
}

func TestAutoIncrementTableOption(t *testing.T) {
	RunAutoIncrementTableOption(t)
}

func TestAutoIncrementForce(t *testing.T) {
	RunAutoIncrementForce(t)
}

func TestAutoIncrementForceAutoIDCache(t *testing.T) {
	RunAutoIncrementForceAutoIDCache(t)
}

func TestIssue20490(t *testing.T) {
	RunIssue20490(t)
}

func TestIssue20741WithEnumField(t *testing.T) {
	RunIssue20741WithEnumField(t)
}

func TestEnumAndSetDefaultValue(t *testing.T) {
	RunEnumAndSetDefaultValue(t)
}

func TestDuplicateErrorMessage(t *testing.T) {
	RunDuplicateErrorMessage(t)
}

func TestIssue22028(t *testing.T) {
	RunIssue22028(t)
}

func TestCreateTemporaryTable(t *testing.T) {
	RunCreateTemporaryTable(t)
}

func TestAccessLocalTmpTableAfterDropDB(t *testing.T) {
	RunAccessLocalTmpTableAfterDropDB(t)
}

func TestAvoidCreateViewOnLocalTemporaryTable(t *testing.T) {
	RunAvoidCreateViewOnLocalTemporaryTable(t)
}

func TestDropTemporaryTable(t *testing.T) {
	RunDropTemporaryTable(t)
}

func TestTruncateLocalTemporaryTable(t *testing.T) {
	RunTruncateLocalTemporaryTable(t)
}

func TestIssue29282(t *testing.T) {
	RunIssue29282(t)
}

func TestEnumDefaultValue(t *testing.T) {
	RunEnumDefaultValue(t)
}

func TestDDLLastInfo(t *testing.T) {
	RunDDLLastInfo(t)
}

func TestDefaultCollationForUTF8MB4(t *testing.T) {
	RunDefaultCollationForUTF8MB4(t)
}

func TestOptimizeTable(t *testing.T) {
	RunOptimizeTable(t)
}

func TestIssue52680(t *testing.T) {
	RunIssue52680(t)
}

func TestCreateIndexWithChangeMaxIndexLength(t *testing.T) {
	RunCreateIndexWithChangeMaxIndexLength(t)
}
