// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestTable(t *testing.T) {
	RunTable(t)
}

func TestTableStructEqual(t *testing.T) {
	RunTableStructEqual(t)
}

func TestSchemacmpEncode(t *testing.T) {
	RunSchemacmpEncode(t)
}
