[package]
name = "tidb-ast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "TiDB SQL abstract syntax tree (Rust)."

[lints]
workspace = true

[dependencies]
serde.workspace = true
tidb-datatype = { path = "../tidb-datatype" }
tidb-lexer = { path = "../tidb-lexer" }

[dev-dependencies]
serde_json.workspace = true

[[bench]]
name = "base_source"
harness = false
