// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestUnparallelSortSpillDisk(t *testing.T) {
	RunUnparallelSortSpillDisk(t)
}

func TestFallBackAction(t *testing.T) {
	RunFallBackAction(t)
}
