load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "orphandata",
    srcs = [
        "monitor.go",
        "scan.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/ingestor/globalsort/orphandata",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ingestor/simplesst",
        "//pkg/metrics",
        "//pkg/objstore",
        "//pkg/objstore/storeapi",
        "@com_github_pingcap_errors//:errors",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "orphandata_test",
    timeout = "short",
    srcs = [
        "monitor_test.go",
        "scan_test.go",
    ],
    embed = [":orphandata"],
    flaky = True,
    shard_count = 4,
    deps = [
        "//pkg/metrics",
        "//pkg/objstore",
        "//pkg/objstore/storeapi",
        "@com_github_prometheus_client_golang//prometheus/testutil",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zaptest/observer",
    ],
)
