CREATE TABLE `mosag_raw_data` (
    `__node_id` bigint NOT NULL PRIMARY KEY,
    `uk` varbinary(2000) DEFAULT NULL UNIQUE KEY,
    `is_active` tinyint(1) DEFAULT NULL,
    `__create_at` timestamp NULL DEFAULT NULL,
    `__update_at` timestamp NULL DEFAULT NULL,
    `url` varbinary(32756) DEFAULT NULL,
    `visited_urls` mediumblob DEFAULT NULL,
    `content_md5_hash` varbinary(16) DEFAULT NULL,
    `image_dimension` varbinary(11) DEFAULT NULL,
    `http_last_modified` varbinary(8) DEFAULT NULL,
    `mosag_last_crawled` varbinary(8) DEFAULT NULL,
    `http_status_code` varbinary(4) DEFAULT NULL,
    `http_error_status_codes` varbinary(5) DEFAULT NULL,
    `http_error_timestamps` varbinary(4) DEFAULT NULL,
    `priority` varbinary(77) DEFAULT NULL,
    `location` varbinary(4239) DEFAULT NULL,
    `content_language` varbinary(1132) DEFAULT NULL,
    `content_encoding` varbinary(101) DEFAULT NULL,
    `status` varbinary(1344) DEFAULT NULL,
    `content_type` varbinary(3135) DEFAULT NULL,
    `content_length` varbinary(40) DEFAULT NULL,
    `last_modified` varbinary(5039) DEFAULT NULL,
    `content_location` varbinary(2308) DEFAULT NULL,
    `cookie` varbinary(5960) DEFAULT NULL,
    `is_active_1` tinyint(1) DEFAULT NULL,
    `__create_at_1` timestamp NULL DEFAULT NULL,
    `__update_at_1` timestamp NULL DEFAULT NULL,
    `url_1` varbinary(32756) DEFAULT NULL,
    `visited_urls_1` mediumblob DEFAULT NULL,
    `content_md5_hash_1` varbinary(16) DEFAULT NULL,
    `image_dimension_1` varbinary(11) DEFAULT NULL,
    `http_last_modified_1` varbinary(8) DEFAULT NULL,
    `mosag_last_crawled_1` varbinary(8) DEFAULT NULL,
    `http_status_code_1` varbinary(4) DEFAULT NULL,
    `http_error_status_codes_1` varbinary(5) DEFAULT NULL,
    `http_error_timestamps_1` varbinary(4) DEFAULT NULL,
    `priority_1` varbinary(77) DEFAULT NULL,
    `location_1` varbinary(4239) DEFAULT NULL,
    `content_language_1` varbinary(1132) DEFAULT NULL,
    `content_encoding_1` varbinary(101) DEFAULT NULL,
    `status_1` varbinary(1344) DEFAULT NULL,
    `content_type_1` varbinary(3135) DEFAULT NULL,
    `content_length_1` varbinary(40) DEFAULT NULL,
    `last_modified_1` varbinary(5039) DEFAULT NULL,
    `content_location_1` varbinary(2308) DEFAULT NULL,
    `cookie_1` varbinary(5960) DEFAULT NULL,
    `is_active_2` tinyint(1) DEFAULT NULL,
    `__create_at_2` timestamp NULL DEFAULT NULL,
    `__update_at_2` timestamp NULL DEFAULT NULL,
    `url_2` varbinary(32756) DEFAULT NULL,
    `visited_urls_2` mediumblob DEFAULT NULL,
    `content_md5_hash_2` varbinary(16) DEFAULT NULL,
    `image_dimension_2` varbinary(11) DEFAULT NULL,
    `http_last_modified_2` varbinary(8) DEFAULT NULL,
    `mosag_last_crawled_2` varbinary(8) DEFAULT NULL,
    `http_status_code_2` varbinary(4) DEFAULT NULL,
    `http_error_status_codes_2` varbinary(5) DEFAULT NULL,
    `http_error_timestamps_2` varbinary(4) DEFAULT NULL,
    `priority_2` varbinary(77) DEFAULT NULL,
    `location_2` varbinary(4239) DEFAULT NULL,
    `content_language_2` varbinary(1132) DEFAULT NULL,
    `content_encoding_2` varbinary(101) DEFAULT NULL,
    `status_2` varbinary(1344) DEFAULT NULL,
    `content_type_2` varbinary(3135) DEFAULT NULL,
    `content_length_2` varbinary(40) DEFAULT NULL,
    `last_modified_2` varbinary(5039) DEFAULT NULL,
    `content_location_2` varbinary(2308) DEFAULT NULL,
    `cookie_2` varbinary(5960) DEFAULT NULL,
    `is_active_3` tinyint(1) DEFAULT NULL,
    `__create_at_3` timestamp NULL DEFAULT NULL,
    `__update_at_3` timestamp NULL DEFAULT NULL,
    `url_3` varbinary(32756) DEFAULT NULL,
    `visited_urls_3` mediumblob DEFAULT NULL,
    `content_md5_hash_3` varbinary(16) DEFAULT NULL,
    `image_dimension_3` varbinary(11) DEFAULT NULL,
    `http_last_modified_3` varbinary(8) DEFAULT NULL,
    `mosag_last_crawled_3` varbinary(8) DEFAULT NULL,
    `http_status_code_3` varbinary(4) DEFAULT NULL,
    `http_error_status_codes_3` varbinary(5) DEFAULT NULL,
    `http_error_timestamps_3` varbinary(4) DEFAULT NULL,
    `priority_3` varbinary(77) DEFAULT NULL,
    `location_3` varbinary(4239) DEFAULT NULL,
    `content_language_3` varbinary(1132) DEFAULT NULL,
    `content_encoding_3` varbinary(101) DEFAULT NULL,
    `status_3` varbinary(1344) DEFAULT NULL,
    `content_type_3` varbinary(3135) DEFAULT NULL,
    `content_length_3` varbinary(40) DEFAULT NULL,
    `last_modified_3` varbinary(5039) DEFAULT NULL,
    `content_location_3` varbinary(2308) DEFAULT NULL,
    `cookie_3` varbinary(5960) DEFAULT NULL,
    `is_active_4` tinyint(1) DEFAULT NULL,
    `__create_at_4` timestamp NULL DEFAULT NULL,
    `__update_at_4` timestamp NULL DEFAULT NULL,
    `url_4` varbinary(32756) DEFAULT NULL,
    `visited_urls_4` mediumblob DEFAULT NULL,
    `content_md5_hash_4` varbinary(16) DEFAULT NULL,
    `image_dimension_4` varbinary(11) DEFAULT NULL,
    `http_last_modified_4` varbinary(8) DEFAULT NULL,
    `mosag_last_crawled_4` varbinary(8) DEFAULT NULL,
    `http_status_code_4` varbinary(4) DEFAULT NULL,
    `http_error_status_codes_4` varbinary(5) DEFAULT NULL,
    `http_error_timestamps_4` varbinary(4) DEFAULT NULL,
    `priority_4` varbinary(77) DEFAULT NULL,
    `location_4` varbinary(4239) DEFAULT NULL,
);
