// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package model_test

import "testing"

func TestJobStartTime(t *testing.T) {
	RunJobStartTime(t)
}

func TestState(t *testing.T) {
	RunState(t)
}

func TestJobCodec(t *testing.T) {
	RunJobCodec(t)
}

func TestLocation(t *testing.T) {
	RunLocation(t)
}

func TestJobClone(t *testing.T) {
	RunJobClone(t)
}

func TestJobSize(t *testing.T) {
	RunJobSize(t)
}

func TestBackfillMetaCodec(t *testing.T) {
	RunBackfillMetaCodec(t)
}

func TestMayNeedReorg(t *testing.T) {
	RunMayNeedReorg(t)
}

func TestInFinalState(t *testing.T) {
	RunInFinalState(t)
}

func TestSchemaState(t *testing.T) {
	RunSchemaState(t)
}

func TestActionTypeReserved(t *testing.T) {
	RunActionTypeReserved(t)
}

func TestString(t *testing.T) {
	RunString(t)
}

func TestJobEncodeV2(t *testing.T) {
	RunJobEncodeV2(t)
}

func TestJobVerInUse(t *testing.T) {
	RunJobVerInUse(t)
}

func TestJobCheckInvolvingSchemaInfo(t *testing.T) {
	RunJobCheckInvolvingSchemaInfo(t)
}
