// Code generated by mega-gen. DO NOT EDIT.

package fastcreatetable_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("ddl_tests_fastcreatetable", "SwitchFastCreateTable", RunSwitchFastCreateTable)
	register.Register("ddl_tests_fastcreatetable", "DDL", RunDDL)
	register.Register("ddl_tests_fastcreatetable", "MergedJob", RunMergedJob)
}
