load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_package_lockdown_inventory_lib",
    srcs = ["main.go"],
    importpath = "github.com/pingcap/tidb/rust/difftests/tools/go_package_lockdown_inventory",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "go_package_lockdown_inventory",
    embed = [":go_package_lockdown_inventory_lib"],
    visibility = ["//visibility:public"],
)
