#!/bin/sh
#
# Copyright 2025 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

log_file="${TEST_DIR}/lightning.log"
if [ $# -gt 1 ]; then
    log_file=$2
fi

if ! grep -Fq "$1" "$log_file"; then
    echo "TEST FAILED: LIGHTNING LOG DOES NOT CONTAIN '$1'"
    echo "____________________________________"
    cat "$log_file"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
    exit 1
fi
