#!/bin/sh

set -eu

PD_ADDR="127.0.0.1:2379"
TIDB_IP="127.0.0.1"
TIDB_PORT="4000"
TIDB_ADDR="127.0.0.1:4000"
TIDB_STATUS_ADDR="127.0.0.1:10080"

stop_services() {
    killall -9 tidb-server || true

    find "$DUMPLING_TEST_DIR" -maxdepth 1 -not -path "$DUMPLING_TEST_DIR" -not -name "*.log" | xargs rm -r || true
}

start_services() {
    stop_services
    echo "Ensure mysql can connected..."

cat > "$DUMPLING_TEST_DIR/mysql.cnf" <<EOF
[client]
user = ${DUMPLING_TEST_USER}
host = ${DUMPLING_TEST_HOST}
port = ${DUMPLING_TEST_PORT}
password = ${DUMPLING_TEST_PASSWORD}
default-character-set = utf8mb4
EOF
    i=0
    while ! run_sql 'select 0 limit 0' > /dev/null; do
       i=$((i+1))
       if [ "$i" -gt 10 ]; then
          echo 'Failed to ping MySQL Server'
          exit 1
       fi
       sleep 3
    done

    bin/tidb-server \
        -P 4000 \
        --status 10080 \
        --store mocktikv \
        --log-file "$DUMPLING_TEST_DIR/tidb.log" &

    echo "Verifying TiDB is started..."
    i=0
    while ! curl -o /dev/null -sf "http://$TIDB_IP:10080/status"; do
        i=$((i+1))
        if [ "$i" -gt 10 ]; then
            echo 'Failed to start TiDB'
            exit 1
        fi
        sleep 3
    done
}

