// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

//go:build ignore_internal_tests
// +build ignore_internal_tests

package executor_test

import "testing"

func TestShowDistributionJobs(t *testing.T) {
	RunShowDistributionJobs(t)
}

func TestDistributeTable(t *testing.T) {
	RunDistributeTable(t)
}

func TestShowTableDistributions(t *testing.T) {
	RunShowTableDistributions(t)
}

func TestCancelDistributionJob(t *testing.T) {
	RunCancelDistributionJob(t)
}
