// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

//go:build ignore_internal_tests
// +build ignore_internal_tests

package executor_test

import "testing"

func TestParseSlowLogPanic(t *testing.T) {
	RunParseSlowLogPanic(t)
}

func TestParseSlowLogFile(t *testing.T) {
	RunParseSlowLogFile(t)
}

func TestParseSlowLogSessionConnectAttrs(t *testing.T) {
	RunParseSlowLogSessionConnectAttrs(t)
}

func TestParseSlowLogFileSerial(t *testing.T) {
	RunParseSlowLogFileSerial(t)
}

func TestSlowLogParseTime(t *testing.T) {
	RunSlowLogParseTime(t)
}

func TestFixParseSlowLogFile(t *testing.T) {
	RunFixParseSlowLogFile(t)
}

func TestSlowQueryRetriever(t *testing.T) {
	RunSlowQueryRetriever(t)
}

func TestSplitbyColon(t *testing.T) {
	RunSplitbyColon(t)
}

func TestBatchLogForReversedScan(t *testing.T) {
	RunBatchLogForReversedScan(t)
}

func TestSlowQueryRetrieverReversedScanWithLimit(t *testing.T) {
	RunSlowQueryRetrieverReversedScanWithLimit(t)
}

func TestPBPlanBuilderPushDownLimitToSlowQueryRetriever(t *testing.T) {
	RunPBPlanBuilderPushDownLimitToSlowQueryRetriever(t)
}

func TestCancelParseSlowLog(t *testing.T) {
	RunCancelParseSlowLog(t)
}

func TestIssue54324(t *testing.T) {
	RunIssue54324(t)
}
