// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

//go:build ignore_internal_tests
// +build ignore_internal_tests

package executor_test

import "testing"

func TestStmtSummaryRetriverV2_TableStatementsSummary(t *testing.T) {
	RunStmtSummaryRetriverV2_TableStatementsSummary(t)
}

func TestStmtSummaryRetriverV2_TableStatementsSummaryEvicted(t *testing.T) {
	RunStmtSummaryRetriverV2_TableStatementsSummaryEvicted(t)
}

func TestStmtSummaryRetriverV2_TableStatementsSummaryHistory(t *testing.T) {
	RunStmtSummaryRetriverV2_TableStatementsSummaryHistory(t)
}
