load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "fulltext",
    srcs = [
        "analyzer.go",
        "document.go",
        "posting.go",
        "query.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/expression/fulltext",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/expression/matchagainst",
        "//pkg/kv",
        "//pkg/meta/model",
        "//pkg/sessionctx",
        "//pkg/sessionctx/vardef",
        "//pkg/sessionctx/variable",
        "@com_github_pingcap_errors//:errors",
    ],
)

go_test(
    name = "fulltext_test",
    timeout = "short",
    srcs = [
        "analyzer_test.go",
        "posting_test.go",
        "query_test.go",
    ],
    embed = [":fulltext"],
    flaky = False,
    shard_count = 23,
    deps = [
        "//pkg/kv",
        "//pkg/meta/model",
        "//pkg/sessionctx/vardef",
        "//pkg/sessionctx/variable",
        "//pkg/util/mock",
        "@com_github_stretchr_testify//require",
    ],
)
