header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: PingCAP, Inc.
  paths-ignore:
    - 'docs/'
    - 'br/'
    - '.gitignore'
    - '.gitattributes'
    - '.golangci.yml'
    - '.licenserc.yaml'
    - 'LICENSES/'
    - '**/*.md'
    - '**/*.json'
    - '**/*.pem'
    - '**/*.crt'
    - '**/*.test'
    - '**/*.result'
    - '**/*.example'
    - '.codecov.yml'
    - 'circle.yml'
    - 'errors.toml'
    - 'Jenkinsfile'
    - '.editorconfig'
    - 'hooks/pre-commit'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - '.github/'
    # The license checker think the following 68 files do not have valid header licenses, need to be discussed.
    # Ignore them for now.
    - 'cmd/explaintest/config.toml'
    - 'cmd/importer/config.toml'
    - 'cmd/portgenerator/portgenerator.go'
    - 'ddl/ddl.go'
    - 'ddl/ddl_api.go'
    - 'ddl/mock.go'
    - 'ddl/options.go'
    - 'executor/aggfuncs/func_stddevpop_test.go'
    - 'executor/aggfuncs/func_stddevsamp_test.go'
    - 'executor/aggfuncs/func_varpop_test.go'
    - 'executor/aggfuncs/func_varsamp_test.go'
    - 'executor/index_lookup_merge_join_test.go'
    - 'executor/pkg_test.go'
    - 'expression/aggregation/base_func_test.go'
    - 'expression/aggregation/util_test.go'
    - 'expression/builtin.go'
    - 'expression/builtin_info.go'
    - 'expression/builtin_math.go'
    - 'expression/builtin_miscellaneous.go'
    - 'expression/builtin_miscellaneous_test.go'
    - 'expression/builtin_string.go'
    - 'expression/builtin_time.go'
    - 'metrics/alertmanager/tidb.rules.yml'
    - 'metrics/topsql.go'
    - 'planner/core/cache_test.go'
    - 'planner/core/logical_plans_test.go'
    - 'planner/core/partition_prune.go'
    - 'planner/core/partition_pruning_test.go'
    - 'planner/core/rule_aggregation_push_down.go'
    - 'planner/core/rule_max_min_eliminate.go'
    - 'planner/core/rule_partition_processor.go'
    - 'planner/core/rule_predicate_push_down.go'
    - 'planner/core/telemetry.go'
    - 'plugin/conn_ip_example/manifest.toml'
    - 'server/conn.go'
    - 'server/conn_stmt.go'
    - 'server/packetio.go'
    - 'server/server.go'
    - 'server/util.go'
    - 'session/bootstrap.go'
    - 'session/session.go'
    - 'session/tidb.go'
    - 'store/driver/kv_test.go'
    - 'store/mockstore/unistore/config/config-template.toml'
    - 'store/mockstore/unistore/server/server.go'
    - 'table/column.go'
    - 'table/table.go'
    - 'table/tables/tables.go'
    - 'tests/globalkilltest/config.toml'
    - 'tests/readonlytest/readonly_test.go'
    - 'tools/check/check-timeout.go'
    - 'tools/check/revive.toml'
    - 'types/convert.go'
    - 'types/etc.go'
    - 'types/fuzzMarshalJSON.go'
    - 'types/fuzzNewBitLiteral.go'
    - 'types/fuzzNewHexLiteral.go'
    - 'util/collate/collate_bench_test.go'
    - 'util/format/format.go'
    - 'util/logutil/slow_query_logger.go'
    - 'util/mvmap/fnv.go'
    - 'util/prefix_helper.go'
    - 'util/resourcegrouptag/resource_group_tag.go'
    - 'util/set/set_with_memory_usage_test.go'
    - 'util/testkit/fake.go'
    - 'util/testleak/leaktest.go'
    - 'util/timeutil/time_test.go'
    - 'util/topsql/reporter/mock/server.go'
  comment: on-failure
