header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: PingCAP, Inc.
  paths-ignore:
    - "docs/"
    - "br/"
    - ".gitignore"
    - ".gitmodules"
    - ".dockerignore"
    - ".gitattributes"
    - ".cilinter.yaml"
    - ".golangci.yml"
    - ".golangci_br.yml"
    - "LICENSES/"
    - "**/BUILD.bazel"
    - "WORKSPACE"
    - "WORKSPACE.patchgo"
    - ".bazelrc"
    - "**/*.key"
    - "**/*.md"
    - "**/*.json"
    - "**/*.toml"
    - "**/*.pem"
    - "**/*.crt"
    - "**/*.test"
    - "**/*.result"
    - "**/*.example"
    - "**/*.patch"
    - "**/*.bzl"
    - ".codecov.yml"
    - "Jenkinsfile"
    - ".editorconfig"
    - "hooks/pre-commit"
    - "**/go.mod"
    - "**/go.sum"
    - "LICENSE"
    - ".github/"
    - "pkg/parser/"
    - "dumpling/"
    - "pkg/tidb-binlog/driver/example"
    - "pkg/tidb-binlog/proto/go-binlog/secondary_binlog.pb.go"
    - "**/*.sql"
    - "**/*.csv"
    - "**/*.parquet"
    - "**/*.zst"
    - ".bazelversion"
    - "build/image/.ci_bazel"
    - "**/OWNERS"
    - "OWNERS_ALIASES"
    - "pkg/disttask/**/mock/**/*_mock.go"
    - "pkg/util/sqlexec/mock/*_mock.go"
  comment: on-failure
