header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: PingCAP, Inc.
  paths-ignore:
<<<<<<< HEAD
    - 'docs/'
    - 'br/'
    - '.gitignore'
    - '.gitattributes'
    - '.golangci.yml'
    - '.golangci_br.yml'
    - 'LICENSES/'
    - '**/*.md'
    - '**/*.json'
    - '**/*.pem'
    - '**/*.crt'
    - '**/*.test'
    - '**/*.result'
    - '**/*.example'
    - '.codecov.yml'
    - 'errors.toml'
    - 'Jenkinsfile'
    - '.editorconfig'
    - 'hooks/pre-commit'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - '.github/'
    - 'parser/'
    - 'dumpling/'
    - '**/*.sql'
=======
    - "docs/"
    - "br/"
    - ".gitignore"
    - ".gitattributes"
    - ".cilinter.yaml"
    - ".golangci.yml"
    - ".golangci_br.yml"
    - "LICENSES/"
    - "**/BUILD.bazel"
    - "WORKSPACE"
    - ".bazelrc"
    - "**/*.key"
    - "**/*.md"
    - "**/*.json"
    - "**/*.toml"
    - "**/*.pem"
    - "**/*.crt"
    - "**/*.test"
    - "**/*.result"
    - "**/*.example"
    - "**/*.patch"
    - "**/*.bzl"
    - ".codecov.yml"
    - "Jenkinsfile"
    - ".editorconfig"
    - "hooks/pre-commit"
    - "**/go.mod"
    - "**/go.sum"
    - "LICENSE"
    - ".github/"
    - "parser/"
    - "dumpling/"
    - "tidb-binlog/driver/example"
    - "tidb-binlog/proto/go-binlog/secondary_binlog.pb.go"
    - "**/*.sql"
>>>>>>> 5f0c58002... *: refine github actions and makefile (#37235)
  comment: on-failure
