header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: PingCAP, Inc.
  paths-ignore:
    - 'docs/'
    - 'br/'
    - '.gitignore'
    - '.gitattributes'
    - '.golangci.yml'
    - '.golangci_br.yml'
    - 'LICENSES/'
    - '**/*.key'
    - '**/*.md'
    - '**/*.json'
    - '**/*.toml'
    - '**/*.pem'
    - '**/*.crt'
    - '**/*.test'
    - '**/*.result'
    - '**/*.example'
    - '.codecov.yml'
    - 'Jenkinsfile'
    - '.editorconfig'
    - 'hooks/pre-commit'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - '.github/'
    - 'parser/'
    - 'dumpling/'
    - 'tidb-binlog/driver/example'
    - 'tidb-binlog/proto/go-binlog/secondary_binlog.pb.go'
  comment: on-failure
