// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/tidb/pkg/domain/sqlsvrapi (interfaces: KSRuntimeHandle)
//
// Generated by this command:
//
//	mockgen -package mock github.com/pingcap/tidb/pkg/domain/sqlsvrapi KSRuntimeHandle
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	kv "github.com/pingcap/tidb/pkg/kv"
	util "github.com/pingcap/tidb/pkg/util"
	gomock "go.uber.org/mock/gomock"
)

// MockKSRuntimeHandle is a mock of KSRuntimeHandle interface.
type MockKSRuntimeHandle struct {
	ctrl     *gomock.Controller
	recorder *MockKSRuntimeHandleMockRecorder
}

// MockKSRuntimeHandleMockRecorder is the mock recorder for MockKSRuntimeHandle.
type MockKSRuntimeHandleMockRecorder struct {
	mock *MockKSRuntimeHandle
}

// NewMockKSRuntimeHandle creates a new mock instance.
func NewMockKSRuntimeHandle(ctrl *gomock.Controller) *MockKSRuntimeHandle {
	mock := &MockKSRuntimeHandle{ctrl: ctrl}
	mock.recorder = &MockKSRuntimeHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKSRuntimeHandle) EXPECT() *MockKSRuntimeHandleMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockKSRuntimeHandle) ISGOMOCK() struct{} {
	return struct{}{}
}

// Release mocks base method.
func (m *MockKSRuntimeHandle) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockKSRuntimeHandleMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockKSRuntimeHandle)(nil).Release))
}

// Store mocks base method.
func (m *MockKSRuntimeHandle) Store() kv.Storage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(kv.Storage)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockKSRuntimeHandleMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockKSRuntimeHandle)(nil).Store))
}

// SysSessionPool mocks base method.
func (m *MockKSRuntimeHandle) SysSessionPool() util.DestroyableSessionPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SysSessionPool")
	ret0, _ := ret[0].(util.DestroyableSessionPool)
	return ret0
}

// SysSessionPool indicates an expected call of SysSessionPool.
func (mr *MockKSRuntimeHandleMockRecorder) SysSessionPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SysSessionPool", reflect.TypeOf((*MockKSRuntimeHandle)(nil).SysSessionPool))
}
