// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package extension_test

import "testing"

func TestExtensionStmtEvents(t *testing.T) {
	RunExtensionStmtEvents(t)
}
