package parser_test

import (
	"testing"
)

func TestLogReplication(t *testing.T) {
	table := []testCase{
		// CREATE/ALTER
		{"ADMIN CREATE LOG REPLICATION test SOURCE_HOST '127.0.0.1'", true, "ADMIN CREATE LOG REPLICATION `test` SOURCE_HOST = '127.0.0.1'"},
		{"ADMIN CREATE LOG REPLICATION test SOURCE_HOST='127.0.0.1' SOURCE_PORT 3306 SOURCE_USER='root' SOURCE_PASSWORD='pwd' PROTECTION_MODE=MAXIMUM_AVAILABILITY DEGRADE_TIMEOUT '30s'", true, "ADMIN CREATE LOG REPLICATION `test` SOURCE_HOST = '127.0.0.1' SOURCE_PORT = 3306 SOURCE_USER = 'root' SOURCE_PASSWORD = 'pwd' PROTECTION_MODE = MAXIMUM_AVAILABILITY DEGRADE_TIMEOUT = '30s'"},
		{"ADMIN CREATE LOG REPLICATION test SOURCE_HOST='127.0.0.1' DETACHED", true, "ADMIN CREATE LOG REPLICATION `test` SOURCE_HOST = '127.0.0.1' DETACHED"},
		{"ADMIN ALTER LOG REPLICATION test SOURCE_HOST='127.0.0.2' SOURCE_PORT=3307 PROTECTION_MODE MAXIMUM_PROTECTION", true, "ADMIN ALTER LOG REPLICATION `test` SOURCE_HOST = '127.0.0.2' SOURCE_PORT = 3307 PROTECTION_MODE = MAXIMUM_PROTECTION"},
		{"ADMIN ALTER LOG REPLICATION test CHANGE SOURCE TO 123", true, "ADMIN ALTER LOG REPLICATION `test` CHANGE SOURCE TO 123"},

		// PAUSE/RESUME/DROP
		{"ADMIN PAUSE LOG REPLICATION test", true, "ADMIN PAUSE LOG REPLICATION `test`"},
		{"ADMIN RESUME LOG REPLICATION test", true, "ADMIN RESUME LOG REPLICATION `test`"},
		{"ADMIN DROP LOG REPLICATION test", true, "ADMIN DROP LOG REPLICATION `test`"},

		// SWITCHOVER/ACTIVATE STANDBY
		{"ADMIN SWITCHOVER PRIMARY TO 456", true, "ADMIN SWITCHOVER PRIMARY TO 456"},
		{"ADMIN SWITCHOVER AS PRIMARY", true, "ADMIN SWITCHOVER AS PRIMARY"},
		{"ADMIN ACTIVATE STANDBY MODE=FLASHBACK", true, "ADMIN ACTIVATE STANDBY MODE = FLASHBACK"},
		{"ADMIN ACTIVATE STANDBY MODE = FORCE_COMMIT", true, "ADMIN ACTIVATE STANDBY MODE = FORCE_COMMIT"},

		// Error cases
		{"ADMIN CREATE LOG REPLICATION test", false, ""},
		{"ADMIN ALTER LOG REPLICATION test SOURCE_HOST = 127", false, ""},
		{"ADMIN ALTER LOG REPLICATION test CHANGE SOURCE TO '123'", false, ""},
		{"ADMIN CREATE LOG REPLICATION test SOURCE_HOST='127.0.0.1', SOURCE_PORT=3306", false, ""},
		{"ADMIN CREATE LOG REPLICATION test SOURCE_HOST='127.0.0.1' FOO='bar'", false, ""},
		{"ADMIN PAUSE LOG REPLICATION", false, ""},
		{"ADMIN SWITCHOVER PRIMARY TO abc", false, ""},
		{"ADMIN SWITCHOVER AS PRIMARY 123", false, ""},
		{"ADMIN ACTIVATE STANDBY", false, ""},
		{"ADMIN ACTIVATE STANDBY MODE = UNKNOWN", false, ""},
	}
	RunTest(t, table, false)
}
