name: 'TiDB Build'
description: 'Build'
inputs:
  bazelrc:
    required: false
  gcp_sa_key:
    required: false
  go-version:
    required: false
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        BAZELRC: ${{ inputs.bazelrc }}
        GCP_SA_KEY: ${{ inputs.gcp_sa_key }}
      run: |
        echo "111111111" | base64
        echo "22222222222" | base64
        echo "33333333333"