// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestSpanFromContext(t *testing.T) {
	RunSpanFromContext(t)
}

func TestChildSpanFromContext(t *testing.T) {
	RunChildSpanFromContext(t)
}

func TestFollowFrom(t *testing.T) {
	RunFollowFrom(t)
}

func TestCreateSapnBeforeSetupGlobalTracer(t *testing.T) {
	RunCreateSapnBeforeSetupGlobalTracer(t)
}

func TestTreeRelationship(t *testing.T) {
	RunTreeRelationship(t)
}

func TestTraceInfoFromContext(t *testing.T) {
	RunTraceInfoFromContext(t)
}
