run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - typecheck
    - varcheck
    - unused
    - structcheck
    - deadcode
    - bodyclose
    - rowserrcheck
    - makezero
    - prealloc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - rowserrcheck
        - makezero

