run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - unused
    - rowserrcheck
    - prealloc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - rowserrcheck
        - makezero

