codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 4
  round: down

  status:
    project: 
      default:
        threshold: 0.2 #Allow the coverage to drop by threshold%, and posting a success status.
    patch: 
      default:
        target: 0% # trial operation
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  require_head: no     # default yes
  require_base: no     # default yes

ignore:
  - "LICENSES"
  - "*_test.go"       
  - ".git"
  - "*.yml"
  - "*.md"
  - "cmd/.*"       
  - "docs/.*"
  - "vendor/.*"
  - "ddl/failtest/.*"
  - "ddl/testutil/.*"
  - "executor/seqtest/.*"
  - "metrics/.*"
  - "expression/generator/.*"

