codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 4
  round: down
  range: "65...90"

  status:
    project: yes
    patch: no
    changes: no
    default:
      threshold: 0.2   #Allow the coverage to drop by threshold%, and posting a success status.

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "LICENSES"
  - "*_test.go"       
  - ".git"
  - "*.yml"
  - "*.md"
  - "cmd/.*"       
  - "docs/.*"
  - "vendor/.*"
  - "ddl/failtest/.*"
  - "ddl/testutil/.*"
  - "executor/seqtest/.*"
  - "metrics/.*"

