version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - gosec
    - ineffassign
    - intrange
    - lll
    - makezero
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G101
        - G112
      severity: low
      confidence: low
    revive:
      max-open-files: 2048
      confidence: 0.8
      severity: error
      error-code: -1
      warning-code: -1
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: duplicated-imports
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: exported
        - name: if-return
        - name: indent-error-flow
        - name: modifies-parameter
        - name: package-comments
        - name: range
        - name: superfluous-else
        - name: var-naming
        - name: unreachable-code
    staticcheck:
      checks:
        - -SA2002
        - -ST1003
        - S1002
        - S1004
        - S1007
        - S1009
        - S1010
        - S1012
        - S1019
        - S1020
        - S1021
        - S1024
        - S1030
        - SA2*
        - SA3*
        - SA4009
        - SA5*
        - SA6000
        - SA6001
        - SA6005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - makezero
          - rowserrcheck
        path: _test\.go
      - linters:
          - revive
        path: pkg/util/hack/map_abi_go126\.go
        text: "don't use underscores in Go names"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
