linters-settings:
  misspell:
   # locale: US


linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
  #  - bodyclose
    - gofmt
    - ineffassign
    - misspell

run:
  skip-dirs:
    - vendor/
    - docs/
    - bin/
    - tools/
  concurrency: 4
  deadline: 10m



# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.18.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"