version: 2

jobs:
  build:
    docker:
      - image: golang:1.11.3
    working_directory: /go/src/github.com/pingcap/tidb
    steps:
      - checkout
      - run:
          name: "Build & Test"
          command: make dev
      - run:
          name: "Check go mod replace is removed"
          command: ./hack/check_parser_replace.sh
