#!/usr/bin/env python3
# Copyright 2026 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate Rust simple-rune casing from Go's exact unicode.CaseRanges."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT = REPO_ROOT / "rust/crates/tidb-mysql/src/simple_case.rs"
ORACLE = REPO_ROOT / "rust/crates/tidb-ast/tests/data/parser_format_simple_case.tsv"
VERSION_RE = re.compile(r'^const Version = "([^"]+)"$', re.MULTILINE)
ROW_RE = re.compile(
    r"^\s*\{(0x[0-9A-F]+), (0x[0-9A-F]+), d\{([^}]+)\}\},\s*$"
)


def go_root(explicit: Path | None) -> Path:
    if explicit is not None:
        return explicit.resolve()
    result = subprocess.run(
        ["go", "env", "GOROOT"],
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    return Path(result.stdout.strip()).resolve()


def parse_case_ranges(table_source: str) -> tuple[str, list[tuple[int, int, str, str]]]:
    version_match = VERSION_RE.search(table_source)
    if version_match is None:
        raise ValueError("Go unicode table has no Version constant")

    marker = "var _CaseRanges = []CaseRange{"
    try:
        block = table_source.split(marker, 1)[1]
    except IndexError as error:
        raise ValueError("Go unicode table has no _CaseRanges block") from error

    rows: list[tuple[int, int, str, str]] = []
    for line in block.splitlines():
        if line == "}":
            break
        match = ROW_RE.match(line)
        if match is None:
            if line.strip():
                raise ValueError(f"unrecognized Go CaseRange row: {line}")
            continue
        lo, hi, deltas = match.groups()
        values = [value.strip() for value in deltas.split(",")]
        if len(values) != 3:
            raise ValueError(f"CaseRange does not have three deltas: {line}")
        rows.append((int(lo, 16), int(hi, 16), values[0], values[1]))

    if not rows:
        raise ValueError("Go unicode table has an empty _CaseRanges block")
    return version_match.group(1), rows


def rust_delta(value: str) -> str:
    return "UPPER_LOWER" if value == "UpperLower" else value


def map_codepoint(codepoint: int, lo: int, delta: str, case: int) -> int:
    if delta == "UpperLower":
        return lo + (((codepoint - lo) & ~1) | (case & 1))
    return codepoint + int(delta)


def render_oracle(version: str, rows: list[tuple[int, int, str, str]]) -> str:
    output = [
        f"# Go unicode.CaseRanges simple mappings; Unicode {version}.",
        "# codepoint\tuppercase\tlowercase",
    ]
    for lo, hi, upper_delta, lower_delta in rows:
        for codepoint in range(lo, hi + 1):
            upper = map_codepoint(codepoint, lo, upper_delta, 0)
            lower = map_codepoint(codepoint, lo, lower_delta, 1)
            if upper != codepoint or lower != codepoint:
                output.append(f"{codepoint:X}\t{upper:X}\t{lower:X}")
    return "\n".join(output) + "\n"


def render(version: str, rows: list[tuple[int, int, str, str]]) -> str:
    entries = "\n".join(
        "    CaseRange { "
        f"lo: 0x{lo:04X}, hi: 0x{hi:04X}, "
        f"upper: {rust_delta(upper)}, lower: {rust_delta(lower)} "
        "},"
        for lo, hi, upper, lower in rows
    )
    return f'''// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by scripts/generate-go-simple-case.py; DO NOT EDIT.
// Source: Go unicode.CaseRanges, Unicode {version}.

/// Unicode version behind Go's exact simple-rune case mappings.
pub const GO_UNICODE_VERSION: &str = "{version}";

const UPPER_CASE: u8 = 0;
const LOWER_CASE: u8 = 1;
const UPPER_LOWER: i32 = 0x110000;

#[derive(Clone, Copy)]
struct CaseRange {{
    lo: u32,
    hi: u32,
    upper: i32,
    lower: i32,
}}

#[rustfmt::skip]
const CASE_RANGES: &[CaseRange] = &[
{entries}
];

/// Applies Go `strings.ToUpper` simple-rune mappings without full-case expansion.
pub fn to_uppercase(value: &str) -> String {{
    map_string(value, UPPER_CASE)
}}

/// Applies Go `strings.ToLower` simple-rune mappings without full-case expansion.
pub fn to_lowercase(value: &str) -> String {{
    map_string(value, LOWER_CASE)
}}

fn map_string(value: &str, case: u8) -> String {{
    let mut output = String::with_capacity(value.len());
    for character in value.chars() {{
        output.push(map_character(character, case));
    }}
    output
}}

fn map_character(character: char, case: u8) -> char {{
    let codepoint = character as u32;
    let mut low = 0;
    let mut high = CASE_RANGES.len();
    while low < high {{
        let middle = low + (high - low) / 2;
        let range = CASE_RANGES[middle];
        if codepoint < range.lo {{
            high = middle;
        }} else if codepoint > range.hi {{
            low = middle + 1;
        }} else {{
            let delta = if case == UPPER_CASE {{
                range.upper
            }} else {{
                range.lower
            }};
            let mapped = if delta == UPPER_LOWER {{
                range.lo + ((codepoint - range.lo) & !1 | u32::from(case & 1))
            }} else {{
                codepoint.wrapping_add_signed(delta)
            }};
            return char::from_u32(mapped).expect("Go CaseRanges must map to a Unicode scalar");
        }}
    }}
    character
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--go-root", type=Path)
    args = parser.parse_args()

    source = (go_root(args.go_root) / "src/unicode/tables.go").read_text(
        encoding="utf-8"
    )
    version, rows = parse_case_ranges(source)
    generated = render(version, rows)
    oracle = render_oracle(version, rows)
    if args.check:
        for path, expected in ((OUTPUT, generated), (ORACLE, oracle)):
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                print(
                    f"{path.relative_to(REPO_ROOT)} is stale; regenerate with "
                    "python3 rust/scripts/generate-go-simple-case.py",
                    file=sys.stderr,
                )
                return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    ORACLE.parent.mkdir(parents=True, exist_ok=True)
    ORACLE.write_text(oracle, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
