// Code generated by mega-gen. DO NOT EDIT.

package sqlescape_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("util_sqlescape", "ReserveBuffer", RunReserveBuffer)
	register.Register("util_sqlescape", "EscapeBackslash", RunEscapeBackslash)
	register.Register("util_sqlescape", "EscapeSQL", RunEscapeSQL)
	register.Register("util_sqlescape", "MustUtils", RunMustUtils)
	register.Register("util_sqlescape", "EscapeString", RunEscapeString)
}
