// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestCheckRequirementsTiFlash(t *testing.T) {
	RunCheckRequirementsTiFlash(t)
}

func TestGetRegionSplitSizeKeys(t *testing.T) {
	RunGetRegionSplitSizeKeys(t)
}
