// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package multivaluedindex

import "github.com/pingcap/tidb/pkg/testkit/mega/register"

func init() {
	register.Register("expression/test/multivaluedindex", "WriteMultiValuedIndex", RunWriteMultiValuedIndex)
	register.Register("expression/test/multivaluedindex", "WriteMultiValuedIndexComposite", RunWriteMultiValuedIndexComposite)
	register.Register("expression/test/multivaluedindex", "WriteMultiValuedIndexPartitionTable", RunWriteMultiValuedIndexPartitionTable)
	register.Register("expression/test/multivaluedindex", "WriteMultiValuedIndexUnique", RunWriteMultiValuedIndexUnique)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "expression/test/multivaluedindex" {
			InitForMega()
		}
	})
}
