// Code generated by mega-gen. DO NOT EDIT.

package test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("parser_types", "FieldType", RunFieldType)
	register.Register("parser_types", "HasCharsetFromStmt", RunHasCharsetFromStmt)
	register.Register("parser_types", "EnumSetFlen", RunEnumSetFlen)
	register.Register("parser_types", "FieldTypeEqual", RunFieldTypeEqual)
	register.Register("parser_types", "CompactStr", RunCompactStr)
}
