// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestDDLAfterLoad(t *testing.T) {
	RunDDLAfterLoad(t)
}

func TestDDLTable(t *testing.T) {
	RunDDLTable(t)
}

func TestSystemTableDDLHasNoEvent(t *testing.T) {
	RunSystemTableDDLHasNoEvent(t)
}

func TestTruncateTable(t *testing.T) {
	RunTruncateTable(t)
}

func TestTruncateAPartitionedTable(t *testing.T) {
	RunTruncateAPartitionedTable(t)
}

func TestDDLHistogram(t *testing.T) {
	RunDDLHistogram(t)
}

func TestDDLPartition(t *testing.T) {
	RunDDLPartition(t)
}

func TestReorgPartitions(t *testing.T) {
	RunReorgPartitions(t)
}

func TestIncreasePartitionCountOfHashPartitionTable(t *testing.T) {
	RunIncreasePartitionCountOfHashPartitionTable(t)
}

func TestDecreasePartitionCountOfHashPartitionTable(t *testing.T) {
	RunDecreasePartitionCountOfHashPartitionTable(t)
}

func TestTruncateAPartition(t *testing.T) {
	RunTruncateAPartition(t)
}

func TestTruncateAPartitionAndDropTableImmediately(t *testing.T) {
	RunTruncateAPartitionAndDropTableImmediately(t)
}

func TestTruncateAHashPartition(t *testing.T) {
	RunTruncateAHashPartition(t)
}

func TestTruncatePartitions(t *testing.T) {
	RunTruncatePartitions(t)
}

func TestDropAPartition(t *testing.T) {
	RunDropAPartition(t)
}

func TestDropPartitions(t *testing.T) {
	RunDropPartitions(t)
}

func TestExchangeAPartition(t *testing.T) {
	RunExchangeAPartition(t)
}

func TestExchangeAPartitionAndDropTableImmediately(t *testing.T) {
	RunExchangeAPartitionAndDropTableImmediately(t)
}

func TestRemovePartitioning(t *testing.T) {
	RunRemovePartitioning(t)
}

func TestAddPartitioning(t *testing.T) {
	RunAddPartitioning(t)
}

func TestDropSchema(t *testing.T) {
	RunDropSchema(t)
}

func TestExchangePartition(t *testing.T) {
	RunExchangePartition(t)
}

func TestDumpStatsDeltaBeforeHandleDDLEvent(t *testing.T) {
	RunDumpStatsDeltaBeforeHandleDDLEvent(t)
}

func TestDumpStatsDeltaBeforeHandleAddColumnEvent(t *testing.T) {
	RunDumpStatsDeltaBeforeHandleAddColumnEvent(t)
}
