[package]
name = "tidb-tablecodec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Complete TiDB table, record, row, and index codec."
autotests = false
build = "../../scripts/aggregate-tests.rs"

[lints]
workspace = true

[dependencies]
chrono.workspace = true
chrono-tz.workspace = true
tidb-codec = { path = "../tidb-codec" }
tidb-datatype = { path = "../tidb-datatype" }
tidb-txnkv = { path = "../tidb-txnkv" }

[[test]]
name = "all"
path = "tests/all.rs"

[[bench]]
name = "tablecodec"
harness = false
