// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Names registered in Go's `pkg/expression/builtin.go::funcs`.
///
/// This is deliberately wider than the Rust evaluator. A registered but not
/// yet evaluated function remains an implementation-boundary 1105; only a
/// name absent from this set is TiDB's 1305 "FUNCTION ... does not exist".
pub(crate) fn is_registered_builtin(name: &str) -> bool {
    const NAMES: &[&str] = &[
        "'tidb`.(dateliteral",
        "'tidb`.(timeliteral",
        "'tidb`.(timestampliteral",
        "abs",
        "acos",
        "adddate",
        "addtime",
        "aes_decrypt",
        "aes_encrypt",
        "and",
        "any_value",
        "ascii",
        "asin",
        "atan",
        "atan2",
        "benchmark",
        "bin",
        "bin_to_uuid",
        "bit_count",
        "bit_length",
        "bitand",
        "bitneg",
        "bitor",
        "bitxor",
        "case",
        "ceil",
        "ceiling",
        "char_func",
        "char_length",
        "character_length",
        "charset",
        "coalesce",
        "coercibility",
        "collation",
        "compress",
        "concat",
        "concat_ws",
        "connection_id",
        "conv",
        "convert",
        "convert_tz",
        "cos",
        "cot",
        "crc32",
        "curdate",
        "current_date",
        "current_resource_group",
        "current_role",
        "current_time",
        "current_timestamp",
        "current_user",
        "curtime",
        "database",
        "date",
        "date_add",
        "date_format",
        "date_sub",
        "datediff",
        "day",
        "dayname",
        "dayofmonth",
        "dayofweek",
        "dayofyear",
        "decode",
        "default_func",
        "degrees",
        "div",
        "elt",
        "encode",
        "eq",
        "exp",
        "export_set",
        "extract",
        "field",
        "find_in_set",
        "floor",
        "format",
        "format_bytes",
        "format_nano_time",
        "found_rows",
        "from_base64",
        "from_days",
        "from_unixtime",
        "fts_match_word",
        "ge",
        "get_format",
        "get_lock",
        "getparam",
        "greatest",
        "grouping",
        "gt",
        "hex",
        "hour",
        "if",
        "ifnull",
        "ilike",
        "in",
        "inet6_aton",
        "inet6_ntoa",
        "inet_aton",
        "inet_ntoa",
        "insert_func",
        "instr",
        "intdiv",
        "interval",
        "is_free_lock",
        "is_ipv4",
        "is_ipv4_compat",
        "is_ipv4_mapped",
        "is_ipv6",
        "is_used_lock",
        "is_uuid",
        "isfalse",
        "isnull",
        "istrue",
        "istrue_with_null",
        "json_array",
        "json_array_append",
        "json_array_insert",
        "json_contains",
        "json_contains_path",
        "json_depth",
        "json_extract",
        "json_insert",
        "json_keys",
        "json_length",
        "json_memberof",
        "json_merge",
        "json_merge_patch",
        "json_merge_preserve",
        "json_object",
        "json_overlaps",
        "json_pretty",
        "json_quote",
        "json_remove",
        "json_replace",
        "json_schema_valid",
        "json_search",
        "json_set",
        "json_storage_free",
        "json_storage_size",
        "json_type",
        "json_unquote",
        "json_valid",
        "last_day",
        "last_insert_id",
        "lastval",
        "lcase",
        "le",
        "least",
        "left",
        "leftshift",
        "length",
        "like",
        "ln",
        "load_file",
        "localtime",
        "localtimestamp",
        "locate",
        "log",
        "log10",
        "log2",
        "lower",
        "lpad",
        "lt",
        "ltrim",
        "make_set",
        "makedate",
        "maketime",
        "match_against",
        "md5",
        "microsecond",
        "mid",
        "minus",
        "minute",
        "mod",
        "month",
        "monthname",
        "mul",
        "name_const",
        "ne",
        "nextval",
        "not",
        "now",
        "nulleq",
        "oct",
        "octet_length",
        "or",
        "ord",
        "password",
        "period_add",
        "period_diff",
        "pi",
        "plus",
        "position",
        "pow",
        "power",
        "quarter",
        "quote",
        "radians",
        "rand",
        "random_bytes",
        "regexp",
        "regexp_instr",
        "regexp_like",
        "regexp_replace",
        "regexp_substr",
        "release_all_locks",
        "release_lock",
        "repeat",
        "replace",
        "reverse",
        "right",
        "rightshift",
        "round",
        "row",
        "row_count",
        "rpad",
        "rtrim",
        "schema",
        "sec_to_time",
        "second",
        "session_user",
        "setval",
        "setvar",
        "sha",
        "sha1",
        "sha2",
        "sign",
        "sin",
        "sleep",
        "sm3",
        "space",
        "sqrt",
        "str_to_date",
        "strcmp",
        "subdate",
        "substr",
        "substring",
        "substring_index",
        "subtime",
        "sysdate",
        "system_user",
        "tan",
        "tidb_bounded_staleness",
        "tidb_current_tso",
        "tidb_decode_binary_plan",
        "tidb_decode_key",
        "tidb_decode_plan",
        "tidb_decode_sql_digests",
        "tidb_encode_index_key",
        "tidb_encode_record_key",
        "tidb_encode_sql_digest",
        "tidb_is_ddl_owner",
        "tidb_mvcc_info",
        "tidb_parse_tso",
        "tidb_parse_tso_logical",
        "tidb_row_checksum",
        "tidb_shard",
        "tidb_version",
        "time",
        "time_format",
        "time_to_sec",
        "timediff",
        "timestamp",
        "timestampadd",
        "timestampdiff",
        "to_base64",
        "to_days",
        "to_seconds",
        "translate",
        "trim",
        "truncate",
        "ucase",
        "unaryminus",
        "uncompress",
        "uncompressed_length",
        "unhex",
        "unix_timestamp",
        "upper",
        "user",
        "utc_date",
        "utc_time",
        "utc_timestamp",
        "uuid",
        "uuid_short",
        "uuid_timestamp",
        "uuid_to_bin",
        "uuid_v4",
        "uuid_v7",
        "uuid_version",
        "validate_password_strength",
        "vec_as_text",
        "vec_cosine_distance",
        "vec_dims",
        "vec_from_text",
        "vec_l1_distance",
        "vec_l2_distance",
        "vec_l2_norm",
        "vec_negative_inner_product",
        "version",
        "vitess_hash",
        "week",
        "weekday",
        "weekofyear",
        "weight_string",
        "xor",
        "year",
        "yearweek",
    ];
    NAMES.binary_search(&name).is_ok()
}

pub(crate) fn unresolved_error(name: &str, current_database: Option<String>) -> crate::EvalError {
    // These names are in Go's registry so the parser can recognize them, but
    // their function classes deliberately return ErrFunctionNotExists.
    let unavailable = match name {
        "default_func" => Some("DEFAULT"),
        "uuid_short" => Some("UUID_SHORT"),
        _ => None,
    };
    if let Some(display_name) = unavailable {
        return crate::EvalError::FunctionNotExists(display_name.to_owned());
    }
    if is_registered_builtin(name) {
        return crate::EvalError::Unsupported("this builtin is not yet built for chunk evaluation");
    }
    match current_database {
        Some(database) if !database.is_empty() => {
            crate::EvalError::FunctionNotExists(format!("{database}.{name}"))
        }
        _ => crate::EvalError::NoDatabaseSelected,
    }
}

#[cfg(test)]
mod tests {
    use super::{is_registered_builtin, unresolved_error};
    use crate::EvalError;

    #[test]
    fn source_registry_distinguishes_unported_from_unknown() {
        assert!(is_registered_builtin("get_lock"));
        assert!(is_registered_builtin("last_insert_id"));
        assert!(!is_registered_builtin("no_such_fn"));
    }

    #[test]
    fn registered_but_unavailable_functions_keep_source_names() {
        assert_eq!(
            unresolved_error("uuid_short", Some("test".to_owned())),
            EvalError::FunctionNotExists("UUID_SHORT".to_owned())
        );
        assert_eq!(
            unresolved_error("default_func", None),
            EvalError::FunctionNotExists("DEFAULT".to_owned())
        );
    }
}
