// Code generated by mega-gen. DO NOT EDIT.

package systimemon_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("util_systimemon", "SystimeMonitor", RunSystimeMonitor)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "util_systimemon" {
			InitForMega()
		}
	})
}
