// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package session_test

import "testing"

func TestGetStartMode(t *testing.T) {
	RunGetStartMode(t)
}

func TestDDLTableVersionTables(t *testing.T) {
	RunDDLTableVersionTables(t)
}

func TestMemArbitratorSession(t *testing.T) {
	RunMemArbitratorSession(t)
}
