load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tidb",
    srcs = ["features.go"],
    importpath = "github.com/pingcap/tidb/pkg/parser/tidb",
    visibility = ["//visibility:public"],
)

go_test(
    name = "tidb_test",
    srcs = ["features_test.go"],
    embed = [":tidb"],
)
