// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package internal_test

import "testing"

func TestPacketIOWrite(t *testing.T) {
	RunPacketIOWrite(t)
}

func TestPacketIOWriteCompressed(t *testing.T) {
	RunPacketIOWriteCompressed(t)
}

func TestPacketIORead(t *testing.T) {
	RunPacketIORead(t)
}

func TestCompressedWriterShort(t *testing.T) {
	RunCompressedWriterShort(t)
}

func TestCompressedWriterLong(t *testing.T) {
	RunCompressedWriterLong(t)
}

func TestCompressedReaderShort(t *testing.T) {
	RunCompressedReaderShort(t)
}

func TestCompressedReaderLong(t *testing.T) {
	RunCompressedReaderLong(t)
}

func TestSubHeaderWithWrongSequenceNumber(t *testing.T) {
	RunSubHeaderWithWrongSequenceNumber(t)
}
