{
 "title": "Test-Cluster-TiDB-Resource-Control",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s-cluster",
    "query": {
     "query": "label_values(pd_cluster_status, k8s_cluster)"
    }
   },
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": {
     "query": "label_values(pd_cluster_status{k8s_cluster=\"$k8s_cluster\"}, tidb_cluster)"
    }
   },
   {
    "name": "tidb_instance",
    "label": "TiDB Instance",
    "query": {
     "query": "label_values(tidb_server_connections{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RU",
   "type": "graph",
   "description": "The total request unit cost for all resource groups.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "RU Per Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "(sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) + sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "RRU",
   "type": "graph",
   "description": "The read request unit cost for all resource groups.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "RRU Per Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(resource_manager_resource_unit_read_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "WRU",
   "type": "graph",
   "description": "The write request unit cost for all resource groups.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "WRU Per Query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(resource_manager_resource_unit_write_request_unit_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Available RU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resource_manager_resource_unit_available_ru{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query Max Duration",
   "type": "graph",
   "description": "TiDB max durations for different resource group",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(tidb_server_handle_query_duration_seconds_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le,resource_group))",
     "legendFormat": "{{resource_group}}"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name, type)",
       "legendFormat": "{{name}}-{{type}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}-total"
      }
     ]
    },
    {
     "title": "KV Request Count Per Query",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"read\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}-read"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}-write"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"read\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total-read"
      },
      {
       "expr": "sum(rate(resource_manager_resource_request_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total-write"
      }
     ]
    },
    {
     "title": "Bytes Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Bytes Read Per Query",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_read_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Bytes Written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Bytes Written Per Query",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_write_byte_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(rate(tidb_session_resource_group_query_total{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "KV CPU Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_kv_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_kv_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "SQL CPU Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_resource_sql_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (name)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(resource_manager_resource_sql_cpu_time_ms_sum{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Resource groups",
     "type": "graph",
     "description": "The current active resource group",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "resource_manager_client_resource_group_status{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Total KV Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance) + sum(rate(resource_manager_client_request_fail{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name) + sum(rate(resource_manager_client_request_fail{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Failed KV Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_client_request_fail{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(rate(resource_manager_client_request_fail{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Successful KV Request Wait Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(resource_manager_client_request_success_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name, le))",
       "legendFormat": "{{instance}}-{{name}}-99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(resource_manager_client_request_success_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name, le))",
       "legendFormat": "{{instance}}-{{name}}-90"
      }
     ]
    },
    {
     "title": "Successful KV Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(rate(resource_manager_client_request_success_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    },
    {
     "title": "Token Request Handle Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(resource_manager_client_token_request_duration_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-{{name}}-99"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(resource_manager_client_token_request_duration_bucket{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, le))",
       "legendFormat": "{{instance}}-{{name}}-999"
      }
     ]
    },
    {
     "title": "Token Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(resource_manager_client_token_request_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "sum(delta(resource_manager_client_token_request_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", type=\"success\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-successful"
      },
      {
       "expr": "sum(delta(resource_manager_client_token_request_duration_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\", type=\"fail\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-failed"
      },
      {
       "expr": "sum(delta(resource_manager_client_token_request_resource_group{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$tidb_instance\"}[1m])) by (instance, name)",
       "legendFormat": "{{instance}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backgroun Task Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Background Task CPU Limit",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "tikv_resource_control_background_quota_limiter{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\", type=\"cpu\"}",
       "legendFormat": "{{name}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task IO Limit",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tikv_resource_control_background_quota_limiter{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\", type=\"io\"}",
       "legendFormat": "{{name}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task CPU Consumption ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_resource_control_background_resource_consumption{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\", type=\"cpu\"}[1m])",
       "legendFormat": "{{name}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task IO Consumption ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_resource_control_background_resource_consumption{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\", type=\"io\"}[1m])",
       "legendFormat": "{{name}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Background Task Total Wait Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_resource_control_background_task_wait_duration{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{name}}-{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}