load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "export",
    srcs = [
        "pipeline.go",
        "proto.go",
        "scan.go",
        "scheduler.go",
        "split.go",
        "task_executor.go",
        "writer.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/dxf/export",
    visibility = ["//visibility:public"],
    deps = [
        "//br/pkg/gc",
        "//pkg/config/kerneltype",
        "//pkg/distsql",
        "//pkg/distsql/context",
        "//pkg/dumpformat/csvfile",
        "//pkg/dxf/framework/handle",
        "//pkg/dxf/framework/proto",
        "//pkg/dxf/framework/scheduler",
        "//pkg/dxf/framework/storage",
        "//pkg/dxf/framework/taskexecutor",
        "//pkg/dxf/framework/taskexecutor/execute",
        "//pkg/expression/exprstatic",
        "//pkg/format/textrow",
        "//pkg/kv",
        "//pkg/lightning/common",
        "//pkg/meta/model",
        "//pkg/objstore",
        "//pkg/objstore/objectio",
        "//pkg/objstore/storeapi",
        "//pkg/parser/charset",
        "//pkg/parser/mysql",
        "//pkg/sessionctx/stmtctx",
        "//pkg/store/copr",
        "//pkg/store/helper",
        "//pkg/table/tables",
        "//pkg/tablecodec",
        "//pkg/types",
        "//pkg/util/backoff",
        "//pkg/util/chunk",
        "//pkg/util/context",
        "//pkg/util/logutil",
        "//pkg/util/mathutil",
        "//pkg/util/timeutil",
        "@com_github_pingcap_errors//:errors",
        "@com_github_pingcap_tipb//go-tipb",
        "@com_github_tikv_client_go_v2//tikv",
        "@com_github_tikv_client_go_v2//util",
        "@org_golang_x_sync//errgroup",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "export_test",
    timeout = "short",
    srcs = [
        "scheduler_test.go",
        "split_test.go",
        "writer_test.go",
    ],
    embed = [":export"],
    flaky = True,
    shard_count = 12,
    deps = [
        "//pkg/dumpformat/csvfile",
        "//pkg/dxf/framework/proto",
        "//pkg/kv",
        "//pkg/meta/model",
        "//pkg/objstore",
        "//pkg/objstore/storeapi",
        "//pkg/parser/ast",
        "//pkg/parser/mysql",
        "//pkg/tablecodec",
        "//pkg/types",
        "//pkg/util/chunk",
        "@com_github_stretchr_testify//require",
    ],
)
