[package]
name = "tidb-stats-handle-usage-collector"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "TiDB generic statistics usage collector."

[dependencies]
crossbeam-channel = "0.5"

[lints]
workspace = true
