#!/bin/sh

set -e

echo "[$(date)] Executing bin/dumpling..."

bin/dumpling -u "$DUMPLING_TEST_USER" -h 127.0.0.1 \
    -P "$DUMPLING_TEST_PORT" -B "$DUMPLING_TEST_DATABASE" \
    -o "$DUMPLING_OUTPUT_DIR" "$@"
