// Code generated by mega-gen. DO NOT EDIT.

package initstats_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("statistics/handle/handletest/initstats", "LiteInitStatsWithTableIDs", RunLiteInitStatsWithTableIDs)
	register.Register("statistics/handle/handletest/initstats", "NonLiteInitStatsWithTableIDs", RunNonLiteInitStatsWithTableIDs)
	register.Register("statistics/handle/handletest/initstats", "ConcurrentlyInitStatsWithMemoryLimit", RunConcurrentlyInitStatsWithMemoryLimit)
	register.Register("statistics/handle/handletest/initstats", "ConcurrentlyInitStatsWithoutMemoryLimit", RunConcurrentlyInitStatsWithoutMemoryLimit)
	register.Register("statistics/handle/handletest/initstats", "DropTableBeforeConcurrentlyInitStats", RunDropTableBeforeConcurrentlyInitStats)
	register.Register("statistics/handle/handletest/initstats", "DropTableBeforeNonLiteInitStats", RunDropTableBeforeNonLiteInitStats)
	register.Register("statistics/handle/handletest/initstats", "SkipStatsInitWithSkipInitStats", RunSkipStatsInitWithSkipInitStats)
	register.Register("statistics/handle/handletest/initstats", "NonLiteInitStatsAndCheckTheLastTableStats", RunNonLiteInitStatsAndCheckTheLastTableStats)
}
