[package]
name = "tidb-stats-handle-initstats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "TiDB statistics initialization workers."

[lints]
workspace = true

[dependencies]
tidb-config = { path = "../tidb-config" }
tidb-log = { path = "../tidb-log" }
tidb-util = { path = "../tidb-util" }
