# Importer Configuration.

[ddl]
table-sql = "create table t(a int primary key, b double, c varchar(10), d date unique, e time unique, f timestamp unique, g date unique, h datetime unique, i year);"

index-sql = "create unique index u_b on t(b);"

[stats]
stats-file-path = "./stats.json"

[sys]
log-level = "info"

worker-count = 2
job-count = 10000
# batch insert rows
batch = 1000

[db]
host = "127.0.0.1"
user = "root"
password = ""
name = "test"
port = 4000
