load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "godump_lib",
    srcs = ["main.go"],
    importpath = "github.com/pingcap/tidb/rust/difftests/godump",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/parser",
        "//pkg/parser/ast",
        "//pkg/parser/format",
        "//pkg/types/parser_driver",
    ],
)

go_binary(
    name = "godump",
    embed = [":godump_lib"],
    visibility = ["//visibility:public"],
)
