load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "util",
    srcs = [
        "buffered_read_conn.go",
        "socket_probe_other.go",
        "socket_probe_unix.go",
        "util.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/server/internal/util",
    visibility = ["//pkg/server:__subpackages__"],
    deps = [
        "//pkg/config",
        "//pkg/parser/charset",
    ],
)

go_test(
    name = "util_test",
    timeout = "short",
    srcs = [
        "buffered_read_conn_test.go",
        "util_test.go",
    ],
    embed = [":util"],
    flaky = True,
    shard_count = 10,
    deps = [
        "@com_github_blacktear23_go_proxyprotocol//:go-proxyprotocol",
        "@com_github_stretchr_testify//require",
    ],
)
