// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package mergejoin_test

import "github.com/pingcap/tidb/pkg/testkit/mega/register"

func init() {
	register.Register("executor/join/test/mergejoin", "MergeJoinInDisk", RunMergeJoinInDisk)
	register.Register("executor/join/test/mergejoin", "ShuffleMergeJoinInDisk", RunShuffleMergeJoinInDisk)
	register.Register("executor/join/test/mergejoin", "VectorizedMergeJoin", RunVectorizedMergeJoin)
	register.Register("executor/join/test/mergejoin", "VectorizedShuffleMergeJoin", RunVectorizedShuffleMergeJoin)
}
