// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package tests_test

import "testing"

func TestSysVar(t *testing.T) {
	RunSysVar(t)
}

func TestIndexJoinBuildV2SysVarCompatibility(t *testing.T) {
	RunIndexJoinBuildV2SysVarCompatibility(t)
}

func TestError(t *testing.T) {
	RunError(t)
}

func TestRegistrationOfNewSysVar(t *testing.T) {
	RunRegistrationOfNewSysVar(t)
}

func TestIntValidation(t *testing.T) {
	RunIntValidation(t)
}

func TestPerformanceSchemaSessionConnectAttrsSizeValidation(t *testing.T) {
	RunPerformanceSchemaSessionConnectAttrsSizeValidation(t)
}

func TestUintValidation(t *testing.T) {
	RunUintValidation(t)
}

func TestEnumValidation(t *testing.T) {
	RunEnumValidation(t)
}

func TestDurationValidation(t *testing.T) {
	RunDurationValidation(t)
}

func TestFloatValidation(t *testing.T) {
	RunFloatValidation(t)
}

func TestBoolValidation(t *testing.T) {
	RunBoolValidation(t)
}

func TestTimeValidation(t *testing.T) {
	RunTimeValidation(t)
}

func TestGetNativeValType(t *testing.T) {
	RunGetNativeValType(t)
}

func TestDeprecation(t *testing.T) {
	RunDeprecation(t)
}

func TestBuiltInCase(t *testing.T) {
	RunBuiltInCase(t)
}

func TestIsNoop(t *testing.T) {
	RunIsNoop(t)
}

func TestDefaultValuesAreSettable(t *testing.T) {
	RunDefaultValuesAreSettable(t)
}

func TestLimitBetweenVariable(t *testing.T) {
	RunLimitBetweenVariable(t)
}

func TestSysVarNameIsLowerCase(t *testing.T) {
	RunSysVarNameIsLowerCase(t)
}

func TestSettersandGetters(t *testing.T) {
	RunSettersandGetters(t)
}

func TestScopeToString(t *testing.T) {
	RunScopeToString(t)
}

func TestValidateWithRelaxedValidation(t *testing.T) {
	RunValidateWithRelaxedValidation(t)
}

func TestValidateInternalSessionVariable(t *testing.T) {
	RunValidateInternalSessionVariable(t)
}

func TestInstanceConfigHasMatchingSysvar(t *testing.T) {
	RunInstanceConfigHasMatchingSysvar(t)
}

func TestInstanceScope(t *testing.T) {
	RunInstanceScope(t)
}

func TestSetSysVar(t *testing.T) {
	RunSetSysVar(t)
}

func TestSkipSysvarCache(t *testing.T) {
	RunSkipSysvarCache(t)
}

func TestTimeValidationWithTimezone(t *testing.T) {
	RunTimeValidationWithTimezone(t)
}

func TestOrderByDependency(t *testing.T) {
	RunOrderByDependency(t)
}
