// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package join_test

import "testing"

func TestHashJoinRuntimeStats(t *testing.T) {
	RunHashJoinRuntimeStats(t)
}

func TestIndexJoinRuntimeStats(t *testing.T) {
	RunIndexJoinRuntimeStats(t)
}
