// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package join_test

import "testing"

func TestJoinTableMetaKeyMode(t *testing.T) {
	RunJoinTableMetaKeyMode(t)
}

func TestJoinTableMetaKeyInlinedAndFixed(t *testing.T) {
	RunJoinTableMetaKeyInlinedAndFixed(t)
}

func TestReadNullMapThreadSafe(t *testing.T) {
	RunReadNullMapThreadSafe(t)
}

func TestJoinTableMetaSerializedMode(t *testing.T) {
	RunJoinTableMetaSerializedMode(t)
}

func TestJoinTableMetaRowColumnsOrder(t *testing.T) {
	RunJoinTableMetaRowColumnsOrder(t)
}

func TestJoinTableMetaNullMapLength(t *testing.T) {
	RunJoinTableMetaNullMapLength(t)
}
