// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package join_test

import "testing"

func TestLeftOuterJoinProbeBasic(t *testing.T) {
	RunLeftOuterJoinProbeBasic(t)
}

func TestLeftOuterJoinProbeAllJoinKeys(t *testing.T) {
	RunLeftOuterJoinProbeAllJoinKeys(t)
}

func TestLeftOuterJoinProbeOtherCondition(t *testing.T) {
	RunLeftOuterJoinProbeOtherCondition(t)
}

func TestLeftOuterJoinProbeWithSel(t *testing.T) {
	RunLeftOuterJoinProbeWithSel(t)
}
