[package]
name = "tidb-datatype"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Core TiDB SQL data types."
autotests = false
build = "../../scripts/aggregate-tests.rs"

[lints]
workspace = true

[dependencies]
chrono.workspace = true
chrono-tz.workspace = true
encoding_rs.workspace = true
serde.workspace = true
serde_json.workspace = true
tidb-error = { path = "../tidb-error" }

[dev-dependencies]
sha2 = { workspace = true }

[[test]]
name = "all"
path = "tests/all.rs"

[[bench]]
name = "collate"
harness = false

[[bench]]
name = "json"
harness = false

[[bench]]
name = "time"
harness = false

[[bench]]
name = "decimal"
harness = false

[[bench]]
name = "datum"
harness = false

[[bin]]
name = "fuzz-json-extract"
path = "fuzz/json_extract.rs"
test = false
bench = false
