// Code generated by mega-gen. DO NOT EDIT.

package extsort_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("util_extsort", "DiskSorterCommon", RunDiskSorterCommon)
	register.Register("util_extsort", "DiskSorterCommonParallel", RunDiskSorterCommonParallel)
	register.Register("util_extsort", "DiskSorterReopen", RunDiskSorterReopen)
	register.Register("util_extsort", "KVStatsCollector", RunKVStatsCollector)
	register.Register("util_extsort", "MakeFilename", RunMakeFilename)
	register.Register("util_extsort", "ParseFilename", RunParseFilename)
	register.Register("util_extsort", "SSTWriter", RunSSTWriter)
	register.Register("util_extsort", "SSTWriterEmpty", RunSSTWriterEmpty)
	register.Register("util_extsort", "SSTWriterError", RunSSTWriterError)
	register.Register("util_extsort", "SSTReaderPool", RunSSTReaderPool)
	register.Register("util_extsort", "SSTReaderPoolParallel", RunSSTReaderPoolParallel)
	register.Register("util_extsort", "SSTIter", RunSSTIter)
	register.Register("util_extsort", "MergingIter", RunMergingIter)
	register.Register("util_extsort", "PickCompactionFiles", RunPickCompactionFiles)
	register.Register("util_extsort", "SplitCompactionFiles", RunSplitCompactionFiles)
	register.Register("util_extsort", "BuildCompactions", RunBuildCompactions)
}
