// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package mega

import (
	// Import test packages to trigger their init() functions
	_ "github.com/pingcap/tidb/pkg/bindinfo/test"
	_ "github.com/pingcap/tidb/pkg/bindinfo/tests/test"
	_ "github.com/pingcap/tidb/pkg/config/kerneltype/test"
	_ "github.com/pingcap/tidb/pkg/ddl/ingest/test"
	_ "github.com/pingcap/tidb/pkg/ddl/notifier/test"
	_ "github.com/pingcap/tidb/pkg/ddl/placement/test"
	_ "github.com/pingcap/tidb/pkg/ddl/schematracker/test"
	_ "github.com/pingcap/tidb/pkg/ddl/schemaver/test"
	_ "github.com/pingcap/tidb/pkg/ddl/serverstate/test"
	_ "github.com/pingcap/tidb/pkg/ddl/session/test"
	_ "github.com/pingcap/tidb/pkg/ddl/systable/test"
	_ "github.com/pingcap/tidb/pkg/ddl/test"
	_ "github.com/pingcap/tidb/pkg/ddl/tests/fastcreatetable/test"
	_ "github.com/pingcap/tidb/pkg/ddl/tests/multivaluedindex/test"
	_ "github.com/pingcap/tidb/pkg/ddl/tests/partition/test"
	_ "github.com/pingcap/tidb/pkg/ddl/tests/serial/test"
	_ "github.com/pingcap/tidb/pkg/ddl/util/test"
	_ "github.com/pingcap/tidb/pkg/domain/crossks/test"
	_ "github.com/pingcap/tidb/pkg/domain/globalconfigsync/test"
	_ "github.com/pingcap/tidb/pkg/domain/test"
	_ "github.com/pingcap/tidb/pkg/dxf/framework/handle/test"
	_ "github.com/pingcap/tidb/pkg/dxf/framework/integrationtests/test"
	_ "github.com/pingcap/tidb/pkg/dxf/framework/planner/test"
	_ "github.com/pingcap/tidb/pkg/dxf/framework/storage/test"
	_ "github.com/pingcap/tidb/pkg/dxf/importinto/conflictedkv/test"
	_ "github.com/pingcap/tidb/pkg/dxf/importinto/jobhistory/test"
	_ "github.com/pingcap/tidb/pkg/dxf/importinto/test"
	_ "github.com/pingcap/tidb/pkg/errctx/test"
	_ "github.com/pingcap/tidb/pkg/executor/aggregate/test"
	_ "github.com/pingcap/tidb/pkg/executor/importer/test"
	_ "github.com/pingcap/tidb/pkg/executor/sortexec/test"
	_ "github.com/pingcap/tidb/pkg/executor/staticrecordset/test"
	_ "github.com/pingcap/tidb/pkg/executor/test"
	_ "github.com/pingcap/tidb/pkg/expression/exprctx/test"
	_ "github.com/pingcap/tidb/pkg/expression/integration_test/test"
	_ "github.com/pingcap/tidb/pkg/expression/sessionexpr/test"
	_ "github.com/pingcap/tidb/pkg/expression/test"
	_ "github.com/pingcap/tidb/pkg/extension/test"
	_ "github.com/pingcap/tidb/pkg/infoschema/perfschema/test"
	_ "github.com/pingcap/tidb/pkg/infoschema/test"
	_ "github.com/pingcap/tidb/pkg/kv/test"
	_ "github.com/pingcap/tidb/pkg/lightning/backend/kv/test"
	_ "github.com/pingcap/tidb/pkg/lightning/backend/test"
	_ "github.com/pingcap/tidb/pkg/lightning/backend/tidb/test"
	_ "github.com/pingcap/tidb/pkg/lightning/checkpoints/test"
	_ "github.com/pingcap/tidb/pkg/lightning/common/test"
	_ "github.com/pingcap/tidb/pkg/lightning/config/test"
	_ "github.com/pingcap/tidb/pkg/lightning/duplicate/test"
	_ "github.com/pingcap/tidb/pkg/lightning/errormanager/test"
	_ "github.com/pingcap/tidb/pkg/lightning/log/test"
	_ "github.com/pingcap/tidb/pkg/lightning/metric/test"
	_ "github.com/pingcap/tidb/pkg/lightning/mydump/test"
	_ "github.com/pingcap/tidb/pkg/lightning/tikv/test"
	_ "github.com/pingcap/tidb/pkg/lightning/verification/test"
	_ "github.com/pingcap/tidb/pkg/lightning/worker/test"
	_ "github.com/pingcap/tidb/pkg/meta/autoid/test"
	_ "github.com/pingcap/tidb/pkg/meta/metabuild/test"
	_ "github.com/pingcap/tidb/pkg/meta/test"
	_ "github.com/pingcap/tidb/pkg/metrics/test"
	_ "github.com/pingcap/tidb/pkg/objstore/objectio/test"
	_ "github.com/pingcap/tidb/pkg/objstore/s3like/test"
	_ "github.com/pingcap/tidb/pkg/objstore/test"
	_ "github.com/pingcap/tidb/pkg/owner/test"
	_ "github.com/pingcap/tidb/pkg/parser/ast/test"
	_ "github.com/pingcap/tidb/pkg/parser/charset/test"
	_ "github.com/pingcap/tidb/pkg/parser/test"
	"github.com/pingcap/tidb/pkg/parser/test_driver"
	_ "github.com/pingcap/tidb/pkg/parser/types/test"
	_ "github.com/pingcap/tidb/pkg/planner/cascades/base/test"
	_ "github.com/pingcap/tidb/pkg/planner/cascades/memo/test"
	_ "github.com/pingcap/tidb/pkg/planner/cascades/old/test"
	_ "github.com/pingcap/tidb/pkg/planner/cascades/pattern/test"
	_ "github.com/pingcap/tidb/pkg/planner/cascades/rule/test"
	_ "github.com/pingcap/tidb/pkg/planner/cascades/task/test"
	_ "github.com/pingcap/tidb/pkg/planner/cascades/test"
	_ "github.com/pingcap/tidb/pkg/planner/core/casetest/test"
	_ "github.com/pingcap/tidb/pkg/planner/core/issuetest/test"
	_ "github.com/pingcap/tidb/pkg/planner/core/rule/test"
	_ "github.com/pingcap/tidb/pkg/planner/core/test"
	_ "github.com/pingcap/tidb/pkg/planner/funcdep/test"
	_ "github.com/pingcap/tidb/pkg/planner/implementation/test"
	_ "github.com/pingcap/tidb/pkg/planner/indexadvisor/test"
	_ "github.com/pingcap/tidb/pkg/planner/memo/test"
	_ "github.com/pingcap/tidb/pkg/planner/planctx/test"
	_ "github.com/pingcap/tidb/pkg/planner/property/test"
	_ "github.com/pingcap/tidb/pkg/planner/util/fixcontrol/test"
	_ "github.com/pingcap/tidb/pkg/planner/util/test"
	_ "github.com/pingcap/tidb/pkg/plugin/test"
	_ "github.com/pingcap/tidb/pkg/resourcegroup/tests/test"
	_ "github.com/pingcap/tidb/pkg/resourcemanager/test"
	_ "github.com/pingcap/tidb/pkg/server/handler/extractorhandler/test"
	_ "github.com/pingcap/tidb/pkg/server/handler/optimizor/test"
	_ "github.com/pingcap/tidb/pkg/server/handler/tests/test"
	_ "github.com/pingcap/tidb/pkg/server/test"
	_ "github.com/pingcap/tidb/pkg/server/tests/commontest/test"
	_ "github.com/pingcap/tidb/pkg/server/tests/cursor/test"
	_ "github.com/pingcap/tidb/pkg/server/tests/standby/test"
	_ "github.com/pingcap/tidb/pkg/server/tests/test"
	_ "github.com/pingcap/tidb/pkg/server/tests/tls/test"
	_ "github.com/pingcap/tidb/pkg/session/test"
	_ "github.com/pingcap/tidb/pkg/sessionctx/stmtctx/test"
	_ "github.com/pingcap/tidb/pkg/sessionctx/variable/tests/test"
	_ "github.com/pingcap/tidb/pkg/sessiontxn/isolation/test"
	_ "github.com/pingcap/tidb/pkg/sessiontxn/staleread/test"
	_ "github.com/pingcap/tidb/pkg/sessiontxn/test"
	_ "github.com/pingcap/tidb/pkg/statistics/asyncload/test"
	_ "github.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/test"
	_ "github.com/pingcap/tidb/pkg/statistics/handle/ddl/test"
	_ "github.com/pingcap/tidb/pkg/statistics/handle/globalstats/test"
	_ "github.com/pingcap/tidb/pkg/statistics/handle/handletest/test"
	_ "github.com/pingcap/tidb/pkg/statistics/handle/storage/test"
	_ "github.com/pingcap/tidb/pkg/statistics/handle/syncload/test"
	_ "github.com/pingcap/tidb/pkg/statistics/handle/updatetest/test"
	_ "github.com/pingcap/tidb/pkg/store/copr/copr_test/test"
	_ "github.com/pingcap/tidb/pkg/store/driver/test"
	_ "github.com/pingcap/tidb/pkg/store/helper/test"
	_ "github.com/pingcap/tidb/pkg/store/mockstore/mockcopr/test"
	_ "github.com/pingcap/tidb/pkg/store/test"
	_ "github.com/pingcap/tidb/pkg/structure/test"
	_ "github.com/pingcap/tidb/pkg/table/tblsession/test"
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
	_ "github.com/pingcap/tidb/pkg/testkit/test"
	_ "github.com/pingcap/tidb/pkg/timer/tablestore/test"
	_ "github.com/pingcap/tidb/pkg/timer/test"
	_ "github.com/pingcap/tidb/pkg/ttl/cache/test"
	_ "github.com/pingcap/tidb/pkg/ttl/client/test"
	_ "github.com/pingcap/tidb/pkg/ttl/metrics/test"
	_ "github.com/pingcap/tidb/pkg/ttl/session/test"
	_ "github.com/pingcap/tidb/pkg/ttl/sqlbuilder/test"
	_ "github.com/pingcap/tidb/pkg/util/admin/test"
	_ "github.com/pingcap/tidb/pkg/util/arena/test"
	_ "github.com/pingcap/tidb/pkg/util/backoff/test"
	_ "github.com/pingcap/tidb/pkg/util/benchdaily/test"
	_ "github.com/pingcap/tidb/pkg/util/bitmap/test"
	_ "github.com/pingcap/tidb/pkg/util/cdcutil/test"
	_ "github.com/pingcap/tidb/pkg/util/cgmon/test"
	_ "github.com/pingcap/tidb/pkg/util/cgroup/test"
	_ "github.com/pingcap/tidb/pkg/util/checksum/test"
	_ "github.com/pingcap/tidb/pkg/util/collate/test"
	_ "github.com/pingcap/tidb/pkg/util/context/test"
	_ "github.com/pingcap/tidb/pkg/util/cpu/test"
	_ "github.com/pingcap/tidb/pkg/util/cpuprofile/test"
	_ "github.com/pingcap/tidb/pkg/util/cteutil/test"
	_ "github.com/pingcap/tidb/pkg/util/dbterror/test"
	_ "github.com/pingcap/tidb/pkg/util/dbutil/test"
	_ "github.com/pingcap/tidb/pkg/util/deadlockhistory/test"
	_ "github.com/pingcap/tidb/pkg/util/disjointset/test"
	_ "github.com/pingcap/tidb/pkg/util/disk/test"
	_ "github.com/pingcap/tidb/pkg/util/encrypt/test"
	_ "github.com/pingcap/tidb/pkg/util/engine/test"
	_ "github.com/pingcap/tidb/pkg/util/etcd/test"
	_ "github.com/pingcap/tidb/pkg/util/fastrand/test"
	_ "github.com/pingcap/tidb/pkg/util/filter/test"
	_ "github.com/pingcap/tidb/pkg/util/format/test"
	_ "github.com/pingcap/tidb/pkg/util/generatedexpr/test"
	_ "github.com/pingcap/tidb/pkg/util/generic/test"
	_ "github.com/pingcap/tidb/pkg/util/globalconn/test"
	_ "github.com/pingcap/tidb/pkg/util/httputil/test"
	_ "github.com/pingcap/tidb/pkg/util/intest/test"
	_ "github.com/pingcap/tidb/pkg/util/keydecoder/test"
	_ "github.com/pingcap/tidb/pkg/util/logutil/test"
	_ "github.com/pingcap/tidb/pkg/util/mathutil/test"
	_ "github.com/pingcap/tidb/pkg/util/mock/test"
	_ "github.com/pingcap/tidb/pkg/util/mvmap/test"
	_ "github.com/pingcap/tidb/pkg/util/naming/test"
	_ "github.com/pingcap/tidb/pkg/util/paging/test"
	_ "github.com/pingcap/tidb/pkg/util/parser/test"
	_ "github.com/pingcap/tidb/pkg/util/prefetch/test"
	_ "github.com/pingcap/tidb/pkg/util/printer/test"
	_ "github.com/pingcap/tidb/pkg/util/profile/test"
	_ "github.com/pingcap/tidb/pkg/util/promutil/test"
	_ "github.com/pingcap/tidb/pkg/util/queue/test"
	_ "github.com/pingcap/tidb/pkg/util/ranger/test"
	_ "github.com/pingcap/tidb/pkg/util/redact/test"
	_ "github.com/pingcap/tidb/pkg/util/resourcegrouptag/test"
	_ "github.com/pingcap/tidb/pkg/util/rowcodec/test"
	_ "github.com/pingcap/tidb/pkg/util/schemacmp/test"
	_ "github.com/pingcap/tidb/pkg/util/selection/test"
	_ "github.com/pingcap/tidb/pkg/util/sem/compat/test"
	_ "github.com/pingcap/tidb/pkg/util/sem/test"
	_ "github.com/pingcap/tidb/pkg/util/set/test"
	_ "github.com/pingcap/tidb/pkg/util/slice/test"
	_ "github.com/pingcap/tidb/pkg/util/sqlescape/test"
	_ "github.com/pingcap/tidb/pkg/util/stringutil/test"
	_ "github.com/pingcap/tidb/pkg/util/sys/linux/test"
	_ "github.com/pingcap/tidb/pkg/util/sys/storage/test"
	_ "github.com/pingcap/tidb/pkg/util/systimemon/test"
	_ "github.com/pingcap/tidb/pkg/util/test"
	_ "github.com/pingcap/tidb/pkg/util/texttree/test"
	_ "github.com/pingcap/tidb/pkg/util/tls/test"
	_ "github.com/pingcap/tidb/pkg/util/topsql/test"
	_ "github.com/pingcap/tidb/pkg/util/traceevent/test"
	_ "github.com/pingcap/tidb/pkg/util/tracing/test"
	_ "github.com/pingcap/tidb/pkg/util/vitess/test"
	_ "github.com/pingcap/tidb/pkg/util/zeropool/test"
	_ "github.com/pingcap/tidb/pkg/workloadlearning/test"
)

func init() {
	// Ensure test_driver wins over types/parser_driver for parser tests.
	// Both packages register ast.NewValueExpr in their init(), but init order
	// is non-deterministic when multiple packages are linked together.
	// We only re-register test_driver for parser/ast tests, because other tests
	// (e.g., ddl) need types/parser_driver to be the active driver.
	register.GlobalRegistry().RegisterOnBeforeRun(func(pkg string) {
		if pkg == "parser/ast" {
			test_driver.Register()
		}
	})
}
