// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestEncoding(t *testing.T) {
	RunEncoding(t)
}

func TestEncodingValidate(t *testing.T) {
	RunEncodingValidate(t)
}

func TestEncodingGB18030(t *testing.T) {
	RunEncodingGB18030(t)
}
