// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package cgmon_test

import "testing"

func TestUploadDefaultValueWithoutCgroup(t *testing.T) {
	RunUploadDefaultValueWithoutCgroup(t)
}
