// Code generated by mega-gen. DO NOT EDIT.

package test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("executor/internal/querywatch", "QueryWatch", RunQueryWatch)
	register.Register("executor/internal/querywatch", "QueryWatchIssue56897", RunQueryWatchIssue56897)
}
