// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package table_test

import "testing"

func TestString(t *testing.T) {
	RunString(t)
}

func TestFind(t *testing.T) {
	RunFind(t)
}

func TestCheck(t *testing.T) {
	RunCheck(t)
}

func TestHandleBadNull(t *testing.T) {
	RunHandleBadNull(t)
}

func TestDesc(t *testing.T) {
	RunDesc(t)
}

func TestGetZeroValue(t *testing.T) {
	RunGetZeroValue(t)
}

func TestCastValue(t *testing.T) {
	RunCastValue(t)
}

func TestGetDefaultValue(t *testing.T) {
	RunGetDefaultValue(t)
}

func TestCastValueStrict(t *testing.T) {
	RunCastValueStrict(t)
}
