[storage]
reserve-space = "1KB"

[raftstore]
# true (default value) for high reliability, this can prevent data loss when power failure.
sync-log = true

[coprocessor]
# Make region split more aggressive.
region-max-keys = 100
region-split-keys = 80

[rocksdb]
# Number of open files that can be used by the DB.  You may need to
# increase this if your database has a large working set. Value -1 means
# files opened are always kept open. You can estimate number of files based
# on target_file_size_base and target_file_size_multiplier for level-based
# compaction.
# If max-open-files = -1, RocksDB will prefetch index and filter blocks into
# block cache at startup, so if your database has a large working set, it will
# take several minutes to open the db.
max-open-files = 1024

[raftdb]
max-open-files = 1024
