// Code generated by mega-gen. DO NOT EDIT.

package cteutil_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("util_cteutil", "StorageBasic", RunStorageBasic)
	register.Register("util_cteutil", "OpenAndClose", RunOpenAndClose)
	register.Register("util_cteutil", "AddAndGetChunk", RunAddAndGetChunk)
	register.Register("util_cteutil", "SpillToDisk", RunSpillToDisk)
	register.Register("util_cteutil", "Reopen", RunReopen)
	register.Register("util_cteutil", "SwapData", RunSwapData)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "util_cteutil" {
			InitForMega()
		}
	})
}
