version: "2"

issues:
  new-from-merge-base: origin/master
  max-issues-per-linter: 0

linters:
  default: none
  enable:
    - forbidigo
  # Ignore test files and executor.go
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - forbidigo
      - path: executor\.go
        linters:
          - forbidigo
  settings:
    forbidigo:
      forbid:
        # Optional message that gets included in error reports.
        # This is a strict check to ensure that the usage of GetSessionVars is appropriate.
        # If GetSessionVars are found in the PR, the check will fail to remind the reviewer.
        - pattern: GetSessionVars
          msg: Please check if the usage of GetSessionVars is appropriate.
      exclude-godoc-examples: false