# This is a configuration file for golangci-lint to check ddl package,
# which is used to check if there are usages of GetSessionVars in new PRs.
# Currently, only files under pkg/ddl are checked, subfolders are not included.
# But it's sufficient, because most of the code related to DDL execution is 
# included.

version: "2"

issues:
  # new-from-merge-base: upstream/master
  max-issues-per-linter: 0

linters:
  default: none
  enable:
    - forbidigo
  # Ignore test files and executor.go
  exclusions:
    rules:
      - path: _test\.go
        linters: [forbidigo]
      - path: executor\.go
        linters: [forbidigo]
      - path: job_submitter\.go
        linters: [forbidigo]
  settings:
    forbidigo:
      forbid:
        - pattern: GetSessionVars
          msg: Please check if the usage of GetSessionVars is appropriate, you can add //nolint:forbidigo to ignore this check if necessary.