version: "2"

issues:
  new-from-merge-base: origin/master

  max-issues-per-linter: 0

linters:
  default: none
  enable:
    - forbidigo
  settings:
    forbidigo:
      forbid:
        # Optional message that gets included in error reports.
        - pattern: GetSessionVars
          msg: Please check if the usage of GetSessionVars is appropriate.
      exclude-godoc-examples: false