// Code generated by mega-gen. DO NOT EDIT.

package indexmerge_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("planner_core_casetest_indexmerge", "IndexMergePathGeneration", RunIndexMergePathGeneration)
	register.Register("planner_core_casetest_indexmerge", "PlanCacheForIntersectionIndexMerge", RunPlanCacheForIntersectionIndexMerge)
	register.Register("planner_core_casetest_indexmerge", "IndexMergeWithOrderProperty", RunIndexMergeWithOrderProperty)
	register.Register("planner_core_casetest_indexmerge", "HintForIntersectionIndexMerge", RunHintForIntersectionIndexMerge)
	register.Register("planner_core_casetest_indexmerge", "CollectFilters4MVIndexMutations", RunCollectFilters4MVIndexMutations)
	register.Register("planner_core_casetest_indexmerge", "MultiMVIndexRandom", RunMultiMVIndexRandom)
	register.Register("planner_core_casetest_indexmerge", "MVIndexRandom", RunMVIndexRandom)
	register.Register("planner_core_casetest_indexmerge", "PlanCacheMVIndex", RunPlanCacheMVIndex)
	register.Register("planner_core_casetest_indexmerge", "AnalyzeVectorIndex", RunAnalyzeVectorIndex)
	register.Register("planner_core_casetest_indexmerge", "AnalyzeColumnarIndex", RunAnalyzeColumnarIndex)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "planner_core_casetest_indexmerge" {
			InitForMega()
		}
	})
}
