// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestSessionRunInTxn(t *testing.T) {
	RunSessionRunInTxn(t)
}

func TestSessionResetTimeZone(t *testing.T) {
	RunSessionResetTimeZone(t)
}

func TestSessionKill(t *testing.T) {
	RunSessionKill(t)
}
