package ast_test

import (
	"testing"

	"github.com/pingcap/tidb/pkg/parser/ast"
)

func TestAdminLogReplicationRestore(t *testing.T) {
	testCases := []NodeRestoreTestCase{
		{
			"ADMIN CREATE LOG REPLICATION test SOURCE_HOST '127.0.0.1'",
			"ADMIN CREATE LOG REPLICATION `test` SOURCE_HOST = '127.0.0.1'",
		},
		{
			"ADMIN CREATE LOG REPLICATION test SOURCE_HOST '127.0.0.1' DETACHED",
			"ADMIN CREATE LOG REPLICATION `test` SOURCE_HOST = '127.0.0.1' DETACHED",
		},
		{
			`ADMIN CREATE LOG REPLICATION test SOURCE_HOST='127.0.0.1' SOURCE_PORT 3306 SOURCE_USER='root' SOURCE_PASSWORD='It\'s a good day' PROTECTION_MODE=MAXIMUM_AVAILABILITY DEGRADE_TIMEOUT '30s'`,
			"ADMIN CREATE LOG REPLICATION `test` SOURCE_HOST = '127.0.0.1' SOURCE_PORT = 3306 SOURCE_USER = 'root' SOURCE_PASSWORD = 'It''s a good day' PROTECTION_MODE = MAXIMUM_AVAILABILITY DEGRADE_TIMEOUT = '30s'",
		},
		{
			"ADMIN CREATE LOG REPLICATION test SOURCE_HOST='127.0.0.1' DETACHED",
			"ADMIN CREATE LOG REPLICATION `test` SOURCE_HOST = '127.0.0.1' DETACHED",
		},
		{
			"ADMIN ALTER LOG REPLICATION test source_HOST='127.0.0.2' SOURCE_PORT=3307 PROTECTION_MODE maximum_protection",
			"ADMIN ALTER LOG REPLICATION `test` SOURCE_HOST = '127.0.0.2' SOURCE_PORT = 3307 PROTECTION_MODE = MAXIMUM_PROTECTION",
		},
		{
			"ADMIN alter LOG REPLICATION test CHANGE SOURCE TO 123",
			"ADMIN ALTER LOG REPLICATION `test` CHANGE SOURCE TO 123",
		},
		{
			"ADMIN PAUSE LOG REPLICATION test",
			"ADMIN PAUSE LOG REPLICATION `test`",
		},
		{
			"ADMIN RESUME LOG REPLICATION test",
			"ADMIN RESUME LOG REPLICATION `test`",
		},
		{
			"ADMIN DROP LOG REPLICATION test",
			"ADMIN DROP LOG REPLICATION `test`",
		},
		{
			"ADMIN SWITCHOVER PRIMARY TO 456",
			"ADMIN SWITCHOVER PRIMARY TO 456",
		},
		{
			"ADMIN SWITCHOVER AS PRIMARY",
			"ADMIN SWITCHOVER AS PRIMARY",
		},
		{
			"ADMIN ACTIVATE STANDBY MODE=FLASHBACK",
			"ADMIN ACTIVATE STANDBY MODE = FLASHBACK",
		},
		{
			"ADMIN ACTIVATE STANDBY MODE = FORCE_COMMIT",
			"ADMIN ACTIVATE STANDBY MODE = FORCE_COMMIT",
		},
	}
	extractNodeFunc := func(node ast.Node) ast.Node {
		return node
	}
	runNodeRestoreTest(t, testCases, "%s", extractNodeFunc)
}
