// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package keyspace_test

import "testing"

func TestSetKeyspaceNameInConf(t *testing.T) {
	RunSetKeyspaceNameInConf(t)
}

func TestNoKeyspaceNameSet(t *testing.T) {
	RunNoKeyspaceNameSet(t)
}
