// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package serial_test

import "testing"

func TestIssue23872(t *testing.T) {
	RunIssue23872(t)
}

func TestChangeMaxIndexLength(t *testing.T) {
	RunChangeMaxIndexLength(t)
}

func TestCreateTableWithLike(t *testing.T) {
	RunCreateTableWithLike(t)
}

func TestCreateTableWithLikeAtTemporaryMode(t *testing.T) {
	RunCreateTableWithLikeAtTemporaryMode(t)
}

func TestCancelAddIndexPanic(t *testing.T) {
	RunCancelAddIndexPanic(t)
}

func TestRecoverTableWithTTL(t *testing.T) {
	RunRecoverTableWithTTL(t)
}

func TestRecoverTableByJobID(t *testing.T) {
	RunRecoverTableByJobID(t)
}

func TestRecoverTableByJobIDFail(t *testing.T) {
	RunRecoverTableByJobIDFail(t)
}

func TestRecoverTableByTableNameFail(t *testing.T) {
	RunRecoverTableByTableNameFail(t)
}

func TestCancelJobByErrorCountLimit(t *testing.T) {
	RunCancelJobByErrorCountLimit(t)
}

func TestTruncateTableUpdateSchemaVersionErr(t *testing.T) {
	RunTruncateTableUpdateSchemaVersionErr(t)
}

func TestCanceledJobTakeTime(t *testing.T) {
	RunCanceledJobTakeTime(t)
}

func TestTableLocksDisable(t *testing.T) {
	RunTableLocksDisable(t)
}

func TestAutoRandom(t *testing.T) {
	RunAutoRandom(t)
}

func TestAutoRandomWithPreSplitRegion(t *testing.T) {
	RunAutoRandomWithPreSplitRegion(t)
}

func TestForbidUnsupportedCollations(t *testing.T) {
	RunForbidUnsupportedCollations(t)
}

func TestCreateTableNoBlock(t *testing.T) {
	RunCreateTableNoBlock(t)
}

func TestCheckEnumLength(t *testing.T) {
	RunCheckEnumLength(t)
}

func TestGetReverseKey(t *testing.T) {
	RunGetReverseKey(t)
}

func TestForbiddenDDLInNextGen(t *testing.T) {
	RunForbiddenDDLInNextGen(t)
}
