
package main

import (
	"bytes"
	"flag"
	"io/ioutil"
	"os"
	"reflect"
	"fmt"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/pingcap/errors"
	pkg_structure "github.com/pingcap/tidb/pkg/structure"
	pkg_infoschema "github.com/pingcap/tidb/pkg/infoschema"
	pkg_table "github.com/pingcap/tidb/pkg/table"
	lightning_pkg_importinto "github.com/pingcap/tidb/lightning/pkg/importinto"
	pkg_lightning_mydump "github.com/pingcap/tidb/pkg/lightning/mydump"
	pkg_store_mockstore_unistore_tikv_kverrors "github.com/pingcap/tidb/pkg/store/mockstore/unistore/tikv/kverrors"
	pkg_session_sessionapi "github.com/pingcap/tidb/pkg/session/sessionapi"
	pkg_util_dbterror_exeerrors "github.com/pingcap/tidb/pkg/util/dbterror/exeerrors"
	pkg_util_logutil_consistency "github.com/pingcap/tidb/pkg/util/logutil/consistency"
	pkg_ddl_systable "github.com/pingcap/tidb/pkg/ddl/systable"
	pkg_expression "github.com/pingcap/tidb/pkg/expression"
	pkg_objstore_s3like "github.com/pingcap/tidb/pkg/objstore/s3like"
	pkg_resourcemanager_pool "github.com/pingcap/tidb/pkg/resourcemanager/pool"
	pkg_util_dbterror "github.com/pingcap/tidb/pkg/util/dbterror"
	pkg_ddl_label "github.com/pingcap/tidb/pkg/ddl/label"
	pkg_expression_exprctx "github.com/pingcap/tidb/pkg/expression/exprctx"
	pkg_importsdk "github.com/pingcap/tidb/pkg/importsdk"
	pkg_statistics "github.com/pingcap/tidb/pkg/statistics"
	pkg_lightning_membuf "github.com/pingcap/tidb/pkg/lightning/membuf"
	pkg_meta "github.com/pingcap/tidb/pkg/meta"
	pkg_server_err "github.com/pingcap/tidb/pkg/server/err"
	pkg_statistics_handle_autoanalyze_priorityqueue "github.com/pingcap/tidb/pkg/statistics/handle/autoanalyze/priorityqueue"
	br_pkg_errors "github.com/pingcap/tidb/br/pkg/errors"
	pkg_ddl_resourcegroup "github.com/pingcap/tidb/pkg/ddl/resourcegroup"
	pkg_table_tables "github.com/pingcap/tidb/pkg/table/tables"
	pkg_util_collate "github.com/pingcap/tidb/pkg/util/collate"
	pkg_util_watcher "github.com/pingcap/tidb/pkg/util/watcher"
	pkg_kv "github.com/pingcap/tidb/pkg/kv"
	lightning_pkg_importer "github.com/pingcap/tidb/lightning/pkg/importer"
	pkg_ddl_placement "github.com/pingcap/tidb/pkg/ddl/placement"
	pkg_domain_infosync "github.com/pingcap/tidb/pkg/domain/infosync"
	pkg_dxf_framework_storage "github.com/pingcap/tidb/pkg/dxf/framework/storage"
	pkg_util_parser "github.com/pingcap/tidb/pkg/util/parser"
	pkg_param "github.com/pingcap/tidb/pkg/param"
	pkg_sessionctx_sessionstates "github.com/pingcap/tidb/pkg/sessionctx/sessionstates"
	pkg_sessionctx_variable "github.com/pingcap/tidb/pkg/sessionctx/variable"
	pkg_store_driver_error "github.com/pingcap/tidb/pkg/store/driver/error"
	pkg_util_admin "github.com/pingcap/tidb/pkg/util/admin"
	pkg_util_stringutil "github.com/pingcap/tidb/pkg/util/stringutil"
	pkg_util_chunk "github.com/pingcap/tidb/pkg/util/chunk"
	pkg_util_topsql_reporter "github.com/pingcap/tidb/pkg/util/topsql/reporter"
	pkg_util_dbterror_plannererrors "github.com/pingcap/tidb/pkg/util/dbterror/plannererrors"
	pkg_dxf_framework_taskexecutor "github.com/pingcap/tidb/pkg/dxf/framework/taskexecutor"
	pkg_ingestor_errdef "github.com/pingcap/tidb/pkg/ingestor/errdef"
	pkg_meta_autoid "github.com/pingcap/tidb/pkg/meta/autoid"
	pkg_store_mockstore_unistore_tikv_dbreader "github.com/pingcap/tidb/pkg/store/mockstore/unistore/tikv/dbreader"
	pkg_util_topsql_state "github.com/pingcap/tidb/pkg/util/topsql/state"
	pkg_metaservice "github.com/pingcap/tidb/pkg/metaservice"
	lightning_pkg_checkpoints_checkpointspb "github.com/pingcap/tidb/lightning/pkg/checkpoints/checkpointspb"
	pkg_session "github.com/pingcap/tidb/pkg/session"
	br_pkg_restore_split "github.com/pingcap/tidb/br/pkg/restore/split"
	pkg_domain "github.com/pingcap/tidb/pkg/domain"
	pkg_lightning_common "github.com/pingcap/tidb/pkg/lightning/common"
	pkg_privilege_privileges "github.com/pingcap/tidb/pkg/privilege/privileges"
	pkg_timer_api "github.com/pingcap/tidb/pkg/timer/api"
	pkg_types "github.com/pingcap/tidb/pkg/types"
	pkg_util_hint "github.com/pingcap/tidb/pkg/util/hint"
	pkg_util_timeutil "github.com/pingcap/tidb/pkg/util/timeutil"
	pkg_lock "github.com/pingcap/tidb/pkg/lock"
	pkg_util_dbutil "github.com/pingcap/tidb/pkg/util/dbutil"
	pkg_ddl_notifier "github.com/pingcap/tidb/pkg/ddl/notifier"
	pkg_executor "github.com/pingcap/tidb/pkg/executor"
)

func main() {
	var outpath string
	flag.StringVar(&outpath, "output", "", "Specify the error documentation output file path")
	flag.Parse()
	if outpath == "" {
		println("Usage: ./_errdoc-generator --output /path/to/errors.toml")
		os.Exit(1)
	}

	// Read-in the exists file and merge the description/workaround from exists file
	existDefinition := map[string]spec{}
	if file, err := ioutil.ReadFile(outpath); err == nil {
		err = toml.Unmarshal(file, &existDefinition)
		if err != nil {
			println(fmt.Sprintf("Invalid toml file %s when merging exists description/workaround: %v", outpath, err))
			os.Exit(1)
		}
	}
	
	var allErrors []error
	allErrors = append(allErrors, pkg_structure.ErrInvalidHashKeyFlag)
	allErrors = append(allErrors, pkg_structure.ErrInvalidListIndex)
	allErrors = append(allErrors, pkg_structure.ErrInvalidListMetaData)
	allErrors = append(allErrors, pkg_structure.ErrWriteOnSnapshot)
	allErrors = append(allErrors, pkg_infoschema.ErrDatabaseExists)
	allErrors = append(allErrors, pkg_infoschema.ErrDatabaseDropExists)
	allErrors = append(allErrors, pkg_infoschema.ErrAccessDenied)
	allErrors = append(allErrors, pkg_infoschema.ErrDatabaseNotExists)
	allErrors = append(allErrors, pkg_infoschema.ErrPlacementPolicyExists)
	allErrors = append(allErrors, pkg_infoschema.ErrPlacementPolicyNotExists)
	allErrors = append(allErrors, pkg_infoschema.ErrResourceGroupExists)
	allErrors = append(allErrors, pkg_infoschema.ErrResourceGroupNotExists)
	allErrors = append(allErrors, pkg_infoschema.ErrResourceGroupInvalidBackgroundTaskName)
	allErrors = append(allErrors, pkg_infoschema.ErrResourceGroupInvalidForRole)
	allErrors = append(allErrors, pkg_infoschema.ErrReservedSyntax)
	allErrors = append(allErrors, pkg_infoschema.ErrTableExists)
	allErrors = append(allErrors, pkg_infoschema.ErrTableDropExists)
	allErrors = append(allErrors, pkg_infoschema.ErrSequenceDropExists)
	allErrors = append(allErrors, pkg_infoschema.ErrColumnNotExists)
	allErrors = append(allErrors, pkg_infoschema.ErrColumnExists)
	allErrors = append(allErrors, pkg_infoschema.ErrKeyNameDuplicate)
	allErrors = append(allErrors, pkg_infoschema.ErrNonuniqTable)
	allErrors = append(allErrors, pkg_infoschema.ErrMultiplePriKey)
	allErrors = append(allErrors, pkg_infoschema.ErrTooManyKeyParts)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyNotExists)
	allErrors = append(allErrors, pkg_infoschema.ErrTableNotLockedForWrite)
	allErrors = append(allErrors, pkg_infoschema.ErrTableNotLocked)
	allErrors = append(allErrors, pkg_infoschema.ErrTableNotExists)
	allErrors = append(allErrors, pkg_infoschema.ErrKeyNotExists)
	allErrors = append(allErrors, pkg_infoschema.ErrCannotAddForeign)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyOnPartitioned)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyNotMatch)
	allErrors = append(allErrors, pkg_infoschema.ErrIndexExists)
	allErrors = append(allErrors, pkg_infoschema.ErrUserDropExists)
	allErrors = append(allErrors, pkg_infoschema.ErrUserAlreadyExists)
	allErrors = append(allErrors, pkg_infoschema.ErrTableLocked)
	allErrors = append(allErrors, pkg_infoschema.ErrWrongObject)
	allErrors = append(allErrors, pkg_infoschema.ErrAdminCheckTable)
	allErrors = append(allErrors, pkg_infoschema.ErrEmptyDatabase)
	allErrors = append(allErrors, pkg_infoschema.ErrForbidSchemaChange)
	allErrors = append(allErrors, pkg_infoschema.ErrTableWithoutPrimaryKey)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyCannotUseVirtualColumn)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyCannotOpenParent)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyNoColumnInParent)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyNoIndexInParent)
	allErrors = append(allErrors, pkg_infoschema.ErrForeignKeyColumnNotNull)
	allErrors = append(allErrors, pkg_infoschema.ErrResourceGroupSupportDisabled)
	allErrors = append(allErrors, pkg_infoschema.ErrCheckConstraintDupName)
	allErrors = append(allErrors, pkg_infoschema.ErrProtectedTableMode)
	allErrors = append(allErrors, pkg_infoschema.ErrInvalidTableModeSet)
	allErrors = append(allErrors, pkg_table.ErrColumnCantNull)
	allErrors = append(allErrors, pkg_table.ErrUnknownColumn)
	allErrors = append(allErrors, pkg_table.ErrWarnNullToNotnull)
	allErrors = append(allErrors, pkg_table.ErrNoDefaultValue)
	allErrors = append(allErrors, pkg_table.ErrIndexOutBound)
	allErrors = append(allErrors, pkg_table.ErrUnsupportedOp)
	allErrors = append(allErrors, pkg_table.ErrRowNotFound)
	allErrors = append(allErrors, pkg_table.ErrTableStateCantNone)
	allErrors = append(allErrors, pkg_table.ErrColumnStateCantNone)
	allErrors = append(allErrors, pkg_table.ErrColumnStateNonPublic)
	allErrors = append(allErrors, pkg_table.ErrIndexStateCantNone)
	allErrors = append(allErrors, pkg_table.ErrInvalidRecordKey)
	allErrors = append(allErrors, pkg_table.ErrTruncatedWrongValueForField)
	allErrors = append(allErrors, pkg_table.ErrUnknownPartition)
	allErrors = append(allErrors, pkg_table.ErrNoPartitionForGivenValue)
	allErrors = append(allErrors, pkg_table.ErrLockOrActiveTransaction)
	allErrors = append(allErrors, pkg_table.ErrSequenceHasRunOut)
	allErrors = append(allErrors, pkg_table.ErrRowDoesNotMatchGivenPartitionSet)
	allErrors = append(allErrors, pkg_table.ErrTempTableFull)
	allErrors = append(allErrors, pkg_table.ErrOptOnCacheTable)
	allErrors = append(allErrors, pkg_table.ErrCheckConstraintViolated)
	allErrors = append(allErrors, lightning_pkg_importinto.ErrFailoverCancel)
	allErrors = append(allErrors, pkg_lightning_mydump.ErrInsertStatementNotFound)
	allErrors = append(allErrors, pkg_store_mockstore_unistore_tikv_kverrors.ErrLockNotFound)
	allErrors = append(allErrors, pkg_store_mockstore_unistore_tikv_kverrors.ErrAlreadyRollback)
	allErrors = append(allErrors, pkg_store_mockstore_unistore_tikv_kverrors.ErrReplaced)
	allErrors = append(allErrors, pkg_session_sessionapi.ErrIdentityNotFound)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrGetStartTS)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrUnknownPlan)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrPrepareMulti)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrPrepareDDL)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrResultIsEmpty)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBuildExecutor)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBatchInsertFail)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrUnsupportedPs)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrSubqueryMoreThan1Row)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrIllegalGrantForTable)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrColumnsNotMatched)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrCantCreateUserWithGrant)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrPasswordNoMatch)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrCannotUser)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrGrantRole)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrPasswordFormat)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrCantChangeTxCharacteristics)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrPsManyParam)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrAdminCheckTable)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrDBaccessDenied)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrTableaccessDenied)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBadDB)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrWrongObject)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrWrongUsage)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrRoleNotGranted)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrDeadlock)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrQueryInterrupted)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrMaxExecTimeExceeded)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrResourceGroupQueryRunawayInterrupted)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrQueryExecStopped)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrResourceGroupQueryRunawayQuarantine)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrDynamicPrivilegeNotRegistered)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrIllegalPrivilegeLevel)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrInvalidSplitRegionRanges)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrViewInvalid)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrInstanceScope)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrSettingNoopVariable)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLazyUniquenessCheckFailure)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrMemoryExceedForQuery)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrMemoryExceedForInstance)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrDeleteNotFoundColumn)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBRIEBackupFailed)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBRIERestoreFailed)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBRIEImportFailed)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBRIEExportFailed)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrBRJobNotFound)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrCTEMaxRecursionDepth)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrPluginIsNotLoaded)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrSetPasswordAuthPlugin)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrFuncNotEnabled)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrSavepointNotExists)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrForeignKeyCascadeDepthExceeded)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrPasswordExpireAnonymousUser)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrMustChangePassword)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrWrongStringLength)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrUnsupportedFlashbackTmpTable)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrTruncateWrongInsertValue)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrExistsInHistoryPassword)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrUserNameNeedPrefix)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrWarnTooFewRecords)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrWarnTooManyRecords)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataFromServerDisk)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadParquetFromLocal)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataEmptyPath)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataUnsupportedFormat)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataInvalidURI)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataCantAccess)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataCantRead)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataWrongFormatConfig)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrUnknownOption)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrInvalidOptionVal)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrDuplicateOption)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataUnsupportedOption)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataDuplicateKeyConflict)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataJobNotFound)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataInvalidOperation)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataLocalUnsupportedOption)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrLoadDataPreCheckFailed)
	allErrors = append(allErrors, pkg_util_dbterror_exeerrors.ErrMaxKeysReadExceeded)
	allErrors = append(allErrors, pkg_util_logutil_consistency.ErrAdminCheckInconsistent)
	allErrors = append(allErrors, pkg_util_logutil_consistency.ErrLookupInconsistent)
	allErrors = append(allErrors, pkg_util_logutil_consistency.ErrAdminCheckInconsistentWithColInfo)
	allErrors = append(allErrors, pkg_ddl_systable.ErrNotFound)
	allErrors = append(allErrors, pkg_expression.ErrIncorrectParameterCount)
	allErrors = append(allErrors, pkg_expression.ErrDivisionByZero)
	allErrors = append(allErrors, pkg_expression.ErrRegexp)
	allErrors = append(allErrors, pkg_expression.ErrOperandColumns)
	allErrors = append(allErrors, pkg_expression.ErrCutValueGroupConcat)
	allErrors = append(allErrors, pkg_expression.ErrFunctionsNoopImpl)
	allErrors = append(allErrors, pkg_expression.ErrInvalidArgumentForLogarithm)
	allErrors = append(allErrors, pkg_expression.ErrIncorrectType)
	allErrors = append(allErrors, pkg_expression.ErrInvalidTypeForJSON)
	allErrors = append(allErrors, pkg_expression.ErrInvalidTableSample)
	allErrors = append(allErrors, pkg_expression.ErrNotSupportedYet)
	allErrors = append(allErrors, pkg_expression.ErrInvalidJSONForFuncIndex)
	allErrors = append(allErrors, pkg_expression.ErrDataOutOfRangeFuncIndex)
	allErrors = append(allErrors, pkg_expression.ErrFuncIndexDataIsTooLong)
	allErrors = append(allErrors, pkg_expression.ErrFunctionNotExists)
	allErrors = append(allErrors, pkg_objstore_s3like.ErrNoSuchBucket)
	allErrors = append(allErrors, pkg_resourcemanager_pool.ErrPoolClosed)
	allErrors = append(allErrors, pkg_resourcemanager_pool.ErrPoolOverload)
	allErrors = append(allErrors, pkg_resourcemanager_pool.ErrPoolParamsInvalid)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidWorker)
	allErrors = append(allErrors, pkg_util_dbterror.ErrNotOwner)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCantDecodeRecord)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidDDLJob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCancelledDDLJob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPausedDDLJob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrBDRRestrictedDDL)
	allErrors = append(allErrors, pkg_util_dbterror.ErrRunMultiSchemaChanges)
	allErrors = append(allErrors, pkg_util_dbterror.ErrOperateSameColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrOperateSameIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWaitReorgTimeout)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidStoreVer)
	allErrors = append(allErrors, pkg_util_dbterror.ErrRepairTableFail)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAddColumnarIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAddVectorIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCantDropColWithIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCantDropColWithAutoInc)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCantDropColWithCheckConstraint)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedEngineAttribute)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAddColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedModifyColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedModifyCharset)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedModifyCollation)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedPKHandle)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedCharset)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedShardRowIDBits)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAlterTableWithValidation)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAlterTableWithoutValidation)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAlterTableOption)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAlterCacheForSysTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAddPartialIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrModifyColumnReferencedByPartialCondition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrBlobKeyWithoutLength)
	allErrors = append(allErrors, pkg_util_dbterror.ErrKeyPart0)
	allErrors = append(allErrors, pkg_util_dbterror.ErrIncorrectPrefixKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooLongKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrKeyColumnDoesNotExits)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidDDLJobVersion)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidUseOfNull)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooManyFields)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooManyKeys)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidSplitRegionRanges)
	allErrors = append(allErrors, pkg_util_dbterror.ErrReorgPanic)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFkColumnCannotDrop)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFkColumnCannotDropChild)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFKIncompatibleColumns)
	allErrors = append(allErrors, pkg_util_dbterror.ErrOnlyOnRangeListPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongKeyColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongKeyColumnFunctionalIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongFKOptionForGeneratedColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedOnGeneratedColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrGeneratedColumnNonPrior)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDependentByGeneratedColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrJSONUsedAsKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrBlobCantHaveDefault)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooLongIndexComment)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooLongTableComment)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooLongFieldComment)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooLongTablePartitionComment)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidDefaultValue)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDefValGeneratedNamedFunctionIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrGeneratedColumnRefAutoInc)
	allErrors = append(allErrors, pkg_util_dbterror.ErrExpressionIndexCanNotRefer)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAddPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedCoalescePartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedReorganizePartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedCheckPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedOptimizePartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedRebuildPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedRemovePartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedRepairPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrGeneratedColumnFunctionIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrGeneratedColumnRowValueIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedPartitionByRangeColumns)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFunctionalIndexFunctionIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFunctionalIndexRowValueIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedCreatePartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedIndexType)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWindowInvalidWindowFuncUse)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDupKeyName)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFkDupName)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidDDLState)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedModifyPrimaryKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPKIndexCantBeInvisible)
	allErrors = append(allErrors, pkg_util_dbterror.ErrColumnBadNull)
	allErrors = append(allErrors, pkg_util_dbterror.ErrBadField)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCantRemoveAllFields)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCantDropFieldOrKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidOnUpdate)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooLongIdent)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongDBName)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongTableName)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongColumnName)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongPartitionName)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongUsage)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidGroupFuncUse)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTableMustHaveColumns)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongNameForIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnknownCharacterSet)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnknownCollation)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCollationCharsetMismatch)
	allErrors = append(allErrors, pkg_util_dbterror.ErrConflictingDeclarations)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPrimaryCantHaveNull)
	allErrors = append(allErrors, pkg_util_dbterror.ErrErrorOnRename)
	allErrors = append(allErrors, pkg_util_dbterror.ErrViewSelectClause)
	allErrors = append(allErrors, pkg_util_dbterror.ErrViewSelectVariable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrNotAllowedTypeInPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionMgmtOnNonpartitioned)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDropPartitionNonExistent)
	allErrors = append(allErrors, pkg_util_dbterror.ErrSameNamePartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrSameNamePartitionField)
	allErrors = append(allErrors, pkg_util_dbterror.ErrRangeNotIncreasing)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionMaxvalue)
	allErrors = append(allErrors, pkg_util_dbterror.ErrMaxvalueInValuesIn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDropLastPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooManyPartitions)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionConstDomain)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionFunctionIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionFuncNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUniqueKeyNeedAllFieldsInPf)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongExprInPartitionFunc)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWarnDataTruncated)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCoalesceOnlyOnHashPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrViewWrongList)
	allErrors = append(allErrors, pkg_util_dbterror.ErrAlterOperationNotSupported)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongObject)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTableCantHandleFt)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFieldNotFoundPart)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongTypeColumnValue)
	allErrors = append(allErrors, pkg_util_dbterror.ErrValuesIsNotIntType)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFunctionalIndexPrimaryKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFunctionalIndexOnField)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidAutoRandom)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedConstraintCheck)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDerivedMustHaveAlias)
	allErrors = append(allErrors, pkg_util_dbterror.ErrNullInValuesLessThan)
	allErrors = append(allErrors, pkg_util_dbterror.ErrSequenceRunOut)
	allErrors = append(allErrors, pkg_util_dbterror.ErrSequenceInvalidData)
	allErrors = append(allErrors, pkg_util_dbterror.ErrSequenceAccessFail)
	allErrors = append(allErrors, pkg_util_dbterror.ErrNotSequence)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnknownSequence)
	allErrors = append(allErrors, pkg_util_dbterror.ErrSequenceUnsupportedTableOption)
	allErrors = append(allErrors, pkg_util_dbterror.ErrColumnTypeUnsupportedNextValue)
	allErrors = append(allErrors, pkg_util_dbterror.ErrAddColumnWithSequenceAsDefault)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedExpressionIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionExchangePartTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionExchangeTempTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTablesDifferentMetadata)
	allErrors = append(allErrors, pkg_util_dbterror.ErrRowDoesNotMatchPartition)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionExchangeForeignKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckNoSuchTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedPartitionType)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionExchangeDifferentOption)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTableOptionUnionUnsupported)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTableOptionInsertMethodUnsupported)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidPlacementPolicyCheck)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPlacementPolicyWithDirectOption)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPlacementPolicyInUse)
	allErrors = append(allErrors, pkg_util_dbterror.ErrMultipleDefConstInListPart)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTruncatedWrongValue)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWarnDataOutOfRange)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTooLongValueForType)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnknownEngine)
	allErrors = append(allErrors, pkg_util_dbterror.ErrExchangePartitionDisabled)
	allErrors = append(allErrors, pkg_util_dbterror.ErrPartitionNoTemporary)
	allErrors = append(allErrors, pkg_util_dbterror.ErrOptOnTemporaryTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrOptOnCacheTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedOnCommitPreserve)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedClusteredSecondaryKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedLocalTempTableDDL)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidAttributesSpec)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFunctionalIndexOnJSONOrGeometryFunction)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDependentByFunctionalIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrFunctionalIndexOnBlob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDependentByPartitionFunctional)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedAlterTableSpec)
	allErrors = append(allErrors, pkg_util_dbterror.ErrGeneralUnsupportedDDL)
	allErrors = append(allErrors, pkg_util_dbterror.ErrAutoConvert)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWrongStringLength)
	allErrors = append(allErrors, pkg_util_dbterror.ErrBinlogUnsafeSystemFunction)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDDLJobNotFound)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCancelFinishedDDLJob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCannotCancelDDLJob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCannotPauseDDLJob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCannotResumeDDLJob)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDDLSetting)
	allErrors = append(allErrors, pkg_util_dbterror.ErrIngestFailed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrIngestCheckEnvFailed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrColumnInChange)
	allErrors = append(allErrors, pkg_util_dbterror.ErrAlterTiFlashModeForTableWithoutTiFlashReplica)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedTiFlashOperationForSysOrMemTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedTiFlashOperationForUnsupportedCharsetTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTiFlashBackfillIndex)
	allErrors = append(allErrors, pkg_util_dbterror.ErrDropIndexNeededInForeignKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrForeignKeyCannotDropParent)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTruncateIllegalForeignKey)
	allErrors = append(allErrors, pkg_util_dbterror.ErrForeignKeyColumnCannotChange)
	allErrors = append(allErrors, pkg_util_dbterror.ErrForeignKeyColumnCannotChangeChild)
	allErrors = append(allErrors, pkg_util_dbterror.ErrNoReferencedRow2)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedColumnInTTLConfig)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTTLColumnCannotDrop)
	allErrors = append(allErrors, pkg_util_dbterror.ErrSetTTLOptionForNonTTLTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTempTableNotAllowedWithTTL)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedTTLReferencedByFK)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedPrimaryKeyTypeWithTTL)
	allErrors = append(allErrors, pkg_util_dbterror.ErrNotSupportedYet)
	allErrors = append(allErrors, pkg_util_dbterror.ErrColumnCheckConstraintReferOther)
	allErrors = append(allErrors, pkg_util_dbterror.ErrTableCheckConstraintReferUnknown)
	allErrors = append(allErrors, pkg_util_dbterror.ErrConstraintNotFound)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckConstraintIsViolated)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckConstraintNamedFuncIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckConstraintFuncIsNotAllowed)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckConstraintVariables)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckConstraintRefersAutoIncrementColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckConstraintUsingFKReferActionColumn)
	allErrors = append(allErrors, pkg_util_dbterror.ErrNonBooleanExprForCheckConstraint)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWarnDeprecatedIntegerDisplayWidth)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWarnDeprecatedZerofill)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCheckConstraintDupName)
	allErrors = append(allErrors, pkg_util_dbterror.ErrUnsupportedDistTask)
	allErrors = append(allErrors, pkg_util_dbterror.ErrGlobalIndexNotExplicitlySet)
	allErrors = append(allErrors, pkg_util_dbterror.ErrWarnGlobalIndexNeedManuallyAnalyze)
	allErrors = append(allErrors, pkg_util_dbterror.ErrEngineAttributeInvalidFormat)
	allErrors = append(allErrors, pkg_util_dbterror.ErrStorageClassInvalidSpec)
	allErrors = append(allErrors, pkg_util_dbterror.ErrCannotSetAffinityOnTable)
	allErrors = append(allErrors, pkg_util_dbterror.ErrInvalidTableAffinity)
	allErrors = append(allErrors, pkg_util_dbterror.ErrForbiddenDDL)
	allErrors = append(allErrors, pkg_ddl_label.ErrInvalidAttributesFormat)
	allErrors = append(allErrors, pkg_expression_exprctx.ErrParamIndexExceedParamCounts)
	allErrors = append(allErrors, pkg_importsdk.ErrNoDatabasesFound)
	allErrors = append(allErrors, pkg_importsdk.ErrSchemaNotFound)
	allErrors = append(allErrors, pkg_importsdk.ErrTableNotFound)
	allErrors = append(allErrors, pkg_importsdk.ErrNoTableDataFiles)
	allErrors = append(allErrors, pkg_importsdk.ErrWildcardNotSpecific)
	allErrors = append(allErrors, pkg_importsdk.ErrJobNotFound)
	allErrors = append(allErrors, pkg_importsdk.ErrNoJobIDReturned)
	allErrors = append(allErrors, pkg_importsdk.ErrInvalidOptions)
	allErrors = append(allErrors, pkg_importsdk.ErrMultipleFieldsDefinedNullBy)
	allErrors = append(allErrors, pkg_importsdk.ErrParseStorageURL)
	allErrors = append(allErrors, pkg_importsdk.ErrCreateExternalStorage)
	allErrors = append(allErrors, pkg_importsdk.ErrCreateLoader)
	allErrors = append(allErrors, pkg_importsdk.ErrCreateSchema)
	allErrors = append(allErrors, pkg_statistics.ErrQueryInterrupted)
	allErrors = append(allErrors, pkg_lightning_membuf.ErrCannotAcquireMemory)
	allErrors = append(allErrors, pkg_meta.ErrDBExists)
	allErrors = append(allErrors, pkg_meta.ErrDBNotExists)
	allErrors = append(allErrors, pkg_meta.ErrPolicyExists)
	allErrors = append(allErrors, pkg_meta.ErrPolicyNotExists)
	allErrors = append(allErrors, pkg_meta.ErrMaskingPolicyExists)
	allErrors = append(allErrors, pkg_meta.ErrMaskingPolicyNotExists)
	allErrors = append(allErrors, pkg_meta.ErrResourceGroupExists)
	allErrors = append(allErrors, pkg_meta.ErrResourceGroupNotExists)
	allErrors = append(allErrors, pkg_meta.ErrTableExists)
	allErrors = append(allErrors, pkg_meta.ErrTableNotExists)
	allErrors = append(allErrors, pkg_meta.ErrDDLReorgElementNotExist)
	allErrors = append(allErrors, pkg_meta.ErrInvalidString)
	allErrors = append(allErrors, pkg_server_err.ErrInvalidType)
	allErrors = append(allErrors, pkg_server_err.ErrInvalidSequence)
	allErrors = append(allErrors, pkg_server_err.ErrNotAllowedCommand)
	allErrors = append(allErrors, pkg_server_err.ErrAccessDenied)
	allErrors = append(allErrors, pkg_server_err.ErrAccessDeniedNoPassword)
	allErrors = append(allErrors, pkg_server_err.ErrConCount)
	allErrors = append(allErrors, pkg_server_err.ErrTooManyUserConnections)
	allErrors = append(allErrors, pkg_server_err.ErrSecureTransportRequired)
	allErrors = append(allErrors, pkg_server_err.ErrUserPrefixMismatch)
	allErrors = append(allErrors, pkg_server_err.ErrMultiStatementDisabled)
	allErrors = append(allErrors, pkg_server_err.ErrNewAbortingConnection)
	allErrors = append(allErrors, pkg_server_err.ErrNotSupportedAuthMode)
	allErrors = append(allErrors, pkg_server_err.ErrNetPacketTooLarge)
	allErrors = append(allErrors, pkg_server_err.ErrMustChangePassword)
	allErrors = append(allErrors, pkg_server_err.ErrServerShutdown)
	allErrors = append(allErrors, pkg_statistics_handle_autoanalyze_priorityqueue.ErrHeapIsEmpty)
	allErrors = append(allErrors, br_pkg_errors.ErrUnknown)
	allErrors = append(allErrors, br_pkg_errors.ErrInvalidArgument)
	allErrors = append(allErrors, br_pkg_errors.ErrUndefinedRestoreDbOrTable)
	allErrors = append(allErrors, br_pkg_errors.ErrVersionMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrFailedToConnect)
	allErrors = append(allErrors, br_pkg_errors.ErrInvalidMetaFile)
	allErrors = append(allErrors, br_pkg_errors.ErrEnvNotSpecified)
	allErrors = append(allErrors, br_pkg_errors.ErrUnsupportedOperation)
	allErrors = append(allErrors, br_pkg_errors.ErrInvalidRange)
	allErrors = append(allErrors, br_pkg_errors.ErrMigrationNotFound)
	allErrors = append(allErrors, br_pkg_errors.ErrMigrationVersionNotSupported)
	allErrors = append(allErrors, br_pkg_errors.ErrPDUpdateFailed)
	allErrors = append(allErrors, br_pkg_errors.ErrPDLeaderNotFound)
	allErrors = append(allErrors, br_pkg_errors.ErrPDInvalidResponse)
	allErrors = append(allErrors, br_pkg_errors.ErrPDBatchScanRegion)
	allErrors = append(allErrors, br_pkg_errors.ErrPDUnknownScatterResult)
	allErrors = append(allErrors, br_pkg_errors.ErrPDNotFullyScatter)
	allErrors = append(allErrors, br_pkg_errors.ErrPDSplitFailed)
	allErrors = append(allErrors, br_pkg_errors.ErrPDRegionsNotFullyScatter)
	allErrors = append(allErrors, br_pkg_errors.ErrBackupChecksumMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrBackupInvalidRange)
	allErrors = append(allErrors, br_pkg_errors.ErrBackupNoLeader)
	allErrors = append(allErrors, br_pkg_errors.ErrBackupGCSafepointExceeded)
	allErrors = append(allErrors, br_pkg_errors.ErrBackupKeyIsLocked)
	allErrors = append(allErrors, br_pkg_errors.ErrBackupRegion)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreModeMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreRangeMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreCheckpointMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreChecksumMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreTableIDMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreRejectStore)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreNoPeer)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreSplitFailed)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreInvalidRewrite)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreInvalidBackup)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreWriteAndIngest)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreSchemaNotExists)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreNotFreshCluster)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreIncompatibleSys)
	allErrors = append(allErrors, br_pkg_errors.ErrUnsupportedSystemTable)
	allErrors = append(allErrors, br_pkg_errors.ErrDatabasesAlreadyExisted)
	allErrors = append(allErrors, br_pkg_errors.ErrTablesAlreadyExisted)
	allErrors = append(allErrors, br_pkg_errors.ErrStreamLogTaskExist)
	allErrors = append(allErrors, br_pkg_errors.ErrStreamLogTaskHasNoStorage)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreRTsConstrain)
	allErrors = append(allErrors, br_pkg_errors.ErrPiTRInvalidCDCLogFormat)
	allErrors = append(allErrors, br_pkg_errors.ErrPiTRTaskNotFound)
	allErrors = append(allErrors, br_pkg_errors.ErrPiTRInvalidTaskInfo)
	allErrors = append(allErrors, br_pkg_errors.ErrPiTRMalformedMetadata)
	allErrors = append(allErrors, br_pkg_errors.ErrPiTRCheckpointWatchRestart)
	allErrors = append(allErrors, br_pkg_errors.ErrStorageUnknown)
	allErrors = append(allErrors, br_pkg_errors.ErrStorageInvalidConfig)
	allErrors = append(allErrors, br_pkg_errors.ErrStorageInvalidPermission)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreTotalKVMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreInvalidPeer)
	allErrors = append(allErrors, br_pkg_errors.ErrRestoreRegionWithoutPeer)
	allErrors = append(allErrors, br_pkg_errors.ErrKVStorage)
	allErrors = append(allErrors, br_pkg_errors.ErrKVUnknown)
	allErrors = append(allErrors, br_pkg_errors.ErrKVClusterIDMismatch)
	allErrors = append(allErrors, br_pkg_errors.ErrKVNotLeader)
	allErrors = append(allErrors, br_pkg_errors.ErrKVNotTiKV)
	allErrors = append(allErrors, br_pkg_errors.ErrKVDiskFull)
	allErrors = append(allErrors, br_pkg_errors.ErrKVEpochNotMatch)
	allErrors = append(allErrors, br_pkg_errors.ErrKVKeyNotInRegion)
	allErrors = append(allErrors, br_pkg_errors.ErrKVRewriteRuleNotFound)
	allErrors = append(allErrors, br_pkg_errors.ErrKVRangeIsEmpty)
	allErrors = append(allErrors, br_pkg_errors.ErrKVDownloadFailed)
	allErrors = append(allErrors, br_pkg_errors.ErrKVIngestFailed)
	allErrors = append(allErrors, br_pkg_errors.ErrPossibleInconsistency)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrInvalidGroupSettings)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrTooLongResourceGroupName)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrInvalidResourceGroupFormat)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrInvalidResourceGroupDuplicatedMode)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrUnknownResourceGroupMode)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrDroppingInternalResourceGroup)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrResourceGroupRunawayRuleIsEmpty)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrUnknownResourceGroupRunawayAction)
	allErrors = append(allErrors, pkg_ddl_resourcegroup.ErrUnknownResourceGroupRunawaySwitchGroupName)
	allErrors = append(allErrors, pkg_table_tables.ErrInconsistentRowValue)
	allErrors = append(allErrors, pkg_table_tables.ErrInconsistentHandle)
	allErrors = append(allErrors, pkg_table_tables.ErrInconsistentIndexedValue)
	allErrors = append(allErrors, pkg_util_collate.ErrUnsupportedCollation)
	allErrors = append(allErrors, pkg_util_collate.ErrIllegalMixCollation)
	allErrors = append(allErrors, pkg_util_collate.ErrIllegalMix2Collation)
	allErrors = append(allErrors, pkg_util_collate.ErrIllegalMix3Collation)
	allErrors = append(allErrors, pkg_util_watcher.ErrWatcherStarted)
	allErrors = append(allErrors, pkg_util_watcher.ErrWatcherClosed)
	allErrors = append(allErrors, pkg_kv.ErrNotExist)
	allErrors = append(allErrors, pkg_kv.ErrTxnRetryable)
	allErrors = append(allErrors, pkg_kv.ErrCannotSetNilValue)
	allErrors = append(allErrors, pkg_kv.ErrInvalidTxn)
	allErrors = append(allErrors, pkg_kv.ErrTxnTooLarge)
	allErrors = append(allErrors, pkg_kv.ErrEntryTooLarge)
	allErrors = append(allErrors, pkg_kv.ErrKeyTooLarge)
	allErrors = append(allErrors, pkg_kv.ErrKeyExists)
	allErrors = append(allErrors, pkg_kv.ErrNotImplemented)
	allErrors = append(allErrors, pkg_kv.ErrWriteConflict)
	allErrors = append(allErrors, pkg_kv.ErrWriteConflictInTiDB)
	allErrors = append(allErrors, pkg_kv.ErrLockExpire)
	allErrors = append(allErrors, pkg_kv.ErrAssertionFailed)
	allErrors = append(allErrors, lightning_pkg_importer.ErrDuplicateKey)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidConstraintFormat)
	allErrors = append(allErrors, pkg_ddl_placement.ErrUnsupportedConstraint)
	allErrors = append(allErrors, pkg_ddl_placement.ErrConflictingConstraints)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidConstraintsMapcnt)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidConstraintsFormat)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidSurvivalPreferenceFormat)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidConstraintsReplicas)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidBundleID)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidBundleIDFormat)
	allErrors = append(allErrors, pkg_ddl_placement.ErrLeaderReplicasMustOne)
	allErrors = append(allErrors, pkg_ddl_placement.ErrMissingRoleField)
	allErrors = append(allErrors, pkg_ddl_placement.ErrNoRulesToDrop)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidPlacementOptions)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidConstraintsMappingWrongSeparator)
	allErrors = append(allErrors, pkg_ddl_placement.ErrInvalidConstraintsMappingNoColonFound)
	allErrors = append(allErrors, pkg_domain_infosync.ErrHTTPServiceError)
	allErrors = append(allErrors, pkg_domain_infosync.ErrPrometheusAddrIsNotSet)
	allErrors = append(allErrors, pkg_dxf_framework_storage.ErrUnstableSubtasks)
	allErrors = append(allErrors, pkg_dxf_framework_storage.ErrTaskNotFound)
	allErrors = append(allErrors, pkg_dxf_framework_storage.ErrTaskAlreadyExists)
	allErrors = append(allErrors, pkg_dxf_framework_storage.ErrTaskStateNotAllow)
	allErrors = append(allErrors, pkg_dxf_framework_storage.ErrTaskChanged)
	allErrors = append(allErrors, pkg_dxf_framework_storage.ErrSubtaskNotFound)
	allErrors = append(allErrors, pkg_util_parser.ErrPatternNotMatch)
	allErrors = append(allErrors, pkg_param.ErrUnknownFieldType)
	allErrors = append(allErrors, pkg_sessionctx_sessionstates.ErrCannotMigrateSession)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrSnapshotTooOld)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrUnsupportedValueForVar)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrUnknownSystemVar)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrIncorrectScope)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrUnknownTimeZone)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrReadOnly)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrWrongValueForVar)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrWrongTypeForVar)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrTruncatedWrongValue)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrMaxPreparedStmtCountReached)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrUnsupportedIsolationLevel)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrNotSupportedInNextGen)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrNotValidPassword)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrFunctionsNoopImpl)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrVariableNoLongerSupported)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrInvalidDefaultUTF8MB4Collation)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrWarnDeprecatedSyntaxNoReplacement)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrWarnDeprecatedSyntaxSimpleMsg)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrTiDBMemArbitratorSoftLimit)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrTiDBMemArbitratorWaitAverse)
	allErrors = append(allErrors, pkg_sessionctx_variable.ErrTiDBMemArbitratorQueryReserved)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTokenLimit)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTiKVServerTimeout)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTiFlashServerTimeout)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTxnAbortedByGC)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTiKVStaleCommand)
	allErrors = append(allErrors, pkg_store_driver_error.ErrQueryInterrupted)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTiKVMaxTimestampNotSynced)
	allErrors = append(allErrors, pkg_store_driver_error.ErrLockAcquireFailAndNoWaitSet)
	allErrors = append(allErrors, pkg_store_driver_error.ErrResolveLockTimeout)
	allErrors = append(allErrors, pkg_store_driver_error.ErrLockWaitTimeout)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTiKVServerBusy)
	allErrors = append(allErrors, pkg_store_driver_error.ErrTiFlashServerBusy)
	allErrors = append(allErrors, pkg_store_driver_error.ErrPDServerTimeout)
	allErrors = append(allErrors, pkg_store_driver_error.ErrRegionUnavailable)
	allErrors = append(allErrors, pkg_store_driver_error.ErrResourceGroupNotExists)
	allErrors = append(allErrors, pkg_store_driver_error.ErrResourceGroupConfigUnavailable)
	allErrors = append(allErrors, pkg_store_driver_error.ErrResourceGroupThrottled)
	allErrors = append(allErrors, pkg_store_driver_error.ErrUnknown)
	allErrors = append(allErrors, pkg_util_admin.ErrAdminCheckTable)
	allErrors = append(allErrors, pkg_util_stringutil.ErrSyntax)
	allErrors = append(allErrors, pkg_util_chunk.ErrCannotAddBecauseSorted)
	allErrors = append(allErrors, pkg_util_topsql_reporter.ErrTopRUConfig)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnsupportedType)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrAnalyzeMissIndex)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrAnalyzeMissColumn)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWrongParamCount)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrSchemaChanged)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrTablenameNotAllowedHere)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNotSupportedYet)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWrongUsage)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnknown)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnknownTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNoSuchTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrViewRecursive)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWrongArguments)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWrongNumberOfColumnsInSelect)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrBadGeneratedColumn)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrFieldNotInGroupBy)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrAggregateOrderNonAggQuery)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrFieldInOrderNotSelect)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrAggregateInOrderNotSelect)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrBadTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrKeyDoesNotExist)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrOperandColumns)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrInvalidGroupFuncUse)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrIllegalReference)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNoDB)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnknownExplainFormat)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWrongGroupField)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrDupFieldName)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNonUpdatableTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrMultiUpdateKeyConflict)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrInternal)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNonUniqTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowInvalidWindowFuncUse)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowInvalidWindowFuncAliasUse)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowNoSuchWindow)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowCircularityInWindowGraph)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowNoChildPartitioning)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowNoInherentFrame)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowNoRedefineOrderBy)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowDuplicateName)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrPartitionClauseOnNonpartitioned)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowFrameStartIllegal)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowFrameEndIllegal)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowFrameIllegal)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowRangeFrameOrderType)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowRangeFrameTemporalType)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowRangeFrameNumericType)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowRangeBoundNotConstant)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowRowsIntervalUse)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWindowFunctionIgnoresFrame)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrInvalidNumberOfArgs)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrFieldInGroupingNotGroupBy)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnsupportedOnGeneratedColumn)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrPrivilegeCheckFail)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrInvalidWildCard)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrMixOfGroupFuncAndFields)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrTooBigPrecision)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrDBaccessDenied)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrTableaccessDenied)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrSpecificAccessDenied)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrViewNoExplain)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWrongValueCountOnRow)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrViewInvalid)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNoSuchThread)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnknownColumn)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrCartesianProductUnsupported)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrStmtNotFound)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrAmbiguous)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnresolvedHintName)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNotHintUpdatable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrWarnConflictingHint)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrCTERecursiveRequiresUnion)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrCTERecursiveRequiresNonRecursiveFirst)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrCTERecursiveForbidsAggregation)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrCTERecursiveForbiddenJoinOrder)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrInvalidLateralJoin)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrInvalidRequiresSingleReference)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrSQLInReadOnlyMode)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrDeleteNotFoundColumn)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrAccessDenied)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrBadNull)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNotSupportedWithSem)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrAsOf)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrOptOnTemporaryTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrOptOnCacheTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrDropTableOnTemporaryTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrPartitionNoTemporary)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrViewSelectTemporaryTable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrSubqueryMoreThan1Row)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrKeyPart0)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrGettingNoopVariable)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrPrepareMulti)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrUnsupportedPs)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrPsManyParam)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrPrepareDDL)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrRowIsReferenced2)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrNoReferencedRow2)
	allErrors = append(allErrors, pkg_util_dbterror_plannererrors.ErrSpDoesNotExist)
	allErrors = append(allErrors, pkg_dxf_framework_taskexecutor.ErrCancelSubtask)
	allErrors = append(allErrors, pkg_dxf_framework_taskexecutor.ErrNonIdempotentSubtask)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrNoLeader)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVEpochNotMatch)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVNotLeader)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVServerIsBusy)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVRegionNotFound)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVReadIndexNotReady)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVDiskFull)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVIngestFailed)
	allErrors = append(allErrors, pkg_ingestor_errdef.ErrKVRaftProposalDropped)
	allErrors = append(allErrors, pkg_meta_autoid.ErrAutoincReadFailed)
	allErrors = append(allErrors, pkg_meta_autoid.ErrWrongAutoKey)
	allErrors = append(allErrors, pkg_meta_autoid.ErrInvalidAllocatorType)
	allErrors = append(allErrors, pkg_meta_autoid.ErrAutoRandReadFailed)
	allErrors = append(allErrors, pkg_store_mockstore_unistore_tikv_dbreader.ErrScanBreak)
	allErrors = append(allErrors, pkg_util_topsql_state.ErrInvalidTopRUItemInterval)
	allErrors = append(allErrors, pkg_metaservice.ErrGroupNotMatch)
	allErrors = append(allErrors, pkg_metaservice.ErrNilKeyspaceMeta)
	allErrors = append(allErrors, lightning_pkg_checkpoints_checkpointspb.ErrInvalidLengthFileCheckpoints)
	allErrors = append(allErrors, lightning_pkg_checkpoints_checkpointspb.ErrIntOverflowFileCheckpoints)
	allErrors = append(allErrors, lightning_pkg_checkpoints_checkpointspb.ErrUnexpectedEndOfGroupFileCheckpoints)
	allErrors = append(allErrors, pkg_session.ErrNonTransactionalJobFailure)
	allErrors = append(allErrors, pkg_session.ErrForUpdateCantRetry)
	allErrors = append(allErrors, br_pkg_restore_split.ErrBackoff)
	allErrors = append(allErrors, br_pkg_restore_split.ErrBackoffAndDontCount)
	allErrors = append(allErrors, pkg_domain.ErrInfoSchemaExpired)
	allErrors = append(allErrors, pkg_domain.ErrInfoSchemaChanged)
	allErrors = append(allErrors, pkg_lightning_common.ErrUnknown)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidArgument)
	allErrors = append(allErrors, pkg_lightning_common.ErrVersionMismatch)
	allErrors = append(allErrors, pkg_lightning_common.ErrReadConfigFile)
	allErrors = append(allErrors, pkg_lightning_common.ErrParseConfigFile)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidConfig)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidTLSConfig)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidSortedKVDir)
	allErrors = append(allErrors, pkg_lightning_common.ErrStorageUnknown)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidPermission)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidStorageConfig)
	allErrors = append(allErrors, pkg_lightning_common.ErrEmptySourceDir)
	allErrors = append(allErrors, pkg_lightning_common.ErrTableRoute)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidSchemaFile)
	allErrors = append(allErrors, pkg_lightning_common.ErrTooManySourceFiles)
	allErrors = append(allErrors, pkg_lightning_common.ErrSystemRequirementNotMet)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckpointSchemaConflict)
	allErrors = append(allErrors, pkg_lightning_common.ErrPreCheckFailed)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckClusterRegion)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckLocalResource)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckTableEmpty)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckCSVHeader)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckDataSource)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckCDCPiTR)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckPDTiDBFromSameCluster)
	allErrors = append(allErrors, pkg_lightning_common.ErrOpenCheckpoint)
	allErrors = append(allErrors, pkg_lightning_common.ErrReadCheckpoint)
	allErrors = append(allErrors, pkg_lightning_common.ErrUpdateCheckpoint)
	allErrors = append(allErrors, pkg_lightning_common.ErrUnknownCheckpointDriver)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidCheckpoint)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckpointNotFound)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckpointTableNotFound)
	allErrors = append(allErrors, pkg_lightning_common.ErrInitCheckpoint)
	allErrors = append(allErrors, pkg_lightning_common.ErrCleanCheckpoint)
	allErrors = append(allErrors, pkg_lightning_common.ErrMetaMgrUnknown)
	allErrors = append(allErrors, pkg_lightning_common.ErrDBConnect)
	allErrors = append(allErrors, pkg_lightning_common.ErrInitErrManager)
	allErrors = append(allErrors, pkg_lightning_common.ErrInitMetaManager)
	allErrors = append(allErrors, pkg_lightning_common.ErrUpdatePD)
	allErrors = append(allErrors, pkg_lightning_common.ErrCreatePDClient)
	allErrors = append(allErrors, pkg_lightning_common.ErrPauseGC)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckKVVersion)
	allErrors = append(allErrors, pkg_lightning_common.ErrCreateKVClient)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckMultiIngest)
	allErrors = append(allErrors, pkg_lightning_common.ErrUnknownBackend)
	allErrors = append(allErrors, pkg_lightning_common.ErrCheckLocalFile)
	allErrors = append(allErrors, pkg_lightning_common.ErrOpenDuplicateDB)
	allErrors = append(allErrors, pkg_lightning_common.ErrSchemaNotExists)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidSchemaStmt)
	allErrors = append(allErrors, pkg_lightning_common.ErrCreateSchema)
	allErrors = append(allErrors, pkg_lightning_common.ErrUnknownColumns)
	allErrors = append(allErrors, pkg_lightning_common.ErrChecksumMismatch)
	allErrors = append(allErrors, pkg_lightning_common.ErrRestoreTable)
	allErrors = append(allErrors, pkg_lightning_common.ErrEncodeKV)
	allErrors = append(allErrors, pkg_lightning_common.ErrCastValue)
	allErrors = append(allErrors, pkg_lightning_common.ErrAllocTableRowIDs)
	allErrors = append(allErrors, pkg_lightning_common.ErrInvalidMetaStatus)
	allErrors = append(allErrors, pkg_lightning_common.ErrTableIsChecksuming)
	allErrors = append(allErrors, pkg_lightning_common.ErrResolveDuplicateRows)
	allErrors = append(allErrors, pkg_lightning_common.ErrFoundDuplicateKeys)
	allErrors = append(allErrors, pkg_lightning_common.ErrAddIndexFailed)
	allErrors = append(allErrors, pkg_lightning_common.ErrDropIndexFailed)
	allErrors = append(allErrors, pkg_lightning_common.ErrFoundDataConflictRecords)
	allErrors = append(allErrors, pkg_lightning_common.ErrFoundIndexConflictRecords)
	allErrors = append(allErrors, pkg_lightning_common.ErrWriteTooSlow)
	allErrors = append(allErrors, pkg_privilege_privileges.ErrNonexistingGrant)
	allErrors = append(allErrors, pkg_privilege_privileges.ErrAccessDenied)
	allErrors = append(allErrors, pkg_privilege_privileges.ErrMustChangePasswordLogin)
	allErrors = append(allErrors, pkg_timer_api.ErrTimerNotExist)
	allErrors = append(allErrors, pkg_timer_api.ErrTimerExists)
	allErrors = append(allErrors, pkg_timer_api.ErrVersionNotMatch)
	allErrors = append(allErrors, pkg_timer_api.ErrEventIDNotMatch)
	allErrors = append(allErrors, pkg_types.ErrDataTooLong)
	allErrors = append(allErrors, pkg_types.ErrIllegalValueForType)
	allErrors = append(allErrors, pkg_types.ErrTruncated)
	allErrors = append(allErrors, pkg_types.ErrOverflow)
	allErrors = append(allErrors, pkg_types.ErrDivByZero)
	allErrors = append(allErrors, pkg_types.ErrTooBigDisplayWidth)
	allErrors = append(allErrors, pkg_types.ErrTooBigFieldLength)
	allErrors = append(allErrors, pkg_types.ErrTooBigSet)
	allErrors = append(allErrors, pkg_types.ErrTooBigScale)
	allErrors = append(allErrors, pkg_types.ErrTooBigPrecision)
	allErrors = append(allErrors, pkg_types.ErrBadNumber)
	allErrors = append(allErrors, pkg_types.ErrInvalidFieldSize)
	allErrors = append(allErrors, pkg_types.ErrMBiggerThanD)
	allErrors = append(allErrors, pkg_types.ErrWarnDataOutOfRange)
	allErrors = append(allErrors, pkg_types.ErrDuplicatedValueInType)
	allErrors = append(allErrors, pkg_types.ErrDatetimeFunctionOverflow)
	allErrors = append(allErrors, pkg_types.ErrCastAsSignedOverflow)
	allErrors = append(allErrors, pkg_types.ErrCastNegIntAsUnsigned)
	allErrors = append(allErrors, pkg_types.ErrInvalidYearFormat)
	allErrors = append(allErrors, pkg_types.ErrInvalidYear)
	allErrors = append(allErrors, pkg_types.ErrTruncatedWrongVal)
	allErrors = append(allErrors, pkg_types.ErrInvalidWeekModeFormat)
	allErrors = append(allErrors, pkg_types.ErrWrongFieldSpec)
	allErrors = append(allErrors, pkg_types.ErrSyntax)
	allErrors = append(allErrors, pkg_types.ErrWrongValue)
	allErrors = append(allErrors, pkg_types.ErrWrongValue2)
	allErrors = append(allErrors, pkg_types.ErrWrongValueForType)
	allErrors = append(allErrors, pkg_types.ErrPartitionStatsMissing)
	allErrors = append(allErrors, pkg_types.ErrPartitionColumnStatsMissing)
	allErrors = append(allErrors, pkg_types.ErrIncorrectDatetimeValue)
	allErrors = append(allErrors, pkg_types.ErrJSONBadOneOrAllArg)
	allErrors = append(allErrors, pkg_types.ErrJSONVacuousPath)
	allErrors = append(allErrors, pkg_types.ErrTimestampInDSTTransition)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONText)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONType)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONTextInParam)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONPath)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONCharset)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONData)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONPathMultipleSelection)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONContainsPathType)
	allErrors = append(allErrors, pkg_types.ErrJSONDocumentNULLKey)
	allErrors = append(allErrors, pkg_types.ErrJSONDocumentTooDeep)
	allErrors = append(allErrors, pkg_types.ErrJSONObjectKeyTooLong)
	allErrors = append(allErrors, pkg_types.ErrInvalidJSONPathArrayCell)
	allErrors = append(allErrors, pkg_types.ErrUnsupportedSecondArgumentType)
	allErrors = append(allErrors, pkg_util_hint.ErrWarnConflictingHint)
	allErrors = append(allErrors, pkg_util_timeutil.ErrUnknownTimeZone)
	allErrors = append(allErrors, pkg_lock.ErrLockedTableDropped)
	allErrors = append(allErrors, pkg_util_dbutil.ErrVersionNotFound)
	allErrors = append(allErrors, pkg_util_dbutil.ErrNoData)
	allErrors = append(allErrors, pkg_ddl_notifier.ErrNotReadyRetryLater)
	allErrors = append(allErrors, pkg_executor.ErrSavepointNotSupportedWithBinlog)

	var dedup = map[string]spec{}
	for _, e := range allErrors {
		terr, ok := e.(*errors.Error)
		if !ok {
			println("Non-normalized error:", e.Error())
		} else {
			val := reflect.ValueOf(terr).Elem()
			codeText := val.FieldByName("codeText")
			message := val.FieldByName("message")
			if previous, found := dedup[codeText.String()]; found {
				println("Duplicated error code:", codeText.String())
				if message.String() < previous.Error {
					continue
				}
			}
			s := spec{
				Code:  codeText.String(),
				Error: message.String(),
			}
			if exist, found := existDefinition[s.Code]; found {
				s.Description = strings.TrimSpace(exist.Description)
				s.Workaround = strings.TrimSpace(exist.Workaround)
			}
			dedup[codeText.String()] = s
		}
	}

	var sorted []spec
	for _, item := range dedup {
		sorted = append(sorted, item)
	}
	sort.Slice(sorted, func(i, j int) bool {
		// TiDB exits duplicated code
		if sorted[i].Code == sorted[j].Code {
			return sorted[i].Error < sorted[j].Error
		}
		return sorted[i].Code < sorted[j].Code
	})

	// We don't use toml library to serialize it due to cannot reserve the order for map[string]spec
	buffer := bytes.NewBufferString("# AUTOGENERATED BY github.com/pingcap/errors/errdoc-gen\n" +
		"# YOU CAN CHANGE THE 'description'/'workaround' FIELDS IF THEM ARE IMPROPER.\n\n")
	for _, item := range sorted {
		buffer.WriteString(fmt.Sprintf("[\"%s\"]\nerror = '''\n%s\n'''\n", item.Code, item.Error))
		if item.Description != "" {
			buffer.WriteString(fmt.Sprintf("description = '''\n%s\n'''\n", item.Description))
		}
		if item.Workaround != "" {
			buffer.WriteString(fmt.Sprintf("workaround = '''\n%s\n'''\n", item.Workaround))
		}
		buffer.WriteString("\n")
	}
	if err := ioutil.WriteFile(outpath, buffer.Bytes(), 0644); err != nil {
		panic(err)
	}
}
type spec struct {
Code        string
Error       string `toml:"error"`
Description string `toml:"description"`
Workaround  string `toml:"workaround"`
}