load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "pluginpkg_lib",
    srcs = [
        "module.go",
        "pluginpkg.go",
    ],
    importpath = "github.com/pingcap/tidb/cmd/pluginpkg",
    visibility = ["//visibility:private"],
    deps = ["@com_github_burntsushi_toml//:toml"],
)

go_binary(
    name = "pluginpkg",
    embed = [":pluginpkg_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "pluginpkg_test",
    timeout = "short",
    srcs = ["module_test.go"],
    data = ["@go_sdk//:files"],
    embed = [":pluginpkg_lib"],
    flaky = True,
    deps = ["@io_bazel_rules_go//go/tools/bazel:go_default_library"],
)
