// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package traceevent_test

import "testing"

func TestSuite(t *testing.T) {
	RunSuite(t)
}

func TestTraceEventModes(t *testing.T) {
	RunTraceEventModes(t)
}

func TestRingBufferSnapshotOrder(t *testing.T) {
	RunRingBufferSnapshotOrder(t)
}

func TestRingBufferFlushTo(t *testing.T) {
	RunRingBufferFlushTo(t)
}

func TestCategoryNames(t *testing.T) {
	RunCategoryNames(t)
}
