[package]
autotests = false
name = "tidb-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tikv-client-kvproto = { path = "../../third_party/tikv-client-rs/kvproto" }

[build-dependencies]
prost.workspace = true
prost-types = "0.14.4"
tonic-prost-build.workspace = true

[lints]
workspace = true

[dev-dependencies]
prost-types = "0.14.4"

[[test]]
name = "all"
path = "tests/all.rs"
