[package]
name = "tidb-sqlexec-mock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "TiDB restricted SQL executor test double."

[lints]
workspace = true

[dependencies]
tidb-ast = { path = "../tidb-ast" }
tidb-datatype = { path = "../tidb-datatype" }
tidb-resolve = { path = "../tidb-resolve" }
tidb-sqlexec = { path = "../tidb-sqlexec" }
tidb-util = { path = "../tidb-util" }
