{
 "title": "Test-Cluster-CRPiTR",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "label": "K8s-cluster",
    "query": "label_values(pd_cluster_status, k8s_cluster)"
   },
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": "label_values(pd_cluster_status{k8s_cluster=\"$k8s_cluster\"}, tidb_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tidb_server_connections{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Advancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live Status",
     "type": "stat",
     "description": "Whether CRR checkpoint advancer is live.",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(tidb_br_crr_service_live{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"})",
       "legendFormat": "live status"
      }
     ]
    },
    {
     "title": "Ready Status",
     "type": "stat",
     "description": "Whether CRR checkpoint advancer is ready.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(tidb_br_crr_service_ready{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"})",
       "legendFormat": "ready status"
      }
     ]
    },
    {
     "title": "Current Round",
     "type": "stat",
     "description": "Current CRR checkpoint advancer calculation round.",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tidb_br_crr_current_round{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "current round"
      }
     ]
    },
    {
     "title": "Alive Store Count",
     "type": "stat",
     "description": "Current alive store count.",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tidb_br_crr_alive_store_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "alive store count"
      }
     ]
    },
    {
     "title": "Synced TS",
     "type": "graph",
     "description": "Current synced ts(minimum synced flush ts across all alive stores) of CRR service adancer.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_synced_ts{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"} / 262144",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "Global Log Backup Checkpoint Gap",
     "type": "graph",
     "description": "Log backup current gap between upstream and downstream global checkpoint.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(tidb_br_crr_last_upstream_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"} - tidb_br_crr_safe_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}) / 262144",
       "legendFormat": "upstream/downstream-gap-{{task}}"
      },
      {
       "expr": "time() * 1000 - tidb_br_crr_safe_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"} / 262144",
       "legendFormat": "downstream-rpo-{{task}}"
      }
     ]
    },
    {
     "title": "Global Log Backup Checkpoint",
     "type": "graph",
     "description": "Log backup current upstream/downstream global checkpoint and the checkpoint persisted to external storage.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_last_upstream_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"} / 262144",
       "legendFormat": "upstream-{{task}}"
      },
      {
       "expr": "tidb_br_crr_safe_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"} / 262144",
       "legendFormat": "downstream-{{task}}"
      },
      {
       "expr": "tidb_log_backup_last_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"} / 262144",
       "legendFormat": "last-checkpoint-{{task}}"
      },
      {
       "expr": "tidb_log_backup_external_storage_checkpoint{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"} / 262144",
       "legendFormat": "external-storage-{{task}}"
      }
     ]
    },
    {
     "title": "Advancer Service State",
     "type": "graph",
     "description": "The history of CRR advancer service state.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_service_state{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{state}}-{{task}}"
      }
     ]
    },
    {
     "title": "Advancer Service Phase",
     "type": "graph",
     "description": "The history of CRR advancer service phase.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_service_phase{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{phase}}-{{task}}"
      }
     ]
    },
    {
     "title": "Loop iteration",
     "type": "graph",
     "description": "Loop iteration to wait downstream files synced in each phase.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_last_loop_iteration{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "Pending File Count",
     "type": "graph",
     "description": "Pending file count in each round.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_pending_file_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "Consecutive Failures",
     "type": "graph",
     "description": "Consecutive failure count since last success time",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_consecutive_failures{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "Upstream Read Meta File Count",
     "type": "graph",
     "description": "Read upstream meta file count in each round",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_upstream_read_meta_file_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "Estimated Sync Log File Count",
     "type": "graph",
     "description": "Estimated sync log file count in each round",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_estimated_sync_log_file_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{task}}"
      }
     ]
    },
    {
     "title": "Estimated Sync Log File Count",
     "type": "graph",
     "description": "Estimated sync log file count in each round",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_br_crr_downstream_check_file_count{k8s_cluster=\"$k8s_cluster\", tidb_cluster=\"$tidb_cluster\", instance=~\"$instance\"}",
       "legendFormat": "{{task}}"
      }
     ]
    }
   ]
  }
 ]
}