[package]
name = "tidb-codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "TiDB mem-comparable scalar and datum-key codec."
autotests = false
build = "../../scripts/aggregate-tests.rs"

[lints]
workspace = true

[dependencies]
chrono.workspace = true
tidb-datatype = { path = "../tidb-datatype" }

[[test]]
name = "all"
path = "tests/all.rs"

[[bench]]
name = "codec"
harness = false
