load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "localfts",
    srcs = [
        "analyzer.go",
        "document.go",
        "query.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/expression/localfts",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/expression/matchagainst",
        "//pkg/meta/model",
        "//pkg/sessionctx",
        "//pkg/sessionctx/variable",
    ],
)

go_test(
    name = "localfts_test",
    timeout = "short",
    srcs = [
        "analyzer_test.go",
        "query_test.go",
    ],
    embed = [":localfts"],
    flaky = False,
    shard_count = 18,
    deps = [
        "//pkg/meta/model",
        "//pkg/sessionctx/variable",
        "//pkg/util/mock",
        "@com_github_stretchr_testify//require",
    ],
)
