// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestDefaultHttpTransport(t *testing.T) {
	RunDefaultHttpTransport(t)
}

func TestDefaultHttpClient(t *testing.T) {
	RunDefaultHttpClient(t)
}

func TestNewMemStorage(t *testing.T) {
	RunNewMemStorage(t)
}
