// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package executor_test

import "testing"

func TestAdminShowNextID(t *testing.T) {
	RunAdminShowNextID(t)
}

func TestAnalyzeNextRawErrorNoLeak(t *testing.T) {
	RunAnalyzeNextRawErrorNoLeak(t)
}

func TestAutoRandRecoverTable(t *testing.T) {
	RunAutoRandRecoverTable(t)
}

func TestBatchInsertDelete(t *testing.T) {
	RunBatchInsertDelete(t)
}

func TestCartesianProduct(t *testing.T) {
	RunCartesianProduct(t)
}

func TestCoprocessorPriority(t *testing.T) {
	RunCoprocessorPriority(t)
}

func TestEarlyClose(t *testing.T) {
	RunEarlyClose(t)
}

func TestIndexDoubleReadClose(t *testing.T) {
	RunIndexDoubleReadClose(t)
}

func TestIndexMergeReaderClose(t *testing.T) {
	RunIndexMergeReaderClose(t)
}

func TestInsertFromSelectConflictRetryAutoID(t *testing.T) {
	RunInsertFromSelectConflictRetryAutoID(t)
}

func TestIssue18744(t *testing.T) {
	RunIssue18744(t)
}

func TestOOMPanicInHashJoinWhenFetchBuildRows(t *testing.T) {
	RunOOMPanicInHashJoinWhenFetchBuildRows(t)
}

func TestParallelHashAggClose(t *testing.T) {
	RunParallelHashAggClose(t)
}

func TestPessimisticConflictRetryAutoID(t *testing.T) {
	RunPessimisticConflictRetryAutoID(t)
}

func TestPrepareMaxParamCountCheck(t *testing.T) {
	RunPrepareMaxParamCountCheck(t)
}

func TestShow(t *testing.T) {
	RunShow(t)
}

func TestShowStatsHealthy(t *testing.T) {
	RunShowStatsHealthy(t)
}

func TestUnparallelHashAggClose(t *testing.T) {
	RunUnparallelHashAggClose(t)
}
