// Code generated by mega-gen. DO NOT EDIT.

package etcd_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("util_etcd", "SetEtcdCliByNamespace", RunSetEtcdCliByNamespace)
}
