// Code generated by mega-gen. DO NOT EDIT.

package test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("server_tests_standby", "Standby", RunStandby)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "server_tests_standby" {
			InitForMega()
		}
	})
}
