// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Go master 93a01d31f6da205ae4bf376825293903a6899fdb pkg/infoschema/tables.go.
// Current and history tables share the upstream declaration.
const STATEMENTS_SUMMARY_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "SUMMARY_BEGIN_TIME",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 1,
        deflt: None,
        comment: Some("Begin time of this summary"),
    },
    InfoColumn {
        name: "SUMMARY_END_TIME",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 1,
        deflt: None,
        comment: Some("End time of this summary"),
    },
    InfoColumn {
        name: "STMT_TYPE",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 1,
        deflt: None,
        comment: Some("Statement type"),
    },
    InfoColumn {
        name: "SCHEMA_NAME",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Current schema"),
    },
    InfoColumn {
        name: "DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "DIGEST_TEXT",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 1,
        deflt: None,
        comment: Some("Normalized statement"),
    },
    InfoColumn {
        name: "TABLE_NAMES",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("Involved tables"),
    },
    InfoColumn {
        name: "INDEX_NAMES",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("Used indices"),
    },
    InfoColumn {
        name: "SAMPLE_USER",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Sampled user who executed these statements"),
    },
    InfoColumn {
        name: "EXEC_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Count of executions"),
    },
    InfoColumn {
        name: "SUM_ERRORS",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Sum of errors"),
    },
    InfoColumn {
        name: "SUM_WARNINGS",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Sum of warnings"),
    },
    InfoColumn {
        name: "SUM_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum latency of these statements"),
    },
    InfoColumn {
        name: "MAX_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max latency of these statements"),
    },
    InfoColumn {
        name: "MIN_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Min latency of these statements"),
    },
    InfoColumn {
        name: "AVG_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average latency of these statements"),
    },
    InfoColumn {
        name: "AVG_PARSE_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average latency of parsing"),
    },
    InfoColumn {
        name: "MAX_PARSE_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max latency of parsing"),
    },
    InfoColumn {
        name: "AVG_COMPILE_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average latency of compiling"),
    },
    InfoColumn {
        name: "MAX_COMPILE_LATENCY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max latency of compiling"),
    },
    InfoColumn {
        name: "SUM_COP_TASK_NUM",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total number of CopTasks"),
    },
    InfoColumn {
        name: "MAX_COP_PROCESS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max processing time of CopTasks"),
    },
    InfoColumn {
        name: "MAX_COP_PROCESS_ADDRESS",
        tp: FieldTypeCode::Varchar,
        size: 256,
        flag: 0,
        deflt: None,
        comment: Some("Address of the CopTask with max processing time"),
    },
    InfoColumn {
        name: "MAX_COP_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max waiting time of CopTasks"),
    },
    InfoColumn {
        name: "MAX_COP_WAIT_ADDRESS",
        tp: FieldTypeCode::Varchar,
        size: 256,
        flag: 0,
        deflt: None,
        comment: Some("Address of the CopTask with max waiting time"),
    },
    InfoColumn {
        name: "AVG_PROCESS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average processing time in TiKV"),
    },
    InfoColumn {
        name: "MAX_PROCESS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max processing time in TiKV"),
    },
    InfoColumn {
        name: "AVG_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average waiting time in TiKV"),
    },
    InfoColumn {
        name: "MAX_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max waiting time in TiKV"),
    },
    InfoColumn {
        name: "AVG_BACKOFF_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average waiting time before retry"),
    },
    InfoColumn {
        name: "MAX_BACKOFF_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max waiting time before retry"),
    },
    InfoColumn {
        name: "AVG_TOTAL_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average number of scanned keys"),
    },
    InfoColumn {
        name: "MAX_TOTAL_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max number of scanned keys"),
    },
    InfoColumn {
        name: "AVG_PROCESSED_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average number of processed keys"),
    },
    InfoColumn {
        name: "MAX_PROCESSED_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max number of processed keys"),
    },
    InfoColumn {
        name: "AVG_ROCKSDB_DELETE_SKIPPED_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of rocksdb delete skipped count"),
    },
    InfoColumn {
        name: "MAX_ROCKSDB_DELETE_SKIPPED_COUNT",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Max number of rocksdb delete skipped count"),
    },
    InfoColumn {
        name: "AVG_ROCKSDB_KEY_SKIPPED_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of rocksdb key skipped count"),
    },
    InfoColumn {
        name: "MAX_ROCKSDB_KEY_SKIPPED_COUNT",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Max number of rocksdb key skipped count"),
    },
    InfoColumn {
        name: "AVG_ROCKSDB_BLOCK_CACHE_HIT_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of rocksdb block cache hit count"),
    },
    InfoColumn {
        name: "MAX_ROCKSDB_BLOCK_CACHE_HIT_COUNT",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Max number of rocksdb block cache hit count"),
    },
    InfoColumn {
        name: "AVG_ROCKSDB_BLOCK_READ_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of rocksdb block read count"),
    },
    InfoColumn {
        name: "MAX_ROCKSDB_BLOCK_READ_COUNT",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Max number of rocksdb block read count"),
    },
    InfoColumn {
        name: "AVG_ROCKSDB_BLOCK_READ_BYTE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of rocksdb block read byte"),
    },
    InfoColumn {
        name: "MAX_ROCKSDB_BLOCK_READ_BYTE",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Max number of rocksdb block read byte"),
    },
    InfoColumn {
        name: "IA_EXEC_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Count of executions that read IA remote segments"),
    },
    InfoColumn {
        name: "AVG_IA_REMOTE_READ_SEGMENT_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of IA remote segments read"),
    },
    InfoColumn {
        name: "MAX_IA_REMOTE_READ_SEGMENT_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max number of IA remote segments read"),
    },
    InfoColumn {
        name: "AVG_IA_REMOTE_READ_SEGMENT_SIZE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of bytes returned from IA remote segment reads"),
    },
    InfoColumn {
        name: "MAX_IA_REMOTE_READ_SEGMENT_SIZE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max number of bytes returned from IA remote segment reads"),
    },
    InfoColumn {
        name: "AVG_IA_REMOTE_READ_SEGMENT_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average time spent waiting for IA remote segment reads"),
    },
    InfoColumn {
        name: "MAX_IA_REMOTE_READ_SEGMENT_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max time spent waiting for IA remote segment reads"),
    },
    InfoColumn {
        name: "AVG_PREWRITE_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average time of prewrite phase"),
    },
    InfoColumn {
        name: "MAX_PREWRITE_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max time of prewrite phase"),
    },
    InfoColumn {
        name: "AVG_COMMIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average time of commit phase"),
    },
    InfoColumn {
        name: "MAX_COMMIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max time of commit phase"),
    },
    InfoColumn {
        name: "AVG_GET_COMMIT_TS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average time of getting commit_ts"),
    },
    InfoColumn {
        name: "MAX_GET_COMMIT_TS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max time of getting commit_ts"),
    },
    InfoColumn {
        name: "AVG_COMMIT_BACKOFF_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average time before retry during commit phase"),
    },
    InfoColumn {
        name: "MAX_COMMIT_BACKOFF_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max time before retry during commit phase"),
    },
    InfoColumn {
        name: "AVG_RESOLVE_LOCK_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average time for resolving locks"),
    },
    InfoColumn {
        name: "MAX_RESOLVE_LOCK_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max time for resolving locks"),
    },
    InfoColumn {
        name: "AVG_LOCAL_LATCH_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average waiting time of local transaction"),
    },
    InfoColumn {
        name: "MAX_LOCAL_LATCH_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max waiting time of local transaction"),
    },
    InfoColumn {
        name: "AVG_WRITE_KEYS",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average count of written keys"),
    },
    InfoColumn {
        name: "MAX_WRITE_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max count of written keys"),
    },
    InfoColumn {
        name: "AVG_WRITE_SIZE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average amount of written bytes"),
    },
    InfoColumn {
        name: "MAX_WRITE_SIZE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max amount of written bytes"),
    },
    InfoColumn {
        name: "AVG_PREWRITE_REGIONS",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of involved regions in prewrite phase"),
    },
    InfoColumn {
        name: "MAX_PREWRITE_REGIONS",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Max number of involved regions in prewrite phase"),
    },
    InfoColumn {
        name: "AVG_TXN_RETRY",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of transaction retries"),
    },
    InfoColumn {
        name: "MAX_TXN_RETRY",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Max number of transaction retries"),
    },
    InfoColumn {
        name: "SUM_EXEC_RETRY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum number of execution retries in pessimistic transactions"),
    },
    InfoColumn {
        name: "SUM_EXEC_RETRY_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum time of execution retries in pessimistic transactions"),
    },
    InfoColumn {
        name: "SUM_BACKOFF_TIMES",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum of retries"),
    },
    InfoColumn {
        name: "BACKOFF_TYPES",
        tp: FieldTypeCode::Varchar,
        size: 1024,
        flag: 0,
        deflt: None,
        comment: Some("Types of errors and the number of retries for each type"),
    },
    InfoColumn {
        name: "AVG_MEM",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average memory(byte) used"),
    },
    InfoColumn {
        name: "MAX_MEM",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max memory(byte) used"),
    },
    InfoColumn {
        name: "AVG_MEM_ARBITRATION",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average time of memory arbitration"),
    },
    InfoColumn {
        name: "MAX_MEM_ARBITRATION",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Max time of memory arbitration"),
    },
    InfoColumn {
        name: "AVG_DISK",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Average disk space(byte) used"),
    },
    InfoColumn {
        name: "MAX_DISK",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Max disk space(byte) used"),
    },
    InfoColumn {
        name: "AVG_KV_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average time of TiKV used"),
    },
    InfoColumn {
        name: "AVG_PD_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average time of PD used"),
    },
    InfoColumn {
        name: "AVG_BACKOFF_TOTAL_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average time of Backoff used"),
    },
    InfoColumn {
        name: "AVG_WRITE_SQL_RESP_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average time of write sql resp used"),
    },
    InfoColumn {
        name: "AVG_TIDB_CPU_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average cpu time tidb used"),
    },
    InfoColumn {
        name: "AVG_TIKV_CPU_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average cpu time tikv used"),
    },
    InfoColumn {
        name: "MAX_RESULT_ROWS",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 1,
        deflt: None,
        comment: Some("Max count of sql result rows"),
    },
    InfoColumn {
        name: "MIN_RESULT_ROWS",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 1,
        deflt: None,
        comment: Some("Min count of sql result rows"),
    },
    InfoColumn {
        name: "AVG_RESULT_ROWS",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 1,
        deflt: None,
        comment: Some("Average count of sql result rows"),
    },
    InfoColumn {
        name: "PREPARED",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether prepared"),
    },
    InfoColumn {
        name: "AVG_AFFECTED_ROWS",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average number of rows affected"),
    },
    InfoColumn {
        name: "FIRST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 1,
        deflt: None,
        comment: Some("The time these statements are seen for the first time"),
    },
    InfoColumn {
        name: "LAST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 1,
        deflt: None,
        comment: Some("The time these statements are seen for the last time"),
    },
    InfoColumn {
        name: "PLAN_IN_CACHE",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement hit plan cache"),
    },
    InfoColumn {
        name: "PLAN_CACHE_HITS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 1,
        deflt: None,
        comment: Some("The number of times these statements hit plan cache"),
    },
    InfoColumn {
        name: "PLAN_IN_BINDING",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement is matched with the hints in the binding"),
    },
    InfoColumn {
        name: "QUERY_SAMPLE_TEXT",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("Sampled original statement"),
    },
    InfoColumn {
        name: "PREV_SAMPLE_TEXT",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("The previous statement before commit"),
    },
    InfoColumn {
        name: "PLAN_DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Digest of its execution plan"),
    },
    InfoColumn {
        name: "PLAN",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("Sampled execution plan"),
    },
    InfoColumn {
        name: "BINARY_PLAN",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("Sampled binary plan"),
    },
    InfoColumn {
        name: "BINDING_DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Digest of normalized statement for bindings"),
    },
    InfoColumn {
        name: "BINDING_DIGEST_TEXT",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 1,
        deflt: None,
        comment: Some("Normalized statement for bindings"),
    },
    InfoColumn {
        name: "CHARSET",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Sampled charset"),
    },
    InfoColumn {
        name: "COLLATION",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Sampled collation"),
    },
    InfoColumn {
        name: "PLAN_HINT",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("Sampled plan hint"),
    },
    InfoColumn {
        name: "MAX_REQUEST_UNIT_READ",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Max read request-unit cost of these statements"),
    },
    InfoColumn {
        name: "AVG_REQUEST_UNIT_READ",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average read request-unit cost of these statements"),
    },
    InfoColumn {
        name: "MAX_REQUEST_UNIT_WRITE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Max write request-unit cost of these statements"),
    },
    InfoColumn {
        name: "AVG_REQUEST_UNIT_WRITE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average write request-unit cost of these statements"),
    },
    InfoColumn {
        name: "MAX_QUEUED_RC_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Max time of waiting for available request-units"),
    },
    InfoColumn {
        name: "AVG_QUEUED_RC_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Average time of waiting for available request-units"),
    },
    InfoColumn {
        name: "RESOURCE_GROUP",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Bind resource group name"),
    },
    InfoColumn {
        name: "PLAN_CACHE_UNQUALIFIED",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 1,
        deflt: None,
        comment: Some(
            "The number of times that these statements are not supported by the plan cache",
        ),
    },
    InfoColumn {
        name: "PLAN_CACHE_UNQUALIFIED_LAST_REASON",
        tp: FieldTypeCode::Blob,
        size: UNSPECIFIED_LENGTH,
        flag: 0,
        deflt: None,
        comment: Some("The last reason why the statement is not supported by the plan cache"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_SENT_TIKV_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tikv"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_RECEIVED_TIKV_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tikv"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_SENT_TIKV_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tikv cross zone"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_RECEIVED_TIKV_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tikv cross zone"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_SENT_TIFLASH_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tiflash"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_RECEIVED_TIFLASH_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tiflash"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_SENT_TIFLASH_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tiflash cross zone"),
    },
    InfoColumn {
        name: "SUM_UNPACKED_BYTES_RECEIVED_TIFLASH_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tiflash cross zone"),
    },
    InfoColumn {
        name: "STORAGE_KV",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement read data from TiKV"),
    },
    InfoColumn {
        name: "STORAGE_MPP",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement read data from TiFlash"),
    },
];
