const WORKLOAD_TIDB_INDEX_USAGE_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "TABLE_SCHEMA",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "TABLE_NAME",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "INDEX_NAME",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "QUERY_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "KV_REQ_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ROWS_ACCESS_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "PERCENTAGE_ACCESS_0",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "PERCENTAGE_ACCESS_0_1",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "PERCENTAGE_ACCESS_1_10",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "PERCENTAGE_ACCESS_10_20",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "PERCENTAGE_ACCESS_20_50",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "PERCENTAGE_ACCESS_50_100",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "PERCENTAGE_ACCESS_100",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "LAST_ACCESS_TIME",
        tp: FieldTypeCode::Datetime,
        size: 21,
        flag: 0,
        deflt: None,
        comment: None,
    },
];

const WORKLOAD_TIDB_STATEMENTS_STATS_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "STMT_TYPE",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 1,
        deflt: None,
        comment: Some("Statement type"),
    },
    InfoColumn {
        name: "SCHEMA_NAME",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Current schema"),
    },
    InfoColumn {
        name: "DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "DIGEST_TEXT",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 1,
        deflt: None,
        comment: Some("Normalized statement"),
    },
    InfoColumn {
        name: "TABLE_NAMES",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Involved tables"),
    },
    InfoColumn {
        name: "INDEX_NAMES",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Used indices"),
    },
    InfoColumn {
        name: "SAMPLE_USER",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Sampled user who executed these statements"),
    },
    InfoColumn {
        name: "EXEC_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Count of executions"),
    },
    InfoColumn {
        name: "ERRORS",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Sum of errors"),
    },
    InfoColumn {
        name: "WARNINGS",
        tp: FieldTypeCode::Long,
        size: 11,
        flag: 33,
        deflt: None,
        comment: Some("Sum of warnings"),
    },
    InfoColumn {
        name: "MEM",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total memory(byte) used"),
    },
    InfoColumn {
        name: "MEM_ARBITRATION",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total time of memory arbitration"),
    },
    InfoColumn {
        name: "DISK",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total disk space(byte) used"),
    },
    InfoColumn {
        name: "TOTAL_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum latency of these statements"),
    },
    InfoColumn {
        name: "PARSE_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total latency of parsing"),
    },
    InfoColumn {
        name: "COMPILE_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total latency of compiling"),
    },
    InfoColumn {
        name: "COP_TASK_NUM",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total number of CopTasks"),
    },
    InfoColumn {
        name: "COP_PROCESS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total processing time of CopTasks"),
    },
    InfoColumn {
        name: "MAX_COP_PROCESS_ADDRESS",
        tp: FieldTypeCode::Varchar,
        size: 256,
        flag: 0,
        deflt: None,
        comment: Some("Address of the CopTask with max processing time"),
    },
    InfoColumn {
        name: "COP_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total waiting time of CopTasks"),
    },
    InfoColumn {
        name: "MAX_COP_WAIT_ADDRESS",
        tp: FieldTypeCode::Varchar,
        size: 256,
        flag: 0,
        deflt: None,
        comment: Some("Address of the CopTask with max waiting time"),
    },
    InfoColumn {
        name: "PD_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total time of PD used"),
    },
    InfoColumn {
        name: "KV_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total time of TiKV used"),
    },
    InfoColumn {
        name: "PROCESS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total processing time in TiKV"),
    },
    InfoColumn {
        name: "WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total waiting time in TiKV"),
    },
    InfoColumn {
        name: "BACKOFF_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total waiting time before retry"),
    },
    InfoColumn {
        name: "TOTAL_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total number of scanned keys"),
    },
    InfoColumn {
        name: "PROCESSED_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total number of processed keys"),
    },
    InfoColumn {
        name: "ROCKSDB_DELETE_SKIPPED_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total RocksDB delete skipped count"),
    },
    InfoColumn {
        name: "ROCKSDB_KEY_SKIPPED_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total RocksDB key skipped count"),
    },
    InfoColumn {
        name: "ROCKSDB_BLOCK_CACHE_HIT_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total RocksDB block cache hit count"),
    },
    InfoColumn {
        name: "ROCKSDB_BLOCK_READ_COUNT",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total RocksDB block read count"),
    },
    InfoColumn {
        name: "ROCKSDB_BLOCK_READ_BYTE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total RocksDB block read byte"),
    },
    InfoColumn {
        name: "PREWRITE_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total time of prewrite phase"),
    },
    InfoColumn {
        name: "COMMIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total time of commit phase"),
    },
    InfoColumn {
        name: "COMMIT_TS_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total time of getting commit_ts"),
    },
    InfoColumn {
        name: "COMMIT_BACKOFF_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total time before retry during commit phase"),
    },
    InfoColumn {
        name: "RESOLVE_LOCK_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total time for resolving locks"),
    },
    InfoColumn {
        name: "LOCAL_LATCH_WAIT_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total waiting time of local transaction"),
    },
    InfoColumn {
        name: "WRITE_KEYS",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total count of written keys"),
    },
    InfoColumn {
        name: "WRITE_SIZE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total amount of written bytes"),
    },
    InfoColumn {
        name: "PREWRITE_REGIONS",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total number of involved regions in prewrite phase"),
    },
    InfoColumn {
        name: "TXN_RETRY",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total number of transaction retries"),
    },
    InfoColumn {
        name: "EXEC_RETRY",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum number of execution retries in pessimistic transactions"),
    },
    InfoColumn {
        name: "EXEC_RETRY_TIME",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum time of execution retries in pessimistic transactions"),
    },
    InfoColumn {
        name: "BACKOFF_TIMES",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Sum of retries"),
    },
    InfoColumn {
        name: "BACKOFF_TYPES",
        tp: FieldTypeCode::Varchar,
        size: 1024,
        flag: 0,
        deflt: None,
        comment: Some("Types of errors and the number of retries for each type"),
    },
    InfoColumn {
        name: "BACKOFF_TOTAL_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total time spent in backoff and retry"),
    },
    InfoColumn {
        name: "WRITE_SQL_RESP_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total time used to write a response to the client."),
    },
    InfoColumn {
        name: "RESULT_ROWS",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 1,
        deflt: None,
        comment: Some("Total count of SQL result rows"),
    },
    InfoColumn {
        name: "AFFECTED_ROWS",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total number of rows affected"),
    },
    InfoColumn {
        name: "PREPARED",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether prepared"),
    },
    InfoColumn {
        name: "FIRST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 1,
        deflt: None,
        comment: Some("The time these statements are seen for the first time"),
    },
    InfoColumn {
        name: "LAST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 1,
        deflt: None,
        comment: Some("The time these statements are seen for the last time"),
    },
    InfoColumn {
        name: "PLAN_IN_CACHE",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement hit the plan cache"),
    },
    InfoColumn {
        name: "PLAN_CACHE_HITS",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 1,
        deflt: None,
        comment: Some("The number of times these statements hit the plan cache"),
    },
    InfoColumn {
        name: "PLAN_IN_BINDING",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement is matched with the hints in the binding"),
    },
    InfoColumn {
        name: "QUERY_SAMPLE_TEXT",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Sampled original statement"),
    },
    InfoColumn {
        name: "PREV_SAMPLE_TEXT",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("The previous statement before commit"),
    },
    InfoColumn {
        name: "PLAN_DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Digest of its execution plan"),
    },
    InfoColumn {
        name: "PLAN",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Sampled execution plan"),
    },
    InfoColumn {
        name: "BINARY_PLAN",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Sampled binary plan"),
    },
    InfoColumn {
        name: "BINDING_DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Digest of normalized statement for bindings"),
    },
    InfoColumn {
        name: "BINDING_DIGEST_TEXT",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 1,
        deflt: None,
        comment: Some("Normalized statement for bindings"),
    },
    InfoColumn {
        name: "CHARSET",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Sampled charset"),
    },
    InfoColumn {
        name: "COLLATION",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Sampled collation"),
    },
    InfoColumn {
        name: "PLAN_HINT",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Sampled plan hint"),
    },
    InfoColumn {
        name: "REQUEST_UNIT_READ",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total read request-unit cost of these statements"),
    },
    InfoColumn {
        name: "REQUEST_UNIT_WRITE",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total write request-unit cost of these statements"),
    },
    InfoColumn {
        name: "QUEUED_RC_TIME",
        tp: FieldTypeCode::LongLong,
        size: 22,
        flag: 33,
        deflt: None,
        comment: Some("Total time waiting for available request-units"),
    },
    InfoColumn {
        name: "RESOURCE_GROUP",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Bind resource group name"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_SENT_TIKV_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tikv"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_RECEIVED_TIKV_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tikv"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_SENT_TIKV_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tikv cross zone"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_RECEIVED_TIKV_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tikv cross zone"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_SENT_TIFLASH_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tiflash"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_RECEIVED_TIFLASH_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tiflash"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_SENT_TIFLASH_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes sent to tiflash cross zone"),
    },
    InfoColumn {
        name: "UNPACKED_BYTES_RECEIVED_TIFLASH_CROSS_ZONE",
        tp: FieldTypeCode::LongLong,
        size: 20,
        flag: 33,
        deflt: None,
        comment: Some("Total bytes received from tiflash cross zone"),
    },
    InfoColumn {
        name: "STORAGE_KV",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement read data from TiKV"),
    },
    InfoColumn {
        name: "STORAGE_MPP",
        tp: FieldTypeCode::Tiny,
        size: 1,
        flag: 1,
        deflt: None,
        comment: Some("Whether the last statement read data from TiFlash"),
    },
];

const WORKLOAD_CLIENT_ERRORS_SUMMARY_BY_HOST_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "HOST",
        tp: FieldTypeCode::Varchar,
        size: 255,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_NUMBER",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_MESSAGE",
        tp: FieldTypeCode::Varchar,
        size: 1024,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "WARNING_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "FIRST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "LAST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: None,
    },
];

const WORKLOAD_CLIENT_ERRORS_SUMMARY_BY_USER_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "USER",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_NUMBER",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_MESSAGE",
        tp: FieldTypeCode::Varchar,
        size: 1024,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "WARNING_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "FIRST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "LAST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: None,
    },
];

const WORKLOAD_CLIENT_ERRORS_SUMMARY_GLOBAL_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "ERROR_NUMBER",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_MESSAGE",
        tp: FieldTypeCode::Varchar,
        size: 1024,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "ERROR_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "WARNING_COUNT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "FIRST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "LAST_SEEN",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: None,
    },
];

const WORKLOAD_TIDB_TRX_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "ID",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 35,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "START_TIME",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: Some("Start time of the transaction"),
    },
    InfoColumn {
        name: "CURRENT_SQL_DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Digest of the sql the transaction are currently running"),
    },
    InfoColumn {
        name: "CURRENT_SQL_DIGEST_TEXT",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("The normalized sql the transaction are currently running"),
    },
    InfoColumn {
        name: "STATE",
        tp: FieldTypeCode::Enum,
        size: 16,
        flag: 0,
        deflt: None,
        comment: Some("Current running state of the transaction"),
    },
    InfoColumn {
        name: "WAITING_START_TIME",
        tp: FieldTypeCode::Timestamp,
        size: 26,
        flag: 0,
        deflt: None,
        comment: Some("Current lock waiting's start time"),
    },
    InfoColumn {
        name: "MEM_BUFFER_KEYS",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: Some("How many entries are in MemDB"),
    },
    InfoColumn {
        name: "MEM_BUFFER_BYTES",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 0,
        deflt: None,
        comment: Some("MemDB used memory"),
    },
    InfoColumn {
        name: "SESSION_ID",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 32,
        deflt: None,
        comment: Some("Which session this transaction belongs to"),
    },
    InfoColumn {
        name: "USER",
        tp: FieldTypeCode::Varchar,
        size: 16,
        flag: 0,
        deflt: None,
        comment: Some("The user who open this session"),
    },
    InfoColumn {
        name: "DB",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("The schema this transaction works on"),
    },
    InfoColumn {
        name: "ALL_SQL_DIGESTS",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("A list of the digests of SQL statements that the transaction has executed"),
    },
    InfoColumn {
        name: "RELATED_TABLE_IDS",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("A list of the table IDs that the transaction has accessed"),
    },
    InfoColumn {
        name: "WAITING_TIME",
        tp: FieldTypeCode::Double,
        size: 22,
        flag: 0,
        deflt: None,
        comment: Some("Current lock waiting time"),
    },
];

const WORKLOAD_DATA_LOCK_WAITS_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "KEY",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 1,
        deflt: None,
        comment: Some("The key that's being waiting on"),
    },
    InfoColumn {
        name: "KEY_INFO",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Information of the key"),
    },
    InfoColumn {
        name: "TRX_ID",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 33,
        deflt: None,
        comment: Some("Current transaction that's waiting for the lock"),
    },
    InfoColumn {
        name: "CURRENT_HOLDING_TRX_ID",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 33,
        deflt: None,
        comment: Some("The transaction that's holding the lock and blocks the current transaction"),
    },
    InfoColumn {
        name: "SQL_DIGEST",
        tp: FieldTypeCode::Varchar,
        size: 64,
        flag: 0,
        deflt: None,
        comment: Some("Digest of the SQL that's trying to acquire the lock"),
    },
    InfoColumn {
        name: "SQL_DIGEST_TEXT",
        tp: FieldTypeCode::Blob,
        size: -1,
        flag: 0,
        deflt: None,
        comment: Some("Digest of the SQL that's trying to acquire the lock"),
    },
];

const WORKLOAD_MEMORY_USAGE_COLUMNS: &[InfoColumn] = &[
    InfoColumn {
        name: "MEMORY_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "MEMORY_LIMIT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "MEMORY_CURRENT",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "MEMORY_MAX_USED",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "CURRENT_OPS",
        tp: FieldTypeCode::Varchar,
        size: 50,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "SESSION_KILL_LAST",
        tp: FieldTypeCode::Datetime,
        size: 0,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "SESSION_KILL_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "GC_LAST",
        tp: FieldTypeCode::Datetime,
        size: 0,
        flag: 0,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "GC_TOTAL",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "DISK_USAGE",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
    InfoColumn {
        name: "QUERY_FORCE_DISK",
        tp: FieldTypeCode::LongLong,
        size: 21,
        flag: 1,
        deflt: None,
        comment: None,
    },
];
