// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package partition_test

import "testing"

func TestGlobalIndexVersion0(t *testing.T) {
	RunGlobalIndexVersion0(t)
}

func TestGlobalIndexVersion1(t *testing.T) {
	RunGlobalIndexVersion1(t)
}

func TestGlobalIndexVersionConstants(t *testing.T) {
	RunGlobalIndexVersionConstants(t)
}

func TestGlobalIndexTruncateAndDropPartition(t *testing.T) {
	RunGlobalIndexTruncateAndDropPartition(t)
}

func TestUpdateIndexesResetsGlobalIndexVersion(t *testing.T) {
	RunUpdateIndexesResetsGlobalIndexVersion(t)
}
