// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package mpp_test

import "testing"

func TestNeedReportExecutionSummary(t *testing.T) {
	RunNeedReportExecutionSummary(t)
}

func TestZoneHelperTryQuickFill(t *testing.T) {
	RunZoneHelperTryQuickFill(t)
}
