// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package admintest

import "github.com/pingcap/tidb/pkg/testkit/mega/register"

func init() {
	register.Register("executor/test/admintest", "AdminCheckGeneratedColumns", RunAdminCheckGeneratedColumns)
	register.Register("executor/test/admintest", "AdminCheckGlobalIndex", RunAdminCheckGlobalIndex)
	register.Register("executor/test/admintest", "AdminCheckGlobalIndexDuringDDL", RunAdminCheckGlobalIndexDuringDDL)
	register.Register("executor/test/admintest", "AdminCheckGlobalIndexWithClusterIndex", RunAdminCheckGlobalIndexWithClusterIndex)
	register.Register("executor/test/admintest", "AdminCheckPartitionTableFailed", RunAdminCheckPartitionTableFailed)
	register.Register("executor/test/admintest", "AdminCheckTableErrorLocate", RunAdminCheckTableErrorLocate)
	register.Register("executor/test/admintest", "AdminCheckTableErrorLocateForClusterIndex", RunAdminCheckTableErrorLocateForClusterIndex)
	register.Register("executor/test/admintest", "AdminCheckTableFailed", RunAdminCheckTableFailed)
	register.Register("executor/test/admintest", "AdminCheckTableWithEnumAndPointGet", RunAdminCheckTableWithEnumAndPointGet)
	register.Register("executor/test/admintest", "AdminCheckTableWithMultiValuedIndex", RunAdminCheckTableWithMultiValuedIndex)
	register.Register("executor/test/admintest", "AdminCheckTableWithSnapshot", RunAdminCheckTableWithSnapshot)
	register.Register("executor/test/admintest", "AdminCheckWithSnapshot", RunAdminCheckWithSnapshot)
	register.Register("executor/test/admintest", "AdminCleanUpGlobalIndex", RunAdminCleanUpGlobalIndex)
	register.Register("executor/test/admintest", "AdminCleanupIndex", RunAdminCleanupIndex)
	register.Register("executor/test/admintest", "AdminCleanupIndexForPartitionTable", RunAdminCleanupIndexForPartitionTable)
	register.Register("executor/test/admintest", "AdminCleanupIndexMore", RunAdminCleanupIndexMore)
	register.Register("executor/test/admintest", "AdminCleanupIndexPKNotHandle", RunAdminCleanupIndexPKNotHandle)
	register.Register("executor/test/admintest", "AdminCleanupMVIndex", RunAdminCleanupMVIndex)
	register.Register("executor/test/admintest", "AdminRecoverGlobalIndex", RunAdminRecoverGlobalIndex)
	register.Register("executor/test/admintest", "AdminRecoverIndex", RunAdminRecoverIndex)
	register.Register("executor/test/admintest", "AdminRecoverIndex1", RunAdminRecoverIndex1)
	register.Register("executor/test/admintest", "AdminRecoverMVIndex", RunAdminRecoverMVIndex)
	register.Register("executor/test/admintest", "AdminRecoverPartitionTableIndex", RunAdminRecoverPartitionTableIndex)
	register.Register("executor/test/admintest", "CheckFailReport", RunCheckFailReport)
	register.Register("executor/test/admintest", "ClusteredAdminCleanupIndex", RunClusteredAdminCleanupIndex)
	register.Register("executor/test/admintest", "ClusteredIndexAdminRecoverIndex", RunClusteredIndexAdminRecoverIndex)
	register.Register("executor/test/admintest", "FastAdminCheckPropagateSessionVarsToSysSession", RunFastAdminCheckPropagateSessionVarsToSysSession)
	register.Register("executor/test/admintest", "FastAdminCheckQuickPassSkipBucketed", RunFastAdminCheckQuickPassSkipBucketed)
	register.Register("executor/test/admintest", "FastAdminCheckWithError", RunFastAdminCheckWithError)
	register.Register("executor/test/admintest", "FastCheckTableConcurrent", RunFastCheckTableConcurrent)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "executor/test/admintest" {
			InitForMega()
		}
	})
}
