// Code generated by mega-gen. DO NOT EDIT.

package hint_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("planner_core_casetest_hint", "ReadFromStorageHint", RunReadFromStorageHint)
	register.Register("planner_core_casetest_hint", "AllViewHintType", RunAllViewHintType)
	register.Register("planner_core_casetest_hint", "JoinHintCompatibility", RunJoinHintCompatibility)
	register.Register("planner_core_casetest_hint", "ReadFromStorageHintAndIsolationRead", RunReadFromStorageHintAndIsolationRead)
	register.Register("planner_core_casetest_hint", "IsolationReadTiFlashUseIndexHint", RunIsolationReadTiFlashUseIndexHint)
	register.Register("planner_core_casetest_hint", "OptimizeHintOnPartitionTable", RunOptimizeHintOnPartitionTable)
	register.Register("planner_core_casetest_hint", "Hints", RunHints)
	register.Register("planner_core_casetest_hint", "QBHintHandlerDuplicateObjects", RunQBHintHandlerDuplicateObjects)
	register.Register("planner_core_casetest_hint", "OptimizerCostFactorHints", RunOptimizerCostFactorHints)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "planner_core_casetest_hint" {
			InitForMega()
		}
	})
}
