// Copyright 2026 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");

//! `ALL_CODES` entries, part 1 of 1 (see `errcode/mod.rs`).

use super::consts_1::*;
use super::consts_2::*;

pub(super) const ALL_CODES_1: &[(&str, u16)] = &[
    ("ErrErrorFirst", ErrErrorFirst),
    ("ErrHashchk", ErrHashchk),
    ("ErrNisamchk", ErrNisamchk),
    ("ErrNo", ErrNo),
    ("ErrYes", ErrYes),
    ("ErrCantCreateFile", ErrCantCreateFile),
    ("ErrCantCreateTable", ErrCantCreateTable),
    ("ErrCantCreateDB", ErrCantCreateDB),
    ("ErrDBCreateExists", ErrDBCreateExists),
    ("ErrDBDropExists", ErrDBDropExists),
    ("ErrDBDropDelete", ErrDBDropDelete),
    ("ErrDBDropRmdir", ErrDBDropRmdir),
    ("ErrCantDeleteFile", ErrCantDeleteFile),
    ("ErrCantFindSystemRec", ErrCantFindSystemRec),
    ("ErrCantGetStat", ErrCantGetStat),
    ("ErrCantGetWd", ErrCantGetWd),
    ("ErrCantLock", ErrCantLock),
    ("ErrCantOpenFile", ErrCantOpenFile),
    ("ErrFileNotFound", ErrFileNotFound),
    ("ErrCantReadDir", ErrCantReadDir),
    ("ErrCantSetWd", ErrCantSetWd),
    ("ErrCheckread", ErrCheckread),
    ("ErrDiskFull", ErrDiskFull),
    ("ErrDupKey", ErrDupKey),
    ("ErrErrorOnClose", ErrErrorOnClose),
    ("ErrErrorOnRead", ErrErrorOnRead),
    ("ErrErrorOnRename", ErrErrorOnRename),
    ("ErrErrorOnWrite", ErrErrorOnWrite),
    ("ErrFileUsed", ErrFileUsed),
    ("ErrFilsortAbort", ErrFilsortAbort),
    ("ErrFormNotFound", ErrFormNotFound),
    ("ErrGetErrno", ErrGetErrno),
    ("ErrIllegalHa", ErrIllegalHa),
    ("ErrKeyNotFound", ErrKeyNotFound),
    ("ErrNotFormFile", ErrNotFormFile),
    ("ErrNotKeyFile", ErrNotKeyFile),
    ("ErrOldKeyFile", ErrOldKeyFile),
    ("ErrOpenAsReadonly", ErrOpenAsReadonly),
    ("ErrOutofMemory", ErrOutofMemory),
    ("ErrOutOfSortMemory", ErrOutOfSortMemory),
    ("ErrUnexpectedEOF", ErrUnexpectedEOF),
    ("ErrConCount", ErrConCount),
    ("ErrOutOfResources", ErrOutOfResources),
    ("ErrBadHost", ErrBadHost),
    ("ErrHandshake", ErrHandshake),
    ("ErrDBaccessDenied", ErrDBaccessDenied),
    ("ErrAccessDenied", ErrAccessDenied),
    ("ErrNoDB", ErrNoDB),
    ("ErrUnknownCom", ErrUnknownCom),
    ("ErrBadNull", ErrBadNull),
    ("ErrBadDB", ErrBadDB),
    ("ErrTableExists", ErrTableExists),
    ("ErrBadTable", ErrBadTable),
    ("ErrNonUniq", ErrNonUniq),
    ("ErrServerShutdown", ErrServerShutdown),
    ("ErrBadField", ErrBadField),
    ("ErrFieldNotInGroupBy", ErrFieldNotInGroupBy),
    ("ErrWrongGroupField", ErrWrongGroupField),
    ("ErrWrongSumSelect", ErrWrongSumSelect),
    ("ErrWrongValueCount", ErrWrongValueCount),
    ("ErrTooLongIdent", ErrTooLongIdent),
    ("ErrDupFieldName", ErrDupFieldName),
    ("ErrDupKeyName", ErrDupKeyName),
    ("ErrDupEntry", ErrDupEntry),
    ("ErrWrongFieldSpec", ErrWrongFieldSpec),
    ("ErrParse", ErrParse),
    ("ErrEmptyQuery", ErrEmptyQuery),
    ("ErrNonuniqTable", ErrNonuniqTable),
    ("ErrInvalidDefault", ErrInvalidDefault),
    ("ErrMultiplePriKey", ErrMultiplePriKey),
    ("ErrTooManyKeys", ErrTooManyKeys),
    ("ErrTooManyKeyParts", ErrTooManyKeyParts),
    ("ErrTooLongKey", ErrTooLongKey),
    ("ErrKeyColumnDoesNotExits", ErrKeyColumnDoesNotExits),
    ("ErrBlobUsedAsKey", ErrBlobUsedAsKey),
    ("ErrTooBigFieldlength", ErrTooBigFieldlength),
    ("ErrWrongAutoKey", ErrWrongAutoKey),
    ("ErrReady", ErrReady),
    ("ErrNormalShutdown", ErrNormalShutdown),
    ("ErrGotSignal", ErrGotSignal),
    ("ErrShutdownComplete", ErrShutdownComplete),
    ("ErrForcingClose", ErrForcingClose),
    ("ErrIpsock", ErrIpsock),
    ("ErrNoSuchIndex", ErrNoSuchIndex),
    ("ErrWrongFieldTerminators", ErrWrongFieldTerminators),
    ("ErrBlobsAndNoTerminated", ErrBlobsAndNoTerminated),
    ("ErrTextFileNotReadable", ErrTextFileNotReadable),
    ("ErrFileExists", ErrFileExists),
    ("ErrLoadInfo", ErrLoadInfo),
    ("ErrAlterInfo", ErrAlterInfo),
    ("ErrWrongSubKey", ErrWrongSubKey),
    ("ErrCantRemoveAllFields", ErrCantRemoveAllFields),
    ("ErrCantDropFieldOrKey", ErrCantDropFieldOrKey),
    ("ErrInsertInfo", ErrInsertInfo),
    ("ErrUpdateTableUsed", ErrUpdateTableUsed),
    ("ErrNoSuchThread", ErrNoSuchThread),
    ("ErrKillDenied", ErrKillDenied),
    ("ErrNoTablesUsed", ErrNoTablesUsed),
    ("ErrTooBigSet", ErrTooBigSet),
    ("ErrNoUniqueLogFile", ErrNoUniqueLogFile),
    ("ErrTableNotLockedForWrite", ErrTableNotLockedForWrite),
    ("ErrTableNotLocked", ErrTableNotLocked),
    ("ErrBlobCantHaveDefault", ErrBlobCantHaveDefault),
    ("ErrWrongDBName", ErrWrongDBName),
    ("ErrWrongTableName", ErrWrongTableName),
    ("ErrTooBigSelect", ErrTooBigSelect),
    ("ErrUnknown", ErrUnknown),
    ("ErrUnknownProcedure", ErrUnknownProcedure),
    (
        "ErrWrongParamcountToProcedure",
        ErrWrongParamcountToProcedure,
    ),
    (
        "ErrWrongParametersToProcedure",
        ErrWrongParametersToProcedure,
    ),
    ("ErrUnknownTable", ErrUnknownTable),
    ("ErrFieldSpecifiedTwice", ErrFieldSpecifiedTwice),
    ("ErrInvalidGroupFuncUse", ErrInvalidGroupFuncUse),
    ("ErrUnsupportedExtension", ErrUnsupportedExtension),
    ("ErrTableMustHaveColumns", ErrTableMustHaveColumns),
    ("ErrRecordFileFull", ErrRecordFileFull),
    ("ErrUnknownCharacterSet", ErrUnknownCharacterSet),
    ("ErrTooManyTables", ErrTooManyTables),
    ("ErrTooManyFields", ErrTooManyFields),
    ("ErrTooBigRowsize", ErrTooBigRowsize),
    ("ErrStackOverrun", ErrStackOverrun),
    ("ErrWrongOuterJoin", ErrWrongOuterJoin),
    ("ErrNullColumnInIndex", ErrNullColumnInIndex),
    ("ErrCantFindUdf", ErrCantFindUdf),
    ("ErrCantInitializeUdf", ErrCantInitializeUdf),
    ("ErrUdfNoPaths", ErrUdfNoPaths),
    ("ErrUdfExists", ErrUdfExists),
    ("ErrCantOpenLibrary", ErrCantOpenLibrary),
    ("ErrCantFindDlEntry", ErrCantFindDlEntry),
    ("ErrFunctionNotDefined", ErrFunctionNotDefined),
    ("ErrHostIsBlocked", ErrHostIsBlocked),
    ("ErrHostNotPrivileged", ErrHostNotPrivileged),
    ("ErrPasswordAnonymousUser", ErrPasswordAnonymousUser),
    ("ErrPasswordNotAllowed", ErrPasswordNotAllowed),
    ("ErrPasswordNoMatch", ErrPasswordNoMatch),
    ("ErrUpdateInfo", ErrUpdateInfo),
    ("ErrCantCreateThread", ErrCantCreateThread),
    ("ErrWrongValueCountOnRow", ErrWrongValueCountOnRow),
    ("ErrCantReopenTable", ErrCantReopenTable),
    ("ErrInvalidUseOfNull", ErrInvalidUseOfNull),
    ("ErrRegexp", ErrRegexp),
    ("ErrMixOfGroupFuncAndFields", ErrMixOfGroupFuncAndFields),
    ("ErrNonexistingGrant", ErrNonexistingGrant),
    ("ErrTableaccessDenied", ErrTableaccessDenied),
    ("ErrColumnaccessDenied", ErrColumnaccessDenied),
    ("ErrIllegalGrantForTable", ErrIllegalGrantForTable),
    ("ErrGrantWrongHostOrUser", ErrGrantWrongHostOrUser),
    ("ErrNoSuchTable", ErrNoSuchTable),
    ("ErrNonexistingTableGrant", ErrNonexistingTableGrant),
    ("ErrNotAllowedCommand", ErrNotAllowedCommand),
    ("ErrSyntax", ErrSyntax),
    ("ErrDelayedCantChangeLock", ErrDelayedCantChangeLock),
    ("ErrTooManyDelayedThreads", ErrTooManyDelayedThreads),
    ("ErrAbortingConnection", ErrAbortingConnection),
    ("ErrNetPacketTooLarge", ErrNetPacketTooLarge),
    ("ErrNetReadErrorFromPipe", ErrNetReadErrorFromPipe),
    ("ErrNetFcntl", ErrNetFcntl),
    ("ErrNetPacketsOutOfOrder", ErrNetPacketsOutOfOrder),
    ("ErrNetUncompress", ErrNetUncompress),
    ("ErrNetRead", ErrNetRead),
    ("ErrNetReadInterrupted", ErrNetReadInterrupted),
    ("ErrNetErrorOnWrite", ErrNetErrorOnWrite),
    ("ErrNetWriteInterrupted", ErrNetWriteInterrupted),
    ("ErrTooLongString", ErrTooLongString),
    ("ErrTableCantHandleBlob", ErrTableCantHandleBlob),
    (
        "ErrTableCantHandleAutoIncrement",
        ErrTableCantHandleAutoIncrement,
    ),
    ("ErrDelayedInsertTableLocked", ErrDelayedInsertTableLocked),
    ("ErrWrongColumnName", ErrWrongColumnName),
    ("ErrWrongKeyColumn", ErrWrongKeyColumn),
    ("ErrWrongMrgTable", ErrWrongMrgTable),
    ("ErrDupUnique", ErrDupUnique),
    ("ErrBlobKeyWithoutLength", ErrBlobKeyWithoutLength),
    ("ErrPrimaryCantHaveNull", ErrPrimaryCantHaveNull),
    ("ErrTooManyRows", ErrTooManyRows),
    ("ErrRequiresPrimaryKey", ErrRequiresPrimaryKey),
    ("ErrNoRaidCompiled", ErrNoRaidCompiled),
    (
        "ErrUpdateWithoutKeyInSafeMode",
        ErrUpdateWithoutKeyInSafeMode,
    ),
    ("ErrKeyDoesNotExist", ErrKeyDoesNotExist),
    ("ErrCheckNoSuchTable", ErrCheckNoSuchTable),
    ("ErrCheckNotImplemented", ErrCheckNotImplemented),
    (
        "ErrCantDoThisDuringAnTransaction",
        ErrCantDoThisDuringAnTransaction,
    ),
    ("ErrErrorDuringCommit", ErrErrorDuringCommit),
    ("ErrErrorDuringRollback", ErrErrorDuringRollback),
    ("ErrErrorDuringFlushLogs", ErrErrorDuringFlushLogs),
    ("ErrErrorDuringCheckpoint", ErrErrorDuringCheckpoint),
    ("ErrNewAbortingConnection", ErrNewAbortingConnection),
    ("ErrDumpNotImplemented", ErrDumpNotImplemented),
    ("ErrFlushMasterBinlogClosed", ErrFlushMasterBinlogClosed),
    ("ErrIndexRebuild", ErrIndexRebuild),
    ("ErrMaster", ErrMaster),
    ("ErrMasterNetRead", ErrMasterNetRead),
    ("ErrMasterNetWrite", ErrMasterNetWrite),
    ("ErrFtMatchingKeyNotFound", ErrFtMatchingKeyNotFound),
    ("ErrLockOrActiveTransaction", ErrLockOrActiveTransaction),
    ("ErrUnknownSystemVariable", ErrUnknownSystemVariable),
    ("ErrCrashedOnUsage", ErrCrashedOnUsage),
    ("ErrCrashedOnRepair", ErrCrashedOnRepair),
    (
        "ErrWarningNotCompleteRollback",
        ErrWarningNotCompleteRollback,
    ),
    ("ErrTransCacheFull", ErrTransCacheFull),
    ("ErrSlaveMustStop", ErrSlaveMustStop),
    ("ErrSlaveNotRunning", ErrSlaveNotRunning),
    ("ErrBadSlave", ErrBadSlave),
    ("ErrMasterInfo", ErrMasterInfo),
    ("ErrSlaveThread", ErrSlaveThread),
    ("ErrTooManyUserConnections", ErrTooManyUserConnections),
    ("ErrSetConstantsOnly", ErrSetConstantsOnly),
    ("ErrLockWaitTimeout", ErrLockWaitTimeout),
    ("ErrLockTableFull", ErrLockTableFull),
    ("ErrReadOnlyTransaction", ErrReadOnlyTransaction),
    ("ErrDropDBWithReadLock", ErrDropDBWithReadLock),
    ("ErrCreateDBWithReadLock", ErrCreateDBWithReadLock),
    ("ErrWrongArguments", ErrWrongArguments),
    ("ErrNoPermissionToCreateUser", ErrNoPermissionToCreateUser),
    ("ErrUnionTablesInDifferentDir", ErrUnionTablesInDifferentDir),
    ("ErrLockDeadlock", ErrLockDeadlock),
    ("ErrTableCantHandleFt", ErrTableCantHandleFt),
    ("ErrCannotAddForeign", ErrCannotAddForeign),
    ("ErrNoReferencedRow", ErrNoReferencedRow),
    ("ErrRowIsReferenced", ErrRowIsReferenced),
    ("ErrConnectToMaster", ErrConnectToMaster),
    ("ErrQueryOnMaster", ErrQueryOnMaster),
    ("ErrErrorWhenExecutingCommand", ErrErrorWhenExecutingCommand),
    ("ErrWrongUsage", ErrWrongUsage),
    (
        "ErrWrongNumberOfColumnsInSelect",
        ErrWrongNumberOfColumnsInSelect,
    ),
    ("ErrCantUpdateWithReadlock", ErrCantUpdateWithReadlock),
    ("ErrMixingNotAllowed", ErrMixingNotAllowed),
    ("ErrDupArgument", ErrDupArgument),
    ("ErrUserLimitReached", ErrUserLimitReached),
    ("ErrSpecificAccessDenied", ErrSpecificAccessDenied),
    ("ErrLocalVariable", ErrLocalVariable),
    ("ErrGlobalVariable", ErrGlobalVariable),
    ("ErrNoDefault", ErrNoDefault),
    ("ErrWrongValueForVar", ErrWrongValueForVar),
    ("ErrWrongTypeForVar", ErrWrongTypeForVar),
    ("ErrVarCantBeRead", ErrVarCantBeRead),
    ("ErrCantUseOptionHere", ErrCantUseOptionHere),
    ("ErrNotSupportedYet", ErrNotSupportedYet),
    (
        "ErrMasterFatalErrorReadingBinlog",
        ErrMasterFatalErrorReadingBinlog,
    ),
    ("ErrSlaveIgnoredTable", ErrSlaveIgnoredTable),
    ("ErrIncorrectGlobalLocalVar", ErrIncorrectGlobalLocalVar),
    ("ErrWrongFkDef", ErrWrongFkDef),
    ("ErrKeyRefDoNotMatchTableRef", ErrKeyRefDoNotMatchTableRef),
    ("ErrOperandColumns", ErrOperandColumns),
    ("ErrSubqueryNo1Row", ErrSubqueryNo1Row),
    ("ErrUnknownStmtHandler", ErrUnknownStmtHandler),
    ("ErrCorruptHelpDB", ErrCorruptHelpDB),
    ("ErrCyclicReference", ErrCyclicReference),
    ("ErrAutoConvert", ErrAutoConvert),
    ("ErrIllegalReference", ErrIllegalReference),
    ("ErrDerivedMustHaveAlias", ErrDerivedMustHaveAlias),
    ("ErrSelectReduced", ErrSelectReduced),
    ("ErrTablenameNotAllowedHere", ErrTablenameNotAllowedHere),
    ("ErrNotSupportedAuthMode", ErrNotSupportedAuthMode),
    ("ErrSpatialCantHaveNull", ErrSpatialCantHaveNull),
    ("ErrCollationCharsetMismatch", ErrCollationCharsetMismatch),
    ("ErrSlaveWasRunning", ErrSlaveWasRunning),
    ("ErrSlaveWasNotRunning", ErrSlaveWasNotRunning),
    ("ErrTooBigForUncompress", ErrTooBigForUncompress),
    ("ErrZlibZMem", ErrZlibZMem),
    ("ErrZlibZBuf", ErrZlibZBuf),
    ("ErrZlibZData", ErrZlibZData),
    ("ErrCutValueGroupConcat", ErrCutValueGroupConcat),
    ("ErrWarnTooFewRecords", ErrWarnTooFewRecords),
    ("ErrWarnTooManyRecords", ErrWarnTooManyRecords),
    ("ErrWarnNullToNotnull", ErrWarnNullToNotnull),
    ("ErrWarnDataOutOfRange", ErrWarnDataOutOfRange),
    ("WarnDataTruncated", WarnDataTruncated),
    ("ErrWarnUsingOtherHandler", ErrWarnUsingOtherHandler),
    ("ErrCantAggregate2collations", ErrCantAggregate2collations),
    ("ErrDropUser", ErrDropUser),
    ("ErrRevokeGrants", ErrRevokeGrants),
    ("ErrCantAggregate3collations", ErrCantAggregate3collations),
    ("ErrCantAggregateNcollations", ErrCantAggregateNcollations),
    ("ErrVariableIsNotStruct", ErrVariableIsNotStruct),
    ("ErrUnknownCollation", ErrUnknownCollation),
    ("ErrSlaveIgnoredSslParams", ErrSlaveIgnoredSslParams),
    ("ErrServerIsInSecureAuthMode", ErrServerIsInSecureAuthMode),
    ("ErrWarnFieldResolved", ErrWarnFieldResolved),
    ("ErrBadSlaveUntilCond", ErrBadSlaveUntilCond),
    ("ErrMissingSkipSlave", ErrMissingSkipSlave),
    ("ErrUntilCondIgnored", ErrUntilCondIgnored),
    ("ErrWrongNameForIndex", ErrWrongNameForIndex),
    ("ErrWrongNameForCatalog", ErrWrongNameForCatalog),
    ("ErrWarnQcResize", ErrWarnQcResize),
    ("ErrBadFtColumn", ErrBadFtColumn),
    ("ErrUnknownKeyCache", ErrUnknownKeyCache),
    ("ErrWarnHostnameWontWork", ErrWarnHostnameWontWork),
    ("ErrUnknownStorageEngine", ErrUnknownStorageEngine),
    ("ErrWarnDeprecatedSyntax", ErrWarnDeprecatedSyntax),
    ("ErrNonUpdatableTable", ErrNonUpdatableTable),
    ("ErrFeatureDisabled", ErrFeatureDisabled),
    ("ErrOptionPreventsStatement", ErrOptionPreventsStatement),
    ("ErrDuplicatedValueInType", ErrDuplicatedValueInType),
    ("ErrTruncatedWrongValue", ErrTruncatedWrongValue),
    ("ErrTooMuchAutoTimestampCols", ErrTooMuchAutoTimestampCols),
    ("ErrInvalidOnUpdate", ErrInvalidOnUpdate),
    ("ErrUnsupportedPs", ErrUnsupportedPs),
    ("ErrGetErrmsg", ErrGetErrmsg),
    ("ErrGetTemporaryErrmsg", ErrGetTemporaryErrmsg),
    ("ErrUnknownTimeZone", ErrUnknownTimeZone),
    ("ErrWarnInvalidTimestamp", ErrWarnInvalidTimestamp),
    ("ErrInvalidCharacterString", ErrInvalidCharacterString),
    (
        "ErrWarnAllowedPacketOverflowed",
        ErrWarnAllowedPacketOverflowed,
    ),
    ("ErrConflictingDeclarations", ErrConflictingDeclarations),
    ("ErrSpNoRecursiveCreate", ErrSpNoRecursiveCreate),
    ("ErrSpAlreadyExists", ErrSpAlreadyExists),
    ("ErrSpDoesNotExist", ErrSpDoesNotExist),
    ("ErrSpDropFailed", ErrSpDropFailed),
    ("ErrSpStoreFailed", ErrSpStoreFailed),
    ("ErrSpLilabelMismatch", ErrSpLilabelMismatch),
    ("ErrSpLabelRedefine", ErrSpLabelRedefine),
    ("ErrSpLabelMismatch", ErrSpLabelMismatch),
    ("ErrSpUninitVar", ErrSpUninitVar),
    ("ErrSpBadselect", ErrSpBadselect),
    ("ErrSpBadreturn", ErrSpBadreturn),
    ("ErrSpBadstatement", ErrSpBadstatement),
    (
        "ErrUpdateLogDeprecatedIgnored",
        ErrUpdateLogDeprecatedIgnored,
    ),
    (
        "ErrUpdateLogDeprecatedTranslated",
        ErrUpdateLogDeprecatedTranslated,
    ),
    ("ErrQueryInterrupted", ErrQueryInterrupted),
    ("ErrSpWrongNoOfArgs", ErrSpWrongNoOfArgs),
    ("ErrSpCondMismatch", ErrSpCondMismatch),
    ("ErrSpNoreturn", ErrSpNoreturn),
    ("ErrSpNoreturnend", ErrSpNoreturnend),
    ("ErrSpBadCursorQuery", ErrSpBadCursorQuery),
    ("ErrSpBadCursorSelect", ErrSpBadCursorSelect),
    ("ErrSpCursorMismatch", ErrSpCursorMismatch),
    ("ErrSpCursorAlreadyOpen", ErrSpCursorAlreadyOpen),
    ("ErrSpCursorNotOpen", ErrSpCursorNotOpen),
    ("ErrSpUndeclaredVar", ErrSpUndeclaredVar),
    ("ErrSpWrongNoOfFetchArgs", ErrSpWrongNoOfFetchArgs),
    ("ErrSpFetchNoData", ErrSpFetchNoData),
    ("ErrSpDupParam", ErrSpDupParam),
    ("ErrSpDupVar", ErrSpDupVar),
    ("ErrSpDupCond", ErrSpDupCond),
    ("ErrSpDupCurs", ErrSpDupCurs),
    ("ErrSpCantAlter", ErrSpCantAlter),
    ("ErrSpSubselectNyi", ErrSpSubselectNyi),
    ("ErrStmtNotAllowedInSfOrTrg", ErrStmtNotAllowedInSfOrTrg),
    ("ErrSpVarcondAfterCurshndlr", ErrSpVarcondAfterCurshndlr),
    ("ErrSpCursorAfterHandler", ErrSpCursorAfterHandler),
    ("ErrSpCaseNotFound", ErrSpCaseNotFound),
    ("ErrFparserTooBigFile", ErrFparserTooBigFile),
    ("ErrFparserBadHeader", ErrFparserBadHeader),
    ("ErrFparserEOFInComment", ErrFparserEOFInComment),
    ("ErrFparserErrorInParameter", ErrFparserErrorInParameter),
    (
        "ErrFparserEOFInUnknownParameter",
        ErrFparserEOFInUnknownParameter,
    ),
    ("ErrViewNoExplain", ErrViewNoExplain),
    ("ErrFrmUnknownType", ErrFrmUnknownType),
    ("ErrWrongObject", ErrWrongObject),
    ("ErrNonupdateableColumn", ErrNonupdateableColumn),
    ("ErrViewSelectDerived", ErrViewSelectDerived),
    ("ErrViewSelectClause", ErrViewSelectClause),
    ("ErrViewSelectVariable", ErrViewSelectVariable),
    ("ErrViewSelectTmptable", ErrViewSelectTmptable),
    ("ErrViewWrongList", ErrViewWrongList),
    ("ErrWarnViewMerge", ErrWarnViewMerge),
    ("ErrWarnViewWithoutKey", ErrWarnViewWithoutKey),
    ("ErrViewInvalid", ErrViewInvalid),
    ("ErrSpNoDropSp", ErrSpNoDropSp),
    ("ErrSpGotoInHndlr", ErrSpGotoInHndlr),
    ("ErrTrgAlreadyExists", ErrTrgAlreadyExists),
    ("ErrTrgDoesNotExist", ErrTrgDoesNotExist),
    ("ErrTrgOnViewOrTempTable", ErrTrgOnViewOrTempTable),
    ("ErrTrgCantChangeRow", ErrTrgCantChangeRow),
    ("ErrTrgNoSuchRowInTrg", ErrTrgNoSuchRowInTrg),
    ("ErrNoDefaultForField", ErrNoDefaultForField),
    ("ErrDivisionByZero", ErrDivisionByZero),
    (
        "ErrTruncatedWrongValueForField",
        ErrTruncatedWrongValueForField,
    ),
    ("ErrIllegalValueForType", ErrIllegalValueForType),
    ("ErrViewNonupdCheck", ErrViewNonupdCheck),
    ("ErrViewCheckFailed", ErrViewCheckFailed),
    ("ErrProcaccessDenied", ErrProcaccessDenied),
    ("ErrRelayLogFail", ErrRelayLogFail),
    ("ErrPasswdLength", ErrPasswdLength),
    ("ErrUnknownTargetBinlog", ErrUnknownTargetBinlog),
    ("ErrIoErrLogIndexRead", ErrIoErrLogIndexRead),
    ("ErrBinlogPurgeProhibited", ErrBinlogPurgeProhibited),
    ("ErrFseekFail", ErrFseekFail),
    ("ErrBinlogPurgeFatalErr", ErrBinlogPurgeFatalErr),
    ("ErrLogInUse", ErrLogInUse),
    ("ErrLogPurgeUnknownErr", ErrLogPurgeUnknownErr),
    ("ErrRelayLogInit", ErrRelayLogInit),
    ("ErrNoBinaryLogging", ErrNoBinaryLogging),
    ("ErrReservedSyntax", ErrReservedSyntax),
    ("ErrWsasFailed", ErrWsasFailed),
    ("ErrDiffGroupsProc", ErrDiffGroupsProc),
    ("ErrNoGroupForProc", ErrNoGroupForProc),
    ("ErrOrderWithProc", ErrOrderWithProc),
    ("ErrLoggingProhibitChangingOf", ErrLoggingProhibitChangingOf),
    ("ErrNoFileMapping", ErrNoFileMapping),
    ("ErrWrongMagic", ErrWrongMagic),
    ("ErrPsManyParam", ErrPsManyParam),
    ("ErrKeyPart0", ErrKeyPart0),
    ("ErrViewChecksum", ErrViewChecksum),
    ("ErrViewMultiupdate", ErrViewMultiupdate),
    ("ErrViewNoInsertFieldList", ErrViewNoInsertFieldList),
    ("ErrViewDeleteMergeView", ErrViewDeleteMergeView),
    ("ErrCannotUser", ErrCannotUser),
    ("ErrXaerNota", ErrXaerNota),
    ("ErrXaerInval", ErrXaerInval),
    ("ErrXaerRmfail", ErrXaerRmfail),
    ("ErrXaerOutside", ErrXaerOutside),
    ("ErrXaerRmerr", ErrXaerRmerr),
    ("ErrXaRbrollback", ErrXaRbrollback),
    ("ErrNonexistingProcGrant", ErrNonexistingProcGrant),
    ("ErrProcAutoGrantFail", ErrProcAutoGrantFail),
    ("ErrProcAutoRevokeFail", ErrProcAutoRevokeFail),
    ("ErrDataTooLong", ErrDataTooLong),
    ("ErrSpBadSQLstate", ErrSpBadSQLstate),
    ("ErrStartup", ErrStartup),
    (
        "ErrLoadFromFixedSizeRowsToVar",
        ErrLoadFromFixedSizeRowsToVar,
    ),
    ("ErrCantCreateUserWithGrant", ErrCantCreateUserWithGrant),
    ("ErrWrongValueForType", ErrWrongValueForType),
    ("ErrTableDefChanged", ErrTableDefChanged),
    ("ErrSpDupHandler", ErrSpDupHandler),
    ("ErrSpNotVarArg", ErrSpNotVarArg),
    ("ErrSpNoRetset", ErrSpNoRetset),
    ("ErrCantCreateGeometryObject", ErrCantCreateGeometryObject),
    ("ErrFailedRoutineBreakBinlog", ErrFailedRoutineBreakBinlog),
    ("ErrBinlogUnsafeRoutine", ErrBinlogUnsafeRoutine),
    (
        "ErrBinlogCreateRoutineNeedSuper",
        ErrBinlogCreateRoutineNeedSuper,
    ),
    ("ErrExecStmtWithOpenCursor", ErrExecStmtWithOpenCursor),
    ("ErrStmtHasNoOpenCursor", ErrStmtHasNoOpenCursor),
    ("ErrCommitNotAllowedInSfOrTrg", ErrCommitNotAllowedInSfOrTrg),
    ("ErrNoDefaultForViewField", ErrNoDefaultForViewField),
    ("ErrSpNoRecursion", ErrSpNoRecursion),
    ("ErrTooBigScale", ErrTooBigScale),
    ("ErrTooBigPrecision", ErrTooBigPrecision),
    ("ErrMBiggerThanD", ErrMBiggerThanD),
    ("ErrWrongLockOfSystemTable", ErrWrongLockOfSystemTable),
    (
        "ErrConnectToForeignDataSource",
        ErrConnectToForeignDataSource,
    ),
    ("ErrQueryOnForeignDataSource", ErrQueryOnForeignDataSource),
    (
        "ErrForeignDataSourceDoesntExist",
        ErrForeignDataSourceDoesntExist,
    ),
    (
        "ErrForeignDataStringInvalidCantCreate",
        ErrForeignDataStringInvalidCantCreate,
    ),
    ("ErrForeignDataStringInvalid", ErrForeignDataStringInvalid),
    ("ErrCantCreateFederatedTable", ErrCantCreateFederatedTable),
    ("ErrTrgInWrongSchema", ErrTrgInWrongSchema),
    ("ErrStackOverrunNeedMore", ErrStackOverrunNeedMore),
    ("ErrTooLongBody", ErrTooLongBody),
    (
        "ErrWarnCantDropDefaultKeycache",
        ErrWarnCantDropDefaultKeycache,
    ),
    ("ErrTooBigDisplaywidth", ErrTooBigDisplaywidth),
    ("ErrXaerDupid", ErrXaerDupid),
    ("ErrDatetimeFunctionOverflow", ErrDatetimeFunctionOverflow),
    (
        "ErrCantUpdateUsedTableInSfOrTrg",
        ErrCantUpdateUsedTableInSfOrTrg,
    ),
    ("ErrViewPreventUpdate", ErrViewPreventUpdate),
    ("ErrPsNoRecursion", ErrPsNoRecursion),
    ("ErrSpCantSetAutocommit", ErrSpCantSetAutocommit),
    ("ErrMalformedDefiner", ErrMalformedDefiner),
    ("ErrViewFrmNoUser", ErrViewFrmNoUser),
    ("ErrViewOtherUser", ErrViewOtherUser),
    ("ErrNoSuchUser", ErrNoSuchUser),
    ("ErrForbidSchemaChange", ErrForbidSchemaChange),
    ("ErrRowIsReferenced2", ErrRowIsReferenced2),
    ("ErrNoReferencedRow2", ErrNoReferencedRow2),
    ("ErrSpBadVarShadow", ErrSpBadVarShadow),
    ("ErrTrgNoDefiner", ErrTrgNoDefiner),
    ("ErrOldFileFormat", ErrOldFileFormat),
    ("ErrSpRecursionLimit", ErrSpRecursionLimit),
    ("ErrSpProcTableCorrupt", ErrSpProcTableCorrupt),
    ("ErrSpWrongName", ErrSpWrongName),
    ("ErrTableNeedsUpgrade", ErrTableNeedsUpgrade),
    ("ErrSpNoAggregate", ErrSpNoAggregate),
    (
        "ErrMaxPreparedStmtCountReached",
        ErrMaxPreparedStmtCountReached,
    ),
    ("ErrViewRecursive", ErrViewRecursive),
    ("ErrNonGroupingFieldUsed", ErrNonGroupingFieldUsed),
    ("ErrTableCantHandleSpkeys", ErrTableCantHandleSpkeys),
    ("ErrNoTriggersOnSystemSchema", ErrNoTriggersOnSystemSchema),
    ("ErrRemovedSpaces", ErrRemovedSpaces),
    ("ErrAutoincReadFailed", ErrAutoincReadFailed),
    ("ErrUsername", ErrUsername),
    ("ErrHostname", ErrHostname),
    ("ErrWrongStringLength", ErrWrongStringLength),
    ("ErrNonInsertableTable", ErrNonInsertableTable),
    ("ErrAdminWrongMrgTable", ErrAdminWrongMrgTable),
    (
        "ErrTooHighLevelOfNestingForSelect",
        ErrTooHighLevelOfNestingForSelect,
    ),
    ("ErrNameBecomesEmpty", ErrNameBecomesEmpty),
    ("ErrAmbiguousFieldTerm", ErrAmbiguousFieldTerm),
    ("ErrForeignServerExists", ErrForeignServerExists),
    ("ErrForeignServerDoesntExist", ErrForeignServerDoesntExist),
    ("ErrIllegalHaCreateOption", ErrIllegalHaCreateOption),
    ("ErrPartitionRequiresValues", ErrPartitionRequiresValues),
    ("ErrPartitionWrongValues", ErrPartitionWrongValues),
    ("ErrPartitionMaxvalue", ErrPartitionMaxvalue),
    ("ErrPartitionSubpartition", ErrPartitionSubpartition),
    ("ErrPartitionSubpartMix", ErrPartitionSubpartMix),
    ("ErrPartitionWrongNoPart", ErrPartitionWrongNoPart),
    ("ErrPartitionWrongNoSubpart", ErrPartitionWrongNoSubpart),
    ("ErrWrongExprInPartitionFunc", ErrWrongExprInPartitionFunc),
    ("ErrNoConstExprInRangeOrList", ErrNoConstExprInRangeOrList),
    ("ErrFieldNotFoundPart", ErrFieldNotFoundPart),
    ("ErrListOfFieldsOnlyInHash", ErrListOfFieldsOnlyInHash),
    ("ErrInconsistentPartitionInfo", ErrInconsistentPartitionInfo),
    ("ErrPartitionFuncNotAllowed", ErrPartitionFuncNotAllowed),
    ("ErrPartitionsMustBeDefined", ErrPartitionsMustBeDefined),
    ("ErrRangeNotIncreasing", ErrRangeNotIncreasing),
    (
        "ErrInconsistentTypeOfFunctions",
        ErrInconsistentTypeOfFunctions,
    ),
    (
        "ErrMultipleDefConstInListPart",
        ErrMultipleDefConstInListPart,
    ),
    ("ErrPartitionEntry", ErrPartitionEntry),
    ("ErrMixHandler", ErrMixHandler),
    ("ErrPartitionNotDefined", ErrPartitionNotDefined),
    ("ErrTooManyPartitions", ErrTooManyPartitions),
    ("ErrSubpartition", ErrSubpartition),
    ("ErrCantCreateHandlerFile", ErrCantCreateHandlerFile),
    ("ErrBlobFieldInPartFunc", ErrBlobFieldInPartFunc),
    (
        "ErrUniqueKeyNeedAllFieldsInPf",
        ErrUniqueKeyNeedAllFieldsInPf,
    ),
    ("ErrNoParts", ErrNoParts),
    (
        "ErrPartitionMgmtOnNonpartitioned",
        ErrPartitionMgmtOnNonpartitioned,
    ),
    ("ErrForeignKeyOnPartitioned", ErrForeignKeyOnPartitioned),
    ("ErrDropPartitionNonExistent", ErrDropPartitionNonExistent),
    ("ErrDropLastPartition", ErrDropLastPartition),
    (
        "ErrCoalesceOnlyOnHashPartition",
        ErrCoalesceOnlyOnHashPartition,
    ),
    ("ErrReorgHashOnlyOnSameNo", ErrReorgHashOnlyOnSameNo),
    ("ErrReorgNoParam", ErrReorgNoParam),
    ("ErrOnlyOnRangeListPartition", ErrOnlyOnRangeListPartition),
    ("ErrAddPartitionSubpart", ErrAddPartitionSubpart),
    (
        "ErrAddPartitionNoNewPartition",
        ErrAddPartitionNoNewPartition,
    ),
    (
        "ErrCoalescePartitionNoPartition",
        ErrCoalescePartitionNoPartition,
    ),
    ("ErrReorgPartitionNotExist", ErrReorgPartitionNotExist),
    ("ErrSameNamePartition", ErrSameNamePartition),
    ("ErrNoBinlog", ErrNoBinlog),
    (
        "ErrConsecutiveReorgPartitions",
        ErrConsecutiveReorgPartitions,
    ),
    ("ErrReorgOutsideRange", ErrReorgOutsideRange),
    ("ErrPartitionFunctionFailure", ErrPartitionFunctionFailure),
    ("ErrPartState", ErrPartState),
    ("ErrLimitedPartRange", ErrLimitedPartRange),
    ("ErrPluginIsNotLoaded", ErrPluginIsNotLoaded),
    ("ErrWrongValue", ErrWrongValue),
    ("ErrNoPartitionForGivenValue", ErrNoPartitionForGivenValue),
    ("ErrFilegroupOptionOnlyOnce", ErrFilegroupOptionOnlyOnce),
    ("ErrCreateFilegroupFailed", ErrCreateFilegroupFailed),
    ("ErrDropFilegroupFailed", ErrDropFilegroupFailed),
    ("ErrTablespaceAutoExtend", ErrTablespaceAutoExtend),
    ("ErrWrongSizeNumber", ErrWrongSizeNumber),
    ("ErrSizeOverflow", ErrSizeOverflow),
    ("ErrAlterFilegroupFailed", ErrAlterFilegroupFailed),
    ("ErrBinlogRowLoggingFailed", ErrBinlogRowLoggingFailed),
    ("ErrBinlogRowWrongTableDef", ErrBinlogRowWrongTableDef),
    ("ErrBinlogRowRbrToSbr", ErrBinlogRowRbrToSbr),
    ("ErrEventAlreadyExists", ErrEventAlreadyExists),
    ("ErrEventStoreFailed", ErrEventStoreFailed),
    ("ErrEventDoesNotExist", ErrEventDoesNotExist),
    ("ErrEventCantAlter", ErrEventCantAlter),
    ("ErrEventDropFailed", ErrEventDropFailed),
    (
        "ErrEventIntervalNotPositiveOrTooBig",
        ErrEventIntervalNotPositiveOrTooBig,
    ),
    ("ErrEventEndsBeforeStarts", ErrEventEndsBeforeStarts),
    ("ErrEventExecTimeInThePast", ErrEventExecTimeInThePast),
    ("ErrEventOpenTableFailed", ErrEventOpenTableFailed),
    ("ErrEventNeitherMExprNorMAt", ErrEventNeitherMExprNorMAt),
    (
        "ErrObsoleteColCountDoesntMatchCorrupted",
        ErrObsoleteColCountDoesntMatchCorrupted,
    ),
    (
        "ErrObsoleteCannotLoadFromTable",
        ErrObsoleteCannotLoadFromTable,
    ),
    ("ErrEventCannotDelete", ErrEventCannotDelete),
    ("ErrEventCompile", ErrEventCompile),
    ("ErrEventSameName", ErrEventSameName),
    ("ErrEventDataTooLong", ErrEventDataTooLong),
    (
        "ErrDropIndexNeededInForeignKey",
        ErrDropIndexNeededInForeignKey,
    ),
    (
        "ErrWarnDeprecatedSyntaxWithVer",
        ErrWarnDeprecatedSyntaxWithVer,
    ),
    ("ErrCantWriteLockLogTable", ErrCantWriteLockLogTable),
    ("ErrCantLockLogTable", ErrCantLockLogTable),
    (
        "ErrForeignDuplicateKeyOldUnused",
        ErrForeignDuplicateKeyOldUnused,
    ),
    (
        "ErrColCountDoesntMatchPleaseUpdate",
        ErrColCountDoesntMatchPleaseUpdate,
    ),
    (
        "ErrTempTablePreventsSwitchOutOfRbr",
        ErrTempTablePreventsSwitchOutOfRbr,
    ),
    (
        "ErrStoredFunctionPreventsSwitchBinlogFormat",
        ErrStoredFunctionPreventsSwitchBinlogFormat,
    ),
    ("ErrNdbCantSwitchBinlogFormat", ErrNdbCantSwitchBinlogFormat),
    ("ErrPartitionNoTemporary", ErrPartitionNoTemporary),
    ("ErrPartitionConstDomain", ErrPartitionConstDomain),
    (
        "ErrPartitionFunctionIsNotAllowed",
        ErrPartitionFunctionIsNotAllowed,
    ),
    ("ErrDdlLog", ErrDdlLog),
    ("ErrNullInValuesLessThan", ErrNullInValuesLessThan),
    ("ErrWrongPartitionName", ErrWrongPartitionName),
    (
        "ErrCantChangeTxCharacteristics",
        ErrCantChangeTxCharacteristics,
    ),
    ("ErrDupEntryAutoincrementCase", ErrDupEntryAutoincrementCase),
    ("ErrEventModifyQueue", ErrEventModifyQueue),
    ("ErrEventSetVar", ErrEventSetVar),
    ("ErrPartitionMerge", ErrPartitionMerge),
    ("ErrCantActivateLog", ErrCantActivateLog),
    ("ErrRbrNotAvailable", ErrRbrNotAvailable),
    ("ErrBase64Decode", ErrBase64Decode),
    ("ErrEventRecursionForbidden", ErrEventRecursionForbidden),
    ("ErrEventsDB", ErrEventsDB),
    ("ErrOnlyIntegersAllowed", ErrOnlyIntegersAllowed),
    ("ErrUnsuportedLogEngine", ErrUnsuportedLogEngine),
    ("ErrBadLogStatement", ErrBadLogStatement),
    ("ErrCantRenameLogTable", ErrCantRenameLogTable),
    (
        "ErrWrongParamcountToNativeFct",
        ErrWrongParamcountToNativeFct,
    ),
    (
        "ErrWrongParametersToNativeFct",
        ErrWrongParametersToNativeFct,
    ),
    (
        "ErrWrongParametersToStoredFct",
        ErrWrongParametersToStoredFct,
    ),
    ("ErrNativeFctNameCollision", ErrNativeFctNameCollision),
    ("ErrDupEntryWithKeyName", ErrDupEntryWithKeyName),
    ("ErrBinlogPurgeEmFile", ErrBinlogPurgeEmFile),
    (
        "ErrEventCannotCreateInThePast",
        ErrEventCannotCreateInThePast,
    ),
    ("ErrEventCannotAlterInThePast", ErrEventCannotAlterInThePast),
    ("ErrSlaveIncident", ErrSlaveIncident),
    (
        "ErrNoPartitionForGivenValueSilent",
        ErrNoPartitionForGivenValueSilent,
    ),
    ("ErrBinlogUnsafeStatement", ErrBinlogUnsafeStatement),
    ("ErrSlaveFatal", ErrSlaveFatal),
    ("ErrSlaveRelayLogReadFailure", ErrSlaveRelayLogReadFailure),
    ("ErrSlaveRelayLogWriteFailure", ErrSlaveRelayLogWriteFailure),
    ("ErrSlaveCreateEventFailure", ErrSlaveCreateEventFailure),
    ("ErrSlaveMasterComFailure", ErrSlaveMasterComFailure),
    ("ErrBinlogLoggingImpossible", ErrBinlogLoggingImpossible),
    ("ErrViewNoCreationCtx", ErrViewNoCreationCtx),
    ("ErrViewInvalidCreationCtx", ErrViewInvalidCreationCtx),
    ("ErrSrInvalidCreationCtx", ErrSrInvalidCreationCtx),
    ("ErrTrgCorruptedFile", ErrTrgCorruptedFile),
    ("ErrTrgNoCreationCtx", ErrTrgNoCreationCtx),
    ("ErrTrgInvalidCreationCtx", ErrTrgInvalidCreationCtx),
    ("ErrEventInvalidCreationCtx", ErrEventInvalidCreationCtx),
    ("ErrTrgCantOpenTable", ErrTrgCantOpenTable),
    ("ErrCantCreateSroutine", ErrCantCreateSroutine),
    ("ErrNeverUsed", ErrNeverUsed),
    (
        "ErrNoFormatDescriptionEventBeforeBinlogStatement",
        ErrNoFormatDescriptionEventBeforeBinlogStatement,
    ),
    ("ErrSlaveCorruptEvent", ErrSlaveCorruptEvent),
    ("ErrLoadDataInvalidColumn", ErrLoadDataInvalidColumn),
    ("ErrLogPurgeNoFile", ErrLogPurgeNoFile),
    ("ErrXaRbtimeout", ErrXaRbtimeout),
    ("ErrXaRbdeadlock", ErrXaRbdeadlock),
    ("ErrNeedReprepare", ErrNeedReprepare),
    ("ErrDelayedNotSupported", ErrDelayedNotSupported),
    ("WarnNoMasterInfo", WarnNoMasterInfo),
    ("WarnOptionIgnored", WarnOptionIgnored),
    ("WarnPluginDeleteBuiltin", WarnPluginDeleteBuiltin),
    ("WarnPluginBusy", WarnPluginBusy),
    ("ErrVariableIsReadonly", ErrVariableIsReadonly),
    (
        "ErrWarnEngineTransactionRollback",
        ErrWarnEngineTransactionRollback,
    ),
    ("ErrSlaveHeartbeatFailure", ErrSlaveHeartbeatFailure),
    (
        "ErrSlaveHeartbeatValueOutOfRange",
        ErrSlaveHeartbeatValueOutOfRange,
    ),
    ("ErrNdbReplicationSchema", ErrNdbReplicationSchema),
    ("ErrConflictFnParse", ErrConflictFnParse),
    ("ErrExceptionsWrite", ErrExceptionsWrite),
    ("ErrTooLongTableComment", ErrTooLongTableComment),
    ("ErrTooLongFieldComment", ErrTooLongFieldComment),
    (
        "ErrFuncInexistentNameCollision",
        ErrFuncInexistentNameCollision,
    ),
    ("ErrDatabaseName", ErrDatabaseName),
    ("ErrTableName", ErrTableName),
    ("ErrPartitionName", ErrPartitionName),
    ("ErrSubpartitionName", ErrSubpartitionName),
    ("ErrTemporaryName", ErrTemporaryName),
    ("ErrRenamedName", ErrRenamedName),
    ("ErrTooManyConcurrentTrxs", ErrTooManyConcurrentTrxs),
    (
        "WarnNonASCIISeparatorNotImplemented",
        WarnNonASCIISeparatorNotImplemented,
    ),
    ("ErrDebugSyncTimeout", ErrDebugSyncTimeout),
    ("ErrDebugSyncHitLimit", ErrDebugSyncHitLimit),
    ("ErrDupSignalSet", ErrDupSignalSet),
    ("ErrSignalWarn", ErrSignalWarn),
    ("ErrSignalNotFound", ErrSignalNotFound),
    ("ErrSignalException", ErrSignalException),
    (
        "ErrResignalWithoutActiveHandler",
        ErrResignalWithoutActiveHandler,
    ),
    ("ErrSignalBadConditionType", ErrSignalBadConditionType),
    ("WarnCondItemTruncated", WarnCondItemTruncated),
    ("ErrCondItemTooLong", ErrCondItemTooLong),
    ("ErrUnknownLocale", ErrUnknownLocale),
    ("ErrSlaveIgnoreServerIDs", ErrSlaveIgnoreServerIDs),
    ("ErrQueryCacheDisabled", ErrQueryCacheDisabled),
    ("ErrSameNamePartitionField", ErrSameNamePartitionField),
    ("ErrPartitionColumnList", ErrPartitionColumnList),
    ("ErrWrongTypeColumnValue", ErrWrongTypeColumnValue),
    (
        "ErrTooManyPartitionFuncFields",
        ErrTooManyPartitionFuncFields,
    ),
    ("ErrMaxvalueInValuesIn", ErrMaxvalueInValuesIn),
    ("ErrTooManyValues", ErrTooManyValues),
    ("ErrRowSinglePartitionField", ErrRowSinglePartitionField),
    (
        "ErrFieldTypeNotAllowedAsPartitionField",
        ErrFieldTypeNotAllowedAsPartitionField,
    ),
    ("ErrPartitionFieldsTooLong", ErrPartitionFieldsTooLong),
    (
        "ErrBinlogRowEngineAndStmtEngine",
        ErrBinlogRowEngineAndStmtEngine,
    ),
    (
        "ErrBinlogRowModeAndStmtEngine",
        ErrBinlogRowModeAndStmtEngine,
    ),
    ("ErrBinlogUnsafeAndStmtEngine", ErrBinlogUnsafeAndStmtEngine),
    (
        "ErrBinlogRowInjectionAndStmtEngine",
        ErrBinlogRowInjectionAndStmtEngine,
    ),
    (
        "ErrBinlogStmtModeAndRowEngine",
        ErrBinlogStmtModeAndRowEngine,
    ),
    (
        "ErrBinlogRowInjectionAndStmtMode",
        ErrBinlogRowInjectionAndStmtMode,
    ),
    (
        "ErrBinlogMultipleEnginesAndSelfLoggingEngine",
        ErrBinlogMultipleEnginesAndSelfLoggingEngine,
    ),
    ("ErrBinlogUnsafeLimit", ErrBinlogUnsafeLimit),
    ("ErrBinlogUnsafeInsertDelayed", ErrBinlogUnsafeInsertDelayed),
    ("ErrBinlogUnsafeSystemTable", ErrBinlogUnsafeSystemTable),
    (
        "ErrBinlogUnsafeAutoincColumns",
        ErrBinlogUnsafeAutoincColumns,
    ),
    ("ErrBinlogUnsafeUdf", ErrBinlogUnsafeUdf),
    (
        "ErrBinlogUnsafeSystemVariable",
        ErrBinlogUnsafeSystemVariable,
    ),
    (
        "ErrBinlogUnsafeSystemFunction",
        ErrBinlogUnsafeSystemFunction,
    ),
    (
        "ErrBinlogUnsafeNontransAfterTrans",
        ErrBinlogUnsafeNontransAfterTrans,
    ),
    ("ErrMessageAndStatement", ErrMessageAndStatement),
    ("ErrSlaveConversionFailed", ErrSlaveConversionFailed),
    ("ErrSlaveCantCreateConversion", ErrSlaveCantCreateConversion),
    (
        "ErrInsideTransactionPreventsSwitchBinlogFormat",
        ErrInsideTransactionPreventsSwitchBinlogFormat,
    ),
    ("ErrPathLength", ErrPathLength),
    (
        "ErrWarnDeprecatedSyntaxNoReplacement",
        ErrWarnDeprecatedSyntaxNoReplacement,
    ),
    ("ErrWrongNativeTableStructure", ErrWrongNativeTableStructure),
    ("ErrWrongPerfSchemaUsage", ErrWrongPerfSchemaUsage),
    ("ErrWarnISSkippedTable", ErrWarnISSkippedTable),
    (
        "ErrInsideTransactionPreventsSwitchBinlogDirect",
        ErrInsideTransactionPreventsSwitchBinlogDirect,
    ),
    (
        "ErrStoredFunctionPreventsSwitchBinlogDirect",
        ErrStoredFunctionPreventsSwitchBinlogDirect,
    ),
    ("ErrSpatialMustHaveGeomCol", ErrSpatialMustHaveGeomCol),
    ("ErrTooLongIndexComment", ErrTooLongIndexComment),
    ("ErrLockAborted", ErrLockAborted),
    ("ErrDataOutOfRange", ErrDataOutOfRange),
    ("ErrWrongSpvarTypeInLimit", ErrWrongSpvarTypeInLimit),
    (
        "ErrBinlogUnsafeMultipleEnginesAndSelfLoggingEngine",
        ErrBinlogUnsafeMultipleEnginesAndSelfLoggingEngine,
    ),
    (
        "ErrBinlogUnsafeMixedStatement",
        ErrBinlogUnsafeMixedStatement,
    ),
    (
        "ErrInsideTransactionPreventsSwitchSQLLogBin",
        ErrInsideTransactionPreventsSwitchSQLLogBin,
    ),
    (
        "ErrStoredFunctionPreventsSwitchSQLLogBin",
        ErrStoredFunctionPreventsSwitchSQLLogBin,
    ),
    ("ErrFailedReadFromParFile", ErrFailedReadFromParFile),
    ("ErrValuesIsNotIntType", ErrValuesIsNotIntType),
    ("ErrAccessDeniedNoPassword", ErrAccessDeniedNoPassword),
    ("ErrSetPasswordAuthPlugin", ErrSetPasswordAuthPlugin),
    ("ErrGrantPluginUserExists", ErrGrantPluginUserExists),
    ("ErrTruncateIllegalForeignKey", ErrTruncateIllegalForeignKey),
    ("ErrPluginIsPermanent", ErrPluginIsPermanent),
    (
        "ErrSlaveHeartbeatValueOutOfRangeMin",
        ErrSlaveHeartbeatValueOutOfRangeMin,
    ),
    (
        "ErrSlaveHeartbeatValueOutOfRangeMax",
        ErrSlaveHeartbeatValueOutOfRangeMax,
    ),
    ("ErrStmtCacheFull", ErrStmtCacheFull),
    ("ErrMultiUpdateKeyConflict", ErrMultiUpdateKeyConflict),
    ("ErrTableNeedsRebuild", ErrTableNeedsRebuild),
    ("WarnOptionBelowLimit", WarnOptionBelowLimit),
    ("ErrIndexColumnTooLong", ErrIndexColumnTooLong),
    ("ErrErrorInTriggerBody", ErrErrorInTriggerBody),
    ("ErrErrorInUnknownTriggerBody", ErrErrorInUnknownTriggerBody),
    ("ErrIndexCorrupt", ErrIndexCorrupt),
    ("ErrUndoRecordTooBig", ErrUndoRecordTooBig),
    (
        "ErrBinlogUnsafeInsertIgnoreSelect",
        ErrBinlogUnsafeInsertIgnoreSelect,
    ),
    (
        "ErrBinlogUnsafeInsertSelectUpdate",
        ErrBinlogUnsafeInsertSelectUpdate,
    ),
    ("ErrBinlogUnsafeReplaceSelect", ErrBinlogUnsafeReplaceSelect),
    (
        "ErrBinlogUnsafeCreateIgnoreSelect",
        ErrBinlogUnsafeCreateIgnoreSelect,
    ),
    (
        "ErrBinlogUnsafeCreateReplaceSelect",
        ErrBinlogUnsafeCreateReplaceSelect,
    ),
    ("ErrBinlogUnsafeUpdateIgnore", ErrBinlogUnsafeUpdateIgnore),
    ("ErrPluginNoUninstall", ErrPluginNoUninstall),
    ("ErrPluginNoInstall", ErrPluginNoInstall),
    (
        "ErrBinlogUnsafeWriteAutoincSelect",
        ErrBinlogUnsafeWriteAutoincSelect,
    ),
    (
        "ErrBinlogUnsafeCreateSelectAutoinc",
        ErrBinlogUnsafeCreateSelectAutoinc,
    ),
    ("ErrBinlogUnsafeInsertTwoKeys", ErrBinlogUnsafeInsertTwoKeys),
    ("ErrTableInFkCheck", ErrTableInFkCheck),
    ("ErrUnsupportedEngine", ErrUnsupportedEngine),
    (
        "ErrBinlogUnsafeAutoincNotFirst",
        ErrBinlogUnsafeAutoincNotFirst,
    ),
    ("ErrCannotLoadFromTableV2", ErrCannotLoadFromTableV2),
    (
        "ErrMasterDelayValueOutOfRange",
        ErrMasterDelayValueOutOfRange,
    ),
    (
        "ErrOnlyFdAndRbrEventsAllowedInBinlogStatement",
        ErrOnlyFdAndRbrEventsAllowedInBinlogStatement,
    ),
    (
        "ErrPartitionExchangeDifferentOption",
        ErrPartitionExchangeDifferentOption,
    ),
    (
        "ErrPartitionExchangePartTable",
        ErrPartitionExchangePartTable,
    ),
    (
        "ErrPartitionExchangeTempTable",
        ErrPartitionExchangeTempTable,
    ),
    (
        "ErrPartitionInsteadOfSubpartition",
        ErrPartitionInsteadOfSubpartition,
    ),
    ("ErrUnknownPartition", ErrUnknownPartition),
    ("ErrTablesDifferentMetadata", ErrTablesDifferentMetadata),
    ("ErrRowDoesNotMatchPartition", ErrRowDoesNotMatchPartition),
    (
        "ErrBinlogCacheSizeGreaterThanMax",
        ErrBinlogCacheSizeGreaterThanMax,
    ),
    ("ErrWarnIndexNotApplicable", ErrWarnIndexNotApplicable),
    (
        "ErrPartitionExchangeForeignKey",
        ErrPartitionExchangeForeignKey,
    ),
    ("ErrNoSuchKeyValue", ErrNoSuchKeyValue),
    ("ErrRplInfoDataTooLong", ErrRplInfoDataTooLong),
    (
        "ErrNetworkReadEventChecksumFailure",
        ErrNetworkReadEventChecksumFailure,
    ),
    (
        "ErrBinlogReadEventChecksumFailure",
        ErrBinlogReadEventChecksumFailure,
    ),
    (
        "ErrBinlogStmtCacheSizeGreaterThanMax",
        ErrBinlogStmtCacheSizeGreaterThanMax,
    ),
    (
        "ErrCantUpdateTableInCreateTableSelect",
        ErrCantUpdateTableInCreateTableSelect,
    ),
    (
        "ErrPartitionClauseOnNonpartitioned",
        ErrPartitionClauseOnNonpartitioned,
    ),
    (
        "ErrRowDoesNotMatchGivenPartitionSet",
        ErrRowDoesNotMatchGivenPartitionSet,
    ),
    ("ErrNoSuchPartitionunused", ErrNoSuchPartitionunused),
    (
        "ErrChangeRplInfoRepositoryFailure",
        ErrChangeRplInfoRepositoryFailure,
    ),
    (
        "ErrWarningNotCompleteRollbackWithCreatedTempTable",
        ErrWarningNotCompleteRollbackWithCreatedTempTable,
    ),
    (
        "ErrWarningNotCompleteRollbackWithDroppedTempTable",
        ErrWarningNotCompleteRollbackWithDroppedTempTable,
    ),
    ("ErrMtsFeatureIsNotSupported", ErrMtsFeatureIsNotSupported),
    ("ErrMtsUpdatedDBsGreaterMax", ErrMtsUpdatedDBsGreaterMax),
    ("ErrMtsCantParallel", ErrMtsCantParallel),
    ("ErrMtsInconsistentData", ErrMtsInconsistentData),
    (
        "ErrFulltextNotSupportedWithPartitioning",
        ErrFulltextNotSupportedWithPartitioning,
    ),
    ("ErrDaInvalidConditionNumber", ErrDaInvalidConditionNumber),
    ("ErrInsecurePlainText", ErrInsecurePlainText),
    ("ErrInsecureChangeMaster", ErrInsecureChangeMaster),
    (
        "ErrForeignDuplicateKeyWithChildInfo",
        ErrForeignDuplicateKeyWithChildInfo,
    ),
    (
        "ErrForeignDuplicateKeyWithoutChildInfo",
        ErrForeignDuplicateKeyWithoutChildInfo,
    ),
    ("ErrSQLthreadWithSecureSlave", ErrSQLthreadWithSecureSlave),
    ("ErrTableHasNoFt", ErrTableHasNoFt),
    (
        "ErrVariableNotSettableInSfOrTrigger",
        ErrVariableNotSettableInSfOrTrigger,
    ),
    (
        "ErrVariableNotSettableInTransaction",
        ErrVariableNotSettableInTransaction,
    ),
    (
        "ErrGtidNextIsNotInGtidNextList",
        ErrGtidNextIsNotInGtidNextList,
    ),
    (
        "ErrCantChangeGtidNextInTransactionWhenGtidNextListIsNull",
        ErrCantChangeGtidNextInTransactionWhenGtidNextListIsNull,
    ),
    (
        "ErrSetStatementCannotInvokeFunction",
        ErrSetStatementCannotInvokeFunction,
    ),
    (
        "ErrGtidNextCantBeAutomaticIfGtidNextListIsNonNull",
        ErrGtidNextCantBeAutomaticIfGtidNextListIsNonNull,
    ),
    ("ErrSkippingLoggedTransaction", ErrSkippingLoggedTransaction),
    (
        "ErrMalformedGtidSetSpecification",
        ErrMalformedGtidSetSpecification,
    ),
    ("ErrMalformedGtidSetEncoding", ErrMalformedGtidSetEncoding),
    (
        "ErrMalformedGtidSpecification",
        ErrMalformedGtidSpecification,
    ),
    ("ErrGnoExhausted", ErrGnoExhausted),
    ("ErrBadSlaveAutoPosition", ErrBadSlaveAutoPosition),
    (
        "ErrAutoPositionRequiresGtidModeOn",
        ErrAutoPositionRequiresGtidModeOn,
    ),
    (
        "ErrCantDoImplicitCommitInTrxWhenGtidNextIsSet",
        ErrCantDoImplicitCommitInTrxWhenGtidNextIsSet,
    ),
    (
        "ErrGtidMode2Or3RequiresEnforceGtidConsistencyOn",
        ErrGtidMode2Or3RequiresEnforceGtidConsistencyOn,
    ),
    ("ErrGtidModeRequiresBinlog", ErrGtidModeRequiresBinlog),
    (
        "ErrCantSetGtidNextToGtidWhenGtidModeIsOff",
        ErrCantSetGtidNextToGtidWhenGtidModeIsOff,
    ),
    (
        "ErrCantSetGtidNextToAnonymousWhenGtidModeIsOn",
        ErrCantSetGtidNextToAnonymousWhenGtidModeIsOn,
    ),
    (
        "ErrCantSetGtidNextListToNonNullWhenGtidModeIsOff",
        ErrCantSetGtidNextListToNonNullWhenGtidModeIsOff,
    ),
    (
        "ErrFoundGtidEventWhenGtidModeIsOff",
        ErrFoundGtidEventWhenGtidModeIsOff,
    ),
    (
        "ErrGtidUnsafeNonTransactionalTable",
        ErrGtidUnsafeNonTransactionalTable,
    ),
    ("ErrGtidUnsafeCreateSelect", ErrGtidUnsafeCreateSelect),
    (
        "ErrGtidUnsafeCreateDropTemporaryTableInTransaction",
        ErrGtidUnsafeCreateDropTemporaryTableInTransaction,
    ),
    (
        "ErrGtidModeCanOnlyChangeOneStepAtATime",
        ErrGtidModeCanOnlyChangeOneStepAtATime,
    ),
    (
        "ErrMasterHasPurgedRequiredGtids",
        ErrMasterHasPurgedRequiredGtids,
    ),
    (
        "ErrCantSetGtidNextWhenOwningGtid",
        ErrCantSetGtidNextWhenOwningGtid,
    ),
    ("ErrUnknownExplainFormat", ErrUnknownExplainFormat),
    (
        "ErrCantExecuteInReadOnlyTransaction",
        ErrCantExecuteInReadOnlyTransaction,
    ),
    (
        "ErrTooLongTablePartitionComment",
        ErrTooLongTablePartitionComment,
    ),
    ("ErrSlaveConfiguration", ErrSlaveConfiguration),
    ("ErrInnodbFtLimit", ErrInnodbFtLimit),
    ("ErrInnodbNoFtTempTable", ErrInnodbNoFtTempTable),
    ("ErrInnodbFtWrongDocidColumn", ErrInnodbFtWrongDocidColumn),
    ("ErrInnodbFtWrongDocidIndex", ErrInnodbFtWrongDocidIndex),
    ("ErrInnodbOnlineLogTooBig", ErrInnodbOnlineLogTooBig),
    ("ErrUnknownAlterAlgorithm", ErrUnknownAlterAlgorithm),
    ("ErrUnknownAlterLock", ErrUnknownAlterLock),
    (
        "ErrMtsChangeMasterCantRunWithGaps",
        ErrMtsChangeMasterCantRunWithGaps,
    ),
    ("ErrMtsRecoveryFailure", ErrMtsRecoveryFailure),
    ("ErrMtsResetWorkers", ErrMtsResetWorkers),
    (
        "ErrColCountDoesntMatchCorruptedV2",
        ErrColCountDoesntMatchCorruptedV2,
    ),
    (
        "ErrSlaveSilentRetryTransaction",
        ErrSlaveSilentRetryTransaction,
    ),
    ("ErrDiscardFkChecksRunning", ErrDiscardFkChecksRunning),
    ("ErrTableSchemaMismatch", ErrTableSchemaMismatch),
    ("ErrTableInSystemTablespace", ErrTableInSystemTablespace),
    ("ErrIoRead", ErrIoRead),
    ("ErrIoWrite", ErrIoWrite),
    ("ErrTablespaceMissing", ErrTablespaceMissing),
    ("ErrTablespaceExists", ErrTablespaceExists),
    ("ErrTablespaceDiscarded", ErrTablespaceDiscarded),
    ("ErrInternal", ErrInternal),
    ("ErrInnodbImport", ErrInnodbImport),
    ("ErrInnodbIndexCorrupt", ErrInnodbIndexCorrupt),
    ("ErrInvalidYearColumnLength", ErrInvalidYearColumnLength),
    ("ErrNotValidPassword", ErrNotValidPassword),
    ("ErrMustChangePassword", ErrMustChangePassword),
    ("ErrFkNoIndexChild", ErrFkNoIndexChild),
    ("ErrForeignKeyNoIndexInParent", ErrForeignKeyNoIndexInParent),
    ("ErrFkFailAddSystem", ErrFkFailAddSystem),
    (
        "ErrForeignKeyCannotOpenParent",
        ErrForeignKeyCannotOpenParent,
    ),
    ("ErrFkIncorrectOption", ErrFkIncorrectOption),
    ("ErrFkDupName", ErrFkDupName),
    ("ErrPasswordFormat", ErrPasswordFormat),
    ("ErrFkColumnCannotDrop", ErrFkColumnCannotDrop),
    ("ErrFkColumnCannotDropChild", ErrFkColumnCannotDropChild),
    ("ErrForeignKeyColumnNotNull", ErrForeignKeyColumnNotNull),
    ("ErrDupIndex", ErrDupIndex),
    (
        "ErrForeignKeyColumnCannotChange",
        ErrForeignKeyColumnCannotChange,
    ),
    (
        "ErrForeignKeyColumnCannotChangeChild",
        ErrForeignKeyColumnCannotChangeChild,
    ),
    ("ErrFkCannotDeleteParent", ErrFkCannotDeleteParent),
    ("ErrMalformedPacket", ErrMalformedPacket),
    ("ErrReadOnlyMode", ErrReadOnlyMode),
    (
        "ErrGtidNextTypeUndefinedGroup",
        ErrGtidNextTypeUndefinedGroup,
    ),
    ("ErrVariableNotSettableInSp", ErrVariableNotSettableInSp),
    (
        "ErrCantSetGtidPurgedWhenGtidModeIsOff",
        ErrCantSetGtidPurgedWhenGtidModeIsOff,
    ),
    (
        "ErrCantSetGtidPurgedWhenGtidExecutedIsNotEmpty",
        ErrCantSetGtidPurgedWhenGtidExecutedIsNotEmpty,
    ),
    (
        "ErrCantSetGtidPurgedWhenOwnedGtidsIsNotEmpty",
        ErrCantSetGtidPurgedWhenOwnedGtidsIsNotEmpty,
    ),
    ("ErrGtidPurgedWasChanged", ErrGtidPurgedWasChanged),
    ("ErrGtidExecutedWasChanged", ErrGtidExecutedWasChanged),
    (
        "ErrBinlogStmtModeAndNoReplTables",
        ErrBinlogStmtModeAndNoReplTables,
    ),
    (
        "ErrAlterOperationNotSupported",
        ErrAlterOperationNotSupported,
    ),
    (
        "ErrAlterOperationNotSupportedReason",
        ErrAlterOperationNotSupportedReason,
    ),
    (
        "ErrAlterOperationNotSupportedReasonCopy",
        ErrAlterOperationNotSupportedReasonCopy,
    ),
    (
        "ErrAlterOperationNotSupportedReasonPartition",
        ErrAlterOperationNotSupportedReasonPartition,
    ),
    (
        "ErrAlterOperationNotSupportedReasonFkRename",
        ErrAlterOperationNotSupportedReasonFkRename,
    ),
    (
        "ErrAlterOperationNotSupportedReasonColumnType",
        ErrAlterOperationNotSupportedReasonColumnType,
    ),
    (
        "ErrAlterOperationNotSupportedReasonFkCheck",
        ErrAlterOperationNotSupportedReasonFkCheck,
    ),
    (
        "ErrAlterOperationNotSupportedReasonIgnore",
        ErrAlterOperationNotSupportedReasonIgnore,
    ),
    (
        "ErrAlterOperationNotSupportedReasonNopk",
        ErrAlterOperationNotSupportedReasonNopk,
    ),
    (
        "ErrAlterOperationNotSupportedReasonAutoinc",
        ErrAlterOperationNotSupportedReasonAutoinc,
    ),
    (
        "ErrAlterOperationNotSupportedReasonHiddenFts",
        ErrAlterOperationNotSupportedReasonHiddenFts,
    ),
    (
        "ErrAlterOperationNotSupportedReasonChangeFts",
        ErrAlterOperationNotSupportedReasonChangeFts,
    ),
    (
        "ErrAlterOperationNotSupportedReasonFts",
        ErrAlterOperationNotSupportedReasonFts,
    ),
    (
        "ErrSQLSlaveSkipCounterNotSettableInGtidMode",
        ErrSQLSlaveSkipCounterNotSettableInGtidMode,
    ),
    ("ErrDupUnknownInIndex", ErrDupUnknownInIndex),
    ("ErrIdentCausesTooLongPath", ErrIdentCausesTooLongPath),
    (
        "ErrAlterOperationNotSupportedReasonNotNull",
        ErrAlterOperationNotSupportedReasonNotNull,
    ),
    ("ErrMustChangePasswordLogin", ErrMustChangePasswordLogin),
    ("ErrRowInWrongPartition", ErrRowInWrongPartition),
    ("ErrErrorLast", ErrErrorLast),
    ("ErrInvalidFieldSize", ErrInvalidFieldSize),
    (
        "ErrPasswordExpireAnonymousUser",
        ErrPasswordExpireAnonymousUser,
    ),
    ("ErrMaxExecTimeExceeded", ErrMaxExecTimeExceeded),
    ("ErrIncorrectType", ErrIncorrectType),
    ("ErrInvalidJSONData", ErrInvalidJSONData),
    (
        "ErrGeneratedColumnFunctionIsNotAllowed",
        ErrGeneratedColumnFunctionIsNotAllowed,
    ),
    (
        "ErrUnsupportedAlterInplaceOnVirtualColumn",
        ErrUnsupportedAlterInplaceOnVirtualColumn,
    ),
    (
        "ErrWrongFKOptionForGeneratedColumn",
        ErrWrongFKOptionForGeneratedColumn,
    ),
    ("ErrBadGeneratedColumn", ErrBadGeneratedColumn),
    (
        "ErrUnsupportedOnGeneratedColumn",
        ErrUnsupportedOnGeneratedColumn,
    ),
    ("ErrGeneratedColumnNonPrior", ErrGeneratedColumnNonPrior),
    (
        "ErrDependentByGeneratedColumn",
        ErrDependentByGeneratedColumn,
    ),
    ("ErrGeneratedColumnRefAutoInc", ErrGeneratedColumnRefAutoInc),
    ("ErrInvalidJSONText", ErrInvalidJSONText),
    ("ErrInvalidJSONTextInParam", ErrInvalidJSONTextInParam),
    ("ErrInvalidJSONPath", ErrInvalidJSONPath),
    ("ErrInvalidJSONCharset", ErrInvalidJSONCharset),
    ("ErrInvalidTypeForJSON", ErrInvalidTypeForJSON),
    ("ErrInvalidJSONPathWildcard", ErrInvalidJSONPathWildcard),
    (
        "ErrInvalidJSONContainsPathType",
        ErrInvalidJSONContainsPathType,
    ),
    ("ErrJSONUsedAsKey", ErrJSONUsedAsKey),
    ("ErrJSONVacuousPath", ErrJSONVacuousPath),
    ("ErrJSONBadOneOrAllArg", ErrJSONBadOneOrAllArg),
    ("ErrJSONDocumentTooDeep", ErrJSONDocumentTooDeep),
    ("ErrJSONDocumentNULLKey", ErrJSONDocumentNULLKey),
    ("ErrBadUser", ErrBadUser),
    ("ErrUserAlreadyExists", ErrUserAlreadyExists),
    ("ErrInvalidJSONPathArrayCell", ErrInvalidJSONPathArrayCell),
    ("ErrInvalidEncryptionOption", ErrInvalidEncryptionOption),
    ("ErrRoleNotGranted", ErrRoleNotGranted),
    (
        "ErrLockAcquireFailAndNoWaitSet",
        ErrLockAcquireFailAndNoWaitSet,
    ),
    ("ErrWindowNoSuchWindow", ErrWindowNoSuchWindow),
    (
        "ErrWindowCircularityInWindowGraph",
        ErrWindowCircularityInWindowGraph,
    ),
    ("ErrWindowNoChildPartitioning", ErrWindowNoChildPartitioning),
    ("ErrWindowNoInherentFrame", ErrWindowNoInherentFrame),
    ("ErrWindowNoRedefineOrderBy", ErrWindowNoRedefineOrderBy),
    ("ErrWindowFrameStartIllegal", ErrWindowFrameStartIllegal),
    ("ErrWindowFrameEndIllegal", ErrWindowFrameEndIllegal),
    ("ErrWindowFrameIllegal", ErrWindowFrameIllegal),
    ("ErrWindowRangeFrameOrderType", ErrWindowRangeFrameOrderType),
    (
        "ErrWindowRangeFrameTemporalType",
        ErrWindowRangeFrameTemporalType,
    ),
    (
        "ErrWindowRangeFrameNumericType",
        ErrWindowRangeFrameNumericType,
    ),
    (
        "ErrWindowRangeBoundNotConstant",
        ErrWindowRangeBoundNotConstant,
    ),
    ("ErrWindowDuplicateName", ErrWindowDuplicateName),
    ("ErrWindowIllegalOrderBy", ErrWindowIllegalOrderBy),
    (
        "ErrWindowInvalidWindowFuncUse",
        ErrWindowInvalidWindowFuncUse,
    ),
    (
        "ErrWindowInvalidWindowFuncAliasUse",
        ErrWindowInvalidWindowFuncAliasUse,
    ),
    (
        "ErrWindowNestedWindowFuncUseInWindowSpec",
        ErrWindowNestedWindowFuncUseInWindowSpec,
    ),
    ("ErrWindowRowsIntervalUse", ErrWindowRowsIntervalUse),
    ("ErrWindowNoGroupOrderUnused", ErrWindowNoGroupOrderUnused),
    ("ErrWindowExplainJson", ErrWindowExplainJson),
    (
        "ErrWindowFunctionIgnoresFrame",
        ErrWindowFunctionIgnoresFrame,
    ),
    (
        "ErrDataTruncatedFunctionalIndex",
        ErrDataTruncatedFunctionalIndex,
    ),
    (
        "ErrDataOutOfRangeFunctionalIndex",
        ErrDataOutOfRangeFunctionalIndex,
    ),
    (
        "ErrFunctionalIndexOnJsonOrGeometryFunction",
        ErrFunctionalIndexOnJsonOrGeometryFunction,
    ),
    (
        "ErrFunctionalIndexRefAutoIncrement",
        ErrFunctionalIndexRefAutoIncrement,
    ),
    (
        "ErrCannotDropColumnFunctionalIndex",
        ErrCannotDropColumnFunctionalIndex,
    ),
    ("ErrFunctionalIndexPrimaryKey", ErrFunctionalIndexPrimaryKey),
    ("ErrFunctionalIndexOnLob", ErrFunctionalIndexOnLob),
    (
        "ErrFunctionalIndexFunctionIsNotAllowed",
        ErrFunctionalIndexFunctionIsNotAllowed,
    ),
    ("ErrFulltextFunctionalIndex", ErrFulltextFunctionalIndex),
    ("ErrSpatialFunctionalIndex", ErrSpatialFunctionalIndex),
    (
        "ErrWrongKeyColumnFunctionalIndex",
        ErrWrongKeyColumnFunctionalIndex,
    ),
    ("ErrFunctionalIndexOnField", ErrFunctionalIndexOnField),
    ("ErrFKIncompatibleColumns", ErrFKIncompatibleColumns),
    (
        "ErrFunctionalIndexRowValueIsNotAllowed",
        ErrFunctionalIndexRowValueIsNotAllowed,
    ),
    (
        "ErrDependentByFunctionalIndex",
        ErrDependentByFunctionalIndex,
    ),
    ("ErrInvalidJSONType", ErrInvalidJSONType),
    (
        "ErrInvalidJsonValueForFuncIndex",
        ErrInvalidJsonValueForFuncIndex,
    ),
    (
        "ErrJsonValueOutOfRangeForFuncIndex",
        ErrJsonValueOutOfRangeForFuncIndex,
    ),
    (
        "ErrFunctionalIndexDataIsTooLong",
        ErrFunctionalIndexDataIsTooLong,
    ),
    (
        "ErrFunctionalIndexNotApplicable",
        ErrFunctionalIndexNotApplicable,
    ),
    (
        "ErrOnlyOneDefaultPartionAllowed",
        ErrOnlyOneDefaultPartionAllowed,
    ),
    (
        "ErrWrongPartitionTypeExpectedSystemTime",
        ErrWrongPartitionTypeExpectedSystemTime,
    ),
    (
        "ErrSystemVersioningWrongPartitions",
        ErrSystemVersioningWrongPartitions,
    ),
    ("ErrSequenceRunOut", ErrSequenceRunOut),
    ("ErrSequenceInvalidData", ErrSequenceInvalidData),
    ("ErrSequenceAccessFail", ErrSequenceAccessFail),
    ("ErrNotSequence", ErrNotSequence),
    ("ErrUnknownSequence", ErrUnknownSequence),
    ("ErrWrongInsertIntoSequence", ErrWrongInsertIntoSequence),
    (
        "ErrSequenceInvalidTableStructure",
        ErrSequenceInvalidTableStructure,
    ),
    (
        "ErrWarnOptimizerHintUnsupportedHint",
        ErrWarnOptimizerHintUnsupportedHint,
    ),
    (
        "ErrWarnOptimizerHintInvalidToken",
        ErrWarnOptimizerHintInvalidToken,
    ),
    ("ErrWarnMemoryQuotaOverflow", ErrWarnMemoryQuotaOverflow),
    (
        "ErrWarnOptimizerHintParseError",
        ErrWarnOptimizerHintParseError,
    ),
    (
        "ErrWarnOptimizerHintInvalidInteger",
        ErrWarnOptimizerHintInvalidInteger,
    ),
    ("ErrWarnOptimizerHintWrongPos", ErrWarnOptimizerHintWrongPos),
];
