// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package physicalop

import (
	"math"

	"github.com/pingcap/tidb/pkg/util/context"
	"github.com/pingcap/tidb/pkg/util/ranger"
)

// SimpleWarnings is a simple implementation of Warnings interface.
type SimpleWarnings struct {
	warnings []*context.SQLWarn
}

// WarningCount returns the number of warnings.
func (s *SimpleWarnings) WarningCount() int {
	return len(s.warnings)
}

// Copy implemented the simple warnings copy to avoid use the same warnings slice for different task instance.
func (s *SimpleWarnings) Copy(src *SimpleWarnings) {
	warnings := make([]*context.SQLWarn, 0, len(src.warnings))
	warnings = append(warnings, src.warnings...)
	s.warnings = warnings
}

// CopyFrom copy the warnings from src to s.
func (s *SimpleWarnings) CopyFrom(src ...*SimpleWarnings) {
	if src == nil {
		return
	}
	length := 0
	for _, one := range src {
		if one == nil {
			continue
		}
		length += one.WarningCount()
	}
	s.warnings = make([]*context.SQLWarn, 0, length)
	for _, one := range src {
		if one == nil {
			continue
		}
		s.warnings = append(s.warnings, one.warnings...)
	}
}

// AppendWarning appends a warning to the warnings slice.
func (s *SimpleWarnings) AppendWarning(warn error) {
	if len(s.warnings) < math.MaxUint16 {
		s.warnings = append(s.warnings, &context.SQLWarn{Level: context.WarnLevelWarning, Err: warn})
	}
}

// AppendNote appends a note to the warnings slice.
func (s *SimpleWarnings) AppendNote(note error) {
	if len(s.warnings) < math.MaxUint16 {
		s.warnings = append(s.warnings, &context.SQLWarn{Level: context.WarnLevelNote, Err: note})
	}
}

// GetWarnings returns the internal all stored warnings.
func (s *SimpleWarnings) GetWarnings() []context.SQLWarn {
	// we just reuse and reorganize pointer of warning elem across different level's
	// task warnings slice to avoid copy them totally leading mem cost.
	// when best task is finished and final warnings is determined, we should convert
	// pointer to struct to append it to session context.
	warnings := make([]context.SQLWarn, 0, len(s.warnings))
	for _, w := range s.warnings {
		warnings = append(warnings, *w)
	}
	return warnings
}

// IndexJoinInfo is generated by index join's inner ds, which will build their own index choice based
// the indexJoinProp pushed down by index join. While index join still need some feedback by this kind
// choice info to make index join runtime compatible, like IdxColLens will help truncate the index key
// to construct suitable lookup contents. KeyOff2IdxOff will help ds to quickly locate the index column
// from lookup contents. Ranges will be used to rebuild the underlying index range if there is any parameter
// affecting the index join's inner range. CompareFilters will be used to quickly evaluate the last-col's
// non-eq range.
// This kind of IndexJoinInfo will be wrapped as a part of CopTask or RootTask, which will be passed upward
// to targeted indexJoin to complete the physicalIndexJoin's detail: ref:
type IndexJoinInfo struct {
	// The following fields are used to keep index join aware of inner plan's index/pk choice.
	IdxColLens     []int
	KeyOff2IdxOff  []int
	Ranges         ranger.MutableRanges
	CompareFilters *ColWithCmpFuncManager
}
