version: 2

jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/pingcap/parser
    steps:
      - checkout
      - run:
          name: "Verify parser.go is up-to-date"
          command: |
            mv parser.go parser.go.committed
            make parser
            diff -u parser.go.committed parser.go
      - run:
          name: "Check code format"
          command: gofmt -l -s . | awk '{print} END{if(NR>0) {exit 1}}'
      - run:
          name: "Build & Test"
          command: make test
