version: 2

jobs:
  build-ut:
    docker:
      - image: golang:1.16
    working_directory: /go/src/github.com/pingcap/parser
    steps:
      - checkout
      - run: echo skip
  build-integration:
    docker:
      - image: golang:1.16
    working_directory: /go/src/github.com/pingcap/parser
    steps:
      - checkout
      - run: echo skip 

workflows:
  version: 2
  build_and_test:
    jobs:
    - build-ut
    - build-integration
