codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  status:
    project:
      default:
        threshold: 0.2
    patch:
      default:
        target: 0% # trial operation
    changes: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
