// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package redact_test

import "testing"

func TestRedact(t *testing.T) {
	RunRedact(t)
}

func TestDeRedact(t *testing.T) {
	RunDeRedact(t)
}

func TestRedactInitAndValueAndKey(t *testing.T) {
	RunRedactInitAndValueAndKey(t)
}
