// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package bootstraptest

import "testing"

func TestANSISQLMode(t *testing.T) {
	RunANSISQLMode(t)
}

func TestAnalyzeVersionUpgradeFrom300To500(t *testing.T) {
	RunAnalyzeVersionUpgradeFrom300To500(t)
}

func TestAnalyzeVersionUpgradeRewritesLegacyV1To2(t *testing.T) {
	RunAnalyzeVersionUpgradeRewritesLegacyV1To2(t)
}

func TestDDLTableCreateDDLNotifierTable(t *testing.T) {
	RunDDLTableCreateDDLNotifierTable(t)
}

func TestIndexJoinMultiPatternByUpgrade650To840(t *testing.T) {
	RunIndexJoinMultiPatternByUpgrade650To840(t)
}

func TestIndexMergeUpgradeFrom300To540(t *testing.T) {
	RunIndexMergeUpgradeFrom300To540(t)
}

func TestIndexMergeUpgradeFrom400To540Disable(t *testing.T) {
	RunIndexMergeUpgradeFrom400To540Disable(t)
}

func TestIndexMergeUpgradeFrom400To540Enable(t *testing.T) {
	RunIndexMergeUpgradeFrom400To540Enable(t)
}

func TestIssue17979_1(t *testing.T) {
	RunIssue17979_1(t)
}

func TestIssue17979_2(t *testing.T) {
	RunIssue17979_2(t)
}

func TestIssue20900_2(t *testing.T) {
	RunIssue20900_2(t)
}

func TestReferencesPrivilegeOnColumn(t *testing.T) {
	RunReferencesPrivilegeOnColumn(t)
}

func TestStmtSummary(t *testing.T) {
	RunStmtSummary(t)
}

func TestTiDBCostModelUpgradeFrom300To650(t *testing.T) {
	RunTiDBCostModelUpgradeFrom300To650(t)
}

func TestTiDBCostModelUpgradeFrom610To650(t *testing.T) {
	RunTiDBCostModelUpgradeFrom610To650(t)
}

func TestTiDBEnablePagingVariable(t *testing.T) {
	RunTiDBEnablePagingVariable(t)
}

func TestTiDBHistoryTableConsistent(t *testing.T) {
	RunTiDBHistoryTableConsistent(t)
}

func TestTiDBOptAdvancedJoinHintWhenUpgrading(t *testing.T) {
	RunTiDBOptAdvancedJoinHintWhenUpgrading(t)
}

func TestTiDBOptRangeMaxSizeWhenUpgrading(t *testing.T) {
	RunTiDBOptRangeMaxSizeWhenUpgrading(t)
}

func TestUpgradeClusteredIndexDefaultValue(t *testing.T) {
	RunUpgradeClusteredIndexDefaultValue(t)
}

func TestWriteDDLTableVersionToMySQLTiDB(t *testing.T) {
	RunWriteDDLTableVersionToMySQLTiDB(t)
}
