//! The fork's `metrics_schema` metric tables: the static definitions
//! extracted from `pkg/infoschema/metric_table_def.go`'s
//! `MetricTableMap` (oracle g-is: the fork pre-populates 642 metric
//! tables whose scans fail with `query metric error: pd unavailable`).

/// The metric table names with their label columns, in definition order.
pub static METRIC_TABLES: &[(&str, &[&str])] = &[
    ("tidb_query_duration", &["instance", "sql_type"]),
    ("tidb_qps", &["instance", "type", "result"]),
    ("tidb_qps_ideal", &[]),
    ("tidb_ops_statement", &["instance", "type"]),
    ("tidb_failed_query_opm", &["instance", "type"]),
    ("tidb_slow_query_duration", &["instance"]),
    ("tidb_slow_query_qps", &["instance", "sql_type"]),
    ("tidb_slow_query_cop_process_duration", &["instance"]),
    ("tidb_slow_query_cop_wait_duration", &["instance"]),
    ("tidb_ops_internal", &["instance"]),
    ("tidb_process_mem_usage", &["instance", "job"]),
    ("go_heap_mem_usage", &["instance", "job"]),
    ("process_cpu_usage", &["instance", "job"]),
    ("tiflash_process_cpu_usage", &["instance", "job"]),
    ("tiflash_cpu_quota", &["instance"]),
    ("tiflash_resource_manager_resource_unit", &[]),
    ("tidb_connection_count", &["instance"]),
    ("tidb_connection_idle_duration", &["instance", "in_txn"]),
    ("tidb_connection_idle_total_count", &["instance", "in_txn"]),
    ("tidb_connection_idle_total_time", &["instance", "in_txn"]),
    ("node_process_open_fd_count", &["instance", "job"]),
    ("goroutines_count", &["instance", "job"]),
    ("go_gc_duration", &["instance", "job"]),
    ("go_threads", &["instance", "job"]),
    ("go_gc_count", &["instance", "job"]),
    ("go_gc_cpu_usage", &["instance", "job"]),
    ("tidb_event_opm", &["instance", "type"]),
    ("tidb_keep_alive_opm", &["instance"]),
    ("tidb_prepared_statement_count", &["instance"]),
    ("tidb_time_jump_back_ops", &["instance"]),
    ("tidb_panic_count", &["instance"]),
    ("tidb_panic_count_total_count", &["instance"]),
    ("tidb_binlog_error_count", &["instance"]),
    ("tidb_binlog_error_total_count", &["instance"]),
    ("tidb_get_token_duration", &["instance"]),
    ("tidb_handshake_error_opm", &["instance"]),
    ("tidb_handshake_error_total_count", &["instance"]),
    ("tidb_transaction_ops", &["instance", "type", "sql_type"]),
    ("tidb_transaction_duration", &["instance", "type", "sql_type"]),
    ("tidb_transaction_retry_num", &["instance"]),
    ("tidb_transaction_statement_num", &["instance", "sql_type"]),
    ("tidb_transaction_retry_error_ops", &["instance", "type", "sql_type"]),
    ("tidb_transaction_retry_error_total_count", &["instance", "type", "sql_type"]),
    ("tidb_transaction_local_latch_wait_duration", &["instance"]),
    ("tidb_parse_duration", &["instance", "sql_type"]),
    ("tidb_compile_duration", &["instance", "sql_type"]),
    ("tidb_execute_duration", &["instance", "sql_type"]),
    ("tidb_expensive_executors_ops", &["instance", "type"]),
    ("tidb_query_using_plan_cache_ops", &["instance", "type"]),
    ("tidb_distsql_execution_duration", &["instance", "type"]),
    ("tidb_distsql_qps", &["instance", "type"]),
    ("tidb_distsql_partial_qps", &["instance"]),
    ("tidb_distsql_scan_key_num", &["instance"]),
    ("tidb_distsql_partial_scan_key_num", &["instance"]),
    ("tidb_distsql_partial_num", &["instance"]),
    ("tidb_cop_duration", &["instance"]),
    ("tidb_kv_backoff_duration", &["instance", "type"]),
    ("tidb_kv_backoff_ops", &["instance", "type"]),
    ("tidb_kv_region_error_ops", &["instance", "type"]),
    ("tidb_kv_region_error_total_count", &["instance", "type"]),
    ("tidb_lock_resolver_ops", &["instance", "type"]),
    ("tidb_lock_resolver_total_num", &["instance", "type"]),
    ("tidb_lock_cleanup_fail_ops", &["instance", "type"]),
    ("tidb_load_safepoint_fail_ops", &["instance", "type"]),
    ("tidb_kv_request_ops", &["instance", "type"]),
    ("tidb_kv_request_duration", &["instance", "type", "store"]),
    ("tidb_kv_txn_ops", &["instance"]),
    ("tidb_kv_write_num", &["instance"]),
    ("tidb_kv_write_size", &["instance"]),
    ("tidb_txn_region_num", &["instance"]),
    ("tidb_load_safepoint_ops", &["instance", "type"]),
    ("tidb_load_safepoint_total_num", &["instance", "type"]),
    ("tidb_kv_snapshot_ops", &["instance"]),
    ("pd_client_cmd_ops", &["instance", "type"]),
    ("pd_client_cmd_duration", &["instance", "type"]),
    ("pd_cmd_fail_ops", &["instance", "type"]),
    ("pd_cmd_fail_total_count", &["instance", "type"]),
    ("pd_request_rpc_ops", &["instance", "type"]),
    ("pd_request_rpc_duration", &["instance", "type"]),
    ("pd_tso_wait_duration", &["instance"]),
    ("pd_tso_rpc_duration", &["instance"]),
    ("pd_start_tso_wait_duration", &["instance"]),
    ("tidb_load_schema_duration", &["instance"]),
    ("tidb_load_schema_ops", &["instance", "type"]),
    ("tidb_schema_lease_error_opm", &["instance"]),
    ("tidb_schema_lease_error_total_count", &["instance"]),
    ("tidb_load_privilege_ops", &["instance", "type"]),
    ("tidb_ddl_duration", &["instance", "type"]),
    ("tidb_ddl_batch_add_index_duration", &["instance", "type"]),
    ("tidb_ddl_add_index_speed", &[]),
    ("tidb_ddl_waiting_jobs_num", &["instance", "type"]),
    ("tidb_ddl_meta_opm", &["instance", "type"]),
    ("tidb_ddl_worker_duration", &["instance", "type", "result", "action"]),
    ("tidb_ddl_deploy_syncer_duration", &["instance", "type", "result"]),
    ("tidb_owner_handle_syncer_duration", &["instance", "type", "result"]),
    ("tidb_ddl_update_self_version_duration", &["instance", "result"]),
    ("tidb_ddl_opm", &["instance", "type"]),
    ("tidb_statistics_auto_analyze_duration", &["instance"]),
    ("tidb_statistics_auto_analyze_ops", &["instance", "type"]),
    ("tidb_statistics_manual_analyze_ops", &["instance", "type"]),
    ("tidb_statistics_stats_inaccuracy_rate", &["instance"]),
    ("tidb_statistics_pseudo_estimation_ops", &["instance"]),
    ("tidb_statistics_pseudo_estimation_total_count", &["instance"]),
    ("tidb_statistics_update_stats_ops", &["instance", "type"]),
    ("tidb_statistics_update_stats_total_count", &["instance", "type"]),
    ("tidb_new_etcd_session_duration", &["instance", "type", "result"]),
    ("tidb_owner_watcher_ops", &["instance", "type", "result"]),
    ("tidb_auto_id_qps", &["instance"]),
    ("tidb_auto_id_request_duration", &["instance", "type"]),
    ("tidb_region_cache_ops", &["instance", "type", "result"]),
    ("tidb_meta_operation_duration", &["instance", "type", "result"]),
    ("tidb_gc_worker_action_opm", &["instance", "type"]),
    ("tidb_gc_duration", &["instance", "stage"]),
    ("tidb_gc_config", &["instance", "type"]),
    ("tidb_gc_fail_opm", &["instance", "type"]),
    ("tidb_gc_delete_range_fail_opm", &["instance", "type"]),
    ("tidb_gc_too_many_locks_opm", &[]),
    ("tidb_gc_action_result_opm", &["instance", "type"]),
    ("tidb_gc_delete_range_task_status", &["instance", "type", "result"]),
    ("tidb_gc_push_task_duration", &["instance", "type"]),
    ("tidb_batch_client_pending_req_count", &["instance", "store"]),
    ("tidb_batch_client_wait_duration", &["instance"]),
    ("tidb_batch_client_wait_conn_duration", &["instance"]),
    ("tidb_batch_client_wait_conn_total_count", &["instance"]),
    ("tidb_batch_client_wait_conn_total_time", &["instance"]),
    ("tidb_batch_client_unavailable_duration", &["instance"]),
    ("uptime", &["instance", "job"]),
    ("up", &["instance", "job"]),
    ("pd_role", &["instance"]),
    ("normal_stores", &["instance"]),
    ("abnormal_stores", &["instance", "type"]),
    ("pd_scheduler_config", &["type"]),
    ("pd_region_label_isolation_level", &["instance", "type"]),
    ("pd_label_distribution", &["name"]),
    ("pd_cluster_status", &["instance", "type"]),
    ("pd_cluster_metadata", &["instance", "type"]),
    ("pd_region_health", &["instance", "type"]),
    ("pd_schedule_operator", &["instance", "type", "event"]),
    ("pd_schedule_operator_total_num", &["instance", "type", "event"]),
    ("pd_operator_finish_duration", &["type"]),
    ("pd_operator_step_finish_duration", &["type"]),
    ("pd_scheduler_store_status", &["instance", "address", "store", "type"]),
    ("store_available_ratio", &["address", "store"]),
    ("store_size_amplification", &["address", "store"]),
    ("pd_scheduler_op_influence", &["instance", "scheduler", "store", "type"]),
    ("pd_scheduler_tolerant_resource", &["instance", "scheduler", "source", "target"]),
    ("pd_hotspot_status", &["instance", "address", "store", "type"]),
    ("pd_scheduler_status", &["instance", "kind", "type"]),
    ("pd_scheduler_balance_leader", &["instance", "address", "store", "type"]),
    ("pd_scheduler_balance_region", &["instance", "address", "store", "type"]),
    ("pd_balance_scheduler_status", &["instance", "name", "type"]),
    ("pd_checker_event_count", &["instance", "name", "type"]),
    ("pd_schedule_filter", &["instance", "scope", "store", "type"]),
    ("pd_scheduler_balance_direction", &["instance", "source", "target", "type"]),
    ("pd_schedule_store_limit", &["instance", "store", "type"]),
    ("pd_grpc_completed_commands_rate", &["instance", "grpc_method"]),
    ("pd_grpc_completed_commands_duration", &["instance", "grpc_method"]),
    ("pd_handle_transactions_rate", &["instance", "result"]),
    ("pd_handle_transactions_duration", &["instance", "result"]),
    ("etcd_wal_fsync_duration", &["instance"]),
    ("pd_peer_round_trip_duration", &["instance", "To"]),
    ("etcd_disk_wal_fsync_rate", &["instance"]),
    ("pd_server_etcd_state", &["instance", "type"]),
    ("pd_request_rpc_duration_avg", &["type"]),
    ("pd_region_heartbeat_duration", &["address", "store"]),
    ("pd_scheduler_region_heartbeat", &["instance", "address", "status", "store", "type"]),
    ("pd_region_syncer_status", &["instance", "type"]),
    ("resource_manager_resource_unit", &[]),
    ("tikv_engine_size", &["instance", "type", "db"]),
    ("tidb_ia_remote_read_segment_count", &["instance"]),
    ("tidb_ia_remote_read_segment_size", &["instance"]),
    ("tidb_ia_remote_read_segment_wait_time_histogram", &["instance", "le"]),
    ("tikv_store_size", &["instance", "type"]),
    ("tikv_cpu_quota", &["instance"]),
    ("tikv_thread_cpu", &["instance", "name"]),
    ("tikv_memory", &["instance"]),
    ("tikv_io_utilization", &["instance", "device"]),
    ("tikv_flow_mbps", &["instance", "type", "db"]),
    ("tikv_grpc_qps", &["instance", "type"]),
    ("tikv_grpc_errors", &["instance", "type"]),
    ("tikv_grpc_error_total_count", &["instance", "type"]),
    ("tikv_critical_error", &["instance", "type"]),
    ("tikv_critical_error_total_count", &["instance", "type"]),
    ("tikv_pd_heartbeat", &["instance", "type"]),
    ("tikv_region_count", &["instance", "type"]),
    ("tikv_scheduler_is_busy", &["instance", "db", "type", "stage"]),
    ("tikv_scheduler_is_busy_total_count", &["instance", "db", "type", "stage"]),
    ("tikv_channel_full", &["instance", "db", "type"]),
    ("tikv_channel_full_total_count", &["instance", "db", "type"]),
    ("tikv_coprocessor_is_busy", &["instance", "db"]),
    ("tikv_coprocessor_is_busy_total_count", &["instance", "db"]),
    ("tikv_engine_write_stall", &["instance", "db"]),
    ("tikv_server_report_failures", &["instance", "store_id", "type"]),
    ("tikv_server_report_failures_total_count", &["instance", "store_id", "type"]),
    ("tikv_storage_async_requests", &["instance", "status", "type"]),
    ("tikv_storage_async_requests_total_count", &["instance", "status", "type"]),
    ("tikv_scheduler_stage", &["instance", "stage", "type"]),
    ("tikv_scheduler_stage_total_num", &["instance", "stage", "type"]),
    ("tikv_coprocessor_request_error", &["instance", "reason"]),
    ("tikv_coprocessor_request_error_total_count", &["instance", "reason"]),
    ("tikv_region_change", &["instance", "type"]),
    ("tikv_leader_missing", &["instance"]),
    ("tikv_active_written_leaders", &["instance"]),
    ("tikv_approximate_region_size", &["instance"]),
    ("tikv_approximate_avg_region_size", &["instance"]),
    ("tikv_approximate_region_size_histogram", &["instance"]),
    ("tikv_region_average_written_bytes", &["instance"]),
    ("tikv_region_written_bytes", &["instance"]),
    ("tikv_region_average_written_keys", &["instance"]),
    ("tikv_region_written_keys", &["instance"]),
    ("tikv_request_batch_avg", &["instance", "type"]),
    ("tikv_request_batch_ratio", &["instance", "type"]),
    ("tikv_request_batch_size_avg", &["instance", "type"]),
    ("tikv_request_batch_size", &["instance", "type"]),
    ("tikv_grpc_message_duration", &["instance", "type"]),
    ("tikv_average_grpc_messge_duration", &["instance", "type"]),
    ("tikv_grpc_req_batch_size", &["instance"]),
    ("tikv_grpc_resp_batch_size", &["instance"]),
    ("tikv_grpc_avg_req_batch_size", &[]),
    ("tikv_grpc_avg_resp_batch_size", &[]),
    ("tikv_raft_message_batch_size", &["instance"]),
    ("tikv_raft_message_avg_batch_size", &[]),
    ("tikv_pd_request_ops", &["instance", "type"]),
    ("tikv_pd_request_duration", &["instance", "type"]),
    ("tikv_pd_request_total_count", &["instance", "type"]),
    ("tikv_pd_request_total_time", &["instance", "type"]),
    ("tikv_pd_request_avg_duration", &["instance", "type"]),
    ("tikv_pd_heartbeats", &["instance", "type"]),
    ("tikv_pd_validate_peers", &["instance", "type"]),
    ("tikv_raftstore_apply_log_avg_duration", &["instance"]),
    ("tikv_raftstore_apply_log_duration", &["instance"]),
    ("tikv_raftstore_append_log_avg_duration", &["instance"]),
    ("tikv_raftstore_append_log_duration", &["instance"]),
    ("tikv_raftstore_commit_log_avg_duration", &[]),
    ("tikv_raftstore_commit_log_duration", &["instance"]),
    ("tikv_ready_handled", &["instance"]),
    ("tikv_raftstore_process_handled", &["instance", "type"]),
    ("tikv_raftstore_process_duration", &["instance", "type"]),
    ("tikv_raft_store_events_duration", &["instance", "type"]),
    ("tikv_raft_sent_messages", &["instance", "type"]),
    ("tikv_raft_sent_messages_total_num", &["instance", "type"]),
    ("tikv_flush_messages", &["instance"]),
    ("tikv_flush_messages_total_num", &["instance"]),
    ("tikv_receive_messages", &["instance"]),
    ("tikv_receive_messages_total_num", &["instance"]),
    ("tikv_raft_dropped_messages", &["instance", "type"]),
    ("tikv_raft_dropped_messages_total", &["instance", "type"]),
    ("tikv_raft_proposals_per_ready", &["instance"]),
    ("tikv_raft_proposals", &["instance", "type"]),
    ("tikv_raft_proposals_total_num", &["instance", "type"]),
    ("tikv_raftstore_propose_wait_duration", &["instance"]),
    ("tikv_propose_avg_wait_duration", &["instance"]),
    ("tikv_raftstore_apply_wait_duration", &["instance"]),
    ("tikv_apply_avg_wait_duration", &["instance"]),
    ("tikv_raft_log_speed", &["instance"]),
    ("tikv_admin_apply", &["instance", "type", "status"]),
    ("tikv_check_split", &["instance", "type"]),
    ("tikv_check_split_duration", &["instance"]),
    ("tikv_local_reader_reject_requests", &["instance", "reason"]),
    ("tikv_local_reader_execute_requests", &["instance"]),
    ("tikv_storage_command_ops", &["instance", "type"]),
    ("tikv_storage_async_request_duration", &["instance", "type"]),
    ("tikv_storage_async_request_avg_duration", &["instance", "type"]),
    ("tikv_scheduler_writing_bytes", &["instance"]),
    ("tikv_scheduler_priority_commands", &["instance", "priority"]),
    ("tikv_scheduler_pending_commands", &["instance"]),
    ("tikv_scheduler_command_duration", &["instance", "type"]),
    ("tikv_scheduler_command_avg_duration", &["instance", "type"]),
    ("tikv_scheduler_latch_wait_duration", &["instance", "type"]),
    ("tikv_scheduler_latch_wait_avg_duration", &["instance", "type"]),
    ("tikv_scheduler_processing_read_duration", &["instance", "type"]),
    ("tikv_scheduler_processing_read_total_count", &["instance", "type"]),
    ("tikv_scheduler_processing_read_total_time", &["instance", "type"]),
    ("tikv_scheduler_keys_read", &["instance", "type"]),
    ("tikv_scheduler_keys_read_avg", &["instance", "type"]),
    ("tikv_scheduler_keys_written", &["instance", "type"]),
    ("tikv_scheduler_keys_written_avg", &["instance", "type"]),
    ("tikv_scheduler_scan_details", &["instance", "tag", "req", "cf"]),
    ("tikv_scheduler_scan_details_total_num", &["instance", "tag", "req", "cf"]),
    ("tikv_mvcc_versions", &["instance"]),
    ("tikv_mvcc_delete_versions", &["instance"]),
    ("tikv_gc_tasks_ops", &["instance", "task"]),
    ("tikv_gc_skipped_tasks", &["instance", "task"]),
    ("tikv_gc_fail_tasks", &["instance", "task"]),
    ("tikv_gc_too_busy", &["instance"]),
    ("tikv_gc_tasks_duration", &["instance", "task"]),
    ("tikv_gc_tasks_avg_duration", &["instance", "task"]),
    ("tikv_gc_keys", &["instance", "tag", "cf"]),
    ("tikv_gc_keys_total_num", &["instance", "tag", "cf"]),
    ("tikv_gc_speed", &[]),
    ("tikv_auto_gc_working", &["instance", "state"]),
    ("tikv_client_task_progress", &["result", "type"]),
    ("tikv_auto_gc_progress", &["instance"]),
    ("tikv_auto_gc_safepoint", &["instance"]),
    ("tikv_send_snapshot_duration", &["instance"]),
    ("tikv_handle_snapshot_duration", &["instance", "type"]),
    ("tikv_snapshot_state_count", &["instance", "type"]),
    ("tikv_snapshot_state_total_count", &["instance", "type"]),
    ("tikv_snapshot_size", &["instance"]),
    ("tikv_snapshot_kv_count", &["instance"]),
    ("tikv_worker_handled_tasks", &["instance", "name"]),
    ("tikv_worker_handled_tasks_total_num", &["instance", "name"]),
    ("tikv_worker_pending_tasks", &["instance", "name"]),
    ("tikv_worker_pending_tasks_total_num", &["instance", "name"]),
    ("tikv_futurepool_handled_tasks", &["instance", "name"]),
    ("tikv_futurepool_handled_tasks_total_num", &["instance", "name"]),
    ("tikv_futurepool_pending_tasks", &["instance", "name"]),
    ("tikv_futurepool_pending_tasks_total_num", &["instance", "name"]),
    ("tikv_cop_request_durations", &["instance", "req"]),
    ("tikv_cop_request_duration", &["instance", "req"]),
    ("tikv_cop_requests_ops", &["instance", "req"]),
    ("tikv_cop_scan_keys_num", &["instance", "req"]),
    ("tikv_cop_kv_cursor_operations", &["instance", "req"]),
    ("tikv_cop_total_rocksdb_perf_statistics", &["instance", "req", "metric"]),
    ("tikv_cop_total_response_size_per_seconds", &["instance"]),
    ("tikv_cop_handle_duration", &["instance", "req"]),
    ("tikv_cop_wait_duration", &["instance", "req", "type"]),
    ("tikv_cop_dag_requests_ops", &["instance", "vec_type"]),
    ("tikv_cop_dag_executors_ops", &["instance", "type"]),
    ("tikv_cop_scan_details", &["instance", "tag", "req", "cf"]),
    ("tikv_cop_scan_details_total", &["instance", "tag", "req", "cf"]),
    ("tikv_threads_state", &["instance", "state"]),
    ("tikv_threads_io", &["instance", "io", "name"]),
    ("tikv_thread_voluntary_context_switches", &["instance", "name"]),
    ("tikv_thread_nonvoluntary_context_switches", &["instance", "name"]),
    ("tikv_engine_get_cpu_cache_operations", &["instance", "type", "db"]),
    ("tikv_engine_get_block_cache_operations", &["instance", "type", "db"]),
    ("tikv_engine_get_memtable_operations", &["instance", "type", "db"]),
    ("tikv_engine_max_get_duration", &["instance", "type", "db"]),
    ("tikv_engine_avg_get_duration", &["instance", "type", "db"]),
    ("tikv_engine_seek_operations", &["instance", "type", "db"]),
    ("tikv_engine_max_seek_duration", &["instance", "type", "db"]),
    ("tikv_engine_avg_seek_duration", &["instance", "type", "db"]),
    ("tikv_engine_write_operations", &["instance", "type", "db"]),
    ("tikv_engine_write_duration", &["instance", "type", "db"]),
    ("tikv_engine_write_max_duration", &["instance", "type", "db"]),
    ("tikv_engine_wal_sync_operations", &["instance", "db"]),
    ("tikv_wal_sync_max_duration", &["instance", "type", "db"]),
    ("tikv_wal_sync_duration", &["instance", "type"]),
    ("tikv_compaction_operations", &["instance", "type", "db"]),
    ("tikv_compaction_max_duration", &["instance", "type", "db"]),
    ("tikv_compaction_duration", &["instance", "type", "db"]),
    ("tikv_sst_read_max_duration", &["instance", "type", "db"]),
    ("tikv_sst_read_duration", &["instance", "type", "db"]),
    ("tikv_write_stall_max_duration", &["instance", "type", "db"]),
    ("tikv_write_stall_avg_duration", &["instance", "type", "db"]),
    ("tikv_memtable_size", &["instance", "cf", "type", "db"]),
    ("tikv_memtable_hit", &["instance", "db"]),
    ("tikv_block_cache_size", &["instance", "cf", "db"]),
    ("tikv_block_all_cache_hit", &["instance", "db"]),
    ("tikv_block_data_cache_hit", &["instance", "db"]),
    ("tikv_block_filter_cache_hit", &["instance", "db"]),
    ("tikv_block_index_cache_hit", &["instance", "db"]),
    ("tikv_block_bloom_prefix_cache_hit", &["instance", "db"]),
    ("tikv_corrrput_keys_flow", &["instance", "db", "cf"]),
    ("tikv_total_keys", &["instance", "db", "cf"]),
    ("tikv_per_read_max_bytes", &["instance", "type", "db"]),
    ("tikv_per_read_avg_bytes", &["instance", "type", "db"]),
    ("tikv_per_write_max_bytes", &["instance", "type", "db"]),
    ("tikv_per_write_avg_bytes", &["instance", "type", "db"]),
    ("tikv_engine_compaction_flow_bytes", &["instance", "type", "db"]),
    ("tikv_compaction_pending_bytes", &["instance", "cf", "db"]),
    ("tikv_read_amplication", &["instance", "db"]),
    ("tikv_compression_ratio", &["instance", "level", "db"]),
    ("tikv_number_of_snapshots", &["instance", "db"]),
    ("tikv_oldest_snapshots_duration", &["instance", "db"]),
    ("tikv_number_files_at_each_level", &["instance", "cf", "level", "db"]),
    ("tikv_ingest_sst_duration", &["instance", "db"]),
    ("tikv_ingest_sst_avg_duration", &["instance"]),
    ("tikv_stall_conditions_changed_of_each_cf", &["instance", "cf", "type", "db"]),
    ("tikv_write_stall_reason", &["instance", "type", "db"]),
    ("tikv_compaction_reason", &["instance", "cf", "reason", "db"]),
    ("tikv_engine_blob_key_max_size", &["instance", "type", "db"]),
    ("tikv_engine_blob_key_avg_size", &["instance", "type", "db"]),
    ("tikv_engine_blob_value_avg_size", &["instance", "type", "db"]),
    ("tikv_engine_blob_value_max_size", &["instance", "type", "db"]),
    ("tikv_engine_blob_seek_duration", &["instance", "type", "db"]),
    ("tikv_engine_blob_seek_operations", &["instance", "type", "db"]),
    ("tikv_engine_blob_get_duration", &["instance", "type", "db"]),
    ("tikv_engine_blob_bytes_flow", &["instance", "type", "db"]),
    ("tikv_engine_blob_file_read_duration", &["instance", "type", "db"]),
    ("tikv_engine_blob_file_write_duration", &["instance", "type", "db"]),
    ("tikv_engine_blob_file_sync_operations", &["instance"]),
    ("tikv_engine_blob_file_sync_duration", &["instance", "type", "db"]),
    ("tikv_engine_blob_file_count", &["instance", "db"]),
    ("tikv_engine_blob_file_size", &["instance", "db"]),
    ("tikv_engine_blob_gc_file", &["instance", "type", "db"]),
    ("tikv_engine_blob_gc_duration", &["instance", "type", "db"]),
    ("tikv_engine_blob_gc_bytes_flow", &["instance", "type", "db"]),
    ("tikv_engine_blob_gc_keys_flow", &["instance", "type", "db"]),
    ("tikv_engine_live_blob_size", &["instance", "db"]),
    ("tikv_lock_manager_handled_tasks", &["instance", "type"]),
    ("tikv_lock_manager_waiter_lifetime_duration", &["instance"]),
    ("tikv_lock_manager_waiter_lifetime_avg_duration", &["instance", "type"]),
    ("tikv_lock_manager_wait_table", &["instance", "type"]),
    ("tikv_lock_manager_deadlock_detect_duration", &["instance"]),
    ("tikv_lock_manager_deadlock_detect_avg_duration", &["instance"]),
    ("tikv_lock_manager_detect_error", &["instance", "type"]),
    ("tikv_lock_manager_detect_error_total_count", &["instance", "type"]),
    ("tikv_lock_manager_deadlock_detector_leader", &["instance"]),
    ("tikv_allocator_stats", &["instance", "type"]),
    ("tikv_backup_range_size", &["instance", "cf"]),
    ("tikv_backup_duration", &["instance"]),
    ("tikv_backup_avg_duration", &["instance"]),
    ("tikv_backup_flow", &["instance"]),
    ("tikv_disk_read_bytes", &["instance", "device"]),
    ("tikv_disk_write_bytes", &["instance", "device"]),
    ("tikv_backup_range_duration", &["instance", "type"]),
    ("tikv_backup_range_avg_duration", &["instance", "type"]),
    ("tikv_backup_errors", &["instance", "error"]),
    ("tikv_backup_errors_total_count", &["instance", "error"]),
    ("node_virtual_cpus", &["instance"]),
    ("node_total_memory", &["instance"]),
    ("node_memory_available", &["instance"]),
    ("node_memory_usage", &["instance"]),
    ("node_memory_swap_used", &["instance"]),
    ("node_uptime", &["instance"]),
    ("node_load1", &["instance"]),
    ("node_load5", &["instance"]),
    ("node_load15", &["instance"]),
    ("node_kernel_interrupts", &["instance"]),
    ("node_kernel_forks", &["instance"]),
    ("node_kernel_context_switches", &["instance"]),
    ("node_cpu_usage", &["instance", "mode"]),
    ("node_memory_free", &["instance"]),
    ("node_memory_buffers", &["instance"]),
    ("node_memory_cached", &["instance"]),
    ("node_memory_active", &["instance"]),
    ("node_memory_inactive", &["instance"]),
    ("node_memory_writeback", &["instance"]),
    ("node_memory_writeback_tmp", &["instance"]),
    ("node_memory_dirty", &["instance"]),
    ("node_memory_shared", &["instance"]),
    ("node_memory_mapped", &["instance"]),
    ("node_disk_size", &["instance", "device", "fstype", "mountpoint"]),
    ("node_disk_available_size", &["instance", "device", "fstype", "mountpoint"]),
    ("node_disk_state", &["instance", "device", "fstype", "mountpoint"]),
    ("node_disk_io_util", &["instance", "device"]),
    ("node_disk_iops", &["instance", "device"]),
    ("node_disk_write_latency", &["instance", "device"]),
    ("node_disk_read_latency", &["instance", "device"]),
    ("node_disk_throughput", &["instance", "device"]),
    ("node_disk_usage", &["instance", "device"]),
    ("node_file_descriptor_allocated", &["instance"]),
    ("node_network_in_drops", &["instance", "device"]),
    ("node_network_out_drops", &["instance", "device"]),
    ("node_network_in_errors", &["instance", "device"]),
    ("node_network_in_errors_total_count", &["instance", "device"]),
    ("node_network_out_errors", &["instance", "device"]),
    ("node_network_out_errors_total_count", &["instance", "device"]),
    ("node_network_in_traffic", &["instance", "device"]),
    ("node_network_out_traffic", &["instance", "device"]),
    ("node_network_in_packets", &["instance", "device"]),
    ("node_network_out_packets", &["instance", "device"]),
    ("node_network_interface_speed", &["instance", "device"]),
    ("node_network_utilization_in_hourly", &["instance", "device"]),
    ("node_network_utilization_out_hourly", &["instance", "device"]),
    ("node_tcp_in_use", &["instance"]),
    ("node_tcp_segments_retransmitted", &["instance"]),
    ("node_tcp_connections", &["instance"]),
    ("node_processes_running", &["instance"]),
    ("node_processes_blocked", &["instance"]),
    ("etcd_wal_fsync_total_count", &["instance"]),
    ("etcd_wal_fsync_total_time", &["instance"]),
    ("pd_client_cmd_total_count", &["instance", "type"]),
    ("pd_client_cmd_total_time", &["instance", "type"]),
    ("pd_grpc_completed_commands_total_count", &["instance", "grpc_method"]),
    ("pd_grpc_completed_commands_total_time", &["instance", "grpc_method"]),
    ("pd_request_rpc_total_count", &["instance", "type"]),
    ("pd_request_rpc_total_time", &["instance", "type"]),
    ("pd_handle_transactions_total_count", &["instance", "result"]),
    ("pd_handle_transactions_total_time", &["instance", "result"]),
    ("pd_operator_finish_total_count", &["type"]),
    ("pd_operator_finish_total_time", &["type"]),
    ("pd_operator_step_finish_total_count", &["type"]),
    ("pd_operator_step_finish_total_time", &["type"]),
    ("pd_peer_round_trip_total_count", &["instance", "To"]),
    ("pd_peer_round_trip_total_time", &["instance", "To"]),
    ("pd_region_heartbeat_total_count", &["address", "store"]),
    ("pd_region_heartbeat_total_time", &["address", "store"]),
    ("pd_start_tso_wait_total_count", &["instance"]),
    ("pd_start_tso_wait_total_time", &["instance"]),
    ("pd_tso_rpc_total_count", &["instance"]),
    ("pd_tso_rpc_total_time", &["instance"]),
    ("pd_tso_wait_total_count", &["instance"]),
    ("pd_tso_wait_total_time", &["instance"]),
    ("tidb_auto_id_request_total_count", &["instance", "type"]),
    ("tidb_auto_id_request_total_time", &["instance", "type"]),
    ("tidb_batch_client_unavailable_total_count", &["instance"]),
    ("tidb_batch_client_unavailable_total_time", &["instance"]),
    ("tidb_batch_client_wait_total_count", &["instance"]),
    ("tidb_batch_client_wait_total_time", &["instance"]),
    ("tidb_compile_total_count", &["instance", "sql_type"]),
    ("tidb_compile_total_time", &["instance", "sql_type"]),
    ("tidb_cop_total_count", &["instance"]),
    ("tidb_cop_total_time", &["instance"]),
    ("tidb_ddl_batch_add_index_total_count", &["instance", "type"]),
    ("tidb_ddl_batch_add_index_total_time", &["instance", "type"]),
    ("tidb_ddl_deploy_syncer_total_count", &["instance", "type", "result"]),
    ("tidb_ddl_deploy_syncer_total_time", &["instance", "type", "result"]),
    ("tidb_ddl_total_count", &["instance", "type"]),
    ("tidb_ddl_total_time", &["instance", "type"]),
    ("tidb_ddl_update_self_version_total_count", &["instance", "result"]),
    ("tidb_ddl_update_self_version_total_time", &["instance", "result"]),
    ("tidb_ddl_worker_total_count", &["instance", "type", "result", "action"]),
    ("tidb_ddl_worker_total_time", &["instance", "type", "result", "action"]),
    ("tidb_distsql_execution_total_count", &["instance", "type"]),
    ("tidb_distsql_execution_total_time", &["instance", "type"]),
    ("tidb_distsql_copr_cache", &["instance", "type"]),
    ("tidb_execute_total_count", &["instance", "sql_type"]),
    ("tidb_execute_total_time", &["instance", "sql_type"]),
    ("tidb_gc_push_task_total_count", &["instance", "type"]),
    ("tidb_gc_push_task_total_time", &["instance", "type"]),
    ("tidb_gc_total_count", &["instance", "stage"]),
    ("tidb_gc_total_time", &["instance", "stage"]),
    ("tidb_get_token_total_count", &["instance"]),
    ("tidb_get_token_total_time", &["instance"]),
    ("tidb_kv_backoff_total_count", &["instance", "type"]),
    ("tidb_kv_backoff_total_time", &["instance", "type"]),
    ("tidb_kv_request_total_count", &["instance", "type", "store"]),
    ("tidb_kv_request_total_time", &["instance", "type", "store"]),
    ("tidb_load_schema_total_count", &["instance"]),
    ("tidb_load_schema_total_time", &["instance"]),
    ("tidb_meta_operation_total_count", &["instance", "type", "result"]),
    ("tidb_meta_operation_total_time", &["instance", "type", "result"]),
    ("tidb_new_etcd_session_total_count", &["instance", "type", "result"]),
    ("tidb_new_etcd_session_total_time", &["instance", "type", "result"]),
    ("tidb_owner_handle_syncer_total_count", &["instance", "type", "result"]),
    ("tidb_owner_handle_syncer_total_time", &["instance", "type", "result"]),
    ("tidb_parse_total_count", &["instance", "sql_type"]),
    ("tidb_parse_total_time", &["instance", "sql_type"]),
    ("tidb_query_total_count", &["instance", "sql_type"]),
    ("tidb_query_total_time", &["instance", "sql_type"]),
    ("tidb_txn_cmd_duration", &["instance", "type"]),
    ("tidb_txn_cmd_total_count", &["instance", "type"]),
    ("tidb_txn_cmd_total_time", &["instance", "type"]),
    ("tidb_slow_query_cop_process_total_count", &["instance"]),
    ("tidb_slow_query_cop_process_total_time", &["instance"]),
    ("tidb_slow_query_cop_wait_total_count", &["instance"]),
    ("tidb_slow_query_cop_wait_total_time", &["instance"]),
    ("tidb_slow_query_total_count", &["instance"]),
    ("tidb_slow_query_total_time", &["instance"]),
    ("tidb_statistics_auto_analyze_total_count", &["instance"]),
    ("tidb_statistics_auto_analyze_total_time", &["instance"]),
    ("tidb_transaction_local_latch_wait_total_count", &["instance"]),
    ("tidb_transaction_local_latch_wait_total_time", &["instance"]),
    ("tidb_transaction_total_count", &["instance", "type", "sql_type"]),
    ("tidb_transaction_total_time", &["instance", "type", "sql_type"]),
    ("tidb_server_maxprocs", &["instance"]),
    ("tikv_raftstore_append_log_total_count", &["instance"]),
    ("tikv_raftstore_append_log_total_time", &["instance"]),
    ("tikv_raftstore_apply_log_total_count", &["instance"]),
    ("tikv_raftstore_apply_log_total_time", &["instance"]),
    ("tikv_raftstore_apply_wait_total_count", &["instance"]),
    ("tikv_raftstore_apply_wait_total_time", &["instance"]),
    ("tikv_backup_range_total_count", &["instance", "type"]),
    ("tikv_backup_range_total_time", &["instance", "type"]),
    ("tikv_backup_total_count", &["instance"]),
    ("tikv_backup_total_time", &["instance"]),
    ("tikv_check_split_total_count", &["instance"]),
    ("tikv_check_split_total_time", &["instance"]),
    ("tikv_raftstore_commit_log_total_count", &["instance"]),
    ("tikv_raftstore_commit_log_total_time", &["instance"]),
    ("tikv_cop_handle_total_count", &["instance", "req"]),
    ("tikv_cop_handle_total_time", &["instance", "req"]),
    ("tikv_cop_request_total_count", &["instance", "req"]),
    ("tikv_cop_request_total_time", &["instance", "req"]),
    ("tikv_cop_wait_total_count", &["instance", "req", "type"]),
    ("tikv_cop_wait_total_time", &["instance", "req", "type"]),
    ("tikv_raft_store_events_total_count", &["instance", "type"]),
    ("tikv_raft_store_events_total_time", &["instance", "type"]),
    ("tikv_gc_tasks_total_count", &["instance", "task"]),
    ("tikv_gc_tasks_total_time", &["instance", "task"]),
    ("tikv_grpc_message_total_count", &["instance", "type"]),
    ("tikv_grpc_message_total_time", &["instance", "type"]),
    ("tikv_handle_snapshot_total_count", &["instance", "type"]),
    ("tikv_handle_snapshot_total_time", &["instance", "type"]),
    ("tikv_ingest_sst_total_count", &["instance", "db"]),
    ("tikv_ingest_sst_total_time", &["instance", "db"]),
    ("tikv_lock_manager_deadlock_detect_total_count", &["instance"]),
    ("tikv_lock_manager_deadlock_detect_total_time", &["instance"]),
    ("tikv_lock_manager_waiter_lifetime_total_count", &["instance"]),
    ("tikv_lock_manager_waiter_lifetime_total_time", &["instance"]),
    ("tikv_raftstore_process_total_count", &["instance", "type"]),
    ("tikv_raftstore_process_total_time", &["instance", "type"]),
    ("tikv_raftstore_propose_wait_total_count", &["instance"]),
    ("tikv_raftstore_propose_wait_total_time", &["instance"]),
    ("tikv_scheduler_command_total_count", &["instance", "type"]),
    ("tikv_scheduler_command_total_time", &["instance", "type"]),
    ("tikv_scheduler_latch_wait_total_count", &["instance", "type"]),
    ("tikv_scheduler_latch_wait_total_time", &["instance", "type"]),
    ("tikv_send_snapshot_total_count", &["instance"]),
    ("tikv_send_snapshot_total_time", &["instance"]),
    ("tikv_storage_async_request_total_count", &["instance", "type"]),
    ("tikv_storage_async_request_total_time", &["instance", "type"]),
    ("tidb_distsql_partial_num_total_count", &["instance"]),
    ("tidb_distsql_partial_scan_key_num_total_count", &["instance"]),
    ("tidb_distsql_partial_scan_key_total_num", &["instance"]),
    ("tidb_distsql_partial_total_num", &["instance"]),
    ("tidb_distsql_scan_key_num_total_count", &["instance"]),
    ("tidb_distsql_scan_key_total_num", &["instance"]),
    ("tidb_kv_write_num_total_count", &["instance"]),
    ("tidb_kv_write_size_total_count", &["instance"]),
    ("tidb_kv_write_total_num", &["instance"]),
    ("tidb_kv_write_total_size", &["instance"]),
    ("tidb_statistics_stats_inaccuracy_rate_total_count", &["instance"]),
    ("tidb_statistics_stats_inaccuracy_total_rate", &["instance"]),
    ("tidb_transaction_retry_num_total_count", &["instance"]),
    ("tidb_transaction_retry_total_num", &["instance"]),
    ("tidb_transaction_statement_num_total_count", &["instance", "sql_type"]),
    ("tidb_transaction_statement_total_num", &["instance", "sql_type"]),
    ("tidb_txn_region_num_total_count", &["instance"]),
    ("tidb_txn_region_total_num", &["instance"]),
    ("tikv_approximate_region_size_total_count", &["instance"]),
    ("tikv_approximate_region_total_size", &["instance"]),
    ("tikv_backup_range_size_total_count", &["instance", "cf"]),
    ("tikv_backup_range_total_size", &["instance", "cf"]),
    ("tikv_cop_kv_cursor_operations_total_count", &["instance", "req"]),
    ("tikv_cop_scan_keys_total_num", &["instance", "req"]),
    ("tikv_cop_total_response_total_size", &["instance"]),
    ("tikv_grpc_req_batch_size_total_count", &["instance"]),
    ("tikv_grpc_req_batch_total_size", &["instance"]),
    ("tikv_grpc_resp_batch_size_total_count", &["instance"]),
    ("tikv_grpc_resp_batch_total_size", &["instance"]),
    ("tikv_raft_message_batch_size_total_count", &["instance"]),
    ("tikv_raft_message_batch_total_size", &["instance"]),
    ("tikv_raft_proposals_per_ready_total_count", &["instance"]),
    ("tikv_raft_proposals_per_total_ready", &["instance"]),
    ("tikv_request_batch_ratio_total_count", &["instance", "type"]),
    ("tikv_request_batch_size_total_count", &["instance", "type"]),
    ("tikv_request_batch_total_ratio", &["instance", "type"]),
    ("tikv_request_batch_total_size", &["instance", "type"]),
    ("tikv_scheduler_keys_read_total_count", &["instance", "type"]),
    ("tikv_scheduler_keys_total_read", &["instance", "type"]),
    ("tikv_scheduler_keys_total_written", &["instance", "type"]),
    ("tikv_scheduler_keys_written_total_count", &["instance", "type"]),
    ("tikv_snapshot_kv_count_total_count", &["instance"]),
    ("tikv_snapshot_kv_total_count", &["instance"]),
    ("tikv_snapshot_size_total_count", &["instance"]),
    ("tikv_snapshot_total_size", &["instance"]),
    ("tikv_config_rocksdb", &["instance", "cf", "name"]),
    ("tikv_config_raftstore", &["instance", "name"]),
];

/// The label columns for one metric table, or `None` for an unknown name.
pub fn metric_table_labels(name: &str) -> Option<&'static [&'static str]> {
    METRIC_TABLES.iter().find(|(table, _)| *table == name).map(|(_, labels)| *labels)
}
