load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "dumpservice",
    srcs = [
        "client.go",
        "docs.go",
    ],
    importpath = "github.com/pingcap/tidb/dumpling/dumpservice",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_pingcap_errors//:errors",
        "@com_github_prometheus_client_model//go",
        "@com_github_prometheus_common//expfmt",
        "@org_golang_x_net//http2",
    ],
)

go_test(
    name = "dumpservice_test",
    timeout = "short",
    srcs = ["client_test.go"],
    embed = [":dumpservice"],
    flaky = True,
    shard_count = 3,
    deps = [
        "@com_github_stretchr_testify//require",
        "@org_golang_x_net//http2",
    ],
)
