load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "generator_lib",
    srcs = ["main.go"],
    importpath = "github.com/pingcap/tidb/pkg/expression/matchagainst/generator",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "generator",
    embed = [":generator_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "generator_test",
    srcs = ["main_test.go"],
    embed = [":generator_lib"],
)
