[package]
name = "tidb-util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Complete TiDB utility package transcreations shared by the Rust SQL node."

[lints]
workspace = true

[features]
default = []
enableassert = []
intest = []
race = []

[dependencies]
aes.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
crc32fast.workspace = true
des.workspace = true
getrandom.workspace = true
num-traits.workspace = true
regex.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
tidb-error = { path = "../tidb-error" }
tracing = "0.1"
tidb-hack = { path = "../tidb-hack" }

[dev-dependencies]
standard-fastrand = { package = "fastrand", version = "2" }

[[bench]]
name = "encrypt"
harness = false

[[bench]]
name = "fastrand"
harness = false

[[bench]]
name = "sqlescape"
harness = false

[[bench]]
name = "zeropool"
harness = false
