[package]
name = "tidb-util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Complete TiDB utility package transcreations shared by the Rust SQL node."

[lints]
workspace = true

[features]
default = []
enableassert = []
intest = []

[dependencies]
aes.workspace = true
chrono.workspace = true
crc32fast.workspace = true
getrandom.workspace = true
num-traits.workspace = true
tidb-hack = { path = "../tidb-hack" }

[[bench]]
name = "encrypt"
harness = false

[[bench]]
name = "sqlescape"
harness = false

[[bench]]
name = "zeropool"
harness = false
