name = "ipwhitelist"
kind = "Audit"
description = "The IP Whitelist Plugin"
version = "1"
license = ""
sysVars = []
validate = "Validate"
onInit = "OnInit"
onShutdown = "OnShutdown"
export = [
    {extPoint="OnConnectionEvent", impl="OnConnectionEvent"}
]
