// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package casetest_test

import "testing"

func TestGroupNDVs(t *testing.T) {
	RunGroupNDVs(t)
}

func TestNDVGroupCols(t *testing.T) {
	RunNDVGroupCols(t)
}
