// Copyright 2026 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");

//! `ALL_CODES` entries, part 1 of 1 (see `errcode/mod.rs`).

use super::consts_1::*;
use super::consts_2::*;

pub(super) const ALL_CODES_1: &[(&str, u16)] = &[
    ("ErrErrorFirst", ErrErrorFirst),
    ("ErrHashchk", ErrHashchk),
    ("ErrNisamchk", ErrNisamchk),
    ("ErrNo", ErrNo),
    ("ErrYes", ErrYes),
    ("ErrCantCreateFile", ErrCantCreateFile),
    ("ErrCantCreateTable", ErrCantCreateTable),
    ("ErrCantCreateDB", ErrCantCreateDB),
    ("ErrDBCreateExists", ErrDBCreateExists),
    ("ErrDBDropExists", ErrDBDropExists),
    ("ErrDBDropDelete", ErrDBDropDelete),
    ("ErrDBDropRmdir", ErrDBDropRmdir),
    ("ErrCantDeleteFile", ErrCantDeleteFile),
    ("ErrCantFindSystemRec", ErrCantFindSystemRec),
    ("ErrCantGetStat", ErrCantGetStat),
    ("ErrCantGetWd", ErrCantGetWd),
    ("ErrCantLock", ErrCantLock),
    ("ErrCantOpenFile", ErrCantOpenFile),
    ("ErrFileNotFound", ErrFileNotFound),
    ("ErrCantReadDir", ErrCantReadDir),
    ("ErrCantSetWd", ErrCantSetWd),
    ("ErrCheckread", ErrCheckread),
    ("ErrDiskFull", ErrDiskFull),
    ("ErrDupKey", ErrDupKey),
    ("ErrErrorOnClose", ErrErrorOnClose),
    ("ErrErrorOnRead", ErrErrorOnRead),
    ("ErrErrorOnRename", ErrErrorOnRename),
    ("ErrErrorOnWrite", ErrErrorOnWrite),
    ("ErrFileUsed", ErrFileUsed),
    ("ErrFilsortAbort", ErrFilsortAbort),
    ("ErrFormNotFound", ErrFormNotFound),
    ("ErrGetErrno", ErrGetErrno),
    ("ErrIllegalHa", ErrIllegalHa),
    ("ErrKeyNotFound", ErrKeyNotFound),
    ("ErrNotFormFile", ErrNotFormFile),
    ("ErrNotKeyFile", ErrNotKeyFile),
    ("ErrOldKeyFile", ErrOldKeyFile),
    ("ErrOpenAsReadonly", ErrOpenAsReadonly),
    ("ErrOutofMemory", ErrOutofMemory),
    ("ErrOutOfSortMemory", ErrOutOfSortMemory),
    ("ErrUnexpectedEOF", ErrUnexpectedEOF),
    ("ErrConCount", ErrConCount),
    ("ErrOutOfResources", ErrOutOfResources),
    ("ErrBadHost", ErrBadHost),
    ("ErrHandshake", ErrHandshake),
    ("ErrDBaccessDenied", ErrDBaccessDenied),
    ("ErrAccessDenied", ErrAccessDenied),
    ("ErrNoDB", ErrNoDB),
    ("ErrUnknownCom", ErrUnknownCom),
    ("ErrBadNull", ErrBadNull),
    ("ErrBadDB", ErrBadDB),
    ("ErrTableExists", ErrTableExists),
    ("ErrBadTable", ErrBadTable),
    ("ErrNonUniq", ErrNonUniq),
    ("ErrServerShutdown", ErrServerShutdown),
    ("ErrBadField", ErrBadField),
    ("ErrFieldNotInGroupBy", ErrFieldNotInGroupBy),
    ("ErrWrongGroupField", ErrWrongGroupField),
    ("ErrWrongSumSelect", ErrWrongSumSelect),
    ("ErrWrongValueCount", ErrWrongValueCount),
    ("ErrTooLongIdent", ErrTooLongIdent),
    ("ErrDupFieldName", ErrDupFieldName),
    ("ErrDupKeyName", ErrDupKeyName),
    ("ErrDupEntry", ErrDupEntry),
    ("ErrWrongFieldSpec", ErrWrongFieldSpec),
    ("ErrParse", ErrParse),
    ("ErrEmptyQuery", ErrEmptyQuery),
    ("ErrNonuniqTable", ErrNonuniqTable),
    ("ErrInvalidDefault", ErrInvalidDefault),
    ("ErrMultiplePriKey", ErrMultiplePriKey),
    ("ErrTooManyKeys", ErrTooManyKeys),
    ("ErrTooManyKeyParts", ErrTooManyKeyParts),
    ("ErrTooLongKey", ErrTooLongKey),
    ("ErrKeyColumnDoesNotExits", ErrKeyColumnDoesNotExits),
    ("ErrBlobUsedAsKey", ErrBlobUsedAsKey),
    ("ErrTooBigFieldlength", ErrTooBigFieldlength),
    ("ErrWrongAutoKey", ErrWrongAutoKey),
    ("ErrReady", ErrReady),
    ("ErrNormalShutdown", ErrNormalShutdown),
    ("ErrGotSignal", ErrGotSignal),
    ("ErrShutdownComplete", ErrShutdownComplete),
    ("ErrForcingClose", ErrForcingClose),
    ("ErrIpsock", ErrIpsock),
    ("ErrNoSuchIndex", ErrNoSuchIndex),
    ("ErrWrongFieldTerminators", ErrWrongFieldTerminators),
    ("ErrBlobsAndNoTerminated", ErrBlobsAndNoTerminated),
    ("ErrTextFileNotReadable", ErrTextFileNotReadable),
    ("ErrFileExists", ErrFileExists),
    ("ErrLoadInfo", ErrLoadInfo),
    ("ErrAlterInfo", ErrAlterInfo),
    ("ErrWrongSubKey", ErrWrongSubKey),
    ("ErrCantRemoveAllFields", ErrCantRemoveAllFields),
    ("ErrCantDropFieldOrKey", ErrCantDropFieldOrKey),
    ("ErrInsertInfo", ErrInsertInfo),
    ("ErrUpdateTableUsed", ErrUpdateTableUsed),
    ("ErrNoSuchThread", ErrNoSuchThread),
    ("ErrKillDenied", ErrKillDenied),
    ("ErrNoTablesUsed", ErrNoTablesUsed),
    ("ErrTooBigSet", ErrTooBigSet),
    ("ErrNoUniqueLogFile", ErrNoUniqueLogFile),
    ("ErrTableNotLockedForWrite", ErrTableNotLockedForWrite),
    ("ErrTableNotLocked", ErrTableNotLocked),
    ("ErrBlobCantHaveDefault", ErrBlobCantHaveDefault),
    ("ErrWrongDBName", ErrWrongDBName),
    ("ErrWrongTableName", ErrWrongTableName),
    ("ErrTooBigSelect", ErrTooBigSelect),
    ("ErrUnknown", ErrUnknown),
    ("ErrUnknownProcedure", ErrUnknownProcedure),
    (
        "ErrWrongParamcountToProcedure",
        ErrWrongParamcountToProcedure,
    ),
    (
        "ErrWrongParametersToProcedure",
        ErrWrongParametersToProcedure,
    ),
    ("ErrUnknownTable", ErrUnknownTable),
    ("ErrFieldSpecifiedTwice", ErrFieldSpecifiedTwice),
    ("ErrInvalidGroupFuncUse", ErrInvalidGroupFuncUse),
    ("ErrUnsupportedExtension", ErrUnsupportedExtension),
    ("ErrTableMustHaveColumns", ErrTableMustHaveColumns),
    ("ErrRecordFileFull", ErrRecordFileFull),
    ("ErrUnknownCharacterSet", ErrUnknownCharacterSet),
    ("ErrTooManyTables", ErrTooManyTables),
    ("ErrTooManyFields", ErrTooManyFields),
    ("ErrTooBigRowsize", ErrTooBigRowsize),
    ("ErrStackOverrun", ErrStackOverrun),
    ("ErrWrongOuterJoin", ErrWrongOuterJoin),
    ("ErrNullColumnInIndex", ErrNullColumnInIndex),
    ("ErrCantFindUdf", ErrCantFindUdf),
    ("ErrCantInitializeUdf", ErrCantInitializeUdf),
    ("ErrUdfNoPaths", ErrUdfNoPaths),
    ("ErrUdfExists", ErrUdfExists),
    ("ErrCantOpenLibrary", ErrCantOpenLibrary),
    ("ErrCantFindDlEntry", ErrCantFindDlEntry),
    ("ErrFunctionNotDefined", ErrFunctionNotDefined),
    ("ErrHostIsBlocked", ErrHostIsBlocked),
    ("ErrHostNotPrivileged", ErrHostNotPrivileged),
    ("ErrPasswordAnonymousUser", ErrPasswordAnonymousUser),
    ("ErrPasswordNotAllowed", ErrPasswordNotAllowed),
    ("ErrPasswordNoMatch", ErrPasswordNoMatch),
    ("ErrUpdateInfo", ErrUpdateInfo),
    ("ErrCantCreateThread", ErrCantCreateThread),
    ("ErrWrongValueCountOnRow", ErrWrongValueCountOnRow),
    ("ErrCantReopenTable", ErrCantReopenTable),
    ("ErrInvalidUseOfNull", ErrInvalidUseOfNull),
    ("ErrRegexp", ErrRegexp),
    ("ErrMixOfGroupFuncAndFields", ErrMixOfGroupFuncAndFields),
    ("ErrNonexistingGrant", ErrNonexistingGrant),
    ("ErrTableaccessDenied", ErrTableaccessDenied),
    ("ErrColumnaccessDenied", ErrColumnaccessDenied),
    ("ErrIllegalGrantForTable", ErrIllegalGrantForTable),
    ("ErrGrantWrongHostOrUser", ErrGrantWrongHostOrUser),
    ("ErrNoSuchTable", ErrNoSuchTable),
    ("ErrNonexistingTableGrant", ErrNonexistingTableGrant),
    ("ErrNotAllowedCommand", ErrNotAllowedCommand),
    ("ErrSyntax", ErrSyntax),
    ("ErrDelayedCantChangeLock", ErrDelayedCantChangeLock),
    ("ErrTooManyDelayedThreads", ErrTooManyDelayedThreads),
    ("ErrAbortingConnection", ErrAbortingConnection),
    ("ErrNetPacketTooLarge", ErrNetPacketTooLarge),
    ("ErrNetReadErrorFromPipe", ErrNetReadErrorFromPipe),
    ("ErrNetFcntl", ErrNetFcntl),
    ("ErrNetPacketsOutOfOrder", ErrNetPacketsOutOfOrder),
    ("ErrNetUncompress", ErrNetUncompress),
    ("ErrNetRead", ErrNetRead),
    ("ErrNetReadInterrupted", ErrNetReadInterrupted),
    ("ErrNetErrorOnWrite", ErrNetErrorOnWrite),
    ("ErrNetWriteInterrupted", ErrNetWriteInterrupted),
    ("ErrTooLongString", ErrTooLongString),
    ("ErrTableCantHandleBlob", ErrTableCantHandleBlob),
    (
        "ErrTableCantHandleAutoIncrement",
        ErrTableCantHandleAutoIncrement,
    ),
    ("ErrDelayedInsertTableLocked", ErrDelayedInsertTableLocked),
    ("ErrWrongColumnName", ErrWrongColumnName),
    ("ErrWrongKeyColumn", ErrWrongKeyColumn),
    ("ErrWrongMrgTable", ErrWrongMrgTable),
    ("ErrDupUnique", ErrDupUnique),
    ("ErrBlobKeyWithoutLength", ErrBlobKeyWithoutLength),
    ("ErrPrimaryCantHaveNull", ErrPrimaryCantHaveNull),
    ("ErrTooManyRows", ErrTooManyRows),
    ("ErrRequiresPrimaryKey", ErrRequiresPrimaryKey),
    ("ErrNoRaidCompiled", ErrNoRaidCompiled),
    (
        "ErrUpdateWithoutKeyInSafeMode",
        ErrUpdateWithoutKeyInSafeMode,
    ),
    ("ErrKeyDoesNotExist", ErrKeyDoesNotExist),
    ("ErrCheckNoSuchTable", ErrCheckNoSuchTable),
    ("ErrCheckNotImplemented", ErrCheckNotImplemented),
    (
        "ErrCantDoThisDuringAnTransaction",
        ErrCantDoThisDuringAnTransaction,
    ),
    ("ErrErrorDuringCommit", ErrErrorDuringCommit),
    ("ErrErrorDuringRollback", ErrErrorDuringRollback),
    ("ErrErrorDuringFlushLogs", ErrErrorDuringFlushLogs),
    ("ErrErrorDuringCheckpoint", ErrErrorDuringCheckpoint),
    ("ErrNewAbortingConnection", ErrNewAbortingConnection),
    ("ErrDumpNotImplemented", ErrDumpNotImplemented),
    ("ErrIndexRebuild", ErrIndexRebuild),
    ("ErrFtMatchingKeyNotFound", ErrFtMatchingKeyNotFound),
    ("ErrLockOrActiveTransaction", ErrLockOrActiveTransaction),
    ("ErrUnknownSystemVariable", ErrUnknownSystemVariable),
    ("ErrCrashedOnUsage", ErrCrashedOnUsage),
    ("ErrCrashedOnRepair", ErrCrashedOnRepair),
    (
        "ErrWarningNotCompleteRollback",
        ErrWarningNotCompleteRollback,
    ),
    ("ErrTransCacheFull", ErrTransCacheFull),
    ("ErrTooManyUserConnections", ErrTooManyUserConnections),
    ("ErrSetConstantsOnly", ErrSetConstantsOnly),
    ("ErrLockWaitTimeout", ErrLockWaitTimeout),
    ("ErrLockTableFull", ErrLockTableFull),
    ("ErrReadOnlyTransaction", ErrReadOnlyTransaction),
    ("ErrDropDBWithReadLock", ErrDropDBWithReadLock),
    ("ErrCreateDBWithReadLock", ErrCreateDBWithReadLock),
    ("ErrWrongArguments", ErrWrongArguments),
    ("ErrNoPermissionToCreateUser", ErrNoPermissionToCreateUser),
    ("ErrUnionTablesInDifferentDir", ErrUnionTablesInDifferentDir),
    ("ErrLockDeadlock", ErrLockDeadlock),
    ("ErrTableCantHandleFt", ErrTableCantHandleFt),
    ("ErrCannotAddForeign", ErrCannotAddForeign),
    ("ErrNoReferencedRow", ErrNoReferencedRow),
    ("ErrRowIsReferenced", ErrRowIsReferenced),
    ("ErrErrorWhenExecutingCommand", ErrErrorWhenExecutingCommand),
    ("ErrWrongUsage", ErrWrongUsage),
    (
        "ErrWrongNumberOfColumnsInSelect",
        ErrWrongNumberOfColumnsInSelect,
    ),
    ("ErrCantUpdateWithReadlock", ErrCantUpdateWithReadlock),
    ("ErrMixingNotAllowed", ErrMixingNotAllowed),
    ("ErrDupArgument", ErrDupArgument),
    ("ErrUserLimitReached", ErrUserLimitReached),
    ("ErrSpecificAccessDenied", ErrSpecificAccessDenied),
    ("ErrLocalVariable", ErrLocalVariable),
    ("ErrGlobalVariable", ErrGlobalVariable),
    ("ErrNoDefault", ErrNoDefault),
    ("ErrWrongValueForVar", ErrWrongValueForVar),
    ("ErrWrongTypeForVar", ErrWrongTypeForVar),
    ("ErrVarCantBeRead", ErrVarCantBeRead),
    ("ErrCantUseOptionHere", ErrCantUseOptionHere),
    ("ErrNotSupportedYet", ErrNotSupportedYet),
    ("ErrIncorrectGlobalLocalVar", ErrIncorrectGlobalLocalVar),
    ("ErrWrongFkDef", ErrWrongFkDef),
    ("ErrKeyRefDoNotMatchTableRef", ErrKeyRefDoNotMatchTableRef),
    ("ErrOperandColumns", ErrOperandColumns),
    ("ErrSubqueryNo1Row", ErrSubqueryNo1Row),
    ("ErrUnknownStmtHandler", ErrUnknownStmtHandler),
    ("ErrCorruptHelpDB", ErrCorruptHelpDB),
    ("ErrCyclicReference", ErrCyclicReference),
    ("ErrAutoConvert", ErrAutoConvert),
    ("ErrIllegalReference", ErrIllegalReference),
    ("ErrDerivedMustHaveAlias", ErrDerivedMustHaveAlias),
    ("ErrSelectReduced", ErrSelectReduced),
    ("ErrTablenameNotAllowedHere", ErrTablenameNotAllowedHere),
    ("ErrNotSupportedAuthMode", ErrNotSupportedAuthMode),
    ("ErrSpatialCantHaveNull", ErrSpatialCantHaveNull),
    ("ErrCollationCharsetMismatch", ErrCollationCharsetMismatch),
    ("ErrTooBigForUncompress", ErrTooBigForUncompress),
    ("ErrZlibZMem", ErrZlibZMem),
    ("ErrZlibZBuf", ErrZlibZBuf),
    ("ErrZlibZData", ErrZlibZData),
    ("ErrCutValueGroupConcat", ErrCutValueGroupConcat),
    ("ErrWarnTooFewRecords", ErrWarnTooFewRecords),
    ("ErrWarnTooManyRecords", ErrWarnTooManyRecords),
    ("ErrWarnNullToNotnull", ErrWarnNullToNotnull),
    ("ErrWarnDataOutOfRange", ErrWarnDataOutOfRange),
    ("WarnDataTruncated", WarnDataTruncated),
    ("ErrWarnUsingOtherHandler", ErrWarnUsingOtherHandler),
    ("ErrCantAggregate2collations", ErrCantAggregate2collations),
    ("ErrDropUser", ErrDropUser),
    ("ErrRevokeGrants", ErrRevokeGrants),
    ("ErrCantAggregate3collations", ErrCantAggregate3collations),
    ("ErrCantAggregateNcollations", ErrCantAggregateNcollations),
    ("ErrVariableIsNotStruct", ErrVariableIsNotStruct),
    ("ErrUnknownCollation", ErrUnknownCollation),
    ("ErrServerIsInSecureAuthMode", ErrServerIsInSecureAuthMode),
    ("ErrWarnFieldResolved", ErrWarnFieldResolved),
    ("ErrUntilCondIgnored", ErrUntilCondIgnored),
    ("ErrWrongNameForIndex", ErrWrongNameForIndex),
    ("ErrWrongNameForCatalog", ErrWrongNameForCatalog),
    ("ErrWarnQcResize", ErrWarnQcResize),
    ("ErrBadFtColumn", ErrBadFtColumn),
    ("ErrUnknownKeyCache", ErrUnknownKeyCache),
    ("ErrWarnHostnameWontWork", ErrWarnHostnameWontWork),
    ("ErrUnknownStorageEngine", ErrUnknownStorageEngine),
    ("ErrWarnDeprecatedSyntax", ErrWarnDeprecatedSyntax),
    ("ErrNonUpdatableTable", ErrNonUpdatableTable),
    ("ErrFeatureDisabled", ErrFeatureDisabled),
    ("ErrOptionPreventsStatement", ErrOptionPreventsStatement),
    ("ErrDuplicatedValueInType", ErrDuplicatedValueInType),
    ("ErrTruncatedWrongValue", ErrTruncatedWrongValue),
    ("ErrTooMuchAutoTimestampCols", ErrTooMuchAutoTimestampCols),
    ("ErrInvalidOnUpdate", ErrInvalidOnUpdate),
    ("ErrUnsupportedPs", ErrUnsupportedPs),
    ("ErrGetErrmsg", ErrGetErrmsg),
    ("ErrGetTemporaryErrmsg", ErrGetTemporaryErrmsg),
    ("ErrUnknownTimeZone", ErrUnknownTimeZone),
    ("ErrWarnInvalidTimestamp", ErrWarnInvalidTimestamp),
    ("ErrInvalidCharacterString", ErrInvalidCharacterString),
    (
        "ErrWarnAllowedPacketOverflowed",
        ErrWarnAllowedPacketOverflowed,
    ),
    ("ErrConflictingDeclarations", ErrConflictingDeclarations),
    ("ErrSpNoRecursiveCreate", ErrSpNoRecursiveCreate),
    ("ErrSpAlreadyExists", ErrSpAlreadyExists),
    ("ErrSpDoesNotExist", ErrSpDoesNotExist),
    ("ErrSpDropFailed", ErrSpDropFailed),
    ("ErrSpStoreFailed", ErrSpStoreFailed),
    ("ErrSpLilabelMismatch", ErrSpLilabelMismatch),
    ("ErrSpLabelRedefine", ErrSpLabelRedefine),
    ("ErrSpLabelMismatch", ErrSpLabelMismatch),
    ("ErrSpUninitVar", ErrSpUninitVar),
    ("ErrSpBadselect", ErrSpBadselect),
    ("ErrSpBadreturn", ErrSpBadreturn),
    ("ErrSpBadstatement", ErrSpBadstatement),
    (
        "ErrUpdateLogDeprecatedIgnored",
        ErrUpdateLogDeprecatedIgnored,
    ),
    (
        "ErrUpdateLogDeprecatedTranslated",
        ErrUpdateLogDeprecatedTranslated,
    ),
    ("ErrQueryInterrupted", ErrQueryInterrupted),
    ("ErrSpWrongNoOfArgs", ErrSpWrongNoOfArgs),
    ("ErrSpCondMismatch", ErrSpCondMismatch),
    ("ErrSpNoreturn", ErrSpNoreturn),
    ("ErrSpNoreturnend", ErrSpNoreturnend),
    ("ErrSpBadCursorQuery", ErrSpBadCursorQuery),
    ("ErrSpBadCursorSelect", ErrSpBadCursorSelect),
    ("ErrSpCursorMismatch", ErrSpCursorMismatch),
    ("ErrSpCursorAlreadyOpen", ErrSpCursorAlreadyOpen),
    ("ErrSpCursorNotOpen", ErrSpCursorNotOpen),
    ("ErrSpUndeclaredVar", ErrSpUndeclaredVar),
    ("ErrSpWrongNoOfFetchArgs", ErrSpWrongNoOfFetchArgs),
    ("ErrSpFetchNoData", ErrSpFetchNoData),
    ("ErrSpDupParam", ErrSpDupParam),
    ("ErrSpDupVar", ErrSpDupVar),
    ("ErrSpDupCond", ErrSpDupCond),
    ("ErrSpDupCurs", ErrSpDupCurs),
    ("ErrSpCantAlter", ErrSpCantAlter),
    ("ErrSpSubselectNyi", ErrSpSubselectNyi),
    ("ErrStmtNotAllowedInSfOrTrg", ErrStmtNotAllowedInSfOrTrg),
    ("ErrSpVarcondAfterCurshndlr", ErrSpVarcondAfterCurshndlr),
    ("ErrSpCursorAfterHandler", ErrSpCursorAfterHandler),
    ("ErrSpCaseNotFound", ErrSpCaseNotFound),
    ("ErrFparserTooBigFile", ErrFparserTooBigFile),
    ("ErrFparserBadHeader", ErrFparserBadHeader),
    ("ErrFparserEOFInComment", ErrFparserEOFInComment),
    ("ErrFparserErrorInParameter", ErrFparserErrorInParameter),
    (
        "ErrFparserEOFInUnknownParameter",
        ErrFparserEOFInUnknownParameter,
    ),
    ("ErrViewNoExplain", ErrViewNoExplain),
    ("ErrFrmUnknownType", ErrFrmUnknownType),
    ("ErrWrongObject", ErrWrongObject),
    ("ErrNonupdateableColumn", ErrNonupdateableColumn),
    ("ErrViewSelectDerived", ErrViewSelectDerived),
    ("ErrViewSelectClause", ErrViewSelectClause),
    ("ErrViewSelectVariable", ErrViewSelectVariable),
    ("ErrViewSelectTmptable", ErrViewSelectTmptable),
    ("ErrViewWrongList", ErrViewWrongList),
    ("ErrWarnViewMerge", ErrWarnViewMerge),
    ("ErrWarnViewWithoutKey", ErrWarnViewWithoutKey),
    ("ErrViewInvalid", ErrViewInvalid),
    ("ErrSpNoDropSp", ErrSpNoDropSp),
    ("ErrSpGotoInHndlr", ErrSpGotoInHndlr),
    ("ErrTrgAlreadyExists", ErrTrgAlreadyExists),
    ("ErrTrgDoesNotExist", ErrTrgDoesNotExist),
    ("ErrTrgOnViewOrTempTable", ErrTrgOnViewOrTempTable),
    ("ErrTrgCantChangeRow", ErrTrgCantChangeRow),
    ("ErrTrgNoSuchRowInTrg", ErrTrgNoSuchRowInTrg),
    ("ErrNoDefaultForField", ErrNoDefaultForField),
    ("ErrDivisionByZero", ErrDivisionByZero),
    (
        "ErrTruncatedWrongValueForField",
        ErrTruncatedWrongValueForField,
    ),
    ("ErrIllegalValueForType", ErrIllegalValueForType),
    ("ErrViewNonupdCheck", ErrViewNonupdCheck),
    ("ErrViewCheckFailed", ErrViewCheckFailed),
    ("ErrProcaccessDenied", ErrProcaccessDenied),
    ("ErrRelayLogFail", ErrRelayLogFail),
    ("ErrPasswdLength", ErrPasswdLength),
    ("ErrUnknownTargetBinlog", ErrUnknownTargetBinlog),
    ("ErrIoErrLogIndexRead", ErrIoErrLogIndexRead),
    ("ErrBinlogPurgeProhibited", ErrBinlogPurgeProhibited),
    ("ErrFseekFail", ErrFseekFail),
    ("ErrBinlogPurgeFatalErr", ErrBinlogPurgeFatalErr),
    ("ErrLogInUse", ErrLogInUse),
    ("ErrLogPurgeUnknownErr", ErrLogPurgeUnknownErr),
    ("ErrRelayLogInit", ErrRelayLogInit),
    ("ErrNoBinaryLogging", ErrNoBinaryLogging),
    ("ErrReservedSyntax", ErrReservedSyntax),
    ("ErrWsasFailed", ErrWsasFailed),
    ("ErrDiffGroupsProc", ErrDiffGroupsProc),
    ("ErrNoGroupForProc", ErrNoGroupForProc),
    ("ErrOrderWithProc", ErrOrderWithProc),
    ("ErrLoggingProhibitChangingOf", ErrLoggingProhibitChangingOf),
    ("ErrNoFileMapping", ErrNoFileMapping),
    ("ErrWrongMagic", ErrWrongMagic),
    ("ErrPsManyParam", ErrPsManyParam),
    ("ErrKeyPart0", ErrKeyPart0),
    ("ErrViewChecksum", ErrViewChecksum),
    ("ErrViewMultiupdate", ErrViewMultiupdate),
    ("ErrViewNoInsertFieldList", ErrViewNoInsertFieldList),
    ("ErrViewDeleteMergeView", ErrViewDeleteMergeView),
    ("ErrCannotUser", ErrCannotUser),
    ("ErrXaerNota", ErrXaerNota),
    ("ErrXaerInval", ErrXaerInval),
    ("ErrXaerRmfail", ErrXaerRmfail),
    ("ErrXaerOutside", ErrXaerOutside),
    ("ErrXaerRmerr", ErrXaerRmerr),
    ("ErrXaRbrollback", ErrXaRbrollback),
    ("ErrNonexistingProcGrant", ErrNonexistingProcGrant),
    ("ErrProcAutoGrantFail", ErrProcAutoGrantFail),
    ("ErrProcAutoRevokeFail", ErrProcAutoRevokeFail),
    ("ErrDataTooLong", ErrDataTooLong),
    ("ErrSpBadSQLstate", ErrSpBadSQLstate),
    ("ErrStartup", ErrStartup),
    (
        "ErrLoadFromFixedSizeRowsToVar",
        ErrLoadFromFixedSizeRowsToVar,
    ),
    ("ErrCantCreateUserWithGrant", ErrCantCreateUserWithGrant),
    ("ErrWrongValueForType", ErrWrongValueForType),
    ("ErrTableDefChanged", ErrTableDefChanged),
    ("ErrSpDupHandler", ErrSpDupHandler),
    ("ErrSpNotVarArg", ErrSpNotVarArg),
    ("ErrSpNoRetset", ErrSpNoRetset),
    ("ErrCantCreateGeometryObject", ErrCantCreateGeometryObject),
    ("ErrFailedRoutineBreakBinlog", ErrFailedRoutineBreakBinlog),
    ("ErrBinlogUnsafeRoutine", ErrBinlogUnsafeRoutine),
    (
        "ErrBinlogCreateRoutineNeedSuper",
        ErrBinlogCreateRoutineNeedSuper,
    ),
    ("ErrExecStmtWithOpenCursor", ErrExecStmtWithOpenCursor),
    ("ErrStmtHasNoOpenCursor", ErrStmtHasNoOpenCursor),
    ("ErrCommitNotAllowedInSfOrTrg", ErrCommitNotAllowedInSfOrTrg),
    ("ErrNoDefaultForViewField", ErrNoDefaultForViewField),
    ("ErrSpNoRecursion", ErrSpNoRecursion),
    ("ErrTooBigScale", ErrTooBigScale),
    ("ErrTooBigPrecision", ErrTooBigPrecision),
    ("ErrMBiggerThanD", ErrMBiggerThanD),
    ("ErrWrongLockOfSystemTable", ErrWrongLockOfSystemTable),
    (
        "ErrConnectToForeignDataSource",
        ErrConnectToForeignDataSource,
    ),
    ("ErrQueryOnForeignDataSource", ErrQueryOnForeignDataSource),
    (
        "ErrForeignDataSourceDoesntExist",
        ErrForeignDataSourceDoesntExist,
    ),
    (
        "ErrForeignDataStringInvalidCantCreate",
        ErrForeignDataStringInvalidCantCreate,
    ),
    ("ErrForeignDataStringInvalid", ErrForeignDataStringInvalid),
    ("ErrCantCreateFederatedTable", ErrCantCreateFederatedTable),
    ("ErrTrgInWrongSchema", ErrTrgInWrongSchema),
    ("ErrStackOverrunNeedMore", ErrStackOverrunNeedMore),
    ("ErrTooLongBody", ErrTooLongBody),
    (
        "ErrWarnCantDropDefaultKeycache",
        ErrWarnCantDropDefaultKeycache,
    ),
    ("ErrTooBigDisplaywidth", ErrTooBigDisplaywidth),
    ("ErrXaerDupid", ErrXaerDupid),
    ("ErrDatetimeFunctionOverflow", ErrDatetimeFunctionOverflow),
    (
        "ErrCantUpdateUsedTableInSfOrTrg",
        ErrCantUpdateUsedTableInSfOrTrg,
    ),
    ("ErrViewPreventUpdate", ErrViewPreventUpdate),
    ("ErrPsNoRecursion", ErrPsNoRecursion),
    ("ErrSpCantSetAutocommit", ErrSpCantSetAutocommit),
    ("ErrMalformedDefiner", ErrMalformedDefiner),
    ("ErrViewFrmNoUser", ErrViewFrmNoUser),
    ("ErrViewOtherUser", ErrViewOtherUser),
    ("ErrNoSuchUser", ErrNoSuchUser),
    ("ErrForbidSchemaChange", ErrForbidSchemaChange),
    ("ErrRowIsReferenced2", ErrRowIsReferenced2),
    ("ErrNoReferencedRow2", ErrNoReferencedRow2),
    ("ErrSpBadVarShadow", ErrSpBadVarShadow),
    ("ErrTrgNoDefiner", ErrTrgNoDefiner),
    ("ErrOldFileFormat", ErrOldFileFormat),
    ("ErrSpRecursionLimit", ErrSpRecursionLimit),
    ("ErrSpProcTableCorrupt", ErrSpProcTableCorrupt),
    ("ErrSpWrongName", ErrSpWrongName),
    ("ErrTableNeedsUpgrade", ErrTableNeedsUpgrade),
    ("ErrSpNoAggregate", ErrSpNoAggregate),
    (
        "ErrMaxPreparedStmtCountReached",
        ErrMaxPreparedStmtCountReached,
    ),
    ("ErrViewRecursive", ErrViewRecursive),
    ("ErrNonGroupingFieldUsed", ErrNonGroupingFieldUsed),
    ("ErrTableCantHandleSpkeys", ErrTableCantHandleSpkeys),
    ("ErrNoTriggersOnSystemSchema", ErrNoTriggersOnSystemSchema),
    ("ErrRemovedSpaces", ErrRemovedSpaces),
    ("ErrAutoincReadFailed", ErrAutoincReadFailed),
    ("ErrUsername", ErrUsername),
    ("ErrHostname", ErrHostname),
    ("ErrWrongStringLength", ErrWrongStringLength),
    ("ErrNonInsertableTable", ErrNonInsertableTable),
    ("ErrAdminWrongMrgTable", ErrAdminWrongMrgTable),
    (
        "ErrTooHighLevelOfNestingForSelect",
        ErrTooHighLevelOfNestingForSelect,
    ),
    ("ErrNameBecomesEmpty", ErrNameBecomesEmpty),
    ("ErrAmbiguousFieldTerm", ErrAmbiguousFieldTerm),
    ("ErrForeignServerExists", ErrForeignServerExists),
    ("ErrForeignServerDoesntExist", ErrForeignServerDoesntExist),
    ("ErrIllegalHaCreateOption", ErrIllegalHaCreateOption),
    ("ErrPartitionRequiresValues", ErrPartitionRequiresValues),
    ("ErrPartitionWrongValues", ErrPartitionWrongValues),
    ("ErrPartitionMaxvalue", ErrPartitionMaxvalue),
    ("ErrPartitionSubpartition", ErrPartitionSubpartition),
    ("ErrPartitionSubpartMix", ErrPartitionSubpartMix),
    ("ErrPartitionWrongNoPart", ErrPartitionWrongNoPart),
    ("ErrPartitionWrongNoSubpart", ErrPartitionWrongNoSubpart),
    ("ErrWrongExprInPartitionFunc", ErrWrongExprInPartitionFunc),
    ("ErrNoConstExprInRangeOrList", ErrNoConstExprInRangeOrList),
    ("ErrFieldNotFoundPart", ErrFieldNotFoundPart),
    ("ErrListOfFieldsOnlyInHash", ErrListOfFieldsOnlyInHash),
    ("ErrInconsistentPartitionInfo", ErrInconsistentPartitionInfo),
    ("ErrPartitionFuncNotAllowed", ErrPartitionFuncNotAllowed),
    ("ErrPartitionsMustBeDefined", ErrPartitionsMustBeDefined),
    ("ErrRangeNotIncreasing", ErrRangeNotIncreasing),
    (
        "ErrInconsistentTypeOfFunctions",
        ErrInconsistentTypeOfFunctions,
    ),
    (
        "ErrMultipleDefConstInListPart",
        ErrMultipleDefConstInListPart,
    ),
    ("ErrPartitionEntry", ErrPartitionEntry),
    ("ErrMixHandler", ErrMixHandler),
    ("ErrPartitionNotDefined", ErrPartitionNotDefined),
    ("ErrTooManyPartitions", ErrTooManyPartitions),
    ("ErrSubpartition", ErrSubpartition),
    ("ErrCantCreateHandlerFile", ErrCantCreateHandlerFile),
    ("ErrBlobFieldInPartFunc", ErrBlobFieldInPartFunc),
    (
        "ErrUniqueKeyNeedAllFieldsInPf",
        ErrUniqueKeyNeedAllFieldsInPf,
    ),
    ("ErrNoParts", ErrNoParts),
    (
        "ErrPartitionMgmtOnNonpartitioned",
        ErrPartitionMgmtOnNonpartitioned,
    ),
    ("ErrForeignKeyOnPartitioned", ErrForeignKeyOnPartitioned),
    ("ErrDropPartitionNonExistent", ErrDropPartitionNonExistent),
    ("ErrDropLastPartition", ErrDropLastPartition),
    (
        "ErrCoalesceOnlyOnHashPartition",
        ErrCoalesceOnlyOnHashPartition,
    ),
    ("ErrReorgHashOnlyOnSameNo", ErrReorgHashOnlyOnSameNo),
    ("ErrReorgNoParam", ErrReorgNoParam),
    ("ErrOnlyOnRangeListPartition", ErrOnlyOnRangeListPartition),
    ("ErrAddPartitionSubpart", ErrAddPartitionSubpart),
    (
        "ErrAddPartitionNoNewPartition",
        ErrAddPartitionNoNewPartition,
    ),
    (
        "ErrCoalescePartitionNoPartition",
        ErrCoalescePartitionNoPartition,
    ),
    ("ErrReorgPartitionNotExist", ErrReorgPartitionNotExist),
    ("ErrSameNamePartition", ErrSameNamePartition),
    ("ErrNoBinlog", ErrNoBinlog),
    (
        "ErrConsecutiveReorgPartitions",
        ErrConsecutiveReorgPartitions,
    ),
    ("ErrReorgOutsideRange", ErrReorgOutsideRange),
    ("ErrPartitionFunctionFailure", ErrPartitionFunctionFailure),
    ("ErrPartState", ErrPartState),
    ("ErrLimitedPartRange", ErrLimitedPartRange),
    ("ErrPluginIsNotLoaded", ErrPluginIsNotLoaded),
    ("ErrWrongValue", ErrWrongValue),
    ("ErrNoPartitionForGivenValue", ErrNoPartitionForGivenValue),
    ("ErrFilegroupOptionOnlyOnce", ErrFilegroupOptionOnlyOnce),
    ("ErrCreateFilegroupFailed", ErrCreateFilegroupFailed),
    ("ErrDropFilegroupFailed", ErrDropFilegroupFailed),
    ("ErrTablespaceAutoExtend", ErrTablespaceAutoExtend),
    ("ErrWrongSizeNumber", ErrWrongSizeNumber),
    ("ErrSizeOverflow", ErrSizeOverflow),
    ("ErrAlterFilegroupFailed", ErrAlterFilegroupFailed),
    ("ErrBinlogRowLoggingFailed", ErrBinlogRowLoggingFailed),
    ("ErrEventAlreadyExists", ErrEventAlreadyExists),
    ("ErrEventStoreFailed", ErrEventStoreFailed),
    ("ErrEventDoesNotExist", ErrEventDoesNotExist),
    ("ErrEventCantAlter", ErrEventCantAlter),
    ("ErrEventDropFailed", ErrEventDropFailed),
    (
        "ErrEventIntervalNotPositiveOrTooBig",
        ErrEventIntervalNotPositiveOrTooBig,
    ),
    ("ErrEventEndsBeforeStarts", ErrEventEndsBeforeStarts),
    ("ErrEventExecTimeInThePast", ErrEventExecTimeInThePast),
    ("ErrEventOpenTableFailed", ErrEventOpenTableFailed),
    ("ErrEventNeitherMExprNorMAt", ErrEventNeitherMExprNorMAt),
    (
        "ErrObsoleteColCountDoesntMatchCorrupted",
        ErrObsoleteColCountDoesntMatchCorrupted,
    ),
    (
        "ErrObsoleteCannotLoadFromTable",
        ErrObsoleteCannotLoadFromTable,
    ),
    ("ErrEventCannotDelete", ErrEventCannotDelete),
    ("ErrEventCompile", ErrEventCompile),
    ("ErrEventSameName", ErrEventSameName),
    ("ErrEventDataTooLong", ErrEventDataTooLong),
    (
        "ErrDropIndexNeededInForeignKey",
        ErrDropIndexNeededInForeignKey,
    ),
    (
        "ErrWarnDeprecatedSyntaxWithVer",
        ErrWarnDeprecatedSyntaxWithVer,
    ),
    ("ErrCantWriteLockLogTable", ErrCantWriteLockLogTable),
    ("ErrCantLockLogTable", ErrCantLockLogTable),
    (
        "ErrForeignDuplicateKeyOldUnused",
        ErrForeignDuplicateKeyOldUnused,
    ),
    (
        "ErrColCountDoesntMatchPleaseUpdate",
        ErrColCountDoesntMatchPleaseUpdate,
    ),
    (
        "ErrTempTablePreventsSwitchOutOfRbr",
        ErrTempTablePreventsSwitchOutOfRbr,
    ),
    (
        "ErrStoredFunctionPreventsSwitchBinlogFormat",
        ErrStoredFunctionPreventsSwitchBinlogFormat,
    ),
    ("ErrNdbCantSwitchBinlogFormat", ErrNdbCantSwitchBinlogFormat),
    ("ErrPartitionNoTemporary", ErrPartitionNoTemporary),
    ("ErrPartitionConstDomain", ErrPartitionConstDomain),
    (
        "ErrPartitionFunctionIsNotAllowed",
        ErrPartitionFunctionIsNotAllowed,
    ),
    ("ErrDdlLog", ErrDdlLog),
    ("ErrNullInValuesLessThan", ErrNullInValuesLessThan),
    ("ErrWrongPartitionName", ErrWrongPartitionName),
    (
        "ErrCantChangeTxCharacteristics",
        ErrCantChangeTxCharacteristics,
    ),
    ("ErrDupEntryAutoincrementCase", ErrDupEntryAutoincrementCase),
    ("ErrEventModifyQueue", ErrEventModifyQueue),
    ("ErrEventSetVar", ErrEventSetVar),
    ("ErrPartitionMerge", ErrPartitionMerge),
    ("ErrCantActivateLog", ErrCantActivateLog),
    ("ErrRbrNotAvailable", ErrRbrNotAvailable),
    ("ErrBase64Decode", ErrBase64Decode),
    ("ErrEventRecursionForbidden", ErrEventRecursionForbidden),
    ("ErrEventsDB", ErrEventsDB),
    ("ErrOnlyIntegersAllowed", ErrOnlyIntegersAllowed),
    ("ErrUnsuportedLogEngine", ErrUnsuportedLogEngine),
    ("ErrBadLogStatement", ErrBadLogStatement),
    ("ErrCantRenameLogTable", ErrCantRenameLogTable),
    (
        "ErrWrongParamcountToNativeFct",
        ErrWrongParamcountToNativeFct,
    ),
    (
        "ErrWrongParametersToNativeFct",
        ErrWrongParametersToNativeFct,
    ),
    (
        "ErrWrongParametersToStoredFct",
        ErrWrongParametersToStoredFct,
    ),
    ("ErrNativeFctNameCollision", ErrNativeFctNameCollision),
    ("ErrDupEntryWithKeyName", ErrDupEntryWithKeyName),
    ("ErrBinlogPurgeEmFile", ErrBinlogPurgeEmFile),
    (
        "ErrEventCannotCreateInThePast",
        ErrEventCannotCreateInThePast,
    ),
    ("ErrEventCannotAlterInThePast", ErrEventCannotAlterInThePast),
    (
        "ErrNoPartitionForGivenValueSilent",
        ErrNoPartitionForGivenValueSilent,
    ),
    ("ErrBinlogUnsafeStatement", ErrBinlogUnsafeStatement),
    ("ErrBinlogLoggingImpossible", ErrBinlogLoggingImpossible),
    ("ErrViewNoCreationCtx", ErrViewNoCreationCtx),
    ("ErrViewInvalidCreationCtx", ErrViewInvalidCreationCtx),
    ("ErrSrInvalidCreationCtx", ErrSrInvalidCreationCtx),
    ("ErrTrgCorruptedFile", ErrTrgCorruptedFile),
    ("ErrTrgNoCreationCtx", ErrTrgNoCreationCtx),
    ("ErrTrgInvalidCreationCtx", ErrTrgInvalidCreationCtx),
    ("ErrEventInvalidCreationCtx", ErrEventInvalidCreationCtx),
    ("ErrTrgCantOpenTable", ErrTrgCantOpenTable),
    ("ErrCantCreateSroutine", ErrCantCreateSroutine),
    (
        "ErrNoFormatDescriptionEventBeforeBinlogStatement",
        ErrNoFormatDescriptionEventBeforeBinlogStatement,
    ),
    ("ErrLoadDataInvalidColumn", ErrLoadDataInvalidColumn),
    ("ErrLogPurgeNoFile", ErrLogPurgeNoFile),
    ("ErrXaRbtimeout", ErrXaRbtimeout),
    ("ErrXaRbdeadlock", ErrXaRbdeadlock),
    ("ErrNeedReprepare", ErrNeedReprepare),
    ("ErrDelayedNotSupported", ErrDelayedNotSupported),
    ("WarnOptionIgnored", WarnOptionIgnored),
    ("WarnPluginDeleteBuiltin", WarnPluginDeleteBuiltin),
    ("WarnPluginBusy", WarnPluginBusy),
    ("ErrVariableIsReadonly", ErrVariableIsReadonly),
    (
        "ErrWarnEngineTransactionRollback",
        ErrWarnEngineTransactionRollback,
    ),
    ("ErrNdbReplicationSchema", ErrNdbReplicationSchema),
    ("ErrConflictFnParse", ErrConflictFnParse),
    ("ErrExceptionsWrite", ErrExceptionsWrite),
    ("ErrTooLongTableComment", ErrTooLongTableComment),
    ("ErrTooLongFieldComment", ErrTooLongFieldComment),
    (
        "ErrFuncInexistentNameCollision",
        ErrFuncInexistentNameCollision,
    ),
    ("ErrDatabaseName", ErrDatabaseName),
    ("ErrTableName", ErrTableName),
    ("ErrPartitionName", ErrPartitionName),
    ("ErrSubpartitionName", ErrSubpartitionName),
    ("ErrTemporaryName", ErrTemporaryName),
    ("ErrRenamedName", ErrRenamedName),
    ("ErrTooManyConcurrentTrxs", ErrTooManyConcurrentTrxs),
    (
        "WarnNonASCIISeparatorNotImplemented",
        WarnNonASCIISeparatorNotImplemented,
    ),
    ("ErrDebugSyncTimeout", ErrDebugSyncTimeout),
    ("ErrDebugSyncHitLimit", ErrDebugSyncHitLimit),
    ("ErrDupSignalSet", ErrDupSignalSet),
    ("ErrSignalWarn", ErrSignalWarn),
    ("ErrSignalNotFound", ErrSignalNotFound),
    ("ErrSignalException", ErrSignalException),
    (
        "ErrResignalWithoutActiveHandler",
        ErrResignalWithoutActiveHandler,
    ),
    ("ErrSignalBadConditionType", ErrSignalBadConditionType),
    ("WarnCondItemTruncated", WarnCondItemTruncated),
    ("ErrCondItemTooLong", ErrCondItemTooLong),
    ("ErrUnknownLocale", ErrUnknownLocale),
    ("ErrQueryCacheDisabled", ErrQueryCacheDisabled),
    ("ErrSameNamePartitionField", ErrSameNamePartitionField),
    ("ErrPartitionColumnList", ErrPartitionColumnList),
    ("ErrWrongTypeColumnValue", ErrWrongTypeColumnValue),
    (
        "ErrTooManyPartitionFuncFields",
        ErrTooManyPartitionFuncFields,
    ),
    ("ErrMaxvalueInValuesIn", ErrMaxvalueInValuesIn),
    ("ErrTooManyValues", ErrTooManyValues),
    ("ErrRowSinglePartitionField", ErrRowSinglePartitionField),
    (
        "ErrFieldTypeNotAllowedAsPartitionField",
        ErrFieldTypeNotAllowedAsPartitionField,
    ),
    ("ErrPartitionFieldsTooLong", ErrPartitionFieldsTooLong),
    (
        "ErrBinlogRowEngineAndStmtEngine",
        ErrBinlogRowEngineAndStmtEngine,
    ),
    (
        "ErrBinlogRowModeAndStmtEngine",
        ErrBinlogRowModeAndStmtEngine,
    ),
    ("ErrBinlogUnsafeAndStmtEngine", ErrBinlogUnsafeAndStmtEngine),
    (
        "ErrBinlogRowInjectionAndStmtEngine",
        ErrBinlogRowInjectionAndStmtEngine,
    ),
    (
        "ErrBinlogStmtModeAndRowEngine",
        ErrBinlogStmtModeAndRowEngine,
    ),
    (
        "ErrBinlogRowInjectionAndStmtMode",
        ErrBinlogRowInjectionAndStmtMode,
    ),
    (
        "ErrBinlogMultipleEnginesAndSelfLoggingEngine",
        ErrBinlogMultipleEnginesAndSelfLoggingEngine,
    ),
    ("ErrBinlogUnsafeLimit", ErrBinlogUnsafeLimit),
    ("ErrBinlogUnsafeInsertDelayed", ErrBinlogUnsafeInsertDelayed),
    (
        "ErrBinlogUnsafeAutoincColumns",
        ErrBinlogUnsafeAutoincColumns,
    ),
    (
        "ErrBinlogUnsafeSystemFunction",
        ErrBinlogUnsafeSystemFunction,
    ),
    (
        "ErrBinlogUnsafeNontransAfterTrans",
        ErrBinlogUnsafeNontransAfterTrans,
    ),
    ("ErrMessageAndStatement", ErrMessageAndStatement),
    (
        "ErrInsideTransactionPreventsSwitchBinlogFormat",
        ErrInsideTransactionPreventsSwitchBinlogFormat,
    ),
    ("ErrPathLength", ErrPathLength),
    (
        "ErrWarnDeprecatedSyntaxNoReplacement",
        ErrWarnDeprecatedSyntaxNoReplacement,
    ),
    ("ErrWrongNativeTableStructure", ErrWrongNativeTableStructure),
    ("ErrWrongPerfSchemaUsage", ErrWrongPerfSchemaUsage),
    ("ErrWarnISSkippedTable", ErrWarnISSkippedTable),
    (
        "ErrInsideTransactionPreventsSwitchBinlogDirect",
        ErrInsideTransactionPreventsSwitchBinlogDirect,
    ),
    (
        "ErrStoredFunctionPreventsSwitchBinlogDirect",
        ErrStoredFunctionPreventsSwitchBinlogDirect,
    ),
    ("ErrSpatialMustHaveGeomCol", ErrSpatialMustHaveGeomCol),
    ("ErrTooLongIndexComment", ErrTooLongIndexComment),
    ("ErrLockAborted", ErrLockAborted),
    ("ErrDataOutOfRange", ErrDataOutOfRange),
    ("ErrWrongSpvarTypeInLimit", ErrWrongSpvarTypeInLimit),
    (
        "ErrBinlogUnsafeMultipleEnginesAndSelfLoggingEngine",
        ErrBinlogUnsafeMultipleEnginesAndSelfLoggingEngine,
    ),
    (
        "ErrBinlogUnsafeMixedStatement",
        ErrBinlogUnsafeMixedStatement,
    ),
    (
        "ErrInsideTransactionPreventsSwitchSQLLogBin",
        ErrInsideTransactionPreventsSwitchSQLLogBin,
    ),
    (
        "ErrStoredFunctionPreventsSwitchSQLLogBin",
        ErrStoredFunctionPreventsSwitchSQLLogBin,
    ),
    ("ErrFailedReadFromParFile", ErrFailedReadFromParFile),
    ("ErrValuesIsNotIntType", ErrValuesIsNotIntType),
    ("ErrAccessDeniedNoPassword", ErrAccessDeniedNoPassword),
    ("ErrSetPasswordAuthPlugin", ErrSetPasswordAuthPlugin),
    ("ErrGrantPluginUserExists", ErrGrantPluginUserExists),
    ("ErrTruncateIllegalForeignKey", ErrTruncateIllegalForeignKey),
    ("ErrPluginIsPermanent", ErrPluginIsPermanent),
    ("ErrStmtCacheFull", ErrStmtCacheFull),
    ("ErrMultiUpdateKeyConflict", ErrMultiUpdateKeyConflict),
    ("ErrTableNeedsRebuild", ErrTableNeedsRebuild),
    ("WarnOptionBelowLimit", WarnOptionBelowLimit),
    ("ErrIndexColumnTooLong", ErrIndexColumnTooLong),
    ("ErrErrorInTriggerBody", ErrErrorInTriggerBody),
    ("ErrErrorInUnknownTriggerBody", ErrErrorInUnknownTriggerBody),
    ("ErrIndexCorrupt", ErrIndexCorrupt),
    ("ErrUndoRecordTooBig", ErrUndoRecordTooBig),
    ("ErrPluginNoUninstall", ErrPluginNoUninstall),
    ("ErrPluginNoInstall", ErrPluginNoInstall),
    ("ErrBinlogUnsafeInsertTwoKeys", ErrBinlogUnsafeInsertTwoKeys),
    ("ErrTableInFkCheck", ErrTableInFkCheck),
    ("ErrUnsupportedEngine", ErrUnsupportedEngine),
    (
        "ErrBinlogUnsafeAutoincNotFirst",
        ErrBinlogUnsafeAutoincNotFirst,
    ),
    ("ErrCannotLoadFromTableV2", ErrCannotLoadFromTableV2),
    (
        "ErrOnlyFdAndRbrEventsAllowedInBinlogStatement",
        ErrOnlyFdAndRbrEventsAllowedInBinlogStatement,
    ),
    (
        "ErrPartitionExchangeDifferentOption",
        ErrPartitionExchangeDifferentOption,
    ),
    (
        "ErrPartitionExchangePartTable",
        ErrPartitionExchangePartTable,
    ),
    (
        "ErrPartitionExchangeTempTable",
        ErrPartitionExchangeTempTable,
    ),
    (
        "ErrPartitionInsteadOfSubpartition",
        ErrPartitionInsteadOfSubpartition,
    ),
    ("ErrUnknownPartition", ErrUnknownPartition),
    ("ErrTablesDifferentMetadata", ErrTablesDifferentMetadata),
    ("ErrRowDoesNotMatchPartition", ErrRowDoesNotMatchPartition),
    (
        "ErrBinlogCacheSizeGreaterThanMax",
        ErrBinlogCacheSizeGreaterThanMax,
    ),
    ("ErrWarnIndexNotApplicable", ErrWarnIndexNotApplicable),
    (
        "ErrPartitionExchangeForeignKey",
        ErrPartitionExchangeForeignKey,
    ),
    ("ErrNoSuchKeyValue", ErrNoSuchKeyValue),
    ("ErrRplInfoDataTooLong", ErrRplInfoDataTooLong),
    (
        "ErrNetworkReadEventChecksumFailure",
        ErrNetworkReadEventChecksumFailure,
    ),
    (
        "ErrBinlogReadEventChecksumFailure",
        ErrBinlogReadEventChecksumFailure,
    ),
    (
        "ErrBinlogStmtCacheSizeGreaterThanMax",
        ErrBinlogStmtCacheSizeGreaterThanMax,
    ),
    (
        "ErrCantUpdateTableInCreateTableSelect",
        ErrCantUpdateTableInCreateTableSelect,
    ),
    (
        "ErrPartitionClauseOnNonpartitioned",
        ErrPartitionClauseOnNonpartitioned,
    ),
    (
        "ErrRowDoesNotMatchGivenPartitionSet",
        ErrRowDoesNotMatchGivenPartitionSet,
    ),
    ("ErrNoSuchPartitionunused", ErrNoSuchPartitionunused),
    (
        "ErrChangeRplInfoRepositoryFailure",
        ErrChangeRplInfoRepositoryFailure,
    ),
    (
        "ErrWarningNotCompleteRollbackWithCreatedTempTable",
        ErrWarningNotCompleteRollbackWithCreatedTempTable,
    ),
    (
        "ErrWarningNotCompleteRollbackWithDroppedTempTable",
        ErrWarningNotCompleteRollbackWithDroppedTempTable,
    ),
    ("ErrMtsUpdatedDBsGreaterMax", ErrMtsUpdatedDBsGreaterMax),
    ("ErrMtsCantParallel", ErrMtsCantParallel),
    ("ErrMtsInconsistentData", ErrMtsInconsistentData),
    (
        "ErrFulltextNotSupportedWithPartitioning",
        ErrFulltextNotSupportedWithPartitioning,
    ),
    ("ErrDaInvalidConditionNumber", ErrDaInvalidConditionNumber),
    ("ErrInsecurePlainText", ErrInsecurePlainText),
    (
        "ErrForeignDuplicateKeyWithChildInfo",
        ErrForeignDuplicateKeyWithChildInfo,
    ),
    (
        "ErrForeignDuplicateKeyWithoutChildInfo",
        ErrForeignDuplicateKeyWithoutChildInfo,
    ),
    ("ErrTableHasNoFt", ErrTableHasNoFt),
    (
        "ErrVariableNotSettableInSfOrTrigger",
        ErrVariableNotSettableInSfOrTrigger,
    ),
    (
        "ErrVariableNotSettableInTransaction",
        ErrVariableNotSettableInTransaction,
    ),
    (
        "ErrGtidNextIsNotInGtidNextList",
        ErrGtidNextIsNotInGtidNextList,
    ),
    (
        "ErrCantChangeGtidNextInTransactionWhenGtidNextListIsNull",
        ErrCantChangeGtidNextInTransactionWhenGtidNextListIsNull,
    ),
    (
        "ErrSetStatementCannotInvokeFunction",
        ErrSetStatementCannotInvokeFunction,
    ),
    (
        "ErrGtidNextCantBeAutomaticIfGtidNextListIsNonNull",
        ErrGtidNextCantBeAutomaticIfGtidNextListIsNonNull,
    ),
    ("ErrSkippingLoggedTransaction", ErrSkippingLoggedTransaction),
    (
        "ErrMalformedGtidSetSpecification",
        ErrMalformedGtidSetSpecification,
    ),
    ("ErrMalformedGtidSetEncoding", ErrMalformedGtidSetEncoding),
    (
        "ErrMalformedGtidSpecification",
        ErrMalformedGtidSpecification,
    ),
    ("ErrGnoExhausted", ErrGnoExhausted),
    (
        "ErrCantDoImplicitCommitInTrxWhenGtidNextIsSet",
        ErrCantDoImplicitCommitInTrxWhenGtidNextIsSet,
    ),
    (
        "ErrGtidMode2Or3RequiresEnforceGtidConsistencyOn",
        ErrGtidMode2Or3RequiresEnforceGtidConsistencyOn,
    ),
    (
        "ErrCantSetGtidNextToGtidWhenGtidModeIsOff",
        ErrCantSetGtidNextToGtidWhenGtidModeIsOff,
    ),
    (
        "ErrCantSetGtidNextToAnonymousWhenGtidModeIsOn",
        ErrCantSetGtidNextToAnonymousWhenGtidModeIsOn,
    ),
    (
        "ErrCantSetGtidNextListToNonNullWhenGtidModeIsOff",
        ErrCantSetGtidNextListToNonNullWhenGtidModeIsOff,
    ),
    (
        "ErrFoundGtidEventWhenGtidModeIsOff",
        ErrFoundGtidEventWhenGtidModeIsOff,
    ),
    (
        "ErrGtidUnsafeNonTransactionalTable",
        ErrGtidUnsafeNonTransactionalTable,
    ),
    ("ErrGtidUnsafeCreateSelect", ErrGtidUnsafeCreateSelect),
    (
        "ErrGtidUnsafeCreateDropTemporaryTableInTransaction",
        ErrGtidUnsafeCreateDropTemporaryTableInTransaction,
    ),
    (
        "ErrGtidModeCanOnlyChangeOneStepAtATime",
        ErrGtidModeCanOnlyChangeOneStepAtATime,
    ),
    (
        "ErrCantSetGtidNextWhenOwningGtid",
        ErrCantSetGtidNextWhenOwningGtid,
    ),
    ("ErrUnknownExplainFormat", ErrUnknownExplainFormat),
    (
        "ErrCantExecuteInReadOnlyTransaction",
        ErrCantExecuteInReadOnlyTransaction,
    ),
    (
        "ErrTooLongTablePartitionComment",
        ErrTooLongTablePartitionComment,
    ),
    ("ErrInnodbFtLimit", ErrInnodbFtLimit),
    ("ErrInnodbNoFtTempTable", ErrInnodbNoFtTempTable),
    ("ErrInnodbFtWrongDocidColumn", ErrInnodbFtWrongDocidColumn),
    ("ErrInnodbFtWrongDocidIndex", ErrInnodbFtWrongDocidIndex),
    ("ErrInnodbOnlineLogTooBig", ErrInnodbOnlineLogTooBig),
    ("ErrUnknownAlterAlgorithm", ErrUnknownAlterAlgorithm),
    ("ErrUnknownAlterLock", ErrUnknownAlterLock),
    ("ErrMtsResetWorkers", ErrMtsResetWorkers),
    (
        "ErrColCountDoesntMatchCorruptedV2",
        ErrColCountDoesntMatchCorruptedV2,
    ),
    ("ErrDiscardFkChecksRunning", ErrDiscardFkChecksRunning),
    ("ErrTableSchemaMismatch", ErrTableSchemaMismatch),
    ("ErrTableInSystemTablespace", ErrTableInSystemTablespace),
    ("ErrIoRead", ErrIoRead),
    ("ErrIoWrite", ErrIoWrite),
    ("ErrTablespaceMissing", ErrTablespaceMissing),
    ("ErrTablespaceExists", ErrTablespaceExists),
    ("ErrTablespaceDiscarded", ErrTablespaceDiscarded),
    ("ErrInternal", ErrInternal),
    ("ErrInnodbImport", ErrInnodbImport),
    ("ErrInnodbIndexCorrupt", ErrInnodbIndexCorrupt),
    ("ErrInvalidYearColumnLength", ErrInvalidYearColumnLength),
    ("ErrNotValidPassword", ErrNotValidPassword),
    ("ErrMustChangePassword", ErrMustChangePassword),
    ("ErrFkNoIndexChild", ErrFkNoIndexChild),
    ("ErrForeignKeyNoIndexInParent", ErrForeignKeyNoIndexInParent),
    ("ErrFkFailAddSystem", ErrFkFailAddSystem),
    (
        "ErrForeignKeyCannotOpenParent",
        ErrForeignKeyCannotOpenParent,
    ),
    ("ErrFkIncorrectOption", ErrFkIncorrectOption),
    ("ErrFkDupName", ErrFkDupName),
    ("ErrPasswordFormat", ErrPasswordFormat),
    ("ErrFkColumnCannotDrop", ErrFkColumnCannotDrop),
    ("ErrFkColumnCannotDropChild", ErrFkColumnCannotDropChild),
    ("ErrForeignKeyColumnNotNull", ErrForeignKeyColumnNotNull),
    ("ErrDupIndex", ErrDupIndex),
    (
        "ErrForeignKeyColumnCannotChange",
        ErrForeignKeyColumnCannotChange,
    ),
    (
        "ErrForeignKeyColumnCannotChangeChild",
        ErrForeignKeyColumnCannotChangeChild,
    ),
    ("ErrFkCannotDeleteParent", ErrFkCannotDeleteParent),
    ("ErrMalformedPacket", ErrMalformedPacket),
    ("ErrReadOnlyMode", ErrReadOnlyMode),
    ("ErrVariableNotSettableInSp", ErrVariableNotSettableInSp),
    (
        "ErrCantSetGtidPurgedWhenGtidModeIsOff",
        ErrCantSetGtidPurgedWhenGtidModeIsOff,
    ),
    (
        "ErrCantSetGtidPurgedWhenGtidExecutedIsNotEmpty",
        ErrCantSetGtidPurgedWhenGtidExecutedIsNotEmpty,
    ),
    (
        "ErrCantSetGtidPurgedWhenOwnedGtidsIsNotEmpty",
        ErrCantSetGtidPurgedWhenOwnedGtidsIsNotEmpty,
    ),
    ("ErrGtidPurgedWasChanged", ErrGtidPurgedWasChanged),
    ("ErrGtidExecutedWasChanged", ErrGtidExecutedWasChanged),
    (
        "ErrBinlogStmtModeAndNoReplTables",
        ErrBinlogStmtModeAndNoReplTables,
    ),
    (
        "ErrAlterOperationNotSupported",
        ErrAlterOperationNotSupported,
    ),
    (
        "ErrAlterOperationNotSupportedReason",
        ErrAlterOperationNotSupportedReason,
    ),
    (
        "ErrAlterOperationNotSupportedReasonCopy",
        ErrAlterOperationNotSupportedReasonCopy,
    ),
    (
        "ErrAlterOperationNotSupportedReasonPartition",
        ErrAlterOperationNotSupportedReasonPartition,
    ),
    (
        "ErrAlterOperationNotSupportedReasonFkRename",
        ErrAlterOperationNotSupportedReasonFkRename,
    ),
    (
        "ErrAlterOperationNotSupportedReasonColumnType",
        ErrAlterOperationNotSupportedReasonColumnType,
    ),
    (
        "ErrAlterOperationNotSupportedReasonFkCheck",
        ErrAlterOperationNotSupportedReasonFkCheck,
    ),
    (
        "ErrAlterOperationNotSupportedReasonIgnore",
        ErrAlterOperationNotSupportedReasonIgnore,
    ),
    (
        "ErrAlterOperationNotSupportedReasonNopk",
        ErrAlterOperationNotSupportedReasonNopk,
    ),
    (
        "ErrAlterOperationNotSupportedReasonAutoinc",
        ErrAlterOperationNotSupportedReasonAutoinc,
    ),
    (
        "ErrAlterOperationNotSupportedReasonHiddenFts",
        ErrAlterOperationNotSupportedReasonHiddenFts,
    ),
    (
        "ErrAlterOperationNotSupportedReasonChangeFts",
        ErrAlterOperationNotSupportedReasonChangeFts,
    ),
    (
        "ErrAlterOperationNotSupportedReasonFts",
        ErrAlterOperationNotSupportedReasonFts,
    ),
    ("ErrDupUnknownInIndex", ErrDupUnknownInIndex),
    ("ErrIdentCausesTooLongPath", ErrIdentCausesTooLongPath),
    (
        "ErrAlterOperationNotSupportedReasonNotNull",
        ErrAlterOperationNotSupportedReasonNotNull,
    ),
    ("ErrMustChangePasswordLogin", ErrMustChangePasswordLogin),
    ("ErrRowInWrongPartition", ErrRowInWrongPartition),
    ("ErrErrorLast", ErrErrorLast),
    (
        "ErrForeignKeyCascadeDepthExceeded",
        ErrForeignKeyCascadeDepthExceeded,
    ),
    ("ErrInvalidFieldSize", ErrInvalidFieldSize),
    (
        "ErrPasswordExpireAnonymousUser",
        ErrPasswordExpireAnonymousUser,
    ),
    (
        "ErrInvalidArgumentForLogarithm",
        ErrInvalidArgumentForLogarithm,
    ),
    ("ErrMaxExecTimeExceeded", ErrMaxExecTimeExceeded),
    ("ErrAggregateOrderNonAggQuery", ErrAggregateOrderNonAggQuery),
    ("ErrUserLockWrongName", ErrUserLockWrongName),
    ("ErrUserLockDeadlock", ErrUserLockDeadlock),
    ("ErrIncorrectType", ErrIncorrectType),
    ("ErrFieldInOrderNotSelect", ErrFieldInOrderNotSelect),
    ("ErrAggregateInOrderNotSelect", ErrAggregateInOrderNotSelect),
    ("ErrInvalidJSONData", ErrInvalidJSONData),
    (
        "ErrGeneratedColumnFunctionIsNotAllowed",
        ErrGeneratedColumnFunctionIsNotAllowed,
    ),
    (
        "ErrUnsupportedAlterInplaceOnVirtualColumn",
        ErrUnsupportedAlterInplaceOnVirtualColumn,
    ),
    (
        "ErrWrongFKOptionForGeneratedColumn",
        ErrWrongFKOptionForGeneratedColumn,
    ),
    ("ErrBadGeneratedColumn", ErrBadGeneratedColumn),
    (
        "ErrUnsupportedOnGeneratedColumn",
        ErrUnsupportedOnGeneratedColumn,
    ),
    ("ErrGeneratedColumnNonPrior", ErrGeneratedColumnNonPrior),
    (
        "ErrDependentByGeneratedColumn",
        ErrDependentByGeneratedColumn,
    ),
    ("ErrGeneratedColumnRefAutoInc", ErrGeneratedColumnRefAutoInc),
    ("ErrAccountHasBeenLocked", ErrAccountHasBeenLocked),
    ("ErrWarnConflictingHint", ErrWarnConflictingHint),
    ("ErrUnresolvedHintName", ErrUnresolvedHintName),
    ("ErrInvalidJSONText", ErrInvalidJSONText),
    ("ErrInvalidJSONTextInParam", ErrInvalidJSONTextInParam),
    ("ErrInvalidJSONPath", ErrInvalidJSONPath),
    ("ErrInvalidJSONCharset", ErrInvalidJSONCharset),
    ("ErrInvalidTypeForJSON", ErrInvalidTypeForJSON),
    (
        "ErrInvalidJSONPathMultipleSelection",
        ErrInvalidJSONPathMultipleSelection,
    ),
    (
        "ErrInvalidJSONContainsPathType",
        ErrInvalidJSONContainsPathType,
    ),
    ("ErrJSONUsedAsKey", ErrJSONUsedAsKey),
    ("ErrJSONVacuousPath", ErrJSONVacuousPath),
    ("ErrJSONBadOneOrAllArg", ErrJSONBadOneOrAllArg),
    ("ErrJSONDocumentTooDeep", ErrJSONDocumentTooDeep),
    ("ErrJSONDocumentNULLKey", ErrJSONDocumentNULLKey),
    ("ErrSecureTransportRequired", ErrSecureTransportRequired),
    ("ErrBadUser", ErrBadUser),
    ("ErrUserAlreadyExists", ErrUserAlreadyExists),
    ("ErrInvalidJSONPathArrayCell", ErrInvalidJSONPathArrayCell),
    ("ErrInvalidEncryptionOption", ErrInvalidEncryptionOption),
    ("ErrTooLongValueForType", ErrTooLongValueForType),
    ("ErrPKIndexCantBeInvisible", ErrPKIndexCantBeInvisible),
    ("ErrGrantRole", ErrGrantRole),
    ("ErrRoleNotGranted", ErrRoleNotGranted),
    (
        "ErrLockAcquireFailAndNoWaitSet",
        ErrLockAcquireFailAndNoWaitSet,
    ),
    ("ErrCTERecursiveRequiresUnion", ErrCTERecursiveRequiresUnion),
    (
        "ErrCTERecursiveRequiresNonRecursiveFirst",
        ErrCTERecursiveRequiresNonRecursiveFirst,
    ),
    (
        "ErrCTERecursiveForbidsAggregation",
        ErrCTERecursiveForbidsAggregation,
    ),
    (
        "ErrCTERecursiveForbiddenJoinOrder",
        ErrCTERecursiveForbiddenJoinOrder,
    ),
    (
        "ErrInvalidRequiresSingleReference",
        ErrInvalidRequiresSingleReference,
    ),
    ("ErrWindowNoSuchWindow", ErrWindowNoSuchWindow),
    (
        "ErrWindowCircularityInWindowGraph",
        ErrWindowCircularityInWindowGraph,
    ),
    ("ErrWindowNoChildPartitioning", ErrWindowNoChildPartitioning),
    ("ErrWindowNoInherentFrame", ErrWindowNoInherentFrame),
    ("ErrWindowNoRedefineOrderBy", ErrWindowNoRedefineOrderBy),
    ("ErrWindowFrameStartIllegal", ErrWindowFrameStartIllegal),
    ("ErrWindowFrameEndIllegal", ErrWindowFrameEndIllegal),
    ("ErrWindowFrameIllegal", ErrWindowFrameIllegal),
    ("ErrWindowRangeFrameOrderType", ErrWindowRangeFrameOrderType),
    (
        "ErrWindowRangeFrameTemporalType",
        ErrWindowRangeFrameTemporalType,
    ),
    (
        "ErrWindowRangeFrameNumericType",
        ErrWindowRangeFrameNumericType,
    ),
    (
        "ErrWindowRangeBoundNotConstant",
        ErrWindowRangeBoundNotConstant,
    ),
    ("ErrWindowDuplicateName", ErrWindowDuplicateName),
    ("ErrWindowIllegalOrderBy", ErrWindowIllegalOrderBy),
    (
        "ErrWindowInvalidWindowFuncUse",
        ErrWindowInvalidWindowFuncUse,
    ),
    (
        "ErrWindowInvalidWindowFuncAliasUse",
        ErrWindowInvalidWindowFuncAliasUse,
    ),
    (
        "ErrWindowNestedWindowFuncUseInWindowSpec",
        ErrWindowNestedWindowFuncUseInWindowSpec,
    ),
    ("ErrWindowRowsIntervalUse", ErrWindowRowsIntervalUse),
    ("ErrWindowNoGroupOrderUnused", ErrWindowNoGroupOrderUnused),
    ("ErrWindowExplainJSON", ErrWindowExplainJSON),
    (
        "ErrWindowFunctionIgnoresFrame",
        ErrWindowFunctionIgnoresFrame,
    ),
    ("ErrInvalidNumberOfArgs", ErrInvalidNumberOfArgs),
    ("ErrFieldInGroupingNotGroupBy", ErrFieldInGroupingNotGroupBy),
    ("ErrIllegalPrivilegeLevel", ErrIllegalPrivilegeLevel),
    ("ErrCTEMaxRecursionDepth", ErrCTEMaxRecursionDepth),
    ("ErrNotHintUpdatable", ErrNotHintUpdatable),
    ("ErrExistsInHistoryPassword", ErrExistsInHistoryPassword),
    (
        "ErrInvalidDefaultUTF8MB4Collation",
        ErrInvalidDefaultUTF8MB4Collation,
    ),
    (
        "ErrForeignKeyCannotDropParent",
        ErrForeignKeyCannotDropParent,
    ),
    (
        "ErrForeignKeyCannotUseVirtualColumn",
        ErrForeignKeyCannotUseVirtualColumn,
    ),
    (
        "ErrForeignKeyNoColumnInParent",
        ErrForeignKeyNoColumnInParent,
    ),
    (
        "ErrDataTruncatedFunctionalIndex",
        ErrDataTruncatedFunctionalIndex,
    ),
    (
        "ErrDataOutOfRangeFunctionalIndex",
        ErrDataOutOfRangeFunctionalIndex,
    ),
    (
        "ErrFunctionalIndexOnJSONOrGeometryFunction",
        ErrFunctionalIndexOnJSONOrGeometryFunction,
    ),
    (
        "ErrFunctionalIndexRefAutoIncrement",
        ErrFunctionalIndexRefAutoIncrement,
    ),
    (
        "ErrCannotDropColumnFunctionalIndex",
        ErrCannotDropColumnFunctionalIndex,
    ),
    ("ErrFunctionalIndexPrimaryKey", ErrFunctionalIndexPrimaryKey),
    ("ErrFunctionalIndexOnBlob", ErrFunctionalIndexOnBlob),
    (
        "ErrFunctionalIndexFunctionIsNotAllowed",
        ErrFunctionalIndexFunctionIsNotAllowed,
    ),
    ("ErrFulltextFunctionalIndex", ErrFulltextFunctionalIndex),
    ("ErrSpatialFunctionalIndex", ErrSpatialFunctionalIndex),
    (
        "ErrWrongKeyColumnFunctionalIndex",
        ErrWrongKeyColumnFunctionalIndex,
    ),
    ("ErrFunctionalIndexOnField", ErrFunctionalIndexOnField),
    (
        "ErrGeneratedColumnRowValueIsNotAllowed",
        ErrGeneratedColumnRowValueIsNotAllowed,
    ),
    (
        "ErrDefValGeneratedNamedFunctionIsNotAllowed",
        ErrDefValGeneratedNamedFunctionIsNotAllowed,
    ),
    ("ErrFKIncompatibleColumns", ErrFKIncompatibleColumns),
    (
        "ErrFunctionalIndexRowValueIsNotAllowed",
        ErrFunctionalIndexRowValueIsNotAllowed,
    ),
    ("ErrInvalidLateralJoin", ErrInvalidLateralJoin),
    (
        "ErrNonBooleanExprForCheckConstraint",
        ErrNonBooleanExprForCheckConstraint,
    ),
    (
        "ErrColumnCheckConstraintReferencesOtherColumn",
        ErrColumnCheckConstraintReferencesOtherColumn,
    ),
    (
        "ErrCheckConstraintNamedFunctionIsNotAllowed",
        ErrCheckConstraintNamedFunctionIsNotAllowed,
    ),
    (
        "ErrCheckConstraintFunctionIsNotAllowed",
        ErrCheckConstraintFunctionIsNotAllowed,
    ),
    ("ErrCheckConstraintVariables", ErrCheckConstraintVariables),
    (
        "ErrCheckConstraintRefersAutoIncrementColumn",
        ErrCheckConstraintRefersAutoIncrementColumn,
    ),
    ("ErrCheckConstraintViolated", ErrCheckConstraintViolated),
    (
        "ErrTableCheckConstraintReferUnknown",
        ErrTableCheckConstraintReferUnknown,
    ),
    ("ErrCheckConstraintDupName", ErrCheckConstraintDupName),
    (
        "ErrCheckConstraintClauseUsingFKReferActionColumn",
        ErrCheckConstraintClauseUsingFKReferActionColumn,
    ),
    (
        "ErrDependentByFunctionalIndex",
        ErrDependentByFunctionalIndex,
    ),
    ("ErrInvalidJSONType", ErrInvalidJSONType),
    ("ErrCannotConvertString", ErrCannotConvertString),
    (
        "ErrDependentByPartitionFunctional",
        ErrDependentByPartitionFunctional,
    ),
    (
        "ErrInvalidJSONValueForFuncIndex",
        ErrInvalidJSONValueForFuncIndex,
    ),
    (
        "ErrJSONValueOutOfRangeForFuncIndex",
        ErrJSONValueOutOfRangeForFuncIndex,
    ),
    (
        "ErrFunctionalIndexDataIsTooLong",
        ErrFunctionalIndexDataIsTooLong,
    ),
    (
        "ErrFunctionalIndexNotApplicable",
        ErrFunctionalIndexNotApplicable,
    ),
    (
        "ErrDynamicPrivilegeNotRegistered",
        ErrDynamicPrivilegeNotRegistered,
    ),
    ("ErrConstraintNotFound", ErrConstraintNotFound),
    (
        "ErUserAccessDeniedForUserAccountBlockedByPasswordLock",
        ErUserAccessDeniedForUserAccountBlockedByPasswordLock,
    ),
    (
        "ErrDependentByCheckConstraint",
        ErrDependentByCheckConstraint,
    ),
    (
        "ErrEngineAttributeNotSupported",
        ErrEngineAttributeNotSupported,
    ),
    ("ErrJSONInBooleanContext", ErrJSONInBooleanContext),
    ("ErrTableWithoutPrimaryKey", ErrTableWithoutPrimaryKey),
    (
        "ErrSecondPasswordCannotBeEmpty",
        ErrSecondPasswordCannotBeEmpty,
    ),
    (
        "ErrPasswordCannotBeRetainedOnPluginChange",
        ErrPasswordCannotBeRetainedOnPluginChange,
    ),
    (
        "ErrCurrentPasswordCannotBeRetained",
        ErrCurrentPasswordCannotBeRetained,
    ),
    (
        "ErrOnlyOneDefaultPartionAllowed",
        ErrOnlyOneDefaultPartionAllowed,
    ),
    (
        "ErrWrongPartitionTypeExpectedSystemTime",
        ErrWrongPartitionTypeExpectedSystemTime,
    ),
    (
        "ErrSystemVersioningWrongPartitions",
        ErrSystemVersioningWrongPartitions,
    ),
    ("ErrSequenceRunOut", ErrSequenceRunOut),
    ("ErrSequenceInvalidData", ErrSequenceInvalidData),
    ("ErrSequenceAccessFail", ErrSequenceAccessFail),
    ("ErrNotSequence", ErrNotSequence),
    ("ErrUnknownSequence", ErrUnknownSequence),
    ("ErrWrongInsertIntoSequence", ErrWrongInsertIntoSequence),
    (
        "ErrSequenceInvalidTableStructure",
        ErrSequenceInvalidTableStructure,
    ),
    ("ErrMemExceedThreshold", ErrMemExceedThreshold),
    ("ErrForUpdateCantRetry", ErrForUpdateCantRetry),
    ("ErrAdminCheckTable", ErrAdminCheckTable),
    ("ErrTxnTooLarge", ErrTxnTooLarge),
    ("ErrWriteConflictInTiDB", ErrWriteConflictInTiDB),
    ("ErrOptOnTemporaryTable", ErrOptOnTemporaryTable),
    ("ErrDropTableOnTemporaryTable", ErrDropTableOnTemporaryTable),
    ("ErrUnsupportedReloadPlugin", ErrUnsupportedReloadPlugin),
    (
        "ErrUnsupportedReloadPluginVar",
        ErrUnsupportedReloadPluginVar,
    ),
    ("ErrTableLocked", ErrTableLocked),
    ("ErrNotExist", ErrNotExist),
    ("ErrTxnRetryable", ErrTxnRetryable),
    ("ErrCannotSetNilValue", ErrCannotSetNilValue),
    ("ErrInvalidTxn", ErrInvalidTxn),
    ("ErrEntryTooLarge", ErrEntryTooLarge),
    ("ErrNotImplemented", ErrNotImplemented),
    ("ErrInfoSchemaExpired", ErrInfoSchemaExpired),
    ("ErrInfoSchemaChanged", ErrInfoSchemaChanged),
    ("ErrBadNumber", ErrBadNumber),
    ("ErrCastAsSignedOverflow", ErrCastAsSignedOverflow),
    ("ErrCastNegIntAsUnsigned", ErrCastNegIntAsUnsigned),
    ("ErrInvalidYearFormat", ErrInvalidYearFormat),
    ("ErrInvalidYear", ErrInvalidYear),
    ("ErrIncorrectDatetimeValue", ErrIncorrectDatetimeValue),
    ("ErrInvalidTimeFormat", ErrInvalidTimeFormat),
    ("ErrInvalidWeekModeFormat", ErrInvalidWeekModeFormat),
    ("ErrFieldGetDefaultFailed", ErrFieldGetDefaultFailed),
    ("ErrIndexOutBound", ErrIndexOutBound),
    ("ErrUnsupportedOp", ErrUnsupportedOp),
    ("ErrRowNotFound", ErrRowNotFound),
    ("ErrTableStateCantNone", ErrTableStateCantNone),
    ("ErrColumnStateNonPublic", ErrColumnStateNonPublic),
    ("ErrIndexStateCantNone", ErrIndexStateCantNone),
    ("ErrInvalidRecordKey", ErrInvalidRecordKey),
    ("ErrColumnStateCantNone", ErrColumnStateCantNone),
    ("ErrUnsupportedValueForVar", ErrUnsupportedValueForVar),
    ("ErrUnsupportedIsolationLevel", ErrUnsupportedIsolationLevel),
    ("ErrLoadPrivilege", ErrLoadPrivilege),
    ("ErrInvalidPrivilegeType", ErrInvalidPrivilegeType),
    ("ErrUnknownFieldType", ErrUnknownFieldType),
    ("ErrInvalidSequence", ErrInvalidSequence),
    ("ErrCantGetValidID", ErrCantGetValidID),
    ("ErrCantSetToNull", ErrCantSetToNull),
    ("ErrSnapshotTooOld", ErrSnapshotTooOld),
    ("ErrInvalidTableID", ErrInvalidTableID),
    ("ErrInvalidType", ErrInvalidType),
    ("ErrUnknownAllocatorType", ErrUnknownAllocatorType),
    ("ErrAutoRandReadFailed", ErrAutoRandReadFailed),
    ("ErrInvalidIncrementAndOffset", ErrInvalidIncrementAndOffset),
    (
        "ErrWarnOptimizerHintUnsupportedHint",
        ErrWarnOptimizerHintUnsupportedHint,
    ),
    (
        "ErrWarnOptimizerHintInvalidToken",
        ErrWarnOptimizerHintInvalidToken,
    ),
    ("ErrWarnMemoryQuotaOverflow", ErrWarnMemoryQuotaOverflow),
    (
        "ErrWarnOptimizerHintParseError",
        ErrWarnOptimizerHintParseError,
    ),
    (
        "ErrWarnOptimizerHintInvalidInteger",
        ErrWarnOptimizerHintInvalidInteger,
    ),
    ("ErrWarnOptimizerHintWrongPos", ErrWarnOptimizerHintWrongPos),
    (
        "ErrUnsupportedSecondArgumentType",
        ErrUnsupportedSecondArgumentType,
    ),
    ("ErrColumnNotMatched", ErrColumnNotMatched),
    ("ErrInvalidPluginID", ErrInvalidPluginID),
    ("ErrInvalidPluginManifest", ErrInvalidPluginManifest),
    ("ErrInvalidPluginName", ErrInvalidPluginName),
    ("ErrInvalidPluginVersion", ErrInvalidPluginVersion),
    ("ErrDuplicatePlugin", ErrDuplicatePlugin),
    ("ErrInvalidPluginSysVarName", ErrInvalidPluginSysVarName),
    ("ErrRequireVersionCheckFail", ErrRequireVersionCheckFail),
    ("ErrUnsupportedType", ErrUnsupportedType),
    ("ErrAnalyzeMissIndex", ErrAnalyzeMissIndex),
    (
        "ErrCartesianProductUnsupported",
        ErrCartesianProductUnsupported,
    ),
    ("ErrPreparedStmtNotFound", ErrPreparedStmtNotFound),
    ("ErrWrongParamCount", ErrWrongParamCount),
    ("ErrSchemaChanged", ErrSchemaChanged),
    ("ErrUnknownPlan", ErrUnknownPlan),
    ("ErrPrepareMulti", ErrPrepareMulti),
    ("ErrPrepareDDL", ErrPrepareDDL),
    ("ErrResultIsEmpty", ErrResultIsEmpty),
    ("ErrBuildExecutor", ErrBuildExecutor),
    ("ErrBatchInsertFail", ErrBatchInsertFail),
    ("ErrGetStartTS", ErrGetStartTS),
    ("ErrPrivilegeCheckFail", ErrPrivilegeCheckFail),
    ("ErrInvalidWildCard", ErrInvalidWildCard),
    (
        "ErrMixOfGroupFuncAndFieldsIncompatible",
        ErrMixOfGroupFuncAndFieldsIncompatible,
    ),
    ("ErrBRIEBackupFailed", ErrBRIEBackupFailed),
    ("ErrBRIERestoreFailed", ErrBRIERestoreFailed),
    ("ErrBRIEImportFailed", ErrBRIEImportFailed),
    ("ErrBRIEExportFailed", ErrBRIEExportFailed),
    ("ErrInvalidTableSample", ErrInvalidTableSample),
    ("ErrJSONObjectKeyTooLong", ErrJSONObjectKeyTooLong),
    ("ErrMultiStatementDisabled", ErrMultiStatementDisabled),
    ("ErrPartitionStatsMissing", ErrPartitionStatsMissing),
    ("ErrNotSupportedWithSem", ErrNotSupportedWithSem),
    (
        "ErrDataInconsistentMismatchCount",
        ErrDataInconsistentMismatchCount,
    ),
    (
        "ErrDataInconsistentMismatchIndex",
        ErrDataInconsistentMismatchIndex,
    ),
    ("ErrAsOf", ErrAsOf),
    ("ErrVariableNoLongerSupported", ErrVariableNoLongerSupported),
    ("ErrAnalyzeMissColumn", ErrAnalyzeMissColumn),
    ("ErrInconsistentRowValue", ErrInconsistentRowValue),
    ("ErrInconsistentHandle", ErrInconsistentHandle),
    ("ErrInconsistentIndexedValue", ErrInconsistentIndexedValue),
    ("ErrAssertionFailed", ErrAssertionFailed),
    ("ErrInstanceScope", ErrInstanceScope),
    (
        "ErrNonTransactionalJobFailure",
        ErrNonTransactionalJobFailure,
    ),
    ("ErrSettingNoopVariable", ErrSettingNoopVariable),
    ("ErrGettingNoopVariable", ErrGettingNoopVariable),
    ("ErrCannotMigrateSession", ErrCannotMigrateSession),
    (
        "ErrLazyUniquenessCheckFailure",
        ErrLazyUniquenessCheckFailure,
    ),
    (
        "ErrUnsupportedColumnInTTLConfig",
        ErrUnsupportedColumnInTTLConfig,
    ),
    ("ErrTTLColumnCannotDrop", ErrTTLColumnCannotDrop),
    (
        "ErrSetTTLOptionForNonTTLTable",
        ErrSetTTLOptionForNonTTLTable,
    ),
    (
        "ErrTempTableNotAllowedWithTTL",
        ErrTempTableNotAllowedWithTTL,
    ),
    (
        "ErrUnsupportedTTLReferencedByFK",
        ErrUnsupportedTTLReferencedByFK,
    ),
    (
        "ErrUnsupportedPrimaryKeyTypeWithTTL",
        ErrUnsupportedPrimaryKeyTypeWithTTL,
    ),
    ("ErrLoadDataFromServerDisk", ErrLoadDataFromServerDisk),
    ("ErrLoadParquetFromLocal", ErrLoadParquetFromLocal),
    ("ErrLoadDataEmptyPath", ErrLoadDataEmptyPath),
    ("ErrLoadDataUnsupportedFormat", ErrLoadDataUnsupportedFormat),
    ("ErrLoadDataInvalidURI", ErrLoadDataInvalidURI),
    ("ErrLoadDataCantAccess", ErrLoadDataCantAccess),
    ("ErrLoadDataCantRead", ErrLoadDataCantRead),
    ("ErrLoadDataWrongFormatConfig", ErrLoadDataWrongFormatConfig),
    ("ErrUnknownOption", ErrUnknownOption),
    ("ErrInvalidOptionVal", ErrInvalidOptionVal),
    ("ErrDuplicateOption", ErrDuplicateOption),
    ("ErrLoadDataUnsupportedOption", ErrLoadDataUnsupportedOption),
    (
        "ErrLoadDataDuplicateKeyConflict",
        ErrLoadDataDuplicateKeyConflict,
    ),
    ("ErrLoadDataJobNotFound", ErrLoadDataJobNotFound),
    ("ErrLoadDataInvalidOperation", ErrLoadDataInvalidOperation),
    (
        "ErrLoadDataLocalUnsupportedOption",
        ErrLoadDataLocalUnsupportedOption,
    ),
    ("ErrLoadDataPreCheckFailed", ErrLoadDataPreCheckFailed),
    ("ErrBRJobNotFound", ErrBRJobNotFound),
    ("ErrMemoryExceedForQuery", ErrMemoryExceedForQuery),
    ("ErrMemoryExceedForInstance", ErrMemoryExceedForInstance),
    ("ErrDeleteNotFoundColumn", ErrDeleteNotFoundColumn),
    ("ErrKeyTooLarge", ErrKeyTooLarge),
    ("ErrTimeStampInDSTTransition", ErrTimeStampInDSTTransition),
    ("ErrQueryExecStopped", ErrQueryExecStopped),
    ("ErrUnsupportedDDLOperation", ErrUnsupportedDDLOperation),
    ("ErrNotOwner", ErrNotOwner),
    ("ErrCantDecodeRecord", ErrCantDecodeRecord),
    ("ErrInvalidDDLWorker", ErrInvalidDDLWorker),
    ("ErrInvalidDDLJob", ErrInvalidDDLJob),
    ("ErrInvalidDDLJobFlag", ErrInvalidDDLJobFlag),
    ("ErrWaitReorgTimeout", ErrWaitReorgTimeout),
    ("ErrInvalidStoreVersion", ErrInvalidStoreVersion),
    ("ErrUnknownTypeLength", ErrUnknownTypeLength),
    ("ErrUnknownFractionLength", ErrUnknownFractionLength),
    ("ErrInvalidDDLState", ErrInvalidDDLState),
    ("ErrReorgPanic", ErrReorgPanic),
    ("ErrInvalidSplitRegionRanges", ErrInvalidSplitRegionRanges),
    ("ErrInvalidDDLJobVersion", ErrInvalidDDLJobVersion),
    ("ErrCancelledDDLJob", ErrCancelledDDLJob),
    ("ErrRepairTable", ErrRepairTable),
    ("ErrInvalidAutoRandom", ErrInvalidAutoRandom),
    ("ErrInvalidHashKeyFlag", ErrInvalidHashKeyFlag),
    ("ErrInvalidListIndex", ErrInvalidListIndex),
    ("ErrInvalidListMetaData", ErrInvalidListMetaData),
    ("ErrWriteOnSnapshot", ErrWriteOnSnapshot),
    ("ErrInvalidKey", ErrInvalidKey),
    ("ErrInvalidIndexKey", ErrInvalidIndexKey),
    ("ErrDataInconsistent", ErrDataInconsistent),
    ("ErrDDLJobNotFound", ErrDDLJobNotFound),
    ("ErrCancelFinishedDDLJob", ErrCancelFinishedDDLJob),
    ("ErrCannotCancelDDLJob", ErrCannotCancelDDLJob),
    (
        "ErrSequenceUnsupportedTableOption",
        ErrSequenceUnsupportedTableOption,
    ),
    (
        "ErrColumnTypeUnsupportedNextValue",
        ErrColumnTypeUnsupportedNextValue,
    ),
    ("ErrLockExpire", ErrLockExpire),
    (
        "ErrAddColumnWithSequenceAsDefault",
        ErrAddColumnWithSequenceAsDefault,
    ),
    (
        "ErrUnsupportedConstraintCheck",
        ErrUnsupportedConstraintCheck,
    ),
    (
        "ErrTableOptionUnionUnsupported",
        ErrTableOptionUnionUnsupported,
    ),
    (
        "ErrTableOptionInsertMethodUnsupported",
        ErrTableOptionInsertMethodUnsupported,
    ),
    ("ErrDDLReorgElementNotExist", ErrDDLReorgElementNotExist),
    ("ErrPlacementPolicyCheck", ErrPlacementPolicyCheck),
    ("ErrInvalidAttributesSpec", ErrInvalidAttributesSpec),
    ("ErrPlacementPolicyExists", ErrPlacementPolicyExists),
    ("ErrPlacementPolicyNotExists", ErrPlacementPolicyNotExists),
    (
        "ErrPlacementPolicyWithDirectOption",
        ErrPlacementPolicyWithDirectOption,
    ),
    ("ErrPlacementPolicyInUse", ErrPlacementPolicyInUse),
    ("ErrOptOnCacheTable", ErrOptOnCacheTable),
    ("ErrHTTPServiceError", ErrHTTPServiceError),
    (
        "ErrPartitionColumnStatsMissing",
        ErrPartitionColumnStatsMissing,
    ),
    ("ErrColumnInChange", ErrColumnInChange),
    ("ErrDDLSetting", ErrDDLSetting),
    ("ErrIngestFailed", ErrIngestFailed),
    ("ErrIngestCheckEnvFailed", ErrIngestCheckEnvFailed),
    ("ErrProtectedTableMode", ErrProtectedTableMode),
    ("ErrInvalidTableModeSet", ErrInvalidTableModeSet),
    ("ErrCannotPauseDDLJob", ErrCannotPauseDDLJob),
    ("ErrCannotResumeDDLJob", ErrCannotResumeDDLJob),
    ("ErrPausedDDLJob", ErrPausedDDLJob),
    ("ErrBDRRestrictedDDL", ErrBDRRestrictedDDL),
    (
        "ErrGlobalIndexNotExplicitlySet",
        ErrGlobalIndexNotExplicitlySet,
    ),
    (
        "ErrWarnGlobalIndexNeedManuallyAnalyze",
        ErrWarnGlobalIndexNeedManuallyAnalyze,
    ),
    ("ErrInvalidAffinityOption", ErrInvalidAffinityOption),
    ("ErrForbiddenDDL", ErrForbiddenDDL),
    ("ErrMaskingPolicyExists", ErrMaskingPolicyExists),
    ("ErrMaskingPolicyNotExists", ErrMaskingPolicyNotExists),
    (
        "ErrMaskingPolicyExprInvalidColumn",
        ErrMaskingPolicyExprInvalidColumn,
    ),
    ("ErrDDLAutoPausedByKVDiskFull", ErrDDLAutoPausedByKVDiskFull),
    ("ErrResourceGroupExists", ErrResourceGroupExists),
    ("ErrResourceGroupNotExists", ErrResourceGroupNotExists),
    (
        "ErrResourceGroupSupportDisabled",
        ErrResourceGroupSupportDisabled,
    ),
    (
        "ErrResourceGroupConfigUnavailable",
        ErrResourceGroupConfigUnavailable,
    ),
    ("ErrResourceGroupThrottled", ErrResourceGroupThrottled),
    (
        "ErrResourceGroupQueryRunawayInterrupted",
        ErrResourceGroupQueryRunawayInterrupted,
    ),
    (
        "ErrResourceGroupQueryRunawayQuarantine",
        ErrResourceGroupQueryRunawayQuarantine,
    ),
    (
        "ErrResourceGroupInvalidBackgroundTaskName",
        ErrResourceGroupInvalidBackgroundTaskName,
    ),
    (
        "ErrResourceGroupInvalidForRole",
        ErrResourceGroupInvalidForRole,
    ),
    (
        "ErrEngineAttributeInvalidFormat",
        ErrEngineAttributeInvalidFormat,
    ),
    ("ErrStorageClassInvalidSpec", ErrStorageClassInvalidSpec),
    (
        "ErrModifyColumnReferencedByPartialCondition",
        ErrModifyColumnReferencedByPartialCondition,
    ),
    (
        "ErrCheckPartialIndexWithoutFastCheck",
        ErrCheckPartialIndexWithoutFastCheck,
    ),
    ("ErrMaxKeysReadExceeded", ErrMaxKeysReadExceeded),
    ("ErrPDServerTimeout", ErrPDServerTimeout),
    ("ErrTiKVServerTimeout", ErrTiKVServerTimeout),
    ("ErrTiKVServerBusy", ErrTiKVServerBusy),
    ("ErrResolveLockTimeout", ErrResolveLockTimeout),
    ("ErrRegionUnavailable", ErrRegionUnavailable),
    ("ErrTxnAbortedByGC", ErrTxnAbortedByGC),
    ("ErrWriteConflict", ErrWriteConflict),
    ("ErrTiKVStoreLimit", ErrTiKVStoreLimit),
    ("ErrPrometheusAddrIsNotSet", ErrPrometheusAddrIsNotSet),
    ("ErrTiKVStaleCommand", ErrTiKVStaleCommand),
    ("ErrTiKVMaxTimestampNotSynced", ErrTiKVMaxTimestampNotSynced),
    ("ErrTiFlashServerTimeout", ErrTiFlashServerTimeout),
    ("ErrTiFlashServerBusy", ErrTiFlashServerBusy),
    ("ErrTiFlashBackfillIndex", ErrTiFlashBackfillIndex),
    ("ErrUserPrefixMismatch", ErrUserPrefixMismatch),
];
