// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Parallelism and admission: executor concurrency, priorities, execution-time limits, resource control.
//!
//! `low_priority_updates` .. `tidb_window_concurrency` -- 19 entries, name-ordered.
//!
//! Captured from Go `pkg/sessionctx/variable/sysvar.go`'s `sysVars`. The
//! registry is one flat name-ordered slice because lookup binary-searches
//! it, so each subject file keeps its own entries sorted and `catalog.rs`
//! MERGES them; see the `sysvar` module doc.

use super::super::{SysVarDef, VarType};

pub(super) static ENTRIES: [SysVarDef; 19] = [
    SysVarDef {
        name: "low_priority_updates",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_execution_time",
        scope: 3,
        value: "0",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_statement_time",
        scope: 3,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "thread_concurrency",
        scope: 0,
        value: "10",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_checksum_table_concurrency",
        scope: 2,
        value: "4",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_resource_control",
        scope: 1,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_tmp_storage_on_oom",
        scope: 1,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_executor_concurrency",
        scope: 3,
        value: "5",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_force_priority",
        scope: 4,
        value: "NO_PRIORITY",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &["NO_PRIORITY", "LOW_PRIORITY", "HIGH_PRIORITY", "DELAYED"],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_hashagg_final_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_hashagg_partial_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_serial_scan_concurrency",
        scope: 3,
        value: "1",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_pipelined_dml_resource_policy",
        scope: 3,
        value: "standard",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_pprof_sql_cpu",
        scope: 4,
        value: "0",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_projection_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: -1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_resource_control_strict_mode",
        scope: 1,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_streamagg_concurrency",
        scope: 3,
        value: "1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_sysproc_scan_concurrency",
        scope: 1,
        value: "4",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_window_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
];
