// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Connections and per-session protocol state: timeouts, network sizing, session tracking, prepared statements.
//!
//! `character_set_connection` .. `wait_timeout` -- 34 entries, name-ordered.
//!
//! Captured from Go `pkg/sessionctx/variable/sysvar.go`'s `sysVars`. The
//! registry is one flat name-ordered slice because lookup binary-searches
//! it, so each subject file keeps its own entries sorted and `catalog.rs`
//! MERGES them; see the `sysvar` module doc.

use super::super::{SysVarDef, VarType};

pub(super) static ENTRIES: [SysVarDef; 34] = [
    SysVarDef {
        name: "character_set_connection",
        scope: 3,
        value: "utf8mb4",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "collation_connection",
        scope: 3,
        value: "utf8mb4_bin",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "connect_timeout",
        scope: 1,
        value: "10",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 2,
        max_value: 31536000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "hostname",
        scope: 0,
        value: "localhost",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "init_connect",
        scope: 1,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "interactive_timeout",
        scope: 3,
        value: "28800",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 31536000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "large_files_support",
        scope: 0,
        value: "1",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_connect_errors",
        scope: 1,
        value: "100",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_connections",
        scope: 4,
        value: "0",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 100000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_delayed_threads",
        scope: 3,
        value: "20",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_insert_delayed_threads",
        scope: 3,
        value: "20",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_user_connections",
        scope: 1,
        value: "0",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 100000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "net_read_timeout",
        scope: 3,
        value: "30",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "net_retry_count",
        scope: 3,
        value: "10",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "net_write_timeout",
        scope: 3,
        value: "60",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "port",
        scope: 0,
        value: "4000",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 65535,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "pseudo_thread_id",
        scope: 2,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "report_port",
        scope: 0,
        value: "3306",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "session_track_schema",
        scope: 3,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "session_track_state_change",
        scope: 3,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "session_track_system_variables",
        scope: 3,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "socket",
        scope: 0,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "thread_handling",
        scope: 0,
        value: "one-thread-per-connection",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "thread_pool_size",
        scope: 1,
        value: "16",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 64,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "thread_stack",
        scope: 0,
        value: "262144",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_dml_type",
        scope: 2,
        value: "STANDARD",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_cache_prepare_stmt",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_lazy_cursor_fetch",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_ignore_prepared_cache_close_stmt",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_last_query_info",
        scope: 2,
        value: "",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_multi_statement_mode",
        scope: 3,
        value: "OFF",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &["OFF", "ON", "WARN"],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_request_source_type",
        scope: 2,
        value: "",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[
            // Go's `tikvcliutil.ExplicitTypeList` opens with
            // `ExplicitTypeEmpty` (""), and `checkEnumSystemVar` matches BY
            // POSITION as well as by name -- so dropping it would both refuse
            // `SET @@tidb_request_source_type = ''` and shift every ordinal,
            // making `= 0` mean `lightning` instead of "no explicit source".
            "",
            "lightning",
            "br",
            "dumpling",
            "background",
            "ddl",
            "stats",
            "import",
        ],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_session_alias",
        scope: 2,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "wait_timeout",
        scope: 3,
        value: "28800",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 31536000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
];
