// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Memory ceilings and buffer sizes: per-statement quotas, sort and join buffers, cache sizes, spill-to-disk.
//!
//! `bulk_insert_buffer_size` .. `tmpdir` -- 50 entries, name-ordered.
//!
//! Captured from Go `pkg/sessionctx/variable/sysvar.go`'s `sysVars`. The
//! registry is one flat name-ordered slice because lookup binary-searches
//! it, so each subject file keeps its own entries sorted and `catalog.rs`
//! MERGES them; see the `sysvar` module doc.

use super::super::{SysVarDef, VarType};

pub(super) static ENTRIES: [SysVarDef; 50] = [
    SysVarDef {
        name: "bulk_insert_buffer_size",
        scope: 3,
        value: "8388608",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "error_count",
        scope: 2,
        value: "0",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "host_cache_size",
        scope: 1,
        value: "279",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "internal_tmp_disk_storage_engine",
        scope: 1,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "join_buffer_size",
        scope: 3,
        value: "262144",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "key_buffer_size",
        scope: 1,
        value: "8388608",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "last_sql_use_alloc",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "locked_in_memory",
        scope: 0,
        value: "0",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_allowed_packet",
        scope: 3,
        value: "67108864",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1024,
        max_value: 1073741824,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_digest_length",
        scope: 0,
        value: "1024",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_error_count",
        scope: 3,
        value: "64",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_heap_table_size",
        scope: 3,
        value: "16777216",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_join_size",
        scope: 3,
        value: "18446744073709551615",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_length_for_sort_data",
        scope: 3,
        value: "1024",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_seeks_for_key",
        scope: 3,
        value: "18446744073709551615",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "max_sort_length",
        scope: 3,
        value: "1024",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 4,
        max_value: 8388608,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "net_buffer_length",
        scope: 3,
        value: "16384",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1024,
        max_value: 1048576,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "preload_buffer_size",
        scope: 3,
        value: "32768",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "query_alloc_block_size",
        scope: 3,
        value: "8192",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "query_prealloc_size",
        scope: 3,
        value: "8192",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "range_alloc_block_size",
        scope: 3,
        value: "4096",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "read_buffer_size",
        scope: 3,
        value: "131072",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "read_rnd_buffer_size",
        scope: 3,
        value: "262144",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "sort_buffer_size",
        scope: 3,
        value: "262144",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "sql_buffer_result",
        scope: 3,
        value: "OFF",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "table_definition_cache",
        scope: 1,
        value: "2000",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 400,
        max_value: 524288,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "table_open_cache",
        scope: 1,
        value: "2000",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "table_open_cache_instances",
        scope: 0,
        value: "1",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "thread_cache_size",
        scope: 1,
        value: "9",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_parallel_hashagg_spill",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_point_get_cache",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_arbitrator_mode",
        scope: 1,
        value: "disable",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_arbitrator_query_reserved",
        scope: 2,
        value: "0",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_arbitrator_soft_limit",
        scope: 1,
        value: "0",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_arbitrator_wait_averse",
        scope: 2,
        value: "0",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_oom_action",
        scope: 1,
        value: "CANCEL",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &["CANCEL", "LOG"],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_quota_apply_cache",
        scope: 3,
        value: "33554432",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_quota_query",
        scope: 3,
        value: "1073741824",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: -1,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_memory_debug_mode_alarm_ratio",
        scope: 2,
        value: "0",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_memory_debug_mode_min_heap_inuse",
        scope: 2,
        value: "0",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: -9223372036854775808,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_memory_usage_alarm_keep_record_num",
        scope: 1,
        value: "5",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 10000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_memory_usage_alarm_ratio",
        scope: 1,
        value: "0.7",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_schema_cache_size",
        scope: 5,
        value: "536870912",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_server_memory_limit",
        scope: 5,
        value: "80%",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_server_memory_limit_sess_min_size",
        scope: 1,
        value: "134217728",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_shard_allocate_step",
        scope: 3,
        value: "9223372036854775807",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_tmp_table_max_size",
        scope: 3,
        value: "67108864",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1048576,
        max_value: 137438953472,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_track_aggregate_memory_usage",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tmp_table_size",
        scope: 3,
        value: "16777216",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1024,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tmpdir",
        scope: 0,
        value: "/var/tmp/",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
];
