// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Statement summary, Top SQL, metrics and plan-replayer capture.
//!
//! `tidb_enable_plan_replayer_capture` .. `tidb_workload_repository_snapshot_interval` -- 27 entries, name-ordered.
//!
//! Captured from Go `pkg/sessionctx/variable/sysvar.go`'s `sysVars`. The
//! registry is one flat name-ordered slice because lookup binary-searches
//! it, so each subject file keeps its own entries sorted and `catalog.rs`
//! MERGES them; see the `sysvar` module doc.

use super::super::{SysVarDef, VarType};

pub(super) static ENTRIES: [SysVarDef; 27] = [
    SysVarDef {
        name: "tidb_enable_plan_replayer_capture",
        global_config_name: "",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_plan_replayer_continuous_capture",
        global_config_name: "",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_stmt_summary",
        global_config_name: "",
        scope: 1,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_telemetry",
        global_config_name: "",
        scope: 1,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_top_sql",
        global_config_name: tidb_vardef::tidb_vars::GLOBAL_CONFIG_ENABLE_TOP_SQL,
        scope: 1,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_last_plan_replayer_token",
        global_config_name: "",
        scope: 2,
        value: "",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_metric_query_range_duration",
        global_config_name: "",
        scope: 2,
        value: "60",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 10,
        max_value: 216000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_metric_query_step",
        global_config_name: "",
        scope: 2,
        value: "60",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 10,
        max_value: 216000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_simplified_metrics",
        global_config_name: "",
        scope: 1,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_enable_persistent",
        global_config_name: "",
        scope: 4,
        value: "",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_file_max_backups",
        global_config_name: "",
        scope: 4,
        value: "",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_file_max_days",
        global_config_name: "",
        scope: 4,
        value: "",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_file_max_size",
        global_config_name: "",
        scope: 4,
        value: "",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_filename",
        global_config_name: "",
        scope: 4,
        value: "",
        var_type: VarType::Str,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_group_by_user",
        global_config_name: "",
        scope: 1,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_history_size",
        global_config_name: "",
        scope: 1,
        value: "24",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 255,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_internal_query",
        global_config_name: "",
        scope: 1,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_max_sql_length",
        global_config_name: "",
        scope: 1,
        value: "32768",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_max_stmt_count",
        global_config_name: "",
        scope: 5,
        value: "3000",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 32767,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_persist_evicted",
        global_config_name: "",
        scope: 1,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_stmt_summary_refresh_interval",
        global_config_name: "",
        scope: 1,
        value: "1800",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_top_sql_max_meta_count",
        global_config_name: "",
        scope: 1,
        value: "5000",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 10000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_top_sql_max_time_series_count",
        global_config_name: "",
        scope: 1,
        value: "100",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 5000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_workload_repository_active_sampling_interval",
        global_config_name: "",
        scope: 1,
        value: "5",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 600,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_workload_repository_dest",
        global_config_name: "",
        scope: 1,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_workload_repository_retention_days",
        global_config_name: "",
        scope: 1,
        value: "7",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 365,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_workload_repository_snapshot_interval",
        global_config_name: "",
        scope: 1,
        value: "3600",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 900,
        max_value: 7200,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
];
