// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Plan choice: the optimizer switches, join strategies, index selection, plan cache and SQL bindings.
//!
//! `bind_address` .. `tiflash_hash_join_version` -- 131 entries, name-ordered.
//!
//! Captured from Go `pkg/sessionctx/variable/sysvar.go`'s `sysVars`. The
//! registry is one flat name-ordered slice because lookup binary-searches
//! it, so each subject file keeps its own entries sorted and `catalog.rs`
//! MERGES them; see the `sysvar` module doc.

use super::super::{SysVarDef, VarType};

pub(super) static ENTRIES: [SysVarDef; 131] = [
    SysVarDef {
        name: "bind_address",
        scope: 0,
        value: "*",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "last_plan_from_binding",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "last_plan_from_cache",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: true,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "mpp_exchange_compression_mode",
        scope: 3,
        value: "UNSPECIFIED",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "mpp_version",
        scope: 3,
        value: "UNSPECIFIED",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "optimizer_prune_level",
        scope: 3,
        value: "1",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "optimizer_search_depth",
        scope: 3,
        value: "62",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "optimizer_switch",
        scope: 0,
        value: "index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mrr=on,mrr_cost_based=on,block_nested_loop=on,batched_key_access=off,materialization=on,semijoin=on,loosescan=on,firstmatch=on,subquery_materialization_cost_based=on,use_index_extensions=on",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_allow_mpp",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_broadcast_join_threshold_count",
        scope: 3,
        value: "10240",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_broadcast_join_threshold_size",
        scope: 3,
        value: "104857600",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_capture_plan_baselines",
        scope: 1,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_cost_model_version",
        scope: 3,
        value: "2",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 2,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_binding_usage",
        scope: 1,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_cascades_planner",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_index_merge",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_index_merge_join",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_inl_join_inner_multi_pattern",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_instance_plan_cache",
        scope: 1,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_new_cost_interface",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_non_prepared_plan_cache",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_non_prepared_plan_cache_for_dml",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_ordered_result_mode",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_outer_join_reorder",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_parallel_apply",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_plan_cache_for_param_limit",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_plan_cache_for_subquery",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_prepared_plan_cache",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enable_prepared_plan_cache_memory_monitor",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_enforce_mpp",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_evolve_plan_baselines",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_hash_join_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_hash_join_version",
        scope: 3,
        value: "optimized",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_ignore_inlist_plan_digest",
        scope: 1,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_join_batch_size",
        scope: 3,
        value: "25000",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_join_double_read_penalty_cost_rate",
        scope: 3,
        value: "0",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_lookup_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_lookup_join_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_lookup_pushdown_policy",
        scope: 3,
        value: "hint-only",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &["hint-only", "affinity-force", "force"],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_lookup_size",
        scope: 3,
        value: "20000",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_index_merge_intersection_concurrency",
        scope: 3,
        value: "-1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_instance_plan_cache_max_size",
        scope: 1,
        value: "104857600",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_instance_plan_cache_reserved_percentage",
        scope: 1,
        value: "0.1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_load_binding_timeout",
        scope: 1,
        value: "200",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_mem_quota_binding_cache",
        scope: 5,
        value: "67108864",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_merge_join_concurrency",
        scope: 3,
        value: "1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: true,
        min_value: 1,
        max_value: 256,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_non_prepared_plan_cache_size",
        scope: 3,
        value: "100",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 100000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_advanced_join_hint",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_agg_push_down",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_always_keep_join_key",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_broadcast_cartesian_join",
        scope: 3,
        value: "1",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_cartesian_join_order_threshold",
        scope: 3,
        value: "0",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_concurrency_factor",
        scope: 3,
        value: "3",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_copcpu_factor",
        scope: 3,
        value: "3",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_correlation_exp_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_correlation_threshold",
        scope: 3,
        value: "0.9",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_cpu_factor",
        scope: 3,
        value: "3",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_derive_topn",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_desc_factor",
        scope: 3,
        value: "3",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_disk_factor",
        scope: 3,
        value: "1.5",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_distinct_agg_push_down",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_advanced_join_reorder",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_correlation_adjustment",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_fuzzy_binding",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_hash_join",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_late_materialization",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_mpp_shared_cte_execution",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_no_decorrelate_in_select",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_non_eval_scalar_subquery",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_semi_join_rewrite",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_enable_three_stage_multi_distinct_agg",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_fix_control",
        scope: 3,
        value: "",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_force_inline_cte",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_group_ndv_skew_ratio",
        scope: 3,
        value: "0",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_hash_agg_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_hash_join_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_join_build_v2",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_join_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_join_max_scan_rows_ratio",
        scope: 3,
        value: "0",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_lookup_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_merge_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_prune_threshold",
        scope: 3,
        value: "20",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: -1,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_reader_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_index_scan_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_insubq_to_join_and_agg",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_join_reorder_threshold",
        scope: 3,
        value: "0",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 63,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_join_reorder_through_proj",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_join_reorder_through_sel",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_limit_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_limit_push_down_threshold",
        scope: 3,
        value: "5000",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 2147483647,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_memory_factor",
        scope: 3,
        value: "0.001",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_merge_join_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_mpp_outer_join_fixed_build_side",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_network_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_objective",
        scope: 3,
        value: "moderate",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &["moderate", "determinate"],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_partial_ordered_index_for_topn",
        scope: 3,
        value: "DISABLE",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &["DISABLE", "COST"],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_prefer_range_scan",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_prefix_index_single_scan",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_projection_push_down",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_range_max_size",
        scope: 3,
        value: "67108864",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 9223372036854775807,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_risk_eq_skew_ratio",
        scope: 3,
        value: "0",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_risk_range_skew_ratio",
        scope: 3,
        value: "0",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_scale_ndv_skew_ratio",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_scan_factor",
        scope: 3,
        value: "1.5",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_seek_factor",
        scope: 3,
        value: "20",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_skew_distinct_agg",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_sort_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_stream_agg_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_table_full_scan_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_table_range_scan_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_table_reader_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_table_rowid_scan_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_table_tiflash_scan_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_three_stage_distinct_agg",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_tiflash_concurrency_factor",
        scope: 3,
        value: "24",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_topn_cost_factor",
        scope: 3,
        value: "1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_use_invisible_indexes",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_opt_write_row_id",
        scope: 2,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_plan_cache_max_plan_size",
        scope: 3,
        value: "2097152",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 18446744073709551615,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_plan_cache_strategy",
        scope: 3,
        value: "all",
        var_type: VarType::Enum,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &["all", "hint_only"],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_prefer_broadcast_join_by_exchange_data_size",
        scope: 3,
        value: "OFF",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_prepared_plan_cache_memory_guard_ratio",
        scope: 1,
        value: "0.1",
        var_type: VarType::Float,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 1,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_prepared_plan_cache_size",
        scope: 3,
        value: "100",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 100000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_regard_null_as_point",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_remove_orderby_in_subquery",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_runtime_filter_mode",
        scope: 3,
        value: "OFF",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_runtime_filter_type",
        scope: 3,
        value: "IN",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_session_plan_cache_size",
        scope: 3,
        value: "100",
        var_type: VarType::Unsigned,
        read_only: false,
        allow_auto_value: false,
        min_value: 1,
        max_value: 100000,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_shard_row_id_bits",
        scope: 3,
        value: "0",
        var_type: VarType::Int,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 15,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tidb_use_plan_baselines",
        scope: 3,
        value: "ON",
        var_type: VarType::Bool,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },
    SysVarDef {
        name: "tiflash_hash_join_version",
        scope: 3,
        value: "legacy",
        var_type: VarType::Str,
        read_only: false,
        allow_auto_value: false,
        min_value: 0,
        max_value: 0,
        possible_values: &[],
        auto_convert_negative_bool: false,
    },];
