// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package physicalop_test

import "testing"

func TestFlattenListPushDownPlan(t *testing.T) {
	RunFlattenListPushDownPlan(t)
}

func TestFlattenTreePushDownPlan(t *testing.T) {
	RunFlattenTreePushDownPlan(t)
}
