// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestExtractHandler(t *testing.T) {
	RunExtractHandler(t)
}

func TestExtractHandlerInfoSchemaV2(t *testing.T) {
	RunExtractHandlerInfoSchemaV2(t)
}
