// Code generated by mega-gen. DO NOT EDIT.

package subquery_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("planner_core_tests_subquery", "CollateSubQuery", RunCollateSubQuery)
}
