// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package pointget_test

import "testing"

func TestPointGetPlanCache(t *testing.T) {
	RunPointGetPlanCache(t)
}

func TestPointGetPlanCacheForNextGen(t *testing.T) {
	RunPointGetPlanCacheForNextGen(t)
}

func TestPointGetId(t *testing.T) {
	RunPointGetId(t)
}

func TestIssue20692(t *testing.T) {
	RunIssue20692(t)
}

func TestIssue18042(t *testing.T) {
	RunIssue18042(t)
}

func TestIssue52592(t *testing.T) {
	RunIssue52592(t)
}

func TestIssue52592ForNextGen(t *testing.T) {
	RunIssue52592ForNextGen(t)
}

func TestIssue56832(t *testing.T) {
	RunIssue56832(t)
}
