// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package clusteredindextest

import (
	"flag"
	"github.com/pingcap/tidb/pkg/config"
	"github.com/pingcap/tidb/pkg/sessionctx/vardef"
	"github.com/pingcap/tidb/pkg/testkit/testsetup"
	"github.com/tikv/client-go/v2/tikv"
	"sync"
	"time"
)

var megaInitOnce sync.Once

func InitForMega() {
	megaInitOnce.Do(func() {
		testsetup.SetupForCommonTest()
		flag.Parse()
		vardef.SetSchemaLease(20 * time.Millisecond)
		config.UpdateGlobal(func(conf *config.Config) {
			conf.TiKVClient.AsyncCommit.SafeWindow = 0
			conf.TiKVClient.AsyncCommit.AllowedClockDrift = 0
		})
		tikv.EnableFailpoints()
	})
}
