// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package reporter_test

import "testing"

func TestDefaultDataSinkRegisterer(t *testing.T) {
	RunDefaultDataSinkRegisterer(t)
}

func TestDefaultDataSinkRegistererTopRUTwoSinksRefCountAndReset(t *testing.T) {
	RunDefaultDataSinkRegistererTopRUTwoSinksRefCountAndReset(t)
}

func TestDefaultDataSinkRegistererTopRUDuplicateRegisterIsIdempotent(t *testing.T) {
	RunDefaultDataSinkRegistererTopRUDuplicateRegisterIsIdempotent(t)
}

func TestDefaultDataSinkRegistererTopRURefCountConcurrentRegisterDeregister(t *testing.T) {
	RunDefaultDataSinkRegistererTopRURefCountConcurrentRegisterDeregister(t)
}

func TestDefaultDataSinkRegistererTopSQLRespectsTopRUOnly(t *testing.T) {
	RunDefaultDataSinkRegistererTopSQLRespectsTopRUOnly(t)
}

func TestDefaultDataSinkRegistererSingleTargetTopRUBehavior(t *testing.T) {
	RunDefaultDataSinkRegistererSingleTargetTopRUBehavior(t)
}
