// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package executor

import "testing"

func TestAdapterStatement(t *testing.T) {
	RunAdapterStatement(t)
}

func TestAdmin(t *testing.T) {
	RunAdmin(t)
}

func TestAdminShowDDLJobs(t *testing.T) {
	RunAdminShowDDLJobs(t)
}

func TestAdminShowDDLJobsInfo(t *testing.T) {
	RunAdminShowDDLJobsInfo(t)
}

func TestApplyCache(t *testing.T) {
	RunApplyCache(t)
}

func TestCheckIndex(t *testing.T) {
	RunCheckIndex(t)
}

func TestClusteredIndexIsPointGet(t *testing.T) {
	RunClusteredIndexIsPointGet(t)
}

func TestCollectDMLRuntimeStats(t *testing.T) {
	RunCollectDMLRuntimeStats(t)
}

func TestColumnName(t *testing.T) {
	RunColumnName(t)
}

func TestCurrentTimestampValueSelection(t *testing.T) {
	RunCurrentTimestampValueSelection(t)
}

func TestDecimalDivPrecisionIncrement(t *testing.T) {
	RunDecimalDivPrecisionIncrement(t)
}

func TestGetResultRowsCount(t *testing.T) {
	RunGetResultRowsCount(t)
}

func TestGlobalMemoryControl2(t *testing.T) {
	RunGlobalMemoryControl2(t)
}

func TestHistoryRead(t *testing.T) {
	RunHistoryRead(t)
}

func TestHistoryReadInTxn(t *testing.T) {
	RunHistoryReadInTxn(t)
}

func TestIsFastPlan(t *testing.T) {
	RunIsFastPlan(t)
}

func TestIsPointGet(t *testing.T) {
	RunIsPointGet(t)
}

func TestIssue19148(t *testing.T) {
	RunIssue19148(t)
}

func TestIssue38756(t *testing.T) {
	RunIssue38756(t)
}

func TestIssue48756(t *testing.T) {
	RunIssue48756(t)
}

func TestIssue50043(t *testing.T) {
	RunIssue50043(t)
}

func TestIssue50043WithPipelinedDML(t *testing.T) {
	RunIssue50043WithPipelinedDML(t)
}

func TestIssue50308(t *testing.T) {
	RunIssue50308(t)
}

func TestIssue51324(t *testing.T) {
	RunIssue51324(t)
}

func TestIssue52984(t *testing.T) {
	RunIssue52984(t)
}

func TestIssue63329(t *testing.T) {
	RunIssue63329(t)
}

func TestIssues40463(t *testing.T) {
	RunIssues40463(t)
}

func TestIssues49377(t *testing.T) {
	RunIssues49377(t)
}

func TestLowResolutionTSORead(t *testing.T) {
	RunLowResolutionTSORead(t)
}

func TestLowResolutionTSOReadScope(t *testing.T) {
	RunLowResolutionTSOReadScope(t)
}

func TestMaxOneRow(t *testing.T) {
	RunMaxOneRow(t)
}

func TestNotFillCacheFlag(t *testing.T) {
	RunNotFillCacheFlag(t)
}

func TestPartitionHashCode(t *testing.T) {
	RunPartitionHashCode(t)
}

func TestPointGetOrderby(t *testing.T) {
	RunPointGetOrderby(t)
}

func TestPrevStmtDesensitization(t *testing.T) {
	RunPrevStmtDesensitization(t)
}

func TestProcessInfoOfSubQuery(t *testing.T) {
	RunProcessInfoOfSubQuery(t)
}

func TestQueryWithKill(t *testing.T) {
	RunQueryWithKill(t)
}

func TestSelectVar(t *testing.T) {
	RunSelectVar(t)
}

func TestSessionRootTrackerDetach(t *testing.T) {
	RunSessionRootTrackerDetach(t)
}

func TestSignalCheckpointForSort(t *testing.T) {
	RunSignalCheckpointForSort(t)
}

func TestTableSampleTemporaryTable(t *testing.T) {
	RunTableSampleTemporaryTable(t)
}

func TestTiDBCurrentTS(t *testing.T) {
	RunTiDBCurrentTS(t)
}

func TestTiDBLastQueryInfo(t *testing.T) {
	RunTiDBLastQueryInfo(t)
}

func TestTiDBLastTxnInfo(t *testing.T) {
	RunTiDBLastTxnInfo(t)
}

func TestTimestampDefaultValueTimeZone(t *testing.T) {
	RunTimestampDefaultValueTimeZone(t)
}

func TestTimezonePushDown(t *testing.T) {
	RunTimezonePushDown(t)
}

func TestTwiceCloseUnionExec(t *testing.T) {
	RunTwiceCloseUnionExec(t)
}

func TestUnion2(t *testing.T) {
	RunUnion2(t)
}

func TestUnionLimit(t *testing.T) {
	RunUnionLimit(t)
}

func TestUnreasonablyClose(t *testing.T) {
	RunUnreasonablyClose(t)
}
