// Copyright 2020 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package variable

import (
	"math"

	"github.com/pingcap/errors"
	"github.com/pingcap/tidb/pkg/sessionctx/vardef"
)

// The following sysVars are noops.
// Some applications will depend on certain variables to be present or settable.
// These are included for MySQL compatibility,
// but changing them has no effect on behavior.

var noopSysVars = []*SysVar{
	// It is unsafe to pretend that any variation of "read only" is enabled when the server
	// does not support it. It is possible that these features will be supported in future,
	// but until then...
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.TxReadOnly, Value: vardef.Off, Type: vardef.TypeBool, Aliases: []string{vardef.TransactionReadOnly}, Validation: func(vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag) (string, error) {
		return checkReadOnly(vars, normalizedValue, originalValue, scope, false)
	}},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.TransactionReadOnly, Value: vardef.Off, Type: vardef.TypeBool, Aliases: []string{vardef.TxReadOnly}, Validation: func(vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag) (string, error) {
		return checkReadOnly(vars, normalizedValue, originalValue, scope, false)
	}},
	{Scope: vardef.ScopeGlobal, Name: vardef.OfflineMode, Value: vardef.Off, Type: vardef.TypeBool, Validation: func(vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag) (string, error) {
		return checkReadOnly(vars, normalizedValue, originalValue, scope, true)
	}},
	{Scope: vardef.ScopeGlobal, Name: vardef.SuperReadOnly, Value: vardef.Off, Type: vardef.TypeBool, Validation: func(vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag) (string, error) {
		return checkReadOnly(vars, normalizedValue, originalValue, scope, false)
	}},
	{Scope: vardef.ScopeGlobal, Name: vardef.ReadOnly, Value: vardef.Off, Type: vardef.TypeBool, Validation: func(vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag) (string, error) {
		return checkReadOnly(vars, normalizedValue, originalValue, scope, false)
	}},
	{Scope: vardef.ScopeGlobal, Name: vardef.ConnectTimeout, Value: "10", Type: vardef.TypeUnsigned, MinValue: 2, MaxValue: secondsPerYear},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "sql_buffer_result",
		Value:                   vardef.Off,
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: vardef.MyISAMUseMmap, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: "gtid_mode", Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: vardef.FlushTime, Value: "0", Type: vardef.TypeUnsigned, MinValue: 0, MaxValue: secondsPerYear},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_mutex_classes", Value: "200"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.LowPriorityUpdates, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.SessionTrackGtids, Value: vardef.Off, Type: vardef.TypeEnum, PossibleValues: []string{vardef.Off, "OWN_GTID", "ALL_GTIDS"}},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndbinfo_max_rows", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndb_index_stat_option", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.OldPasswords, Value: "0", Type: vardef.TypeUnsigned, MinValue: 0, MaxValue: 2},
	{Scope: vardef.ScopeNone, Name: "innodb_version", Value: "5.6.25"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.BigTables, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeNone, Name: "skip_external_locking", Value: "1"},
	{Scope: vardef.ScopeNone, Name: "innodb_sync_array_size", Value: "1"},
	{Scope: vardef.ScopeSession, Name: "gtid_next", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "ndb_show_foreign_key_mock_tables", Value: ""},
	{Scope: vardef.ScopeNone, Name: "multi_range_count", Value: "256"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "binlog_error_action", Value: "IGNORE_ERROR"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "default_storage_engine", Value: "InnoDB"},
	{Scope: vardef.ScopeNone, Name: "ft_query_expansion_limit", Value: "20"},
	{Scope: vardef.ScopeGlobal, Name: vardef.MaxConnectErrors, Value: "100", Type: vardef.TypeUnsigned, MinValue: 1, MaxValue: math.MaxUint64},
	{Scope: vardef.ScopeGlobal, Name: vardef.SyncBinlog, Value: "0", Type: vardef.TypeUnsigned, MinValue: 0, MaxValue: 4294967295},
	{Scope: vardef.ScopeNone, Name: "max_digest_length", Value: "1024"},
	{Scope: vardef.ScopeNone, Name: "innodb_force_load_corrupted", Value: "0"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_table_handles", Value: "4000"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbFastShutdown, Value: "1", Type: vardef.TypeUnsigned, MinValue: 0, MaxValue: 2},
	{Scope: vardef.ScopeNone, Name: "ft_max_word_len", Value: "84"},
	{Scope: vardef.ScopeGlobal, Name: "log_backward_compatible_user_definitions", Value: ""},
	{Scope: vardef.ScopeNone, Name: "lc_messages_dir", Value: "/usr/local/mysql-5.6.25-osx10.8-x86_64/share/"},
	{Scope: vardef.ScopeGlobal, Name: "ft_boolean_syntax", Value: `+ -><()~*:""&|`},
	{Scope: vardef.ScopeGlobal, Name: vardef.TableDefinitionCache, Value: "2000", Type: vardef.TypeUnsigned, MinValue: 400, MaxValue: 524288},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_file_handles", Value: "32768"},
	{Scope: vardef.ScopeSession, Name: "transaction_allow_batching", Value: ""},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_statement_classes", Value: "168"},
	{Scope: vardef.ScopeGlobal, Name: "server_id", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_flushing_avg_loops", Value: "30"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_max_purge_lag", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "preload_buffer_size", Value: "32768"},
	{Scope: vardef.ScopeGlobal, Name: vardef.CheckProxyUsers, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "innodb_flush_log_at_timeout", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_max_undo_log_size", Value: ""},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "range_alloc_block_size",
		Value:                   "4096",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: "have_rtree_keys", Value: "YES"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_old_blocks_pct", Value: "37"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_default_row_format", Value: "dynamic", Type: vardef.TypeEnum, PossibleValues: []string{"redundant", "compact", "dynamic"}},
	{Scope: vardef.ScopeGlobal, Name: "innodb_compression_failure_threshold_pct", Value: "5"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_events_waits_history_long_size", Value: "10000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_checksum_algorithm", Value: "innodb"},
	{Scope: vardef.ScopeNone, Name: "innodb_ft_sort_pll_degree", Value: "2"},
	{Scope: vardef.ScopeNone, Name: "thread_stack", Value: "262144"},
	{Scope: vardef.ScopeGlobal, Name: "relay_log_info_repository", Value: "FILE"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "max_delayed_threads", Value: "20"},
	{Scope: vardef.ScopeNone, Name: "protocol_version", Value: "10"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "new", Value: vardef.Off},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "myisam_sort_buffer_size", Value: "8388608"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "optimizer_trace_offset", Value: "-1"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbBufferPoolDumpAtShutdown, Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.SQLNotes, Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbCmpPerIndexEnabled, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: "innodb_ft_server_stopword_table", Value: ""},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_file_instances", Value: "7693"},
	{Scope: vardef.ScopeNone, Name: "log_output", Value: "FILE"},
	{Scope: vardef.ScopeGlobal, Name: "binlog_group_commit_sync_delay", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "binlog_group_commit_sync_no_delay_count", Value: ""},
	{Scope: vardef.ScopeNone, Name: "have_crypt", Value: "YES"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_log_write_ahead_size", Value: ""},
	{Scope: vardef.ScopeNone, Name: "innodb_log_group_home_dir", Value: "./"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_events_statements_history_size", Value: "10"},
	{Scope: vardef.ScopeGlobal, Name: vardef.GeneralLog, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: vardef.BinlogOrderCommits, Value: vardef.On, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "key_cache_division_limit", Value: "100"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "max_insert_delayed_threads", Value: "20"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_session_connect_attrs_size", Value: "512"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_max_dirty_pages_pct", Value: "75"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbFilePerTable, Value: vardef.On, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbLogCompressedPages, Value: "1"},
	{Scope: vardef.ScopeNone, Name: "skip_networking", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_monitor_reset", Value: ""},
	{Scope: vardef.ScopeNone, Name: "ssl_cipher", Value: ""},
	{Scope: vardef.ScopeNone, Name: "tls_version", Value: "TLSv1,TLSv1.1,TLSv1.2"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbPrintAllDeadlocks, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeNone, Name: "innodb_autoinc_lock_mode", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: "key_buffer_size", Value: "8388608"},
	{Scope: vardef.ScopeGlobal, Name: "host_cache_size", Value: "279"},
	{Scope: vardef.ScopeGlobal, Name: vardef.DelayKeyWrite, Value: vardef.On, Type: vardef.TypeEnum, PossibleValues: []string{vardef.Off, vardef.On, "ALL"}},
	{Scope: vardef.ScopeNone, Name: "metadata_locks_cache_size", Value: "1024"},
	{Scope: vardef.ScopeNone, Name: "innodb_force_recovery", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "debug", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "log_warnings", Value: "1"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.InnodbStrictMode, Value: vardef.On, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: "innodb_rollback_segments", Value: "128"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "join_buffer_size",
		Value:                   "262144",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: "max_binlog_size", Value: "1073741824"},
	{Scope: vardef.ScopeGlobal, Name: "concurrent_insert", Value: "AUTO"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbAdaptiveHashIndex, Value: vardef.On, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbFtEnableStopword, Value: vardef.On, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: "general_log_file", Value: "/usr/local/mysql/data/localhost.log"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_compression_level", Value: "6"},
	{Scope: vardef.ScopeNone, Name: "myisam_mmap_size", Value: "18446744073709551615"},
	{Scope: vardef.ScopeNone, Name: "innodb_buffer_pool_instances", Value: "8"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "max_length_for_sort_data",
		Value:                   "1024",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: vardef.CharacterSetSystem, Value: "utf8"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.CharacterSetFilesystem, Value: "binary", Validation: func(vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag) (string, error) {
		return checkCharacterSet(normalizedValue, vardef.CharacterSetFilesystem)
	}},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbOptimizeFullTextOnly, Value: "0"},
	{Scope: vardef.ScopeNone, Name: "character_sets_dir", Value: "/usr/local/mysql-5.6.25-osx10.8-x86_64/share/charsets/"},
	{Scope: vardef.ScopeNone, Name: "innodb_rollback_on_timeout", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "query_alloc_block_size", Value: "8192"},
	{Scope: vardef.ScopeNone, Name: "have_compress", Value: "YES"},
	{Scope: vardef.ScopeNone, Name: "thread_concurrency", Value: "10"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "query_prealloc_size", Value: "8192"},
	{Scope: vardef.ScopeNone, Name: "relay_log_space_limit", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.MaxUserConnections, Value: "0", Type: vardef.TypeUnsigned, MinValue: 0, MaxValue: 4294967295},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_thread_classes", Value: "50"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_api_trx_level", Value: "0"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_file_classes", Value: "50"},
	{Scope: vardef.ScopeGlobal, Name: "expire_logs_days", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.BinlogRowQueryLogEvents, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeNone, Name: "pid_file", Value: "/usr/local/mysql/data/localhost.pid"},
	{Scope: vardef.ScopeNone, Name: "innodb_undo_tablespaces", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbStatusOutputLocks, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeNone, Name: "performance_schema_accounts_size", Value: "100"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "max_error_count",
		Value:                   "64",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: "max_write_lock_count", Value: "18446744073709551615"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_socket_instances", Value: "322"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_table_instances", Value: "12500"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_stats_persistent_sample_pages", Value: "20"},
	{Scope: vardef.ScopeGlobal, Name: "show_compatibility_56", Value: ""},
	{Scope: vardef.ScopeNone, Name: "innodb_open_files", Value: "2000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_spin_wait_delay", Value: "6"},
	{Scope: vardef.ScopeGlobal, Name: "thread_cache_size", Value: "9"},
	{Scope: vardef.ScopeGlobal, Name: vardef.LogSlowAdminStatements, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeNone, Name: "ft_stopword_file", Value: "(built-in)"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_max_dirty_pages_pct_lwm", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: vardef.LogQueriesNotUsingIndexes, Value: vardef.Off, Type: vardef.TypeBool},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "max_heap_table_size",
		Value:                   "16777216",
		IsHintUpdatableVerified: true,
	},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "tmp_table_size",
		Value:                   "16777216",
		Type:                    vardef.TypeUnsigned,
		MinValue:                1024,
		MaxValue:                math.MaxUint64,
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: "innodb_lru_scan_depth", Value: "1024"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_purge_rseg_truncate_frequency", Value: ""},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    vardef.SQLAutoIsNull,
		Value:                   vardef.Off,
		Type:                    vardef.TypeBool,
		IsHintUpdatableVerified: true,
		Validation: func(
			vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag,
		) (string, error) {
			// checkSQLAutoIsNull requires TiDBEnableNoopFuncs != OFF for the same scope otherwise an error will be returned.
			// See also https://github.com/pingcap/tidb/issues/28230
			errMsg := ErrFunctionsNoopImpl.FastGenByArgs("sql_auto_is_null")
			if TiDBOptOn(normalizedValue) {
				if scope == vardef.ScopeSession && vars.NoopFuncsMode != OnInt {
					if vars.NoopFuncsMode == OffInt {
						return vardef.Off, errors.Trace(errMsg)
					}
					vars.StmtCtx.AppendWarning(errMsg)
				}
				if scope == vardef.ScopeGlobal {
					val, err := vars.GlobalVarsAccessor.GetGlobalSysVar(vardef.TiDBEnableNoopFuncs)
					if err != nil {
						return originalValue, errUnknownSystemVariable.GenWithStackByArgs(vardef.TiDBEnableNoopFuncs)
					}
					if val == vardef.Off {
						return vardef.Off, errors.Trace(errMsg)
					}
					if val == vardef.Warn {
						vars.StmtCtx.AppendWarning(errMsg)
					}
				}
			}
			return normalizedValue, nil
		}},
	{Scope: vardef.ScopeNone, Name: "innodb_api_enable_binlog", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "innodb_ft_user_stopword_table", Value: ""},
	{Scope: vardef.ScopeNone, Name: "server_id_bits", Value: "32"},
	{Scope: vardef.ScopeNone, Name: "innodb_buffer_pool_load_at_startup", Value: "1"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "sort_buffer_size",
		Value:                   "262144",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: "innodb_flush_neighbors", Value: "1"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_socket_classes", Value: "10"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_stage_classes", Value: "150"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_purge_batch_size", Value: "300"},
	{Scope: vardef.ScopeNone, Name: "have_profiling", Value: "NO"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbBufferPoolDumpNow, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: vardef.RelayLogPurge, Value: vardef.On, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "ndb_distribution", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "myisam_data_pointer_size", Value: "6"},
	{Scope: vardef.ScopeGlobal, Name: "ndb_optimization_delay", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "innodb_ft_num_word_optimize", Value: "2000"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "max_join_size",
		Value:                   "18446744073709551615",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: vardef.CoreFile, Value: vardef.Off, Type: vardef.TypeBool},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "max_seeks_for_key",
		Value:                   "18446744073709551615",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: "innodb_log_buffer_size", Value: "8388608"},
	{Scope: vardef.ScopeGlobal, Name: "delayed_insert_timeout", Value: "300"},
	{Scope: vardef.ScopeGlobal, Name: "max_relay_log_size", Value: "0"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    vardef.MaxSortLength,
		Value:                   "1024",
		Type:                    vardef.TypeUnsigned,
		MinValue:                4,
		MaxValue:                8388608,
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: "metadata_locks_hash_instances", Value: "8"},
	{Scope: vardef.ScopeGlobal, Name: "ndb_eventbuffer_free_percent", Value: ""},
	{Scope: vardef.ScopeNone, Name: "large_files_support", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: "binlog_max_flush_queue_time", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_fill_factor", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "log_syslog_facility", Value: ""},
	{Scope: vardef.ScopeNone, Name: "innodb_ft_min_token_size", Value: "3"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "transaction_write_set_extraction", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndb_blob_write_batch_bytes", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "automatic_sp_privileges", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_flush_sync", Value: ""},
	{Scope: vardef.ScopeNone, Name: "performance_schema_events_statements_history_long_size", Value: "10000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_monitor_disable", Value: ""},
	{Scope: vardef.ScopeNone, Name: "innodb_doublewrite", Value: "1"},
	{Scope: vardef.ScopeNone, Name: "log_bin_use_v1_row_events", Value: "0"},
	{Scope: vardef.ScopeSession, Name: "innodb_optimize_point_storage", Value: ""},
	{Scope: vardef.ScopeNone, Name: "innodb_api_disable_rowlock", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_adaptive_flushing_lwm", Value: "10"},
	{Scope: vardef.ScopeNone, Name: "innodb_log_files_in_group", Value: "2"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbBufferPoolLoadNow, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_rwlock_classes", Value: "40"},
	{Scope: vardef.ScopeNone, Name: "binlog_gtid_simple_recovery", Value: "1"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_digests_size", Value: "10000"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.Profiling, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "sha256_password_proxy_users", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.SQLQuoteShowCreate, Value: vardef.On, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "binlogging_impossible_mode", Value: "IGNORE_ERROR"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_stats_transient_sample_pages", Value: "8"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbStatsOnMetadata, Value: "0"},
	{Scope: vardef.ScopeNone, Name: "server_uuid", Value: "00000000-0000-0000-0000-000000000000"},
	{Scope: vardef.ScopeNone, Name: "open_files_limit", Value: "5000"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndb_force_send", Value: ""},
	{Scope: vardef.ScopeNone, Name: "skip_show_database", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "log_timestamps", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "event_scheduler", Value: vardef.Off},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndb_deferred_constraints", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "log_syslog_include_pid", Value: ""},
	{Scope: vardef.ScopeNone, Name: "innodb_ft_cache_size", Value: "8000000"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbDisableSortFileCache, Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "log_error_verbosity", Value: ""},
	{Scope: vardef.ScopeNone, Name: "performance_schema_hosts_size", Value: "100"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_replication_delay", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: vardef.SlowQueryLog, Value: "0"},
	{Scope: vardef.ScopeSession, Name: "debug_sync", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbStatsAutoRecalc, Value: "1"},
	// lc_messages cannot be read_only, see https://github.com/pingcap/tidb/issues/38231.
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "lc_messages", Value: "en_US"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "bulk_insert_buffer_size",
		Value:                   "8388608",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.BinlogDirectNonTransactionalUpdates, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "innodb_change_buffering", Value: "all"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    vardef.SQLBigSelects,
		Value:                   vardef.On,
		Type:                    vardef.TypeBool,
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: "innodb_max_purge_lag_delay", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "session_track_schema", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "innodb_io_capacity_max", Value: "2000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_autoextend_increment", Value: "64"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "binlog_format", Value: "STATEMENT"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "optimizer_trace", Value: "enabled=off,one_line=off"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "read_rnd_buffer_size",
		Value:                   "262144",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.NetWriteTimeout, Value: "60"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbBufferPoolLoadAbort, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "transaction_prealloc_size", Value: "4096"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_setup_objects_size", Value: "100"},
	{Scope: vardef.ScopeGlobal, Name: "sync_relay_log", Value: "10000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_ft_result_cache_limit", Value: "2000000000"},
	{Scope: vardef.ScopeNone, Name: "innodb_sort_buffer_size", Value: "1048576"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_ft_enable_diag_print", Type: vardef.TypeBool, Value: vardef.Off},
	{Scope: vardef.ScopeNone, Name: "thread_handling", Value: "one-thread-per-connection"},
	{Scope: vardef.ScopeGlobal, Name: "stored_program_cache", Value: "256"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_mutex_instances", Value: "15906"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_adaptive_max_sleep_delay", Value: "150000"},
	{Scope: vardef.ScopeNone, Name: "large_pages", Value: vardef.Off},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "session_track_system_variables", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "innodb_change_buffer_max_size", Value: "25"},
	{Scope: vardef.ScopeGlobal, Name: vardef.LogBinTrustFunctionCreators, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeNone, Name: "innodb_write_io_threads", Value: "4"},
	{Scope: vardef.ScopeGlobal, Name: "mysql_native_password_proxy_users", Value: ""},
	{Scope: vardef.ScopeNone, Name: "large_page_size", Value: "0"},
	{Scope: vardef.ScopeNone, Name: "table_open_cache_instances", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbStatsPersistent, Value: vardef.On, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "session_track_state_change", Value: ""},
	{
		Scope:                   vardef.ScopeNone,
		Name:                    vardef.OptimizerSwitch,
		Value:                   "index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mrr=on,mrr_cost_based=on,block_nested_loop=on,batched_key_access=off,materialization=on,semijoin=on,loosescan=on,firstmatch=on,subquery_materialization_cost_based=on,use_index_extensions=on",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: "delayed_queue_size", Value: "1000"},
	{Scope: vardef.ScopeNone, Name: "innodb_read_only", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "log_syslog", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "transaction_alloc_block_size", Value: "8192"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_cond_classes", Value: "80"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_io_capacity", Value: "200"},
	{Scope: vardef.ScopeGlobal, Name: "max_binlog_cache_size", Value: "18446744073709547520"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndb_index_stat_enable", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "executed_gtids_compression_period", Value: ""},
	{Scope: vardef.ScopeNone, Name: "time_format", Value: "%H:%i:%s"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.OldAlterTable, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "long_query_time", Value: "10.000000"},
	{Scope: vardef.ScopeNone, Name: "innodb_use_native_aio", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "log_throttle_queries_not_using_indexes", Value: "0"},
	{Scope: vardef.ScopeNone, Name: "locked_in_memory", Value: "0"},
	{Scope: vardef.ScopeNone, Name: "innodb_api_enable_mdl", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "binlog_cache_size", Value: "32768"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_compression_pad_pct_max", Value: "50"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbCommitConcurrency, Value: "0", Type: vardef.TypeUnsigned, MinValue: 0, MaxValue: 1000},
	{Scope: vardef.ScopeNone, Name: "ft_min_word_len", Value: "4"},
	{Scope: vardef.ScopeGlobal, Name: vardef.EnforceGtidConsistency, Value: vardef.Off, Type: vardef.TypeEnum, PossibleValues: []string{vardef.Off, vardef.On, "WARN"}},
	{Scope: vardef.ScopeGlobal, Name: vardef.SecureAuth, Value: vardef.On, Type: vardef.TypeBool, Validation: func(vars *SessionVars, normalizedValue string, originalValue string, scope vardef.ScopeFlag) (string, error) {
		if TiDBOptOn(normalizedValue) {
			return vardef.On, nil
		}
		return normalizedValue, ErrWrongValueForVar.GenWithStackByArgs(vardef.SecureAuth, originalValue)
	}},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbRandomReadAhead, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    vardef.UniqueChecks,
		Value:                   vardef.On,
		Type:                    vardef.TypeBool,
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: "internal_tmp_disk_storage_engine", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "myisam_repair_threads", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: "ndb_eventbuffer_max_alloc", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "innodb_read_ahead_threshold", Value: "56"},
	{Scope: vardef.ScopeGlobal, Name: "key_cache_block_size", Value: "1024"},
	{Scope: vardef.ScopeNone, Name: "ndb_recv_thread_cpu_mask", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "gtid_purged", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "max_binlog_stmt_cache_size", Value: "18446744073709547520"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "lock_wait_timeout", Value: "31536000"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "read_buffer_size",
		Value:                   "131072",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: "innodb_read_io_threads", Value: "4"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.MaxSpRecursionDepth, Value: "0", Type: vardef.TypeUnsigned, MinValue: 0, MaxValue: 255},
	{Scope: vardef.ScopeNone, Name: "ignore_builtin_innodb", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "slow_query_log_file", Value: "/usr/local/mysql/data/localhost-slow.log"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_thread_sleep_delay", Value: "10000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_ft_aux_table", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.SQLWarnings, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.KeepFilesOnCreate, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeNone, Name: "innodb_data_file_path", Value: "ibdata1:12M:autoextend"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_setup_actors_size", Value: "100"},
	{Scope: vardef.ScopeNone, Name: "log_error", Value: "/usr/local/mysql/data/localhost.err"},
	{Scope: vardef.ScopeGlobal, Name: "binlog_stmt_cache_size", Value: "32768"},
	{Scope: vardef.ScopeNone, Name: "relay_log_info_file", Value: "relay-log.info"},
	{Scope: vardef.ScopeNone, Name: "innodb_ft_total_cache_size", Value: "640000000"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_rwlock_instances", Value: "9102"},
	{Scope: vardef.ScopeGlobal, Name: "table_open_cache", Value: "2000"},
	{Scope: vardef.ScopeNone, Name: "performance_schema_events_stages_history_long_size", Value: "10000"},
	{Scope: vardef.ScopeSession, Name: "insert_id", Value: ""},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "default_tmp_storage_engine",
		Value:                   "InnoDB",
		IsHintUpdatableVerified: true,
	},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "optimizer_search_depth",
		Value:                   "62",
		IsHintUpdatableVerified: true,
	},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "max_points_in_geometry",
		Value:                   "65536",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "profiling_history_size", Value: "15"},
	{Scope: vardef.ScopeNone, Name: "have_symlink", Value: "YES"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "storage_engine", Value: "InnoDB"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "sql_log_off", Value: "0"},
	// In MySQL, the default value of `explicit_defaults_for_timestamp` is `0`.
	// But In TiDB, it's set to `1` to be consistent with TiDB timestamp behavior.
	// See: https://github.com/pingcap/tidb/pull/6068 for details
	{Scope: vardef.ScopeNone, Name: "explicit_defaults_for_timestamp", Value: vardef.On, Type: vardef.TypeBool},
	{Scope: vardef.ScopeNone, Name: "performance_schema_events_waits_history_size", Value: "10"},
	{Scope: vardef.ScopeGlobal, Name: "log_syslog_tag", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "innodb_undo_log_truncate", Value: ""},
	{Scope: vardef.ScopeSession, Name: "innodb_create_intrinsic", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "gtid_executed_compression_period", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "ndb_log_empty_epochs", Value: ""},
	{Scope: vardef.ScopeNone, Name: "have_geometry", Value: "YES"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "optimizer_trace_max_mem_size", Value: "16384"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "net_retry_count", Value: "10"},
	{Scope: vardef.ScopeSession, Name: "ndb_table_no_logging", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "optimizer_trace_features", Value: "greedy_search=on,range_optimizer=on,dynamic_range=on,repeated_subselect=on"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_flush_log_at_trx_commit", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: "rewriter_enabled", Value: ""},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "updatable_views_with_limit",
		Value:                   "YES",
		IsHintUpdatableVerified: true,
	},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "optimizer_prune_level",
		Value:                   "1",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "completion_type", Value: "NO_CHAIN"},
	{Scope: vardef.ScopeGlobal, Name: "binlog_checksum", Value: "CRC32"},
	{Scope: vardef.ScopeNone, Name: "report_port", Value: "3306"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.ShowOldTemporals, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "innodb_buffer_pool_size", Value: "4294967296"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbAdaptiveFlushing, Value: vardef.On, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal, Name: "innodb_monitor_enable", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "innodb_buffer_pool_filename", Value: "ib_buffer_pool"},
	{Scope: vardef.ScopeGlobal, Name: "slow_launch_time", Value: "2"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndb_use_transactions", Value: ""},
	{Scope: vardef.ScopeNone, Name: "innodb_purge_threads", Value: "1"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_concurrency_tickets", Value: "5000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_monitor_reset_all", Value: ""},
	{Scope: vardef.ScopeNone, Name: "performance_schema_users_size", Value: "100"},
	{Scope: vardef.ScopeGlobal, Name: "ndb_log_updated_only", Value: ""},
	{Scope: vardef.ScopeNone, Name: "basedir", Value: "/usr/local/mysql"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_old_blocks_time", Value: "1000"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_stats_method", Value: "nulls_equal"},
	{Scope: vardef.ScopeGlobal, Name: vardef.LocalInFile, Value: vardef.On, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "myisam_stats_method", Value: "nulls_unequal"},
	{Scope: vardef.ScopeNone, Name: "relay_log_recovery", Value: "0"},
	{Scope: vardef.ScopeNone, Name: "old", Value: "0"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.InnodbTableLocks, Value: vardef.On, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeNone, Name: vardef.PerformanceSchema, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeNone, Name: "myisam_recover_options", Value: vardef.Off},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: vardef.NetBufferLength, Value: "16384", Type: vardef.TypeUnsigned, MinValue: 1024, MaxValue: 1048576},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "binlog_row_image", Value: "FULL"},
	{Scope: vardef.ScopeSession, Name: "rbr_exec_mode", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "myisam_max_sort_file_size", Value: "9223372036853727232"},
	{Scope: vardef.ScopeNone, Name: "back_log", Value: "80"},
	{Scope: vardef.ScopeSession, Name: "pseudo_thread_id", Value: ""},
	{Scope: vardef.ScopeNone, Name: "have_dynamic_loading", Value: "YES"},
	{Scope: vardef.ScopeGlobal, Name: "rewriter_verbose", Value: ""},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_cond_instances", Value: "3504"},
	{Scope: vardef.ScopeGlobal, Name: "delayed_insert_limit", Value: "100"},
	{Scope: vardef.ScopeGlobal, Name: vardef.Flush, Value: vardef.Off, Type: vardef.TypeBool},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    "eq_range_index_dive_limit",
		Value:                   "200",
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: "performance_schema_events_stages_history_size", Value: "10"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndb_join_pushdown", Value: ""},
	{Scope: vardef.ScopeNone, Name: "performance_schema_max_thread_instances", Value: "402"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "ndbinfo_show_hidden", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "net_read_timeout", Value: "30"},
	{Scope: vardef.ScopeNone, Name: "innodb_page_size", Value: "16384"},
	{Scope: vardef.ScopeNone, Name: "innodb_log_file_size", Value: "50331648"},
	{Scope: vardef.ScopeGlobal, Name: "sync_relay_log_info", Value: "10000"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "optimizer_trace_limit", Value: "1"},
	{Scope: vardef.ScopeNone, Name: "innodb_ft_max_token_size", Value: "84"},
	{Scope: vardef.ScopeGlobal, Name: "ndb_log_binlog_index", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "innodb_api_bk_commit_interval", Value: "5"},
	{Scope: vardef.ScopeNone, Name: "innodb_undo_directory", Value: "."},
	{Scope: vardef.ScopeNone, Name: "bind_address", Value: "*"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_sync_spin_loops", Value: "30"},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    vardef.SQLSafeUpdates,
		Value:                   vardef.Off,
		Type:                    vardef.TypeBool,
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeNone, Name: "tmpdir", Value: "/var/tmp/"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_thread_concurrency", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "innodb_buffer_pool_dump_pct", Value: ""},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "lc_time_names", Value: "en_US", ReadOnly: true},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "max_statement_time", Value: ""},
	{
		Scope:                   vardef.ScopeGlobal | vardef.ScopeSession,
		Name:                    vardef.EndMarkersInJSON,
		Value:                   vardef.Off,
		Type:                    vardef.TypeBool,
		IsHintUpdatableVerified: true,
	},
	{Scope: vardef.ScopeGlobal, Name: vardef.AvoidTemporalUpgrade, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "key_cache_age_threshold", Value: "300"},
	{Scope: vardef.ScopeGlobal, Name: vardef.InnodbStatusOutput, Value: vardef.Off, Type: vardef.TypeBool, AutoConvertNegativeBool: true},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "min_examined_row_limit", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "sync_frm", Type: vardef.TypeBool, Value: vardef.On},
	{Scope: vardef.ScopeGlobal, Name: "innodb_online_alter_log_max_size", Value: "134217728"},
	{Scope: vardef.ScopeGlobal | vardef.ScopeSession, Name: "information_schema_stats_expiry", Value: "86400"},
	{Scope: vardef.ScopeGlobal, Name: vardef.ThreadPoolSize, Value: "16", Type: vardef.TypeUnsigned, MinValue: 1, MaxValue: 64},
	{Scope: vardef.ScopeNone, Name: "lower_case_file_system", Value: "1"},
	{Scope: vardef.ScopeNone, Name: vardef.LowerCaseTableNames, Value: "2"},

	// for compatibility purpose, we should leave them alone.
	// TODO: Follow the Terminology Updates of MySQL after their changes arrived.
	// https://mysqlhighavailability.com/mysql-terminology-updates/
	{Scope: vardef.ScopeSession, Name: vardef.PseudoSlaveMode, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "slave_pending_jobs_size_max", Value: "16777216"},
	{Scope: vardef.ScopeGlobal, Name: "slave_transaction_retries", Value: "10"},
	{Scope: vardef.ScopeGlobal, Name: "slave_checkpoint_period", Value: "300"},
	{Scope: vardef.ScopeGlobal, Name: vardef.MasterVerifyChecksum, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_master_trace_level", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "master_info_repository", Value: "FILE"},
	{Scope: vardef.ScopeGlobal, Name: "rpl_stop_slave_timeout", Value: "31536000"},
	{Scope: vardef.ScopeGlobal, Name: "slave_net_timeout", Value: "3600"},
	{Scope: vardef.ScopeGlobal, Name: "sync_master_info", Value: "10000"},
	{Scope: vardef.ScopeGlobal, Name: "init_slave", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: vardef.SlaveCompressedProtocol, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_slave_trace_level", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: vardef.LogSlowSlaveStatements, Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "slave_checkpoint_group", Value: "512"},
	{Scope: vardef.ScopeNone, Name: "slave_load_tmpdir", Value: "/var/tmp/"},
	{Scope: vardef.ScopeGlobal, Name: "slave_parallel_type", Value: ""},
	{Scope: vardef.ScopeGlobal, Name: "slave_parallel_workers", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_master_timeout", Value: "10000", Type: vardef.TypeInt, MaxValue: math.MaxInt64},
	{Scope: vardef.ScopeNone, Name: "slave_skip_errors", Value: vardef.Off},
	{Scope: vardef.ScopeGlobal, Name: "sql_slave_skip_counter", Value: "0"},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_slave_enabled", Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_master_enabled", Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "slave_preserve_commit_order", Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "slave_exec_mode", Value: "STRICT"},
	{Scope: vardef.ScopeNone, Name: "log_slave_updates", Value: vardef.Off, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_master_wait_point", Value: "AFTER_SYNC", Type: vardef.TypeEnum, PossibleValues: []string{"AFTER_SYNC", "AFTER_COMMIT"}},
	{Scope: vardef.ScopeGlobal, Name: "slave_sql_verify_checksum", Value: vardef.On, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "slave_max_allowed_packet", Value: "1073741824"},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_master_wait_for_slave_count", Value: "1", Type: vardef.TypeInt, MinValue: 1, MaxValue: 65535},
	{Scope: vardef.ScopeGlobal, Name: "rpl_semi_sync_master_wait_no_slave", Value: vardef.On, Type: vardef.TypeBool},
	{Scope: vardef.ScopeGlobal, Name: "slave_rows_search_algorithms", Value: "TABLE_SCAN,INDEX_SCAN"},
	{Scope: vardef.ScopeGlobal, Name: vardef.SlaveAllowBatching, Value: vardef.Off, Type: vardef.TypeBool},
}
