#!/bin/bash
#
# Copyright 2019 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

SQL="$1"
shift

echo "[$(date)] Executing SQL: $SQL" > "$TEST_DIR/sql_res.$TEST_NAME.txt"
mysql -uroot -h127.0.0.1 -P4000 \
    --ssl-ca="$TEST_DIR/certs/ca.pem" \
    --ssl-cert="$TEST_DIR/certs/curl.pem" \
    --ssl-key="$TEST_DIR/certs/curl.key" \
    "$@" \
    --default-character-set utf8 -E -e "$SQL" | tee -a "$TEST_DIR/sql_res.$TEST_NAME.txt"
