#!/bin/sh
#
# Copyright 2019 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eux

echo "[$(date)] <<<<<< RUNNING TEST FOR: tests/$TEST_NAME $@ >>>>>>" >> "$TEST_DIR/lightning.log"
bin/tidb-lightning.test -test.coverprofile="$TEST_DIR/cov.$TEST_NAME.$$.out" DEVEL \
    --ca "$TEST_DIR/certs/ca.pem" \
    --cert "$TEST_DIR/certs/lightning.pem" \
    --key "$TEST_DIR/certs/lightning.key" \
    --log-file "$TEST_DIR/lightning.log" \
    --tidb-port 4000 \
    --pd-urls '127.0.0.1:2379' \
    --config "tests/$TEST_NAME/config.toml" \
    -d "tests/$TEST_NAME/data" \
    --sorted-kv-dir "$TEST_DIR/$TEST_NAME.sorted" \
    --enable-checkpoint=0 \
    --check-requirements=0 \
    "$@"
