// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package jointest

import "github.com/pingcap/tidb/pkg/testkit/mega/register"

func init() {
	register.Register("executor/test/jointest", "Issue11895", RunIssue11895)
	register.Register("executor/test/jointest", "Issue11896", RunIssue11896)
	register.Register("executor/test/jointest", "Issue18070", RunIssue18070)
	register.Register("executor/test/jointest", "Issue20779", RunIssue20779)
	register.Register("executor/test/jointest", "Issue30211", RunIssue30211)
	register.Register("executor/test/jointest", "Issue37932", RunIssue37932)
	register.Register("executor/test/jointest", "Issue49033", RunIssue49033)
	register.Register("executor/test/jointest", "Join2", RunJoin2)
	register.Register("executor/test/jointest", "JoinLeak", RunJoinLeak)
	register.Register("executor/test/jointest", "NullEmptyAwareSemiJoin", RunNullEmptyAwareSemiJoin)
	register.Register("executor/test/jointest", "SingleTaskIncrementalIndexHashJoin", RunSingleTaskIncrementalIndexHashJoin)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "executor/test/jointest" {
			InitForMega()
		}
	})
}
