port = 4001
lease = "0"
mem-quota-query = 34359738368
nested-loop-join-cache-capacity = 20971520

[status]
status-port = 10081

[performance]
stats-lease = "0"

[experimental]
allow-expression-index = true
