# Copyright 2021 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

lease = "0"
host = "127.0.0.1"
new_collations_enabled_on_first_bootstrap = true

[status]
status-host = "127.0.0.1"

[performance]
stats-lease = "0"

[experimental]
enable-new-charset = true
allow-expression-index = true
