load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_test(
    name = "ruv3_test",
    timeout = "short",
    srcs = ["model_test.go"],
    embed = [":ruv3"],
    flaky = True,
    shard_count = 5,
)

go_library(
    name = "ruv3",
    srcs = ["model.go"],
    importpath = "github.com/pingcap/tidb/pkg/resourcegroup/ruv3",
    visibility = ["//visibility:public"],
)
