// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestGenLightningDataDir(t *testing.T) {
	RunGenLightningDataDir(t)
}

func TestLitBackendCtxMgr(t *testing.T) {
	RunLitBackendCtxMgr(t)
}
