// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestMergePartialResult4Avg(t *testing.T) {
	RunMergePartialResult4Avg(t)
}

func TestAvg(t *testing.T) {
	RunAvg(t)
}

func TestMemAvg(t *testing.T) {
	RunMemAvg(t)
}
