// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestMergePartialResult4Stddevsamp(t *testing.T) {
	RunMergePartialResult4Stddevsamp(t)
}

func TestStddevsamp(t *testing.T) {
	RunStddevsamp(t)
}
