// Code generated by mega-gen. DO NOT EDIT.

package stmtsummary_test

import (
	"github.com/pingcap/tidb/pkg/testkit/mega/register"
)

func init() {
	register.Register("util_stmtsummary", "MapToEvictedCountDatum", RunMapToEvictedCountDatum)
	register.Register("util_stmtsummary", "SimpleStmtSummaryByDigestEvicted", RunSimpleStmtSummaryByDigestEvicted)
	register.Register("util_stmtsummary", "StmtSummaryByDigestEvictedElement", RunStmtSummaryByDigestEvictedElement)
	register.Register("util_stmtsummary", "EvictedCountDetailed", RunEvictedCountDetailed)
	register.Register("util_stmtsummary", "NewStmtSummaryByDigestEvictedElement", RunNewStmtSummaryByDigestEvictedElement)
	register.Register("util_stmtsummary", "StmtSummaryByDigestEvicted", RunStmtSummaryByDigestEvicted)
	register.Register("util_stmtsummary", "AddInfo", RunAddInfo)
	register.Register("util_stmtsummary", "SetUp", RunSetUp)
	register.Register("util_stmtsummary", "AddStatement", RunAddStatement)
	register.Register("util_stmtsummary", "ToDatum", RunToDatum)
	register.Register("util_stmtsummary", "AddStatementParallel", RunAddStatementParallel)
	register.Register("util_stmtsummary", "MaxStmtCount", RunMaxStmtCount)
	register.Register("util_stmtsummary", "MaxSQLLength", RunMaxSQLLength)
	register.Register("util_stmtsummary", "FormatSQLClone", RunFormatSQLClone)
	register.Register("util_stmtsummary", "SetMaxStmtCountParallel", RunSetMaxStmtCountParallel)
	register.Register("util_stmtsummary", "StmtSummaryMetrics", RunStmtSummaryMetrics)
	register.Register("util_stmtsummary", "StmtSummaryMetricsAfterCapacityChange", RunStmtSummaryMetricsAfterCapacityChange)
	register.Register("util_stmtsummary", "DisableStmtSummary", RunDisableStmtSummary)
	register.Register("util_stmtsummary", "EnableSummaryParallel", RunEnableSummaryParallel)
	register.Register("util_stmtsummary", "FormatBackoffTypes", RunFormatBackoffTypes)
	register.Register("util_stmtsummary", "RefreshCurrentSummary", RunRefreshCurrentSummary)
	register.Register("util_stmtsummary", "SummaryHistory", RunSummaryHistory)
	register.Register("util_stmtsummary", "PrevSQL", RunPrevSQL)
	register.Register("util_stmtsummary", "EndTime", RunEndTime)
	register.Register("util_stmtsummary", "PointGet", RunPointGet)
	register.Register("util_stmtsummary", "AccessPrivilege", RunAccessPrivilege)
}
