// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package runtime_test

import "testing"

func TestRuntimeStartStop(t *testing.T) {
	RunRuntimeStartStop(t)
}

func TestEnsureWorker(t *testing.T) {
	RunEnsureWorker(t)
}

func TestTryTriggerTimer(t *testing.T) {
	RunTryTriggerTimer(t)
}

func TestTryTriggerTimePriority(t *testing.T) {
	RunTryTriggerTimePriority(t)
}

func TestHandleHookWorkerResponse(t *testing.T) {
	RunHandleHookWorkerResponse(t)
}

func TestNextTryTriggerDuration(t *testing.T) {
	RunNextTryTriggerDuration(t)
}

func TestFullRefreshTimers(t *testing.T) {
	RunFullRefreshTimers(t)
}

func TestBatchHandlerWatchResponses(t *testing.T) {
	RunBatchHandlerWatchResponses(t)
}

func TestCloseWaitingCloseTimers(t *testing.T) {
	RunCloseWaitingCloseTimers(t)
}

func TestCreateWatchTimerChan(t *testing.T) {
	RunCreateWatchTimerChan(t)
}

func TestWatchTimerRetry(t *testing.T) {
	RunWatchTimerRetry(t)
}

func TestTimerFullProcess(t *testing.T) {
	RunTimerFullProcess(t)
}

func TestTimerRuntimeLoopPanicRecover(t *testing.T) {
	RunTimerRuntimeLoopPanicRecover(t)
}
