// Copyright 2023 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "util/collate/ucadata/generator"; DO NOT EDIT.

package ucadata

// {{.Name}} is the collation element table for the corresponding unicode version.
// it's generated from {{.URL}}
var {{.Name}} = struct {
    MapTable4 [{{.Length}}]uint64
    LongRuneMap map[rune][2]uint64
} {
    MapTable4: [{{.Length}}]uint64{ {{range $idx, $item := .MapTable4}} {{if mod $idx 0xF}}{{printf "\n"}}{{end}} {{$item | printf "0x%X"}}, {{end}}
    },
    LongRuneMap: map[rune][2]uint64{
        {{range $key, $item := .LongRuneMap}}{{$key | printf "0x%X"}}: { {{range $idx, $w := $item}} {{$w | printf "0x%X"}},{{end}} },
        {{end}}
    },
}
