// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "util/collate/ucadata/generator"; DO NOT EDIT.

package ucadata

// {{.Name}} is the multi-level collation element table for the corresponding unicode version.
// It keeps all three weight levels (primary, secondary, tertiary) so accent- and case-sensitive
// collations can be implemented. It is generated from {{.URL}}.
//
// Layout (compressed sparse row): the collation elements of rune r are CEData[Offset[r]:Offset[r+1]].
// Each element packs the three levels as (primary<<32 | secondary<<16 | tertiary). Runes whose range
// is empty are not explicitly listed in the DUCET; their weights are computed implicitly by the collator.
var {{.Name}} = struct {
    CEData []uint64
    Offset []uint32
} {
    CEData: []uint64{ {{range $idx, $item := .CEData}} {{if mod $idx 0xF}}{{printf "\n"}}{{end}} {{$item | printf "0x%X"}}, {{end}}
    },
    Offset: []uint32{ {{range $idx, $item := .Offset}} {{if mod $idx 0xF}}{{printf "\n"}}{{end}} {{$item | printf "0x%X"}}, {{end}}
    },
}
