[package]
name = "tidb-stats-handle-cache-internal-lfu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "TiDB statistics handle Ristretto LFU cache."

[lints]
workspace = true

[dependencies]
stretto = "0.9"
tidb-stats = { path = "../tidb-stats" }
tidb-stats-handle-cache-internal = { path = "../tidb-stats-handle-cache-internal" }
tidb-stats-handle-cache-metrics = { path = "../tidb-stats-handle-cache-metrics" }
tidb-util = { path = "../tidb-util" }

[dev-dependencies]
tidb-stats-handle-cache-internal-testutil = { path = "../tidb-stats-handle-cache-internal-testutil" }
