language: go
sudo: false
go:
  - 1.11.x
  - 1.12.x
go_import_path: go.uber.org/zap
env:
  global:
    - TEST_TIMEOUT_SCALE=10
cache:
  directories:
    - vendor
install:
  - make dependencies
script:
  - make lint
  - make test
  - make bench
after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
