// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package set_test

import "testing"

func TestSetBasic(t *testing.T) {
	RunSetBasic(t)
}

func TestSetOperation(t *testing.T) {
	RunSetOperation(t)
}

func TestSetCombination(t *testing.T) {
	RunSetCombination(t)
}
