[package]
name = "difftest-parser-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Parser and lexer differential tests against TiDB's Go implementation."
publish = false
autotests = false
build = "../../scripts/aggregate-tests.rs"

[lints]
workspace = true

[dependencies]
difftest = { path = ".." }
tidb-lexer = { path = "../../crates/tidb-lexer" }
tidb-ast = { path = "../../crates/tidb-ast" }
tidb-parser = { path = "../../crates/tidb-parser" }

[[test]]
name = "all"
path = "tests/all.rs"
