// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package memory_test

import "testing"

func TestSetLabel(t *testing.T) {
	RunSetLabel(t)
}

func TestSetLabel2(t *testing.T) {
	RunSetLabel2(t)
}

func TestConsume(t *testing.T) {
	RunConsume(t)
}

func TestRelease(t *testing.T) {
	RunRelease(t)
}

func TestBufferedConsumeAndRelease(t *testing.T) {
	RunBufferedConsumeAndRelease(t)
}

func TestOOMAction(t *testing.T) {
	RunOOMAction(t)
}

func TestAttachTo(t *testing.T) {
	RunAttachTo(t)
}

func TestDetach(t *testing.T) {
	RunDetach(t)
}

func TestReplaceChild(t *testing.T) {
	RunReplaceChild(t)
}

func TestToString(t *testing.T) {
	RunToString(t)
}

func TestMaxConsumed(t *testing.T) {
	RunMaxConsumed(t)
}

func TestGlobalTracker(t *testing.T) {
	RunGlobalTracker(t)
}

func TestFormatBytesWithPrune(t *testing.T) {
	RunFormatBytesWithPrune(t)
}

func TestErrorCode(t *testing.T) {
	RunErrorCode(t)
}

func TestOOMActionPriority(t *testing.T) {
	RunOOMActionPriority(t)
}

func TestGlobalMemArbitrator(t *testing.T) {
	RunGlobalMemArbitrator(t)
}
