load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gobinaryrow_lib",
    srcs = ["main.go"],
    importpath = "github.com/pingcap/tidb/rust/difftests/gobinaryrow",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/parser/mysql",
        "//pkg/server/internal/column",
        "//pkg/types",
        "//pkg/util/chunk",
    ],
)

go_binary(
    name = "gobinaryrow",
    embed = [":gobinaryrow_lib"],
    visibility = ["//visibility:public"],
)
