// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package copr_test_test

import "testing"

func TestBuildCopIteratorWithRowCountHint(t *testing.T) {
	RunBuildCopIteratorWithRowCountHint(t)
}

func TestBuildCopIteratorWithBatchStoreCopr(t *testing.T) {
	RunBuildCopIteratorWithBatchStoreCopr(t)
}

func TestBuildCopIteratorWithRunawayChecker(t *testing.T) {
	RunBuildCopIteratorWithRunawayChecker(t)
}

func TestQueryWithConcurrentSmallCop(t *testing.T) {
	RunQueryWithConcurrentSmallCop(t)
}

func TestDMLWithLiteCopWorker(t *testing.T) {
	RunDMLWithLiteCopWorker(t)
}
