name: Auto Assign Question and Bug Reports

on:
  issues:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Run issues assignment to project SIG Runtime Kanban
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        (
        contains(github.event.issue.labels.*.name, 'type/question') ||
        contains(github.event.issue.labels.*.name, 'type/bug')
        ) && 
        (
        contains(github.event.issue.labels.*.name, 'component/parser') ||
        contains(github.event.issue.labels.*.name, 'component/ddl') ||
        contains(github.event.issue.labels.*.name, 'component/infoschema') ||
        contains(github.event.issue.labels.*.name, 'component/charset') ||
        contains(github.event.issue.labels.*.name, 'component/binlog') ||
        contains(github.event.issue.labels.*.name, 'component/expression') ||
        contains(github.event.issue.labels.*.name, 'component/executor') ||
        contains(github.event.issue.labels.*.name, 'component/statistics') ||
        contains(github.event.issue.labels.*.name, 'component/planner') ||
        contains(github.event.issue.labels.*.name, 'component/transaction')     
        )
      with:
        project: 'https://github.com/pingcap/tidb/projects/36'
        column_name: 'In Progress: Handled to SIGs'
