name: BR & Lightning
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths:
      - "br/**"
      - "!**.html"
      - "!**.md"
      - "!CNAME"
      - "!LICENSE"
      - "!br/docs/**"
      - "!br/tests/**"
      - "!br/docker/**"
  #change trigger policy
  pull_request:
    types:
      - labeled # <--
    branches:
      - master
      - "release-[0-9].[0-9]*"
    paths:
      - "br/**"
      - "!**.html"
      - "!**.md"
      - "!CNAME"
      - "!LICENSE"
      - "!br/docs/**"
      - "!br/tests/**"
      - "!br/docker/**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile for ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest,  ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run build
        run: make build_tools

  compile-freebsd:
    name: Compile for FreeBSD job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Compile for FreeBSD
        run: GOOS=freebsd make build_tools
