name: BR & Lightning 
on:
  push:
    branches:
      - master
      - 'release-[0-9].[0-9]*'
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
#change trigger policy
  pull_request:
    types:
      - labeled  # <--
    branches:
      - master
      - 'release-[0-9].[0-9]*'
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile-windows:
    if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.label.name == 'action/run-br-cross-platform-build'
    name: Compile for Windows job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run build
        run: make build_tools
        
  compile:
    if: github.event_name == 'pull_request' && github.event.label.name == 'action/run-br-cross-platform-build'
    name: Compile for ${{ matrix.os }} / ${{ matrix.target}}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run build
        run: make build_tools

  compile-freebsd:
    if: github.event_name == 'pull_request' && github.event.label.name == 'action/run-br-cross-platform-build'
    name: Compile for FreeBSD job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Compile for FreeBSD
        run: GOOS=freebsd make build_tools
