name: misc

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
      - "main"
      - "release-**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git pull origin ${{ github.event.pull_request.base.sha }}
      - name: Check File Permission
        run: make check-file-perm
      - name: Check License Header
        uses: apache/skywalking-eyes/header@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/licenserc.yml
      - name: Check Leaked Secrets
        uses: trufflesecurity/trufflehog@3.4.3
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
