name: misc

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
      - "main"
      - "release-**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check File Permission
        run: make check-file-perm
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        with:
          log: info
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/licenserc.yml
