name: Pessimistic Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pessimistic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Setup TiKV cluster
        run: TAG=nightly docker-compose -f pessimistictest/docker/cluster.yml up --remove-orphans -d
      - name: Run Tests
        run: |
          export log_level=error
          make failpoint-enable
          cd pessimistictest
          go test -v -with-real-tikv -timeout 20m
