load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "rule",
    srcs = [
        "logical_rules.go",
        "rule_build_key_info.go",
        "rule_constant_propagation.go",
        "rule_init.go",
        "rule_order_aware_join_reorder.go",
        "rule_prune_indexes.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/planner/core/rule",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/expression",
        "//pkg/meta/model",
        "//pkg/planner/core/base",
        "//pkg/planner/core/joinorder",
        "//pkg/planner/core/operator/logicalop",
        "//pkg/planner/core/rule/util",
        "//pkg/planner/util",
        "//pkg/planner/util/fixcontrol",
        "//pkg/planner/util/optimizetrace",
        "@com_github_pingcap_failpoint//:failpoint",
    ],
)

go_test(
    name = "rule_test",
    srcs = ["rule_prune_indexes_internal_test.go"],
    embed = [":rule"],
    deps = [
        "//pkg/expression",
        "//pkg/meta/model",
        "//pkg/parser/model",
        "//pkg/parser/mysql",
        "//pkg/planner/core/operator/logicalop",
        "//pkg/planner/util",
        "//pkg/types",
        "@com_github_stretchr_testify//require",
    ],
)
