// Code generated by mega migration. DO NOT EDIT.

//go:build intest
// +build intest

package vars

import "github.com/pingcap/tidb/pkg/testkit/mega/register"

func init() {
	register.Register("session/test/vars", "GlobalVarAccessor", RunGlobalVarAccessor)
	register.Register("session/test/vars", "IndexJoinBuildV2SysVarCompatibility", RunIndexJoinBuildV2SysVarCompatibility)
	register.Register("session/test/vars", "KVVars", RunKVVars)
	register.Register("session/test/vars", "PrepareExecuteWithSQLHints", RunPrepareExecuteWithSQLHints)
	register.Register("session/test/vars", "RemovedSysVars", RunRemovedSysVars)
	register.Register("session/test/vars", "SetInstanceSysvarBySetGlobalSysVar", RunSetInstanceSysvarBySetGlobalSysVar)
	register.Register("session/test/vars", "TiDBAdvancerCheckPointLagLimit", RunTiDBAdvancerCheckPointLagLimit)
	register.Register("session/test/vars", "TiDBValidateTS", RunTiDBValidateTS)
	register.Register("session/test/vars", "TiKVSystemVars", RunTiKVSystemVars)
	register.Register("session/test/vars", "TimeZone", RunTimeZone)
	register.Register("session/test/vars", "UpgradeSysvars", RunUpgradeSysvars)
	register.RegisterOnBeforeRun(func(pkg string) {
		if pkg == "session/test/vars" {
			InitForMega()
		}
	})
}
