// Code generated by mega-gen. DO NOT EDIT.
// Actual source is in the corresponding .go file.

package test

import "testing"

func TestDetector(t *testing.T) {
	RunDetector(t)
}

func TestDetectorFail(t *testing.T) {
	RunDetectorFail(t)
}
